// Code generated by Kitex v0.13.1. DO NOT EDIT.

package workflowservice

import (
	"context"
	"errors"
	base "github.com/aiagt/aiagt/kitex_gen/base"
	workflowsvc "github.com/aiagt/aiagt/kitex_gen/workflowsvc"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateWorkflow": kitex.NewMethodInfo(
		createWorkflowHandler,
		newWorkflowServiceCreateWorkflowArgs,
		newWorkflowServiceCreateWorkflowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateWorkflow": kitex.NewMethodInfo(
		updateWorkflowHandler,
		newWorkflowServiceUpdateWorkflowArgs,
		newWorkflowServiceUpdateWorkflowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteWorkflow": kitex.NewMethodInfo(
		deleteWorkflowHandler,
		newWorkflowServiceDeleteWorkflowArgs,
		newWorkflowServiceDeleteWorkflowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetWorkflowByID": kitex.NewMethodInfo(
		getWorkflowByIDHandler,
		newWorkflowServiceGetWorkflowByIDArgs,
		newWorkflowServiceGetWorkflowByIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateWorkflowNode": kitex.NewMethodInfo(
		createWorkflowNodeHandler,
		newWorkflowServiceCreateWorkflowNodeArgs,
		newWorkflowServiceCreateWorkflowNodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateWorkflowNode": kitex.NewMethodInfo(
		updateWorkflowNodeHandler,
		newWorkflowServiceUpdateWorkflowNodeArgs,
		newWorkflowServiceUpdateWorkflowNodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteWorkflowNode": kitex.NewMethodInfo(
		deleteWorkflowNodeHandler,
		newWorkflowServiceDeleteWorkflowNodeArgs,
		newWorkflowServiceDeleteWorkflowNodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetWorkflowNodeByID": kitex.NewMethodInfo(
		getWorkflowNodeByIDHandler,
		newWorkflowServiceGetWorkflowNodeByIDArgs,
		newWorkflowServiceGetWorkflowNodeByIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CallWorkflow": kitex.NewMethodInfo(
		callWorkflowHandler,
		newWorkflowServiceCallWorkflowArgs,
		newWorkflowServiceCallWorkflowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	workflowServiceServiceInfo                = NewServiceInfo()
	workflowServiceServiceInfoForClient       = NewServiceInfoForClient()
	workflowServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return workflowServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return workflowServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return workflowServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "WorkflowService"
	handlerType := (*workflowsvc.WorkflowService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "workflowsvc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func createWorkflowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceCreateWorkflowArgs)
	realResult := result.(*workflowsvc.WorkflowServiceCreateWorkflowResult)
	success, err := handler.(workflowsvc.WorkflowService).CreateWorkflow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceCreateWorkflowArgs() interface{} {
	return workflowsvc.NewWorkflowServiceCreateWorkflowArgs()
}

func newWorkflowServiceCreateWorkflowResult() interface{} {
	return workflowsvc.NewWorkflowServiceCreateWorkflowResult()
}

func updateWorkflowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceUpdateWorkflowArgs)
	realResult := result.(*workflowsvc.WorkflowServiceUpdateWorkflowResult)
	success, err := handler.(workflowsvc.WorkflowService).UpdateWorkflow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceUpdateWorkflowArgs() interface{} {
	return workflowsvc.NewWorkflowServiceUpdateWorkflowArgs()
}

func newWorkflowServiceUpdateWorkflowResult() interface{} {
	return workflowsvc.NewWorkflowServiceUpdateWorkflowResult()
}

func deleteWorkflowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceDeleteWorkflowArgs)
	realResult := result.(*workflowsvc.WorkflowServiceDeleteWorkflowResult)
	success, err := handler.(workflowsvc.WorkflowService).DeleteWorkflow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceDeleteWorkflowArgs() interface{} {
	return workflowsvc.NewWorkflowServiceDeleteWorkflowArgs()
}

func newWorkflowServiceDeleteWorkflowResult() interface{} {
	return workflowsvc.NewWorkflowServiceDeleteWorkflowResult()
}

func getWorkflowByIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceGetWorkflowByIDArgs)
	realResult := result.(*workflowsvc.WorkflowServiceGetWorkflowByIDResult)
	success, err := handler.(workflowsvc.WorkflowService).GetWorkflowByID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceGetWorkflowByIDArgs() interface{} {
	return workflowsvc.NewWorkflowServiceGetWorkflowByIDArgs()
}

func newWorkflowServiceGetWorkflowByIDResult() interface{} {
	return workflowsvc.NewWorkflowServiceGetWorkflowByIDResult()
}

func createWorkflowNodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceCreateWorkflowNodeArgs)
	realResult := result.(*workflowsvc.WorkflowServiceCreateWorkflowNodeResult)
	success, err := handler.(workflowsvc.WorkflowService).CreateWorkflowNode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceCreateWorkflowNodeArgs() interface{} {
	return workflowsvc.NewWorkflowServiceCreateWorkflowNodeArgs()
}

func newWorkflowServiceCreateWorkflowNodeResult() interface{} {
	return workflowsvc.NewWorkflowServiceCreateWorkflowNodeResult()
}

func updateWorkflowNodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceUpdateWorkflowNodeArgs)
	realResult := result.(*workflowsvc.WorkflowServiceUpdateWorkflowNodeResult)
	success, err := handler.(workflowsvc.WorkflowService).UpdateWorkflowNode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceUpdateWorkflowNodeArgs() interface{} {
	return workflowsvc.NewWorkflowServiceUpdateWorkflowNodeArgs()
}

func newWorkflowServiceUpdateWorkflowNodeResult() interface{} {
	return workflowsvc.NewWorkflowServiceUpdateWorkflowNodeResult()
}

func deleteWorkflowNodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceDeleteWorkflowNodeArgs)
	realResult := result.(*workflowsvc.WorkflowServiceDeleteWorkflowNodeResult)
	success, err := handler.(workflowsvc.WorkflowService).DeleteWorkflowNode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceDeleteWorkflowNodeArgs() interface{} {
	return workflowsvc.NewWorkflowServiceDeleteWorkflowNodeArgs()
}

func newWorkflowServiceDeleteWorkflowNodeResult() interface{} {
	return workflowsvc.NewWorkflowServiceDeleteWorkflowNodeResult()
}

func getWorkflowNodeByIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceGetWorkflowNodeByIDArgs)
	realResult := result.(*workflowsvc.WorkflowServiceGetWorkflowNodeByIDResult)
	success, err := handler.(workflowsvc.WorkflowService).GetWorkflowNodeByID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceGetWorkflowNodeByIDArgs() interface{} {
	return workflowsvc.NewWorkflowServiceGetWorkflowNodeByIDArgs()
}

func newWorkflowServiceGetWorkflowNodeByIDResult() interface{} {
	return workflowsvc.NewWorkflowServiceGetWorkflowNodeByIDResult()
}

func callWorkflowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*workflowsvc.WorkflowServiceCallWorkflowArgs)
	realResult := result.(*workflowsvc.WorkflowServiceCallWorkflowResult)
	success, err := handler.(workflowsvc.WorkflowService).CallWorkflow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkflowServiceCallWorkflowArgs() interface{} {
	return workflowsvc.NewWorkflowServiceCallWorkflowArgs()
}

func newWorkflowServiceCallWorkflowResult() interface{} {
	return workflowsvc.NewWorkflowServiceCallWorkflowResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateWorkflow(ctx context.Context, req *workflowsvc.CreateWorkflowReq) (r *base.Empty, err error) {
	var _args workflowsvc.WorkflowServiceCreateWorkflowArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceCreateWorkflowResult
	if err = p.c.Call(ctx, "CreateWorkflow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateWorkflow(ctx context.Context, req *workflowsvc.UpdateWorkflowReq) (r *base.Empty, err error) {
	var _args workflowsvc.WorkflowServiceUpdateWorkflowArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceUpdateWorkflowResult
	if err = p.c.Call(ctx, "UpdateWorkflow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteWorkflow(ctx context.Context, req *base.IDReq) (r *base.Empty, err error) {
	var _args workflowsvc.WorkflowServiceDeleteWorkflowArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceDeleteWorkflowResult
	if err = p.c.Call(ctx, "DeleteWorkflow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetWorkflowByID(ctx context.Context, req *base.IDReq) (r *workflowsvc.Workflow, err error) {
	var _args workflowsvc.WorkflowServiceGetWorkflowByIDArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceGetWorkflowByIDResult
	if err = p.c.Call(ctx, "GetWorkflowByID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateWorkflowNode(ctx context.Context, req *workflowsvc.CreateWorkflowNodeReq) (r *base.Empty, err error) {
	var _args workflowsvc.WorkflowServiceCreateWorkflowNodeArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceCreateWorkflowNodeResult
	if err = p.c.Call(ctx, "CreateWorkflowNode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateWorkflowNode(ctx context.Context, req *workflowsvc.UpdateWorkflowNodeReq) (r *base.Empty, err error) {
	var _args workflowsvc.WorkflowServiceUpdateWorkflowNodeArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceUpdateWorkflowNodeResult
	if err = p.c.Call(ctx, "UpdateWorkflowNode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteWorkflowNode(ctx context.Context, req *base.IDReq) (r *base.Empty, err error) {
	var _args workflowsvc.WorkflowServiceDeleteWorkflowNodeArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceDeleteWorkflowNodeResult
	if err = p.c.Call(ctx, "DeleteWorkflowNode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetWorkflowNodeByID(ctx context.Context, req *base.IDReq) (r *workflowsvc.WorkflowNode, err error) {
	var _args workflowsvc.WorkflowServiceGetWorkflowNodeByIDArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceGetWorkflowNodeByIDResult
	if err = p.c.Call(ctx, "GetWorkflowNodeByID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CallWorkflow(ctx context.Context, req *workflowsvc.CallWorkflowReq) (r *workflowsvc.CallWorkflowResp, err error) {
	var _args workflowsvc.WorkflowServiceCallWorkflowArgs
	_args.Req = req
	var _result workflowsvc.WorkflowServiceCallWorkflowResult
	if err = p.c.Call(ctx, "CallWorkflow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
