// Code generated by tools/init_service. DO NOT EDIT.

package handler

import "github.com/aiagt/aiagt/common/bizerr"

const (
	ServiceName = "knowledge"

	bizCodeDeleteDocument         = 0
	bizCodeDeleteKnowledge        = 1
	bizCodeGetDocumentByKnowledge = 2
	bizCodeGetKnowledgeByID       = 3
	bizCodeGetKnowledgeByIDs      = 4
	bizCodeSetMilvusClient        = 5
	bizCodeListKnowledge          = 6
	bizCodePreviewChunks          = 7
	bizCodeRetrieval              = 8
	bizCodeSaveKnowledge          = 9
	bizCodeUpdateDocument         = 10
	bizCodeUploadDocument         = 11
)

var (
	bizDeleteDocument         *bizerr.Biz
	bizDeleteKnowledge        *bizerr.Biz
	bizGetDocumentByKnowledge *bizerr.Biz
	bizGetKnowledgeByID       *bizerr.Biz
	bizGetKnowledgeByIDs      *bizerr.Biz
	bizSetMilvusClient        *bizerr.Biz
	bizListKnowledge          *bizerr.Biz
	bizPreviewChunks          *bizerr.Biz
	bizRetrieval              *bizerr.Biz
	bizSaveKnowledge          *bizerr.Biz
	bizUpdateDocument         *bizerr.Biz
	bizUploadDocument         *bizerr.Biz
)

func initServiceBusiness(serviceCode int) {
	baseCode := (serviceCode + 100) * 100

	bizDeleteDocument = bizerr.NewBiz(ServiceName, "delete_document", baseCode+bizCodeDeleteDocument)
	bizDeleteKnowledge = bizerr.NewBiz(ServiceName, "delete_knowledge", baseCode+bizCodeDeleteKnowledge)
	bizGetDocumentByKnowledge = bizerr.NewBiz(ServiceName, "get_document_by_knowledge", baseCode+bizCodeGetDocumentByKnowledge)
	bizGetKnowledgeByID = bizerr.NewBiz(ServiceName, "get_knowledge_by_id", baseCode+bizCodeGetKnowledgeByID)
	bizGetKnowledgeByIDs = bizerr.NewBiz(ServiceName, "get_knowledge_by_i_ds", baseCode+bizCodeGetKnowledgeByIDs)
	bizSetMilvusClient = bizerr.NewBiz(ServiceName, "set_milvus_client", baseCode+bizCodeSetMilvusClient)
	bizListKnowledge = bizerr.NewBiz(ServiceName, "list_knowledge", baseCode+bizCodeListKnowledge)
	bizPreviewChunks = bizerr.NewBiz(ServiceName, "preview_chunks", baseCode+bizCodePreviewChunks)
	bizRetrieval = bizerr.NewBiz(ServiceName, "retrieval", baseCode+bizCodeRetrieval)
	bizSaveKnowledge = bizerr.NewBiz(ServiceName, "save_knowledge", baseCode+bizCodeSaveKnowledge)
	bizUpdateDocument = bizerr.NewBiz(ServiceName, "update_document", baseCode+bizCodeUpdateDocument)
	bizUploadDocument = bizerr.NewBiz(ServiceName, "upload_document", baseCode+bizCodeUploadDocument)
}
