// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package knowledgesvc

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/aiagt/aiagt/kitex_gen/base"
	"github.com/aiagt/aiagt/kitex_gen/usersvc"
)

type EmbeddingStatus int64

const (
	EmbeddingStatus_PENDING EmbeddingStatus = 0
	EmbeddingStatus_SUCCESS EmbeddingStatus = 1
	EmbeddingStatus_FAILED  EmbeddingStatus = 2
)

func (p EmbeddingStatus) String() string {
	switch p {
	case EmbeddingStatus_PENDING:
		return "PENDING"
	case EmbeddingStatus_SUCCESS:
		return "SUCCESS"
	case EmbeddingStatus_FAILED:
		return "FAILED"
	}
	return "<UNSET>"
}

func EmbeddingStatusFromString(s string) (EmbeddingStatus, error) {
	switch s {
	case "PENDING":
		return EmbeddingStatus_PENDING, nil
	case "SUCCESS":
		return EmbeddingStatus_SUCCESS, nil
	case "FAILED":
		return EmbeddingStatus_FAILED, nil
	}
	return EmbeddingStatus(0), fmt.Errorf("not a valid EmbeddingStatus string")
}

func EmbeddingStatusPtr(v EmbeddingStatus) *EmbeddingStatus { return &v }
func (p *EmbeddingStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = EmbeddingStatus(result.Int64)
	return
}

func (p *EmbeddingStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Knowledge struct {
	Id             int64         `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Name           string        `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Description    string        `thrift:"description,3,required" frugal:"3,required,string" json:"description"`
	AuthorId       int64         `thrift:"author_id,4,required" frugal:"4,required,i64" json:"author_id"`
	Author         *usersvc.User `thrift:"author,5,optional" frugal:"5,optional,usersvc.User" json:"author,omitempty"`
	IsPrivate      bool          `thrift:"is_private,6,required" frugal:"6,required,bool" json:"is_private"`
	Logo           string        `thrift:"logo,7,required" frugal:"7,required,string" json:"logo"`
	EmbedModelId   int64         `thrift:"embed_model_id,8,required" frugal:"8,required,i64" json:"embed_model_id"`
	TopK           int64         `thrift:"top_k,9,required" frugal:"9,required,i64" json:"top_k"`
	ScoreThreshold *float64      `thrift:"score_threshold,10,optional" frugal:"10,optional,double" json:"score_threshold,omitempty"`
	CreatedAt      *base.Time    `thrift:"created_at,11,required" frugal:"11,required,base.Time" json:"created_at"`
	UpdatedAt      *base.Time    `thrift:"updated_at,12,required" frugal:"12,required,base.Time" json:"updated_at"`
	PublishedAt    *base.Time    `thrift:"published_at,13,required" frugal:"13,required,base.Time" json:"published_at"`
}

func NewKnowledge() *Knowledge {
	return &Knowledge{}
}

func (p *Knowledge) InitDefault() {
}

func (p *Knowledge) GetId() (v int64) {
	return p.Id
}

func (p *Knowledge) GetName() (v string) {
	return p.Name
}

func (p *Knowledge) GetDescription() (v string) {
	return p.Description
}

func (p *Knowledge) GetAuthorId() (v int64) {
	return p.AuthorId
}

var Knowledge_Author_DEFAULT *usersvc.User

func (p *Knowledge) GetAuthor() (v *usersvc.User) {
	if !p.IsSetAuthor() {
		return Knowledge_Author_DEFAULT
	}
	return p.Author
}

func (p *Knowledge) GetIsPrivate() (v bool) {
	return p.IsPrivate
}

func (p *Knowledge) GetLogo() (v string) {
	return p.Logo
}

func (p *Knowledge) GetEmbedModelId() (v int64) {
	return p.EmbedModelId
}

func (p *Knowledge) GetTopK() (v int64) {
	return p.TopK
}

var Knowledge_ScoreThreshold_DEFAULT float64

func (p *Knowledge) GetScoreThreshold() (v float64) {
	if !p.IsSetScoreThreshold() {
		return Knowledge_ScoreThreshold_DEFAULT
	}
	return *p.ScoreThreshold
}

var Knowledge_CreatedAt_DEFAULT *base.Time

func (p *Knowledge) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return Knowledge_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}

var Knowledge_UpdatedAt_DEFAULT *base.Time

func (p *Knowledge) GetUpdatedAt() (v *base.Time) {
	if !p.IsSetUpdatedAt() {
		return Knowledge_UpdatedAt_DEFAULT
	}
	return p.UpdatedAt
}

var Knowledge_PublishedAt_DEFAULT *base.Time

func (p *Knowledge) GetPublishedAt() (v *base.Time) {
	if !p.IsSetPublishedAt() {
		return Knowledge_PublishedAt_DEFAULT
	}
	return p.PublishedAt
}
func (p *Knowledge) SetId(val int64) {
	p.Id = val
}
func (p *Knowledge) SetName(val string) {
	p.Name = val
}
func (p *Knowledge) SetDescription(val string) {
	p.Description = val
}
func (p *Knowledge) SetAuthorId(val int64) {
	p.AuthorId = val
}
func (p *Knowledge) SetAuthor(val *usersvc.User) {
	p.Author = val
}
func (p *Knowledge) SetIsPrivate(val bool) {
	p.IsPrivate = val
}
func (p *Knowledge) SetLogo(val string) {
	p.Logo = val
}
func (p *Knowledge) SetEmbedModelId(val int64) {
	p.EmbedModelId = val
}
func (p *Knowledge) SetTopK(val int64) {
	p.TopK = val
}
func (p *Knowledge) SetScoreThreshold(val *float64) {
	p.ScoreThreshold = val
}
func (p *Knowledge) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}
func (p *Knowledge) SetUpdatedAt(val *base.Time) {
	p.UpdatedAt = val
}
func (p *Knowledge) SetPublishedAt(val *base.Time) {
	p.PublishedAt = val
}

func (p *Knowledge) IsSetAuthor() bool {
	return p.Author != nil
}

func (p *Knowledge) IsSetScoreThreshold() bool {
	return p.ScoreThreshold != nil
}

func (p *Knowledge) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *Knowledge) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *Knowledge) IsSetPublishedAt() bool {
	return p.PublishedAt != nil
}

func (p *Knowledge) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Knowledge(%+v)", *p)
}

var fieldIDToName_Knowledge = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "description",
	4:  "author_id",
	5:  "author",
	6:  "is_private",
	7:  "logo",
	8:  "embed_model_id",
	9:  "top_k",
	10: "score_threshold",
	11: "created_at",
	12: "updated_at",
	13: "published_at",
}

type KnowledgeDocument struct {
	Id             int64           `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	KnowledgeId    int64           `thrift:"knowledge_id,2,required" frugal:"2,required,i64" json:"knowledge_id"`
	Name           string          `thrift:"name,3,required" frugal:"3,required,string" json:"name"`
	Url            string          `thrift:"url,4,required" frugal:"4,required,string" json:"url"`
	Type           string          `thrift:"type,5,required" frugal:"5,required,string" json:"type"`
	Preview        string          `thrift:"preview,6,required" frugal:"6,required,string" json:"preview"`
	Size           int64           `thrift:"size,7,required" frugal:"7,required,i64" json:"size"`
	RetrievalCount int64           `thrift:"retrieval_count,8,required" frugal:"8,required,i64" json:"retrieval_count"`
	UpdatedAt      *base.Time      `thrift:"updated_at,9,required" frugal:"9,required,base.Time" json:"updated_at"`
	ChunkSize      int64           `thrift:"chunk_size,10,optional" frugal:"10,optional,i64" json:"chunk_size,omitempty"`
	OverlapSize    int64           `thrift:"overlap_size,11,optional" frugal:"11,optional,i64" json:"overlap_size,omitempty"`
	Separators     []string        `thrift:"separators,12,optional" frugal:"12,optional,list<string>" json:"separators,omitempty"`
	Status         EmbeddingStatus `thrift:"status,13,required" frugal:"13,required,EmbeddingStatus" json:"status"`
	FailedReason   *string         `thrift:"failed_reason,14,optional" frugal:"14,optional,string" json:"failed_reason,omitempty"`
}

func NewKnowledgeDocument() *KnowledgeDocument {
	return &KnowledgeDocument{

		ChunkSize:   1024,
		OverlapSize: 50,
	}
}

func (p *KnowledgeDocument) InitDefault() {
	p.ChunkSize = 1024
	p.OverlapSize = 50
}

func (p *KnowledgeDocument) GetId() (v int64) {
	return p.Id
}

func (p *KnowledgeDocument) GetKnowledgeId() (v int64) {
	return p.KnowledgeId
}

func (p *KnowledgeDocument) GetName() (v string) {
	return p.Name
}

func (p *KnowledgeDocument) GetUrl() (v string) {
	return p.Url
}

func (p *KnowledgeDocument) GetType() (v string) {
	return p.Type
}

func (p *KnowledgeDocument) GetPreview() (v string) {
	return p.Preview
}

func (p *KnowledgeDocument) GetSize() (v int64) {
	return p.Size
}

func (p *KnowledgeDocument) GetRetrievalCount() (v int64) {
	return p.RetrievalCount
}

var KnowledgeDocument_UpdatedAt_DEFAULT *base.Time

func (p *KnowledgeDocument) GetUpdatedAt() (v *base.Time) {
	if !p.IsSetUpdatedAt() {
		return KnowledgeDocument_UpdatedAt_DEFAULT
	}
	return p.UpdatedAt
}

var KnowledgeDocument_ChunkSize_DEFAULT int64 = 1024

func (p *KnowledgeDocument) GetChunkSize() (v int64) {
	if !p.IsSetChunkSize() {
		return KnowledgeDocument_ChunkSize_DEFAULT
	}
	return p.ChunkSize
}

var KnowledgeDocument_OverlapSize_DEFAULT int64 = 50

func (p *KnowledgeDocument) GetOverlapSize() (v int64) {
	if !p.IsSetOverlapSize() {
		return KnowledgeDocument_OverlapSize_DEFAULT
	}
	return p.OverlapSize
}

var KnowledgeDocument_Separators_DEFAULT []string

func (p *KnowledgeDocument) GetSeparators() (v []string) {
	if !p.IsSetSeparators() {
		return KnowledgeDocument_Separators_DEFAULT
	}
	return p.Separators
}

func (p *KnowledgeDocument) GetStatus() (v EmbeddingStatus) {
	return p.Status
}

var KnowledgeDocument_FailedReason_DEFAULT string

func (p *KnowledgeDocument) GetFailedReason() (v string) {
	if !p.IsSetFailedReason() {
		return KnowledgeDocument_FailedReason_DEFAULT
	}
	return *p.FailedReason
}
func (p *KnowledgeDocument) SetId(val int64) {
	p.Id = val
}
func (p *KnowledgeDocument) SetKnowledgeId(val int64) {
	p.KnowledgeId = val
}
func (p *KnowledgeDocument) SetName(val string) {
	p.Name = val
}
func (p *KnowledgeDocument) SetUrl(val string) {
	p.Url = val
}
func (p *KnowledgeDocument) SetType(val string) {
	p.Type = val
}
func (p *KnowledgeDocument) SetPreview(val string) {
	p.Preview = val
}
func (p *KnowledgeDocument) SetSize(val int64) {
	p.Size = val
}
func (p *KnowledgeDocument) SetRetrievalCount(val int64) {
	p.RetrievalCount = val
}
func (p *KnowledgeDocument) SetUpdatedAt(val *base.Time) {
	p.UpdatedAt = val
}
func (p *KnowledgeDocument) SetChunkSize(val int64) {
	p.ChunkSize = val
}
func (p *KnowledgeDocument) SetOverlapSize(val int64) {
	p.OverlapSize = val
}
func (p *KnowledgeDocument) SetSeparators(val []string) {
	p.Separators = val
}
func (p *KnowledgeDocument) SetStatus(val EmbeddingStatus) {
	p.Status = val
}
func (p *KnowledgeDocument) SetFailedReason(val *string) {
	p.FailedReason = val
}

func (p *KnowledgeDocument) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *KnowledgeDocument) IsSetChunkSize() bool {
	return p.ChunkSize != KnowledgeDocument_ChunkSize_DEFAULT
}

func (p *KnowledgeDocument) IsSetOverlapSize() bool {
	return p.OverlapSize != KnowledgeDocument_OverlapSize_DEFAULT
}

func (p *KnowledgeDocument) IsSetSeparators() bool {
	return p.Separators != nil
}

func (p *KnowledgeDocument) IsSetFailedReason() bool {
	return p.FailedReason != nil
}

func (p *KnowledgeDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeDocument(%+v)", *p)
}

var fieldIDToName_KnowledgeDocument = map[int16]string{
	1:  "id",
	2:  "knowledge_id",
	3:  "name",
	4:  "url",
	5:  "type",
	6:  "preview",
	7:  "size",
	8:  "retrieval_count",
	9:  "updated_at",
	10: "chunk_size",
	11: "overlap_size",
	12: "separators",
	13: "status",
	14: "failed_reason",
}

type KnowledgeChunk struct {
	Id             string          `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	KnowledgeId    int64           `thrift:"knowledge_id,2,required" frugal:"2,required,i64" json:"knowledge_id"`
	DocumentId     int64           `thrift:"document_id,3,required" frugal:"3,required,i64" json:"document_id"`
	Content        string          `thrift:"content,4,required" frugal:"4,required,string" json:"content"`
	Vector         []float64       `thrift:"vector,5,optional" frugal:"5,optional,list<double>" json:"vector,omitempty"`
	Order          int64           `thrift:"order,6,required" frugal:"6,required,i64" json:"order"`
	RetrievalCount int64           `thrift:"retrieval_count,7,required" frugal:"7,required,i64" json:"retrieval_count"`
	Status         EmbeddingStatus `thrift:"status,8,required" frugal:"8,required,EmbeddingStatus" json:"status"`
}

func NewKnowledgeChunk() *KnowledgeChunk {
	return &KnowledgeChunk{}
}

func (p *KnowledgeChunk) InitDefault() {
}

func (p *KnowledgeChunk) GetId() (v string) {
	return p.Id
}

func (p *KnowledgeChunk) GetKnowledgeId() (v int64) {
	return p.KnowledgeId
}

func (p *KnowledgeChunk) GetDocumentId() (v int64) {
	return p.DocumentId
}

func (p *KnowledgeChunk) GetContent() (v string) {
	return p.Content
}

var KnowledgeChunk_Vector_DEFAULT []float64

func (p *KnowledgeChunk) GetVector() (v []float64) {
	if !p.IsSetVector() {
		return KnowledgeChunk_Vector_DEFAULT
	}
	return p.Vector
}

func (p *KnowledgeChunk) GetOrder() (v int64) {
	return p.Order
}

func (p *KnowledgeChunk) GetRetrievalCount() (v int64) {
	return p.RetrievalCount
}

func (p *KnowledgeChunk) GetStatus() (v EmbeddingStatus) {
	return p.Status
}
func (p *KnowledgeChunk) SetId(val string) {
	p.Id = val
}
func (p *KnowledgeChunk) SetKnowledgeId(val int64) {
	p.KnowledgeId = val
}
func (p *KnowledgeChunk) SetDocumentId(val int64) {
	p.DocumentId = val
}
func (p *KnowledgeChunk) SetContent(val string) {
	p.Content = val
}
func (p *KnowledgeChunk) SetVector(val []float64) {
	p.Vector = val
}
func (p *KnowledgeChunk) SetOrder(val int64) {
	p.Order = val
}
func (p *KnowledgeChunk) SetRetrievalCount(val int64) {
	p.RetrievalCount = val
}
func (p *KnowledgeChunk) SetStatus(val EmbeddingStatus) {
	p.Status = val
}

func (p *KnowledgeChunk) IsSetVector() bool {
	return p.Vector != nil
}

func (p *KnowledgeChunk) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeChunk(%+v)", *p)
}

var fieldIDToName_KnowledgeChunk = map[int16]string{
	1: "id",
	2: "knowledge_id",
	3: "document_id",
	4: "content",
	5: "vector",
	6: "order",
	7: "retrieval_count",
	8: "status",
}

type EmbeddingModel struct {
	Id          int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Name        string `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Description string `thrift:"description,3,required" frugal:"3,required,string" json:"description"`
	ModelKey    string `thrift:"model_key,4,required" frugal:"4,required,string" json:"model_key"`
	Dim         int64  `thrift:"dim,5,required" frugal:"5,required,i64" json:"dim"`
}

func NewEmbeddingModel() *EmbeddingModel {
	return &EmbeddingModel{}
}

func (p *EmbeddingModel) InitDefault() {
}

func (p *EmbeddingModel) GetId() (v int64) {
	return p.Id
}

func (p *EmbeddingModel) GetName() (v string) {
	return p.Name
}

func (p *EmbeddingModel) GetDescription() (v string) {
	return p.Description
}

func (p *EmbeddingModel) GetModelKey() (v string) {
	return p.ModelKey
}

func (p *EmbeddingModel) GetDim() (v int64) {
	return p.Dim
}
func (p *EmbeddingModel) SetId(val int64) {
	p.Id = val
}
func (p *EmbeddingModel) SetName(val string) {
	p.Name = val
}
func (p *EmbeddingModel) SetDescription(val string) {
	p.Description = val
}
func (p *EmbeddingModel) SetModelKey(val string) {
	p.ModelKey = val
}
func (p *EmbeddingModel) SetDim(val int64) {
	p.Dim = val
}

func (p *EmbeddingModel) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmbeddingModel(%+v)", *p)
}

var fieldIDToName_EmbeddingModel = map[int16]string{
	1: "id",
	2: "name",
	3: "description",
	4: "model_key",
	5: "dim",
}

type RetrievalReq struct {
	KnowledgeIds []int64 `thrift:"knowledge_ids,1,required" frugal:"1,required,list<i64>" json:"knowledge_ids"`
	Query        string  `thrift:"query,2,required" frugal:"2,required,string" json:"query"`
}

func NewRetrievalReq() *RetrievalReq {
	return &RetrievalReq{}
}

func (p *RetrievalReq) InitDefault() {
}

func (p *RetrievalReq) GetKnowledgeIds() (v []int64) {
	return p.KnowledgeIds
}

func (p *RetrievalReq) GetQuery() (v string) {
	return p.Query
}
func (p *RetrievalReq) SetKnowledgeIds(val []int64) {
	p.KnowledgeIds = val
}
func (p *RetrievalReq) SetQuery(val string) {
	p.Query = val
}

func (p *RetrievalReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RetrievalReq(%+v)", *p)
}

var fieldIDToName_RetrievalReq = map[int16]string{
	1: "knowledge_ids",
	2: "query",
}

type RetrievalResp struct {
	Chunks []*KnowledgeChunk `thrift:"chunks,1,required" frugal:"1,required,list<KnowledgeChunk>" json:"chunks"`
}

func NewRetrievalResp() *RetrievalResp {
	return &RetrievalResp{}
}

func (p *RetrievalResp) InitDefault() {
}

func (p *RetrievalResp) GetChunks() (v []*KnowledgeChunk) {
	return p.Chunks
}
func (p *RetrievalResp) SetChunks(val []*KnowledgeChunk) {
	p.Chunks = val
}

func (p *RetrievalResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RetrievalResp(%+v)", *p)
}

var fieldIDToName_RetrievalResp = map[int16]string{
	1: "chunks",
}

type SaveKnowledgeReq struct {
	Id             *int64   `thrift:"id,1,optional" frugal:"1,optional,i64" path:"id"`
	Name           string   `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Description    string   `thrift:"description,3,required" frugal:"3,required,string" json:"description"`
	IsPrivate      bool     `thrift:"is_private,4,required" frugal:"4,required,bool" json:"is_private"`
	EmbedModelId   int64    `thrift:"embed_model_id,5,required" frugal:"5,required,i64" json:"embed_model_id"`
	TopK           int64    `thrift:"top_k,6,required" frugal:"6,required,i64" json:"top_k"`
	ScoreThreshold *float64 `thrift:"score_threshold,7,optional" frugal:"7,optional,double" json:"score_threshold,omitempty"`
	Logo           string   `thrift:"logo,8,required" frugal:"8,required,string" json:"logo"`
}

func NewSaveKnowledgeReq() *SaveKnowledgeReq {
	return &SaveKnowledgeReq{}
}

func (p *SaveKnowledgeReq) InitDefault() {
}

var SaveKnowledgeReq_Id_DEFAULT int64

func (p *SaveKnowledgeReq) GetId() (v int64) {
	if !p.IsSetId() {
		return SaveKnowledgeReq_Id_DEFAULT
	}
	return *p.Id
}

func (p *SaveKnowledgeReq) GetName() (v string) {
	return p.Name
}

func (p *SaveKnowledgeReq) GetDescription() (v string) {
	return p.Description
}

func (p *SaveKnowledgeReq) GetIsPrivate() (v bool) {
	return p.IsPrivate
}

func (p *SaveKnowledgeReq) GetEmbedModelId() (v int64) {
	return p.EmbedModelId
}

func (p *SaveKnowledgeReq) GetTopK() (v int64) {
	return p.TopK
}

var SaveKnowledgeReq_ScoreThreshold_DEFAULT float64

func (p *SaveKnowledgeReq) GetScoreThreshold() (v float64) {
	if !p.IsSetScoreThreshold() {
		return SaveKnowledgeReq_ScoreThreshold_DEFAULT
	}
	return *p.ScoreThreshold
}

func (p *SaveKnowledgeReq) GetLogo() (v string) {
	return p.Logo
}
func (p *SaveKnowledgeReq) SetId(val *int64) {
	p.Id = val
}
func (p *SaveKnowledgeReq) SetName(val string) {
	p.Name = val
}
func (p *SaveKnowledgeReq) SetDescription(val string) {
	p.Description = val
}
func (p *SaveKnowledgeReq) SetIsPrivate(val bool) {
	p.IsPrivate = val
}
func (p *SaveKnowledgeReq) SetEmbedModelId(val int64) {
	p.EmbedModelId = val
}
func (p *SaveKnowledgeReq) SetTopK(val int64) {
	p.TopK = val
}
func (p *SaveKnowledgeReq) SetScoreThreshold(val *float64) {
	p.ScoreThreshold = val
}
func (p *SaveKnowledgeReq) SetLogo(val string) {
	p.Logo = val
}

func (p *SaveKnowledgeReq) IsSetId() bool {
	return p.Id != nil
}

func (p *SaveKnowledgeReq) IsSetScoreThreshold() bool {
	return p.ScoreThreshold != nil
}

func (p *SaveKnowledgeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SaveKnowledgeReq(%+v)", *p)
}

var fieldIDToName_SaveKnowledgeReq = map[int16]string{
	1: "id",
	2: "name",
	3: "description",
	4: "is_private",
	5: "embed_model_id",
	6: "top_k",
	7: "score_threshold",
	8: "logo",
}

type UploadDocumentReq struct {
	KnowledgeId int64    `thrift:"knowledge_id,1,required" frugal:"1,required,i64" form:"knowledge_id"`
	Name        string   `thrift:"name,2,required" frugal:"2,required,string" form:"name"`
	Content     []byte   `thrift:"content,3,required" frugal:"3,required,binary" form:"content"`
	Type        string   `thrift:"type,4,required" frugal:"4,required,string" form:"type"`
	ChunkSize   int64    `thrift:"chunk_size,5,optional" frugal:"5,optional,i64" form:"chunk_size"`
	OverlapSize int64    `thrift:"overlap_size,6,optional" frugal:"6,optional,i64" form:"overlap_size"`
	Separators  []string `thrift:"separators,7,optional" frugal:"7,optional,list<string>" form:"separators"`
}

func NewUploadDocumentReq() *UploadDocumentReq {
	return &UploadDocumentReq{

		ChunkSize:   1024,
		OverlapSize: 50,
	}
}

func (p *UploadDocumentReq) InitDefault() {
	p.ChunkSize = 1024
	p.OverlapSize = 50
}

func (p *UploadDocumentReq) GetKnowledgeId() (v int64) {
	return p.KnowledgeId
}

func (p *UploadDocumentReq) GetName() (v string) {
	return p.Name
}

func (p *UploadDocumentReq) GetContent() (v []byte) {
	return p.Content
}

func (p *UploadDocumentReq) GetType() (v string) {
	return p.Type
}

var UploadDocumentReq_ChunkSize_DEFAULT int64 = 1024

func (p *UploadDocumentReq) GetChunkSize() (v int64) {
	if !p.IsSetChunkSize() {
		return UploadDocumentReq_ChunkSize_DEFAULT
	}
	return p.ChunkSize
}

var UploadDocumentReq_OverlapSize_DEFAULT int64 = 50

func (p *UploadDocumentReq) GetOverlapSize() (v int64) {
	if !p.IsSetOverlapSize() {
		return UploadDocumentReq_OverlapSize_DEFAULT
	}
	return p.OverlapSize
}

var UploadDocumentReq_Separators_DEFAULT []string

func (p *UploadDocumentReq) GetSeparators() (v []string) {
	if !p.IsSetSeparators() {
		return UploadDocumentReq_Separators_DEFAULT
	}
	return p.Separators
}
func (p *UploadDocumentReq) SetKnowledgeId(val int64) {
	p.KnowledgeId = val
}
func (p *UploadDocumentReq) SetName(val string) {
	p.Name = val
}
func (p *UploadDocumentReq) SetContent(val []byte) {
	p.Content = val
}
func (p *UploadDocumentReq) SetType(val string) {
	p.Type = val
}
func (p *UploadDocumentReq) SetChunkSize(val int64) {
	p.ChunkSize = val
}
func (p *UploadDocumentReq) SetOverlapSize(val int64) {
	p.OverlapSize = val
}
func (p *UploadDocumentReq) SetSeparators(val []string) {
	p.Separators = val
}

func (p *UploadDocumentReq) IsSetChunkSize() bool {
	return p.ChunkSize != UploadDocumentReq_ChunkSize_DEFAULT
}

func (p *UploadDocumentReq) IsSetOverlapSize() bool {
	return p.OverlapSize != UploadDocumentReq_OverlapSize_DEFAULT
}

func (p *UploadDocumentReq) IsSetSeparators() bool {
	return p.Separators != nil
}

func (p *UploadDocumentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadDocumentReq(%+v)", *p)
}

var fieldIDToName_UploadDocumentReq = map[int16]string{
	1: "knowledge_id",
	2: "name",
	3: "content",
	4: "type",
	5: "chunk_size",
	6: "overlap_size",
	7: "separators",
}

type UpdateDocumentReq struct {
	Id          int64    `thrift:"id,1,required" frugal:"1,required,i64" path:"id"`
	ChunkSize   int64    `thrift:"chunk_size,2,optional" frugal:"2,optional,i64" json:"chunk_size,omitempty"`
	OverlapSize int64    `thrift:"overlap_size,3,optional" frugal:"3,optional,i64" json:"overlap_size,omitempty"`
	Separators  []string `thrift:"separators,4,optional" frugal:"4,optional,list<string>" json:"separators,omitempty"`
}

func NewUpdateDocumentReq() *UpdateDocumentReq {
	return &UpdateDocumentReq{

		ChunkSize:   1024,
		OverlapSize: 50,
	}
}

func (p *UpdateDocumentReq) InitDefault() {
	p.ChunkSize = 1024
	p.OverlapSize = 50
}

func (p *UpdateDocumentReq) GetId() (v int64) {
	return p.Id
}

var UpdateDocumentReq_ChunkSize_DEFAULT int64 = 1024

func (p *UpdateDocumentReq) GetChunkSize() (v int64) {
	if !p.IsSetChunkSize() {
		return UpdateDocumentReq_ChunkSize_DEFAULT
	}
	return p.ChunkSize
}

var UpdateDocumentReq_OverlapSize_DEFAULT int64 = 50

func (p *UpdateDocumentReq) GetOverlapSize() (v int64) {
	if !p.IsSetOverlapSize() {
		return UpdateDocumentReq_OverlapSize_DEFAULT
	}
	return p.OverlapSize
}

var UpdateDocumentReq_Separators_DEFAULT []string

func (p *UpdateDocumentReq) GetSeparators() (v []string) {
	if !p.IsSetSeparators() {
		return UpdateDocumentReq_Separators_DEFAULT
	}
	return p.Separators
}
func (p *UpdateDocumentReq) SetId(val int64) {
	p.Id = val
}
func (p *UpdateDocumentReq) SetChunkSize(val int64) {
	p.ChunkSize = val
}
func (p *UpdateDocumentReq) SetOverlapSize(val int64) {
	p.OverlapSize = val
}
func (p *UpdateDocumentReq) SetSeparators(val []string) {
	p.Separators = val
}

func (p *UpdateDocumentReq) IsSetChunkSize() bool {
	return p.ChunkSize != UpdateDocumentReq_ChunkSize_DEFAULT
}

func (p *UpdateDocumentReq) IsSetOverlapSize() bool {
	return p.OverlapSize != UpdateDocumentReq_OverlapSize_DEFAULT
}

func (p *UpdateDocumentReq) IsSetSeparators() bool {
	return p.Separators != nil
}

func (p *UpdateDocumentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDocumentReq(%+v)", *p)
}

var fieldIDToName_UpdateDocumentReq = map[int16]string{
	1: "id",
	2: "chunk_size",
	3: "overlap_size",
	4: "separators",
}

type GetDocumentByKnowledgeResp struct {
	Documents []*KnowledgeDocument `thrift:"documents,1,required" frugal:"1,required,list<KnowledgeDocument>" json:"documents"`
}

func NewGetDocumentByKnowledgeResp() *GetDocumentByKnowledgeResp {
	return &GetDocumentByKnowledgeResp{}
}

func (p *GetDocumentByKnowledgeResp) InitDefault() {
}

func (p *GetDocumentByKnowledgeResp) GetDocuments() (v []*KnowledgeDocument) {
	return p.Documents
}
func (p *GetDocumentByKnowledgeResp) SetDocuments(val []*KnowledgeDocument) {
	p.Documents = val
}

func (p *GetDocumentByKnowledgeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDocumentByKnowledgeResp(%+v)", *p)
}

var fieldIDToName_GetDocumentByKnowledgeResp = map[int16]string{
	1: "documents",
}

type ListKnowledgeReq struct {
	Pagination *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	AuthorId   *int64              `thrift:"author_id,2,optional" frugal:"2,optional,i64" json:"author_id,omitempty"`
	Name       *string             `thrift:"name,3,optional" frugal:"3,optional,string" json:"name,omitempty"`
}

func NewListKnowledgeReq() *ListKnowledgeReq {
	return &ListKnowledgeReq{}
}

func (p *ListKnowledgeReq) InitDefault() {
}

var ListKnowledgeReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListKnowledgeReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListKnowledgeReq_Pagination_DEFAULT
	}
	return p.Pagination
}

var ListKnowledgeReq_AuthorId_DEFAULT int64

func (p *ListKnowledgeReq) GetAuthorId() (v int64) {
	if !p.IsSetAuthorId() {
		return ListKnowledgeReq_AuthorId_DEFAULT
	}
	return *p.AuthorId
}

var ListKnowledgeReq_Name_DEFAULT string

func (p *ListKnowledgeReq) GetName() (v string) {
	if !p.IsSetName() {
		return ListKnowledgeReq_Name_DEFAULT
	}
	return *p.Name
}
func (p *ListKnowledgeReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListKnowledgeReq) SetAuthorId(val *int64) {
	p.AuthorId = val
}
func (p *ListKnowledgeReq) SetName(val *string) {
	p.Name = val
}

func (p *ListKnowledgeReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListKnowledgeReq) IsSetAuthorId() bool {
	return p.AuthorId != nil
}

func (p *ListKnowledgeReq) IsSetName() bool {
	return p.Name != nil
}

func (p *ListKnowledgeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListKnowledgeReq(%+v)", *p)
}

var fieldIDToName_ListKnowledgeReq = map[int16]string{
	1: "pagination",
	2: "author_id",
	3: "name",
}

type ListKnowledgeResp struct {
	Pagination    *base.PaginationResp `thrift:"pagination,1,required" frugal:"1,required,base.PaginationResp" json:"pagination"`
	KnowledgeList []*Knowledge         `thrift:"knowledge_list,2,required" frugal:"2,required,list<Knowledge>" json:"knowledge_list"`
}

func NewListKnowledgeResp() *ListKnowledgeResp {
	return &ListKnowledgeResp{}
}

func (p *ListKnowledgeResp) InitDefault() {
}

var ListKnowledgeResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListKnowledgeResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListKnowledgeResp_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListKnowledgeResp) GetKnowledgeList() (v []*Knowledge) {
	return p.KnowledgeList
}
func (p *ListKnowledgeResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}
func (p *ListKnowledgeResp) SetKnowledgeList(val []*Knowledge) {
	p.KnowledgeList = val
}

func (p *ListKnowledgeResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListKnowledgeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListKnowledgeResp(%+v)", *p)
}

var fieldIDToName_ListKnowledgeResp = map[int16]string{
	1: "pagination",
	2: "knowledge_list",
}

type PreviewChunksReq struct {
	Content     []byte   `thrift:"content,1,optional" frugal:"1,optional,binary" form:"content"`
	Url         *string  `thrift:"url,2,optional" frugal:"2,optional,string" form:"url"`
	ChunkSize   int64    `thrift:"chunk_size,3,optional" frugal:"3,optional,i64" form:"chunk_size"`
	OverlapSize int64    `thrift:"overlap_size,4,optional" frugal:"4,optional,i64" form:"overlap_size"`
	Separators  []string `thrift:"separators,5,optional" frugal:"5,optional,list<string>" form:"separators"`
	Type        string   `thrift:"type,6,required" frugal:"6,required,string" form:"type"`
}

func NewPreviewChunksReq() *PreviewChunksReq {
	return &PreviewChunksReq{

		ChunkSize:   1024,
		OverlapSize: 50,
	}
}

func (p *PreviewChunksReq) InitDefault() {
	p.ChunkSize = 1024
	p.OverlapSize = 50
}

var PreviewChunksReq_Content_DEFAULT []byte

func (p *PreviewChunksReq) GetContent() (v []byte) {
	if !p.IsSetContent() {
		return PreviewChunksReq_Content_DEFAULT
	}
	return p.Content
}

var PreviewChunksReq_Url_DEFAULT string

func (p *PreviewChunksReq) GetUrl() (v string) {
	if !p.IsSetUrl() {
		return PreviewChunksReq_Url_DEFAULT
	}
	return *p.Url
}

var PreviewChunksReq_ChunkSize_DEFAULT int64 = 1024

func (p *PreviewChunksReq) GetChunkSize() (v int64) {
	if !p.IsSetChunkSize() {
		return PreviewChunksReq_ChunkSize_DEFAULT
	}
	return p.ChunkSize
}

var PreviewChunksReq_OverlapSize_DEFAULT int64 = 50

func (p *PreviewChunksReq) GetOverlapSize() (v int64) {
	if !p.IsSetOverlapSize() {
		return PreviewChunksReq_OverlapSize_DEFAULT
	}
	return p.OverlapSize
}

var PreviewChunksReq_Separators_DEFAULT []string

func (p *PreviewChunksReq) GetSeparators() (v []string) {
	if !p.IsSetSeparators() {
		return PreviewChunksReq_Separators_DEFAULT
	}
	return p.Separators
}

func (p *PreviewChunksReq) GetType() (v string) {
	return p.Type
}
func (p *PreviewChunksReq) SetContent(val []byte) {
	p.Content = val
}
func (p *PreviewChunksReq) SetUrl(val *string) {
	p.Url = val
}
func (p *PreviewChunksReq) SetChunkSize(val int64) {
	p.ChunkSize = val
}
func (p *PreviewChunksReq) SetOverlapSize(val int64) {
	p.OverlapSize = val
}
func (p *PreviewChunksReq) SetSeparators(val []string) {
	p.Separators = val
}
func (p *PreviewChunksReq) SetType(val string) {
	p.Type = val
}

func (p *PreviewChunksReq) IsSetContent() bool {
	return p.Content != nil
}

func (p *PreviewChunksReq) IsSetUrl() bool {
	return p.Url != nil
}

func (p *PreviewChunksReq) IsSetChunkSize() bool {
	return p.ChunkSize != PreviewChunksReq_ChunkSize_DEFAULT
}

func (p *PreviewChunksReq) IsSetOverlapSize() bool {
	return p.OverlapSize != PreviewChunksReq_OverlapSize_DEFAULT
}

func (p *PreviewChunksReq) IsSetSeparators() bool {
	return p.Separators != nil
}

func (p *PreviewChunksReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PreviewChunksReq(%+v)", *p)
}

var fieldIDToName_PreviewChunksReq = map[int16]string{
	1: "content",
	2: "url",
	3: "chunk_size",
	4: "overlap_size",
	5: "separators",
	6: "type",
}

type PreviewChunksResp struct {
	Chunks []*KnowledgeChunk `thrift:"chunks,1,required" frugal:"1,required,list<KnowledgeChunk>" json:"chunks"`
}

func NewPreviewChunksResp() *PreviewChunksResp {
	return &PreviewChunksResp{}
}

func (p *PreviewChunksResp) InitDefault() {
}

func (p *PreviewChunksResp) GetChunks() (v []*KnowledgeChunk) {
	return p.Chunks
}
func (p *PreviewChunksResp) SetChunks(val []*KnowledgeChunk) {
	p.Chunks = val
}

func (p *PreviewChunksResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PreviewChunksResp(%+v)", *p)
}

var fieldIDToName_PreviewChunksResp = map[int16]string{
	1: "chunks",
}

type KnowledgeService interface {
	Retrieval(ctx context.Context, req *RetrievalReq) (r *RetrievalResp, err error)

	ListKnowledge(ctx context.Context, req *ListKnowledgeReq) (r *ListKnowledgeResp, err error)

	GetKnowledgeByID(ctx context.Context, req *base.IDReq) (r *Knowledge, err error)

	GetKnowledgeByIDs(ctx context.Context, req *base.IDsReq) (r []*Knowledge, err error)

	SaveKnowledge(ctx context.Context, req *SaveKnowledgeReq) (r *base.Empty, err error)

	DeleteKnowledge(ctx context.Context, req *base.IDReq) (r *base.Empty, err error)

	GetDocumentByKnowledge(ctx context.Context, req *base.IDReq) (r *GetDocumentByKnowledgeResp, err error)

	UploadDocument(ctx context.Context, req *UploadDocumentReq) (r *base.Empty, err error)

	UpdateDocument(ctx context.Context, req *UpdateDocumentReq) (r *base.Empty, err error)

	DeleteDocument(ctx context.Context, req *base.IDReq) (r *base.Empty, err error)

	PreviewChunks(ctx context.Context, req *PreviewChunksReq) (r *PreviewChunksResp, err error)
}

type KnowledgeServiceRetrievalArgs struct {
	Req *RetrievalReq `thrift:"req,1" frugal:"1,default,RetrievalReq" json:"req"`
}

func NewKnowledgeServiceRetrievalArgs() *KnowledgeServiceRetrievalArgs {
	return &KnowledgeServiceRetrievalArgs{}
}

func (p *KnowledgeServiceRetrievalArgs) InitDefault() {
}

var KnowledgeServiceRetrievalArgs_Req_DEFAULT *RetrievalReq

func (p *KnowledgeServiceRetrievalArgs) GetReq() (v *RetrievalReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceRetrievalArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceRetrievalArgs) SetReq(val *RetrievalReq) {
	p.Req = val
}

func (p *KnowledgeServiceRetrievalArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceRetrievalArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceRetrievalArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceRetrievalArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceRetrievalResult struct {
	Success *RetrievalResp `thrift:"success,0,optional" frugal:"0,optional,RetrievalResp" json:"success,omitempty"`
}

func NewKnowledgeServiceRetrievalResult() *KnowledgeServiceRetrievalResult {
	return &KnowledgeServiceRetrievalResult{}
}

func (p *KnowledgeServiceRetrievalResult) InitDefault() {
}

var KnowledgeServiceRetrievalResult_Success_DEFAULT *RetrievalResp

func (p *KnowledgeServiceRetrievalResult) GetSuccess() (v *RetrievalResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceRetrievalResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceRetrievalResult) SetSuccess(x interface{}) {
	p.Success = x.(*RetrievalResp)
}

func (p *KnowledgeServiceRetrievalResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceRetrievalResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceRetrievalResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceRetrievalResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceListKnowledgeArgs struct {
	Req *ListKnowledgeReq `thrift:"req,1" frugal:"1,default,ListKnowledgeReq" json:"req"`
}

func NewKnowledgeServiceListKnowledgeArgs() *KnowledgeServiceListKnowledgeArgs {
	return &KnowledgeServiceListKnowledgeArgs{}
}

func (p *KnowledgeServiceListKnowledgeArgs) InitDefault() {
}

var KnowledgeServiceListKnowledgeArgs_Req_DEFAULT *ListKnowledgeReq

func (p *KnowledgeServiceListKnowledgeArgs) GetReq() (v *ListKnowledgeReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceListKnowledgeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceListKnowledgeArgs) SetReq(val *ListKnowledgeReq) {
	p.Req = val
}

func (p *KnowledgeServiceListKnowledgeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceListKnowledgeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceListKnowledgeArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceListKnowledgeArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceListKnowledgeResult struct {
	Success *ListKnowledgeResp `thrift:"success,0,optional" frugal:"0,optional,ListKnowledgeResp" json:"success,omitempty"`
}

func NewKnowledgeServiceListKnowledgeResult() *KnowledgeServiceListKnowledgeResult {
	return &KnowledgeServiceListKnowledgeResult{}
}

func (p *KnowledgeServiceListKnowledgeResult) InitDefault() {
}

var KnowledgeServiceListKnowledgeResult_Success_DEFAULT *ListKnowledgeResp

func (p *KnowledgeServiceListKnowledgeResult) GetSuccess() (v *ListKnowledgeResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceListKnowledgeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceListKnowledgeResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListKnowledgeResp)
}

func (p *KnowledgeServiceListKnowledgeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceListKnowledgeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceListKnowledgeResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceListKnowledgeResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceGetKnowledgeByIDArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewKnowledgeServiceGetKnowledgeByIDArgs() *KnowledgeServiceGetKnowledgeByIDArgs {
	return &KnowledgeServiceGetKnowledgeByIDArgs{}
}

func (p *KnowledgeServiceGetKnowledgeByIDArgs) InitDefault() {
}

var KnowledgeServiceGetKnowledgeByIDArgs_Req_DEFAULT *base.IDReq

func (p *KnowledgeServiceGetKnowledgeByIDArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceGetKnowledgeByIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceGetKnowledgeByIDArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *KnowledgeServiceGetKnowledgeByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceGetKnowledgeByIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetKnowledgeByIDArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetKnowledgeByIDArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceGetKnowledgeByIDResult struct {
	Success *Knowledge `thrift:"success,0,optional" frugal:"0,optional,Knowledge" json:"success,omitempty"`
}

func NewKnowledgeServiceGetKnowledgeByIDResult() *KnowledgeServiceGetKnowledgeByIDResult {
	return &KnowledgeServiceGetKnowledgeByIDResult{}
}

func (p *KnowledgeServiceGetKnowledgeByIDResult) InitDefault() {
}

var KnowledgeServiceGetKnowledgeByIDResult_Success_DEFAULT *Knowledge

func (p *KnowledgeServiceGetKnowledgeByIDResult) GetSuccess() (v *Knowledge) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceGetKnowledgeByIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceGetKnowledgeByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*Knowledge)
}

func (p *KnowledgeServiceGetKnowledgeByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceGetKnowledgeByIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetKnowledgeByIDResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetKnowledgeByIDResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceGetKnowledgeByIDsArgs struct {
	Req *base.IDsReq `thrift:"req,1" frugal:"1,default,base.IDsReq" json:"req"`
}

func NewKnowledgeServiceGetKnowledgeByIDsArgs() *KnowledgeServiceGetKnowledgeByIDsArgs {
	return &KnowledgeServiceGetKnowledgeByIDsArgs{}
}

func (p *KnowledgeServiceGetKnowledgeByIDsArgs) InitDefault() {
}

var KnowledgeServiceGetKnowledgeByIDsArgs_Req_DEFAULT *base.IDsReq

func (p *KnowledgeServiceGetKnowledgeByIDsArgs) GetReq() (v *base.IDsReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceGetKnowledgeByIDsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceGetKnowledgeByIDsArgs) SetReq(val *base.IDsReq) {
	p.Req = val
}

func (p *KnowledgeServiceGetKnowledgeByIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceGetKnowledgeByIDsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetKnowledgeByIDsArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetKnowledgeByIDsArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceGetKnowledgeByIDsResult struct {
	Success []*Knowledge `thrift:"success,0,optional" frugal:"0,optional,list<Knowledge>" json:"success,omitempty"`
}

func NewKnowledgeServiceGetKnowledgeByIDsResult() *KnowledgeServiceGetKnowledgeByIDsResult {
	return &KnowledgeServiceGetKnowledgeByIDsResult{}
}

func (p *KnowledgeServiceGetKnowledgeByIDsResult) InitDefault() {
}

var KnowledgeServiceGetKnowledgeByIDsResult_Success_DEFAULT []*Knowledge

func (p *KnowledgeServiceGetKnowledgeByIDsResult) GetSuccess() (v []*Knowledge) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceGetKnowledgeByIDsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceGetKnowledgeByIDsResult) SetSuccess(x interface{}) {
	p.Success = x.([]*Knowledge)
}

func (p *KnowledgeServiceGetKnowledgeByIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceGetKnowledgeByIDsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetKnowledgeByIDsResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetKnowledgeByIDsResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceSaveKnowledgeArgs struct {
	Req *SaveKnowledgeReq `thrift:"req,1" frugal:"1,default,SaveKnowledgeReq" json:"req"`
}

func NewKnowledgeServiceSaveKnowledgeArgs() *KnowledgeServiceSaveKnowledgeArgs {
	return &KnowledgeServiceSaveKnowledgeArgs{}
}

func (p *KnowledgeServiceSaveKnowledgeArgs) InitDefault() {
}

var KnowledgeServiceSaveKnowledgeArgs_Req_DEFAULT *SaveKnowledgeReq

func (p *KnowledgeServiceSaveKnowledgeArgs) GetReq() (v *SaveKnowledgeReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceSaveKnowledgeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceSaveKnowledgeArgs) SetReq(val *SaveKnowledgeReq) {
	p.Req = val
}

func (p *KnowledgeServiceSaveKnowledgeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceSaveKnowledgeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceSaveKnowledgeArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceSaveKnowledgeArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceSaveKnowledgeResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewKnowledgeServiceSaveKnowledgeResult() *KnowledgeServiceSaveKnowledgeResult {
	return &KnowledgeServiceSaveKnowledgeResult{}
}

func (p *KnowledgeServiceSaveKnowledgeResult) InitDefault() {
}

var KnowledgeServiceSaveKnowledgeResult_Success_DEFAULT *base.Empty

func (p *KnowledgeServiceSaveKnowledgeResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceSaveKnowledgeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceSaveKnowledgeResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *KnowledgeServiceSaveKnowledgeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceSaveKnowledgeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceSaveKnowledgeResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceSaveKnowledgeResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceDeleteKnowledgeArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewKnowledgeServiceDeleteKnowledgeArgs() *KnowledgeServiceDeleteKnowledgeArgs {
	return &KnowledgeServiceDeleteKnowledgeArgs{}
}

func (p *KnowledgeServiceDeleteKnowledgeArgs) InitDefault() {
}

var KnowledgeServiceDeleteKnowledgeArgs_Req_DEFAULT *base.IDReq

func (p *KnowledgeServiceDeleteKnowledgeArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceDeleteKnowledgeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceDeleteKnowledgeArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *KnowledgeServiceDeleteKnowledgeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceDeleteKnowledgeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceDeleteKnowledgeArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceDeleteKnowledgeArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceDeleteKnowledgeResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewKnowledgeServiceDeleteKnowledgeResult() *KnowledgeServiceDeleteKnowledgeResult {
	return &KnowledgeServiceDeleteKnowledgeResult{}
}

func (p *KnowledgeServiceDeleteKnowledgeResult) InitDefault() {
}

var KnowledgeServiceDeleteKnowledgeResult_Success_DEFAULT *base.Empty

func (p *KnowledgeServiceDeleteKnowledgeResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceDeleteKnowledgeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceDeleteKnowledgeResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *KnowledgeServiceDeleteKnowledgeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceDeleteKnowledgeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceDeleteKnowledgeResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceDeleteKnowledgeResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceGetDocumentByKnowledgeArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewKnowledgeServiceGetDocumentByKnowledgeArgs() *KnowledgeServiceGetDocumentByKnowledgeArgs {
	return &KnowledgeServiceGetDocumentByKnowledgeArgs{}
}

func (p *KnowledgeServiceGetDocumentByKnowledgeArgs) InitDefault() {
}

var KnowledgeServiceGetDocumentByKnowledgeArgs_Req_DEFAULT *base.IDReq

func (p *KnowledgeServiceGetDocumentByKnowledgeArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceGetDocumentByKnowledgeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceGetDocumentByKnowledgeArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *KnowledgeServiceGetDocumentByKnowledgeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceGetDocumentByKnowledgeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetDocumentByKnowledgeArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetDocumentByKnowledgeArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceGetDocumentByKnowledgeResult struct {
	Success *GetDocumentByKnowledgeResp `thrift:"success,0,optional" frugal:"0,optional,GetDocumentByKnowledgeResp" json:"success,omitempty"`
}

func NewKnowledgeServiceGetDocumentByKnowledgeResult() *KnowledgeServiceGetDocumentByKnowledgeResult {
	return &KnowledgeServiceGetDocumentByKnowledgeResult{}
}

func (p *KnowledgeServiceGetDocumentByKnowledgeResult) InitDefault() {
}

var KnowledgeServiceGetDocumentByKnowledgeResult_Success_DEFAULT *GetDocumentByKnowledgeResp

func (p *KnowledgeServiceGetDocumentByKnowledgeResult) GetSuccess() (v *GetDocumentByKnowledgeResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceGetDocumentByKnowledgeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceGetDocumentByKnowledgeResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetDocumentByKnowledgeResp)
}

func (p *KnowledgeServiceGetDocumentByKnowledgeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceGetDocumentByKnowledgeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceGetDocumentByKnowledgeResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceGetDocumentByKnowledgeResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceUploadDocumentArgs struct {
	Req *UploadDocumentReq `thrift:"req,1" frugal:"1,default,UploadDocumentReq" json:"req"`
}

func NewKnowledgeServiceUploadDocumentArgs() *KnowledgeServiceUploadDocumentArgs {
	return &KnowledgeServiceUploadDocumentArgs{}
}

func (p *KnowledgeServiceUploadDocumentArgs) InitDefault() {
}

var KnowledgeServiceUploadDocumentArgs_Req_DEFAULT *UploadDocumentReq

func (p *KnowledgeServiceUploadDocumentArgs) GetReq() (v *UploadDocumentReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceUploadDocumentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceUploadDocumentArgs) SetReq(val *UploadDocumentReq) {
	p.Req = val
}

func (p *KnowledgeServiceUploadDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceUploadDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceUploadDocumentArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceUploadDocumentArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceUploadDocumentResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewKnowledgeServiceUploadDocumentResult() *KnowledgeServiceUploadDocumentResult {
	return &KnowledgeServiceUploadDocumentResult{}
}

func (p *KnowledgeServiceUploadDocumentResult) InitDefault() {
}

var KnowledgeServiceUploadDocumentResult_Success_DEFAULT *base.Empty

func (p *KnowledgeServiceUploadDocumentResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceUploadDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceUploadDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *KnowledgeServiceUploadDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceUploadDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceUploadDocumentResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceUploadDocumentResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceUpdateDocumentArgs struct {
	Req *UpdateDocumentReq `thrift:"req,1" frugal:"1,default,UpdateDocumentReq" json:"req"`
}

func NewKnowledgeServiceUpdateDocumentArgs() *KnowledgeServiceUpdateDocumentArgs {
	return &KnowledgeServiceUpdateDocumentArgs{}
}

func (p *KnowledgeServiceUpdateDocumentArgs) InitDefault() {
}

var KnowledgeServiceUpdateDocumentArgs_Req_DEFAULT *UpdateDocumentReq

func (p *KnowledgeServiceUpdateDocumentArgs) GetReq() (v *UpdateDocumentReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceUpdateDocumentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceUpdateDocumentArgs) SetReq(val *UpdateDocumentReq) {
	p.Req = val
}

func (p *KnowledgeServiceUpdateDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceUpdateDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceUpdateDocumentArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceUpdateDocumentArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceUpdateDocumentResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewKnowledgeServiceUpdateDocumentResult() *KnowledgeServiceUpdateDocumentResult {
	return &KnowledgeServiceUpdateDocumentResult{}
}

func (p *KnowledgeServiceUpdateDocumentResult) InitDefault() {
}

var KnowledgeServiceUpdateDocumentResult_Success_DEFAULT *base.Empty

func (p *KnowledgeServiceUpdateDocumentResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceUpdateDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceUpdateDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *KnowledgeServiceUpdateDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceUpdateDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceUpdateDocumentResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceUpdateDocumentResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceDeleteDocumentArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewKnowledgeServiceDeleteDocumentArgs() *KnowledgeServiceDeleteDocumentArgs {
	return &KnowledgeServiceDeleteDocumentArgs{}
}

func (p *KnowledgeServiceDeleteDocumentArgs) InitDefault() {
}

var KnowledgeServiceDeleteDocumentArgs_Req_DEFAULT *base.IDReq

func (p *KnowledgeServiceDeleteDocumentArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceDeleteDocumentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceDeleteDocumentArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *KnowledgeServiceDeleteDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceDeleteDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceDeleteDocumentArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceDeleteDocumentArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceDeleteDocumentResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewKnowledgeServiceDeleteDocumentResult() *KnowledgeServiceDeleteDocumentResult {
	return &KnowledgeServiceDeleteDocumentResult{}
}

func (p *KnowledgeServiceDeleteDocumentResult) InitDefault() {
}

var KnowledgeServiceDeleteDocumentResult_Success_DEFAULT *base.Empty

func (p *KnowledgeServiceDeleteDocumentResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceDeleteDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceDeleteDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *KnowledgeServiceDeleteDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceDeleteDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceDeleteDocumentResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceDeleteDocumentResult = map[int16]string{
	0: "success",
}

type KnowledgeServicePreviewChunksArgs struct {
	Req *PreviewChunksReq `thrift:"req,1" frugal:"1,default,PreviewChunksReq" json:"req"`
}

func NewKnowledgeServicePreviewChunksArgs() *KnowledgeServicePreviewChunksArgs {
	return &KnowledgeServicePreviewChunksArgs{}
}

func (p *KnowledgeServicePreviewChunksArgs) InitDefault() {
}

var KnowledgeServicePreviewChunksArgs_Req_DEFAULT *PreviewChunksReq

func (p *KnowledgeServicePreviewChunksArgs) GetReq() (v *PreviewChunksReq) {
	if !p.IsSetReq() {
		return KnowledgeServicePreviewChunksArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServicePreviewChunksArgs) SetReq(val *PreviewChunksReq) {
	p.Req = val
}

func (p *KnowledgeServicePreviewChunksArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServicePreviewChunksArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServicePreviewChunksArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServicePreviewChunksArgs = map[int16]string{
	1: "req",
}

type KnowledgeServicePreviewChunksResult struct {
	Success *PreviewChunksResp `thrift:"success,0,optional" frugal:"0,optional,PreviewChunksResp" json:"success,omitempty"`
}

func NewKnowledgeServicePreviewChunksResult() *KnowledgeServicePreviewChunksResult {
	return &KnowledgeServicePreviewChunksResult{}
}

func (p *KnowledgeServicePreviewChunksResult) InitDefault() {
}

var KnowledgeServicePreviewChunksResult_Success_DEFAULT *PreviewChunksResp

func (p *KnowledgeServicePreviewChunksResult) GetSuccess() (v *PreviewChunksResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServicePreviewChunksResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServicePreviewChunksResult) SetSuccess(x interface{}) {
	p.Success = x.(*PreviewChunksResp)
}

func (p *KnowledgeServicePreviewChunksResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServicePreviewChunksResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServicePreviewChunksResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServicePreviewChunksResult = map[int16]string{
	0: "success",
}
