// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package usersvc

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/aiagt/aiagt/kitex_gen/base"
)

type CaptchaType int64

const (
	CaptchaType_AUTH  CaptchaType = 0
	CaptchaType_RESET CaptchaType = 1
)

func (p CaptchaType) String() string {
	switch p {
	case CaptchaType_AUTH:
		return "AUTH"
	case CaptchaType_RESET:
		return "RESET"
	}
	return "<UNSET>"
}

func CaptchaTypeFromString(s string) (CaptchaType, error) {
	switch s {
	case "AUTH":
		return CaptchaType_AUTH, nil
	case "RESET":
		return CaptchaType_RESET, nil
	}
	return CaptchaType(0), fmt.Errorf("not a valid CaptchaType string")
}

func CaptchaTypePtr(v CaptchaType) *CaptchaType { return &v }
func (p *CaptchaType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = CaptchaType(result.Int64)
	return
}

func (p *CaptchaType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type User struct {
	Id            int64      `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Username      string     `thrift:"username,2,required" frugal:"2,required,string" json:"username"`
	Email         string     `thrift:"email,3,required" frugal:"3,required,string" json:"email"`
	PhoneNumber   string     `thrift:"phone_number,4,required" frugal:"4,required,string" json:"phone_number"`
	Signature     string     `thrift:"signature,5,required" frugal:"5,required,string" json:"signature"`
	Homepage      string     `thrift:"homepage,6,required" frugal:"6,required,string" json:"homepage"`
	DescriptionMd string     `thrift:"description_md,7,required" frugal:"7,required,string" json:"description_md"`
	Github        string     `thrift:"github,8,required" frugal:"8,required,string" json:"github"`
	Avatar        string     `thrift:"avatar,9,required" frugal:"9,required,string" json:"avatar"`
	CreatedAt     *base.Time `thrift:"created_at,10,required" frugal:"10,required,base.Time" json:"created_at"`
	UpdatedAt     *base.Time `thrift:"updated_at,11,required" frugal:"11,required,base.Time" json:"updated_at"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetPhoneNumber() (v string) {
	return p.PhoneNumber
}

func (p *User) GetSignature() (v string) {
	return p.Signature
}

func (p *User) GetHomepage() (v string) {
	return p.Homepage
}

func (p *User) GetDescriptionMd() (v string) {
	return p.DescriptionMd
}

func (p *User) GetGithub() (v string) {
	return p.Github
}

func (p *User) GetAvatar() (v string) {
	return p.Avatar
}

var User_CreatedAt_DEFAULT *base.Time

func (p *User) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return User_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}

var User_UpdatedAt_DEFAULT *base.Time

func (p *User) GetUpdatedAt() (v *base.Time) {
	if !p.IsSetUpdatedAt() {
		return User_UpdatedAt_DEFAULT
	}
	return p.UpdatedAt
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetPhoneNumber(val string) {
	p.PhoneNumber = val
}
func (p *User) SetSignature(val string) {
	p.Signature = val
}
func (p *User) SetHomepage(val string) {
	p.Homepage = val
}
func (p *User) SetDescriptionMd(val string) {
	p.DescriptionMd = val
}
func (p *User) SetGithub(val string) {
	p.Github = val
}
func (p *User) SetAvatar(val string) {
	p.Avatar = val
}
func (p *User) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}
func (p *User) SetUpdatedAt(val *base.Time) {
	p.UpdatedAt = val
}

func (p *User) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *User) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1:  "id",
	2:  "username",
	3:  "email",
	4:  "phone_number",
	5:  "signature",
	6:  "homepage",
	7:  "description_md",
	8:  "github",
	9:  "avatar",
	10: "created_at",
	11: "updated_at",
}

type Secret struct {
	Id         int64      `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	UserId     int64      `thrift:"user_id,2,required" frugal:"2,required,i64" json:"user_id"`
	PluginId   int64      `thrift:"plugin_id,3,required" frugal:"3,required,i64" json:"plugin_id"`
	Name       string     `thrift:"name,4,required" frugal:"4,required,string" json:"name"`
	Value      string     `thrift:"value,5,required" frugal:"5,required,string" json:"value"`
	CreatedAt  *base.Time `thrift:"created_at,6,required" frugal:"6,required,base.Time" json:"created_at"`
	UpdatedAt  *base.Time `thrift:"updated_at,7,required" frugal:"7,required,base.Time" json:"updated_at"`
	PluginName *string    `thrift:"plugin_name,8,optional" frugal:"8,optional,string" json:"plugin_name,omitempty"`
	PluginLogo *string    `thrift:"plugin_logo,9,optional" frugal:"9,optional,string" json:"plugin_logo,omitempty"`
}

func NewSecret() *Secret {
	return &Secret{}
}

func (p *Secret) InitDefault() {
}

func (p *Secret) GetId() (v int64) {
	return p.Id
}

func (p *Secret) GetUserId() (v int64) {
	return p.UserId
}

func (p *Secret) GetPluginId() (v int64) {
	return p.PluginId
}

func (p *Secret) GetName() (v string) {
	return p.Name
}

func (p *Secret) GetValue() (v string) {
	return p.Value
}

var Secret_CreatedAt_DEFAULT *base.Time

func (p *Secret) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return Secret_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}

var Secret_UpdatedAt_DEFAULT *base.Time

func (p *Secret) GetUpdatedAt() (v *base.Time) {
	if !p.IsSetUpdatedAt() {
		return Secret_UpdatedAt_DEFAULT
	}
	return p.UpdatedAt
}

var Secret_PluginName_DEFAULT string

func (p *Secret) GetPluginName() (v string) {
	if !p.IsSetPluginName() {
		return Secret_PluginName_DEFAULT
	}
	return *p.PluginName
}

var Secret_PluginLogo_DEFAULT string

func (p *Secret) GetPluginLogo() (v string) {
	if !p.IsSetPluginLogo() {
		return Secret_PluginLogo_DEFAULT
	}
	return *p.PluginLogo
}
func (p *Secret) SetId(val int64) {
	p.Id = val
}
func (p *Secret) SetUserId(val int64) {
	p.UserId = val
}
func (p *Secret) SetPluginId(val int64) {
	p.PluginId = val
}
func (p *Secret) SetName(val string) {
	p.Name = val
}
func (p *Secret) SetValue(val string) {
	p.Value = val
}
func (p *Secret) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}
func (p *Secret) SetUpdatedAt(val *base.Time) {
	p.UpdatedAt = val
}
func (p *Secret) SetPluginName(val *string) {
	p.PluginName = val
}
func (p *Secret) SetPluginLogo(val *string) {
	p.PluginLogo = val
}

func (p *Secret) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *Secret) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *Secret) IsSetPluginName() bool {
	return p.PluginName != nil
}

func (p *Secret) IsSetPluginLogo() bool {
	return p.PluginLogo != nil
}

func (p *Secret) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Secret(%+v)", *p)
}

var fieldIDToName_Secret = map[int16]string{
	1: "id",
	2: "user_id",
	3: "plugin_id",
	4: "name",
	5: "value",
	6: "created_at",
	7: "updated_at",
	8: "plugin_name",
	9: "plugin_logo",
}

type RegisterReq struct {
	Email    string  `thrift:"email,1,required" frugal:"1,required,string" json:"email"`
	Captcha  string  `thrift:"captcha,2,required" frugal:"2,required,string" json:"captcha"`
	Username *string `thrift:"username,3,optional" frugal:"3,optional,string" json:"username,omitempty"`
	Password *string `thrift:"password,4,optional" frugal:"4,optional,string" json:"password,omitempty"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetEmail() (v string) {
	return p.Email
}

func (p *RegisterReq) GetCaptcha() (v string) {
	return p.Captcha
}

var RegisterReq_Username_DEFAULT string

func (p *RegisterReq) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return RegisterReq_Username_DEFAULT
	}
	return *p.Username
}

var RegisterReq_Password_DEFAULT string

func (p *RegisterReq) GetPassword() (v string) {
	if !p.IsSetPassword() {
		return RegisterReq_Password_DEFAULT
	}
	return *p.Password
}
func (p *RegisterReq) SetEmail(val string) {
	p.Email = val
}
func (p *RegisterReq) SetCaptcha(val string) {
	p.Captcha = val
}
func (p *RegisterReq) SetUsername(val *string) {
	p.Username = val
}
func (p *RegisterReq) SetPassword(val *string) {
	p.Password = val
}

func (p *RegisterReq) IsSetUsername() bool {
	return p.Username != nil
}

func (p *RegisterReq) IsSetPassword() bool {
	return p.Password != nil
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "email",
	2: "captcha",
	3: "username",
	4: "password",
}

type RegisterResp struct {
	Token  string     `thrift:"token,1,required" frugal:"1,required,string" json:"token"`
	Expire *base.Time `thrift:"expire,2,required" frugal:"2,required,base.Time" json:"expire"`
	User   *User      `thrift:"user,3,required" frugal:"3,required,User" json:"user"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

func (p *RegisterResp) GetToken() (v string) {
	return p.Token
}

var RegisterResp_Expire_DEFAULT *base.Time

func (p *RegisterResp) GetExpire() (v *base.Time) {
	if !p.IsSetExpire() {
		return RegisterResp_Expire_DEFAULT
	}
	return p.Expire
}

var RegisterResp_User_DEFAULT *User

func (p *RegisterResp) GetUser() (v *User) {
	if !p.IsSetUser() {
		return RegisterResp_User_DEFAULT
	}
	return p.User
}
func (p *RegisterResp) SetToken(val string) {
	p.Token = val
}
func (p *RegisterResp) SetExpire(val *base.Time) {
	p.Expire = val
}
func (p *RegisterResp) SetUser(val *User) {
	p.User = val
}

func (p *RegisterResp) IsSetExpire() bool {
	return p.Expire != nil
}

func (p *RegisterResp) IsSetUser() bool {
	return p.User != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "token",
	2: "expire",
	3: "user",
}

type LoginReq struct {
	Email    string  `thrift:"email,1,required" frugal:"1,required,string" json:"email"`
	Password *string `thrift:"password,2,optional" frugal:"2,optional,string" json:"password,omitempty"`
	Captcha  *string `thrift:"captcha,3,optional" frugal:"3,optional,string" json:"captcha,omitempty"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetEmail() (v string) {
	return p.Email
}

var LoginReq_Password_DEFAULT string

func (p *LoginReq) GetPassword() (v string) {
	if !p.IsSetPassword() {
		return LoginReq_Password_DEFAULT
	}
	return *p.Password
}

var LoginReq_Captcha_DEFAULT string

func (p *LoginReq) GetCaptcha() (v string) {
	if !p.IsSetCaptcha() {
		return LoginReq_Captcha_DEFAULT
	}
	return *p.Captcha
}
func (p *LoginReq) SetEmail(val string) {
	p.Email = val
}
func (p *LoginReq) SetPassword(val *string) {
	p.Password = val
}
func (p *LoginReq) SetCaptcha(val *string) {
	p.Captcha = val
}

func (p *LoginReq) IsSetPassword() bool {
	return p.Password != nil
}

func (p *LoginReq) IsSetCaptcha() bool {
	return p.Captcha != nil
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "email",
	2: "password",
	3: "captcha",
}

type LoginResp struct {
	Token  string     `thrift:"token,1,required" frugal:"1,required,string" json:"token"`
	Expire *base.Time `thrift:"expire,2,required" frugal:"2,required,base.Time" json:"expire"`
	User   *User      `thrift:"user,3,required" frugal:"3,required,User" json:"user"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

func (p *LoginResp) GetToken() (v string) {
	return p.Token
}

var LoginResp_Expire_DEFAULT *base.Time

func (p *LoginResp) GetExpire() (v *base.Time) {
	if !p.IsSetExpire() {
		return LoginResp_Expire_DEFAULT
	}
	return p.Expire
}

var LoginResp_User_DEFAULT *User

func (p *LoginResp) GetUser() (v *User) {
	if !p.IsSetUser() {
		return LoginResp_User_DEFAULT
	}
	return p.User
}
func (p *LoginResp) SetToken(val string) {
	p.Token = val
}
func (p *LoginResp) SetExpire(val *base.Time) {
	p.Expire = val
}
func (p *LoginResp) SetUser(val *User) {
	p.User = val
}

func (p *LoginResp) IsSetExpire() bool {
	return p.Expire != nil
}

func (p *LoginResp) IsSetUser() bool {
	return p.User != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "token",
	2: "expire",
	3: "user",
}

type UpdateUserReq struct {
	Username      *string `thrift:"username,1,optional" frugal:"1,optional,string" json:"username,omitempty"`
	Email         *string `thrift:"email,2,optional" frugal:"2,optional,string" json:"email,omitempty"`
	PhoneNumber   *string `thrift:"phone_number,3,optional" frugal:"3,optional,string" json:"phone_number,omitempty"`
	Signature     *string `thrift:"signature,4,optional" frugal:"4,optional,string" json:"signature,omitempty"`
	Homepage      *string `thrift:"homepage,5,optional" frugal:"5,optional,string" json:"homepage,omitempty"`
	DescriptionMd *string `thrift:"description_md,6,optional" frugal:"6,optional,string" json:"description_md,omitempty"`
	Github        *string `thrift:"github,7,optional" frugal:"7,optional,string" json:"github,omitempty"`
	Avatar        *string `thrift:"avatar,8,optional" frugal:"8,optional,string" json:"avatar,omitempty"`
}

func NewUpdateUserReq() *UpdateUserReq {
	return &UpdateUserReq{}
}

func (p *UpdateUserReq) InitDefault() {
}

var UpdateUserReq_Username_DEFAULT string

func (p *UpdateUserReq) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return UpdateUserReq_Username_DEFAULT
	}
	return *p.Username
}

var UpdateUserReq_Email_DEFAULT string

func (p *UpdateUserReq) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return UpdateUserReq_Email_DEFAULT
	}
	return *p.Email
}

var UpdateUserReq_PhoneNumber_DEFAULT string

func (p *UpdateUserReq) GetPhoneNumber() (v string) {
	if !p.IsSetPhoneNumber() {
		return UpdateUserReq_PhoneNumber_DEFAULT
	}
	return *p.PhoneNumber
}

var UpdateUserReq_Signature_DEFAULT string

func (p *UpdateUserReq) GetSignature() (v string) {
	if !p.IsSetSignature() {
		return UpdateUserReq_Signature_DEFAULT
	}
	return *p.Signature
}

var UpdateUserReq_Homepage_DEFAULT string

func (p *UpdateUserReq) GetHomepage() (v string) {
	if !p.IsSetHomepage() {
		return UpdateUserReq_Homepage_DEFAULT
	}
	return *p.Homepage
}

var UpdateUserReq_DescriptionMd_DEFAULT string

func (p *UpdateUserReq) GetDescriptionMd() (v string) {
	if !p.IsSetDescriptionMd() {
		return UpdateUserReq_DescriptionMd_DEFAULT
	}
	return *p.DescriptionMd
}

var UpdateUserReq_Github_DEFAULT string

func (p *UpdateUserReq) GetGithub() (v string) {
	if !p.IsSetGithub() {
		return UpdateUserReq_Github_DEFAULT
	}
	return *p.Github
}

var UpdateUserReq_Avatar_DEFAULT string

func (p *UpdateUserReq) GetAvatar() (v string) {
	if !p.IsSetAvatar() {
		return UpdateUserReq_Avatar_DEFAULT
	}
	return *p.Avatar
}
func (p *UpdateUserReq) SetUsername(val *string) {
	p.Username = val
}
func (p *UpdateUserReq) SetEmail(val *string) {
	p.Email = val
}
func (p *UpdateUserReq) SetPhoneNumber(val *string) {
	p.PhoneNumber = val
}
func (p *UpdateUserReq) SetSignature(val *string) {
	p.Signature = val
}
func (p *UpdateUserReq) SetHomepage(val *string) {
	p.Homepage = val
}
func (p *UpdateUserReq) SetDescriptionMd(val *string) {
	p.DescriptionMd = val
}
func (p *UpdateUserReq) SetGithub(val *string) {
	p.Github = val
}
func (p *UpdateUserReq) SetAvatar(val *string) {
	p.Avatar = val
}

func (p *UpdateUserReq) IsSetUsername() bool {
	return p.Username != nil
}

func (p *UpdateUserReq) IsSetEmail() bool {
	return p.Email != nil
}

func (p *UpdateUserReq) IsSetPhoneNumber() bool {
	return p.PhoneNumber != nil
}

func (p *UpdateUserReq) IsSetSignature() bool {
	return p.Signature != nil
}

func (p *UpdateUserReq) IsSetHomepage() bool {
	return p.Homepage != nil
}

func (p *UpdateUserReq) IsSetDescriptionMd() bool {
	return p.DescriptionMd != nil
}

func (p *UpdateUserReq) IsSetGithub() bool {
	return p.Github != nil
}

func (p *UpdateUserReq) IsSetAvatar() bool {
	return p.Avatar != nil
}

func (p *UpdateUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserReq(%+v)", *p)
}

var fieldIDToName_UpdateUserReq = map[int16]string{
	1: "username",
	2: "email",
	3: "phone_number",
	4: "signature",
	5: "homepage",
	6: "description_md",
	7: "github",
	8: "avatar",
}

type ResetPasswordReq struct {
	Email    string `thrift:"email,1,required" frugal:"1,required,string" json:"email"`
	Captcha  string `thrift:"captcha,2,required" frugal:"2,required,string" json:"captcha"`
	Password string `thrift:"password,3,required" frugal:"3,required,string" json:"password"`
}

func NewResetPasswordReq() *ResetPasswordReq {
	return &ResetPasswordReq{}
}

func (p *ResetPasswordReq) InitDefault() {
}

func (p *ResetPasswordReq) GetEmail() (v string) {
	return p.Email
}

func (p *ResetPasswordReq) GetCaptcha() (v string) {
	return p.Captcha
}

func (p *ResetPasswordReq) GetPassword() (v string) {
	return p.Password
}
func (p *ResetPasswordReq) SetEmail(val string) {
	p.Email = val
}
func (p *ResetPasswordReq) SetCaptcha(val string) {
	p.Captcha = val
}
func (p *ResetPasswordReq) SetPassword(val string) {
	p.Password = val
}

func (p *ResetPasswordReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResetPasswordReq(%+v)", *p)
}

var fieldIDToName_ResetPasswordReq = map[int16]string{
	1: "email",
	2: "captcha",
	3: "password",
}

type SaveSecretReqItem struct {
	PluginId int64  `thrift:"plugin_id,1,required" frugal:"1,required,i64" json:"plugin_id"`
	Name     string `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Value    string `thrift:"value,3,required" frugal:"3,required,string" json:"value"`
}

func NewSaveSecretReqItem() *SaveSecretReqItem {
	return &SaveSecretReqItem{}
}

func (p *SaveSecretReqItem) InitDefault() {
}

func (p *SaveSecretReqItem) GetPluginId() (v int64) {
	return p.PluginId
}

func (p *SaveSecretReqItem) GetName() (v string) {
	return p.Name
}

func (p *SaveSecretReqItem) GetValue() (v string) {
	return p.Value
}
func (p *SaveSecretReqItem) SetPluginId(val int64) {
	p.PluginId = val
}
func (p *SaveSecretReqItem) SetName(val string) {
	p.Name = val
}
func (p *SaveSecretReqItem) SetValue(val string) {
	p.Value = val
}

func (p *SaveSecretReqItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SaveSecretReqItem(%+v)", *p)
}

var fieldIDToName_SaveSecretReqItem = map[int16]string{
	1: "plugin_id",
	2: "name",
	3: "value",
}

type SaveSecretReq struct {
	Secrets []*SaveSecretReqItem `thrift:"secrets,1,required" frugal:"1,required,list<SaveSecretReqItem>" json:"secrets"`
}

func NewSaveSecretReq() *SaveSecretReq {
	return &SaveSecretReq{}
}

func (p *SaveSecretReq) InitDefault() {
}

func (p *SaveSecretReq) GetSecrets() (v []*SaveSecretReqItem) {
	return p.Secrets
}
func (p *SaveSecretReq) SetSecrets(val []*SaveSecretReqItem) {
	p.Secrets = val
}

func (p *SaveSecretReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SaveSecretReq(%+v)", *p)
}

var fieldIDToName_SaveSecretReq = map[int16]string{
	1: "secrets",
}

type ListSecretReq struct {
	Pagination *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	PluginId   *int64              `thrift:"plugin_id,2,optional" frugal:"2,optional,i64" json:"plugin_id,omitempty"`
	PluginIds  []int64             `thrift:"plugin_ids,3,optional" frugal:"3,optional,list<i64>" json:"plugin_ids,omitempty"`
	Name       *string             `thrift:"name,4,optional" frugal:"4,optional,string" json:"name,omitempty"`
}

func NewListSecretReq() *ListSecretReq {
	return &ListSecretReq{}
}

func (p *ListSecretReq) InitDefault() {
}

var ListSecretReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListSecretReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListSecretReq_Pagination_DEFAULT
	}
	return p.Pagination
}

var ListSecretReq_PluginId_DEFAULT int64

func (p *ListSecretReq) GetPluginId() (v int64) {
	if !p.IsSetPluginId() {
		return ListSecretReq_PluginId_DEFAULT
	}
	return *p.PluginId
}

var ListSecretReq_PluginIds_DEFAULT []int64

func (p *ListSecretReq) GetPluginIds() (v []int64) {
	if !p.IsSetPluginIds() {
		return ListSecretReq_PluginIds_DEFAULT
	}
	return p.PluginIds
}

var ListSecretReq_Name_DEFAULT string

func (p *ListSecretReq) GetName() (v string) {
	if !p.IsSetName() {
		return ListSecretReq_Name_DEFAULT
	}
	return *p.Name
}
func (p *ListSecretReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListSecretReq) SetPluginId(val *int64) {
	p.PluginId = val
}
func (p *ListSecretReq) SetPluginIds(val []int64) {
	p.PluginIds = val
}
func (p *ListSecretReq) SetName(val *string) {
	p.Name = val
}

func (p *ListSecretReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListSecretReq) IsSetPluginId() bool {
	return p.PluginId != nil
}

func (p *ListSecretReq) IsSetPluginIds() bool {
	return p.PluginIds != nil
}

func (p *ListSecretReq) IsSetName() bool {
	return p.Name != nil
}

func (p *ListSecretReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListSecretReq(%+v)", *p)
}

var fieldIDToName_ListSecretReq = map[int16]string{
	1: "pagination",
	2: "plugin_id",
	3: "plugin_ids",
	4: "name",
}

type ListSecretResp struct {
	Pagination *base.PaginationResp `thrift:"pagination,1,required" frugal:"1,required,base.PaginationResp" json:"pagination"`
	Secrets    []*Secret            `thrift:"secrets,2,required" frugal:"2,required,list<Secret>" json:"secrets"`
}

func NewListSecretResp() *ListSecretResp {
	return &ListSecretResp{}
}

func (p *ListSecretResp) InitDefault() {
}

var ListSecretResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListSecretResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListSecretResp_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListSecretResp) GetSecrets() (v []*Secret) {
	return p.Secrets
}
func (p *ListSecretResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}
func (p *ListSecretResp) SetSecrets(val []*Secret) {
	p.Secrets = val
}

func (p *ListSecretResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListSecretResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListSecretResp(%+v)", *p)
}

var fieldIDToName_ListSecretResp = map[int16]string{
	1: "pagination",
	2: "secrets",
}

type SendCaptchaReq struct {
	Email string      `thrift:"email,1,required" frugal:"1,required,string" json:"email"`
	Type  CaptchaType `thrift:"type,2,required" frugal:"2,required,CaptchaType" json:"type"`
}

func NewSendCaptchaReq() *SendCaptchaReq {
	return &SendCaptchaReq{}
}

func (p *SendCaptchaReq) InitDefault() {
}

func (p *SendCaptchaReq) GetEmail() (v string) {
	return p.Email
}

func (p *SendCaptchaReq) GetType() (v CaptchaType) {
	return p.Type
}
func (p *SendCaptchaReq) SetEmail(val string) {
	p.Email = val
}
func (p *SendCaptchaReq) SetType(val CaptchaType) {
	p.Type = val
}

func (p *SendCaptchaReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendCaptchaReq(%+v)", *p)
}

var fieldIDToName_SendCaptchaReq = map[int16]string{
	1: "email",
	2: "type",
}

type SendCaptchaResp struct {
	Exists bool `thrift:"exists,1,required" frugal:"1,required,bool" json:"exists"`
}

func NewSendCaptchaResp() *SendCaptchaResp {
	return &SendCaptchaResp{}
}

func (p *SendCaptchaResp) InitDefault() {
}

func (p *SendCaptchaResp) GetExists() (v bool) {
	return p.Exists
}
func (p *SendCaptchaResp) SetExists(val bool) {
	p.Exists = val
}

func (p *SendCaptchaResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendCaptchaResp(%+v)", *p)
}

var fieldIDToName_SendCaptchaResp = map[int16]string{
	1: "exists",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	GenToken(ctx context.Context, token int64) (r string, err error)

	ParseToken(ctx context.Context, token string) (r int64, err error)

	ResetPassword(ctx context.Context, req *ResetPasswordReq) (r *base.Empty, err error)

	SendCaptcha(ctx context.Context, req *SendCaptchaReq) (r *SendCaptchaResp, err error)

	UpdateUser(ctx context.Context, req *UpdateUserReq) (r *base.Empty, err error)

	GetUser(ctx context.Context) (r *User, err error)

	GetUserByID(ctx context.Context, req *base.IDReq) (r *User, err error)

	GetUserByIds(ctx context.Context, req *base.IDsReq) (r []*User, err error)

	SaveSecrets(ctx context.Context, req *SaveSecretReq) (r *base.Empty, err error)

	DeleteSecret(ctx context.Context, req *base.IDReq) (r *base.Empty, err error)

	ListSecret(ctx context.Context, req *ListSecretReq) (r *ListSecretResp, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResp

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceGenTokenArgs struct {
	Token int64 `thrift:"token,1" frugal:"1,default,i64" json:"token"`
}

func NewUserServiceGenTokenArgs() *UserServiceGenTokenArgs {
	return &UserServiceGenTokenArgs{}
}

func (p *UserServiceGenTokenArgs) InitDefault() {
}

func (p *UserServiceGenTokenArgs) GetToken() (v int64) {
	return p.Token
}
func (p *UserServiceGenTokenArgs) SetToken(val int64) {
	p.Token = val
}

func (p *UserServiceGenTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGenTokenArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGenTokenArgs = map[int16]string{
	1: "token",
}

type UserServiceGenTokenResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewUserServiceGenTokenResult() *UserServiceGenTokenResult {
	return &UserServiceGenTokenResult{}
}

func (p *UserServiceGenTokenResult) InitDefault() {
}

var UserServiceGenTokenResult_Success_DEFAULT string

func (p *UserServiceGenTokenResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return UserServiceGenTokenResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceGenTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *UserServiceGenTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGenTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGenTokenResult(%+v)", *p)
}

var fieldIDToName_UserServiceGenTokenResult = map[int16]string{
	0: "success",
}

type UserServiceParseTokenArgs struct {
	Token string `thrift:"token,1" frugal:"1,default,string" json:"token"`
}

func NewUserServiceParseTokenArgs() *UserServiceParseTokenArgs {
	return &UserServiceParseTokenArgs{}
}

func (p *UserServiceParseTokenArgs) InitDefault() {
}

func (p *UserServiceParseTokenArgs) GetToken() (v string) {
	return p.Token
}
func (p *UserServiceParseTokenArgs) SetToken(val string) {
	p.Token = val
}

func (p *UserServiceParseTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceParseTokenArgs(%+v)", *p)
}

var fieldIDToName_UserServiceParseTokenArgs = map[int16]string{
	1: "token",
}

type UserServiceParseTokenResult struct {
	Success *int64 `thrift:"success,0,optional" frugal:"0,optional,i64" json:"success,omitempty"`
}

func NewUserServiceParseTokenResult() *UserServiceParseTokenResult {
	return &UserServiceParseTokenResult{}
}

func (p *UserServiceParseTokenResult) InitDefault() {
}

var UserServiceParseTokenResult_Success_DEFAULT int64

func (p *UserServiceParseTokenResult) GetSuccess() (v int64) {
	if !p.IsSetSuccess() {
		return UserServiceParseTokenResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceParseTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*int64)
}

func (p *UserServiceParseTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceParseTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceParseTokenResult(%+v)", *p)
}

var fieldIDToName_UserServiceParseTokenResult = map[int16]string{
	0: "success",
}

type UserServiceResetPasswordArgs struct {
	Req *ResetPasswordReq `thrift:"req,1" frugal:"1,default,ResetPasswordReq" json:"req"`
}

func NewUserServiceResetPasswordArgs() *UserServiceResetPasswordArgs {
	return &UserServiceResetPasswordArgs{}
}

func (p *UserServiceResetPasswordArgs) InitDefault() {
}

var UserServiceResetPasswordArgs_Req_DEFAULT *ResetPasswordReq

func (p *UserServiceResetPasswordArgs) GetReq() (v *ResetPasswordReq) {
	if !p.IsSetReq() {
		return UserServiceResetPasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceResetPasswordArgs) SetReq(val *ResetPasswordReq) {
	p.Req = val
}

func (p *UserServiceResetPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceResetPasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPasswordArgs(%+v)", *p)
}

var fieldIDToName_UserServiceResetPasswordArgs = map[int16]string{
	1: "req",
}

type UserServiceResetPasswordResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewUserServiceResetPasswordResult() *UserServiceResetPasswordResult {
	return &UserServiceResetPasswordResult{}
}

func (p *UserServiceResetPasswordResult) InitDefault() {
}

var UserServiceResetPasswordResult_Success_DEFAULT *base.Empty

func (p *UserServiceResetPasswordResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return UserServiceResetPasswordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceResetPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *UserServiceResetPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceResetPasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPasswordResult(%+v)", *p)
}

var fieldIDToName_UserServiceResetPasswordResult = map[int16]string{
	0: "success",
}

type UserServiceSendCaptchaArgs struct {
	Req *SendCaptchaReq `thrift:"req,1" frugal:"1,default,SendCaptchaReq" json:"req"`
}

func NewUserServiceSendCaptchaArgs() *UserServiceSendCaptchaArgs {
	return &UserServiceSendCaptchaArgs{}
}

func (p *UserServiceSendCaptchaArgs) InitDefault() {
}

var UserServiceSendCaptchaArgs_Req_DEFAULT *SendCaptchaReq

func (p *UserServiceSendCaptchaArgs) GetReq() (v *SendCaptchaReq) {
	if !p.IsSetReq() {
		return UserServiceSendCaptchaArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceSendCaptchaArgs) SetReq(val *SendCaptchaReq) {
	p.Req = val
}

func (p *UserServiceSendCaptchaArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceSendCaptchaArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSendCaptchaArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSendCaptchaArgs = map[int16]string{
	1: "req",
}

type UserServiceSendCaptchaResult struct {
	Success *SendCaptchaResp `thrift:"success,0,optional" frugal:"0,optional,SendCaptchaResp" json:"success,omitempty"`
}

func NewUserServiceSendCaptchaResult() *UserServiceSendCaptchaResult {
	return &UserServiceSendCaptchaResult{}
}

func (p *UserServiceSendCaptchaResult) InitDefault() {
}

var UserServiceSendCaptchaResult_Success_DEFAULT *SendCaptchaResp

func (p *UserServiceSendCaptchaResult) GetSuccess() (v *SendCaptchaResp) {
	if !p.IsSetSuccess() {
		return UserServiceSendCaptchaResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceSendCaptchaResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendCaptchaResp)
}

func (p *UserServiceSendCaptchaResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSendCaptchaResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSendCaptchaResult(%+v)", *p)
}

var fieldIDToName_UserServiceSendCaptchaResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserArgs struct {
	Req *UpdateUserReq `thrift:"req,1" frugal:"1,default,UpdateUserReq" json:"req"`
}

func NewUserServiceUpdateUserArgs() *UserServiceUpdateUserArgs {
	return &UserServiceUpdateUserArgs{}
}

func (p *UserServiceUpdateUserArgs) InitDefault() {
}

var UserServiceUpdateUserArgs_Req_DEFAULT *UpdateUserReq

func (p *UserServiceUpdateUserArgs) GetReq() (v *UpdateUserReq) {
	if !p.IsSetReq() {
		return UserServiceUpdateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateUserArgs) SetReq(val *UpdateUserReq) {
	p.Req = val
}

func (p *UserServiceUpdateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateUserResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewUserServiceUpdateUserResult() *UserServiceUpdateUserResult {
	return &UserServiceUpdateUserResult{}
}

func (p *UserServiceUpdateUserResult) InitDefault() {
}

var UserServiceUpdateUserResult_Success_DEFAULT *base.Empty

func (p *UserServiceUpdateUserResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *UserServiceUpdateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserArgs struct {
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{}

type UserServiceGetUserResult struct {
	Success *User `thrift:"success,0,optional" frugal:"0,optional,User" json:"success,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *User

func (p *UserServiceGetUserResult) GetSuccess() (v *User) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*User)
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserByIDArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewUserServiceGetUserByIDArgs() *UserServiceGetUserByIDArgs {
	return &UserServiceGetUserByIDArgs{}
}

func (p *UserServiceGetUserByIDArgs) InitDefault() {
}

var UserServiceGetUserByIDArgs_Req_DEFAULT *base.IDReq

func (p *UserServiceGetUserByIDArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserByIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserByIDArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *UserServiceGetUserByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserByIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserByIDArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserByIDArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserByIDResult struct {
	Success *User `thrift:"success,0,optional" frugal:"0,optional,User" json:"success,omitempty"`
}

func NewUserServiceGetUserByIDResult() *UserServiceGetUserByIDResult {
	return &UserServiceGetUserByIDResult{}
}

func (p *UserServiceGetUserByIDResult) InitDefault() {
}

var UserServiceGetUserByIDResult_Success_DEFAULT *User

func (p *UserServiceGetUserByIDResult) GetSuccess() (v *User) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserByIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*User)
}

func (p *UserServiceGetUserByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserByIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserByIDResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserByIDResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserByIdsArgs struct {
	Req *base.IDsReq `thrift:"req,1" frugal:"1,default,base.IDsReq" json:"req"`
}

func NewUserServiceGetUserByIdsArgs() *UserServiceGetUserByIdsArgs {
	return &UserServiceGetUserByIdsArgs{}
}

func (p *UserServiceGetUserByIdsArgs) InitDefault() {
}

var UserServiceGetUserByIdsArgs_Req_DEFAULT *base.IDsReq

func (p *UserServiceGetUserByIdsArgs) GetReq() (v *base.IDsReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserByIdsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserByIdsArgs) SetReq(val *base.IDsReq) {
	p.Req = val
}

func (p *UserServiceGetUserByIdsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserByIdsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserByIdsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserByIdsArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserByIdsResult struct {
	Success []*User `thrift:"success,0,optional" frugal:"0,optional,list<User>" json:"success,omitempty"`
}

func NewUserServiceGetUserByIdsResult() *UserServiceGetUserByIdsResult {
	return &UserServiceGetUserByIdsResult{}
}

func (p *UserServiceGetUserByIdsResult) InitDefault() {
}

var UserServiceGetUserByIdsResult_Success_DEFAULT []*User

func (p *UserServiceGetUserByIdsResult) GetSuccess() (v []*User) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserByIdsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserByIdsResult) SetSuccess(x interface{}) {
	p.Success = x.([]*User)
}

func (p *UserServiceGetUserByIdsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserByIdsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserByIdsResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserByIdsResult = map[int16]string{
	0: "success",
}

type UserServiceSaveSecretsArgs struct {
	Req *SaveSecretReq `thrift:"req,1" frugal:"1,default,SaveSecretReq" json:"req"`
}

func NewUserServiceSaveSecretsArgs() *UserServiceSaveSecretsArgs {
	return &UserServiceSaveSecretsArgs{}
}

func (p *UserServiceSaveSecretsArgs) InitDefault() {
}

var UserServiceSaveSecretsArgs_Req_DEFAULT *SaveSecretReq

func (p *UserServiceSaveSecretsArgs) GetReq() (v *SaveSecretReq) {
	if !p.IsSetReq() {
		return UserServiceSaveSecretsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceSaveSecretsArgs) SetReq(val *SaveSecretReq) {
	p.Req = val
}

func (p *UserServiceSaveSecretsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceSaveSecretsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSaveSecretsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSaveSecretsArgs = map[int16]string{
	1: "req",
}

type UserServiceSaveSecretsResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewUserServiceSaveSecretsResult() *UserServiceSaveSecretsResult {
	return &UserServiceSaveSecretsResult{}
}

func (p *UserServiceSaveSecretsResult) InitDefault() {
}

var UserServiceSaveSecretsResult_Success_DEFAULT *base.Empty

func (p *UserServiceSaveSecretsResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return UserServiceSaveSecretsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceSaveSecretsResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *UserServiceSaveSecretsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSaveSecretsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSaveSecretsResult(%+v)", *p)
}

var fieldIDToName_UserServiceSaveSecretsResult = map[int16]string{
	0: "success",
}

type UserServiceDeleteSecretArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewUserServiceDeleteSecretArgs() *UserServiceDeleteSecretArgs {
	return &UserServiceDeleteSecretArgs{}
}

func (p *UserServiceDeleteSecretArgs) InitDefault() {
}

var UserServiceDeleteSecretArgs_Req_DEFAULT *base.IDReq

func (p *UserServiceDeleteSecretArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return UserServiceDeleteSecretArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceDeleteSecretArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *UserServiceDeleteSecretArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceDeleteSecretArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteSecretArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteSecretArgs = map[int16]string{
	1: "req",
}

type UserServiceDeleteSecretResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewUserServiceDeleteSecretResult() *UserServiceDeleteSecretResult {
	return &UserServiceDeleteSecretResult{}
}

func (p *UserServiceDeleteSecretResult) InitDefault() {
}

var UserServiceDeleteSecretResult_Success_DEFAULT *base.Empty

func (p *UserServiceDeleteSecretResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteSecretResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceDeleteSecretResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *UserServiceDeleteSecretResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteSecretResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteSecretResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteSecretResult = map[int16]string{
	0: "success",
}

type UserServiceListSecretArgs struct {
	Req *ListSecretReq `thrift:"req,1" frugal:"1,default,ListSecretReq" json:"req"`
}

func NewUserServiceListSecretArgs() *UserServiceListSecretArgs {
	return &UserServiceListSecretArgs{}
}

func (p *UserServiceListSecretArgs) InitDefault() {
}

var UserServiceListSecretArgs_Req_DEFAULT *ListSecretReq

func (p *UserServiceListSecretArgs) GetReq() (v *ListSecretReq) {
	if !p.IsSetReq() {
		return UserServiceListSecretArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceListSecretArgs) SetReq(val *ListSecretReq) {
	p.Req = val
}

func (p *UserServiceListSecretArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceListSecretArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListSecretArgs(%+v)", *p)
}

var fieldIDToName_UserServiceListSecretArgs = map[int16]string{
	1: "req",
}

type UserServiceListSecretResult struct {
	Success *ListSecretResp `thrift:"success,0,optional" frugal:"0,optional,ListSecretResp" json:"success,omitempty"`
}

func NewUserServiceListSecretResult() *UserServiceListSecretResult {
	return &UserServiceListSecretResult{}
}

func (p *UserServiceListSecretResult) InitDefault() {
}

var UserServiceListSecretResult_Success_DEFAULT *ListSecretResp

func (p *UserServiceListSecretResult) GetSuccess() (v *ListSecretResp) {
	if !p.IsSetSuccess() {
		return UserServiceListSecretResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceListSecretResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListSecretResp)
}

func (p *UserServiceListSecretResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceListSecretResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListSecretResult(%+v)", *p)
}

var fieldIDToName_UserServiceListSecretResult = map[int16]string{
	0: "success",
}
