services:
  gateway:
    image: aiagt/aiagt-gateway:latest
    networks:
      - aiagt-network
    ports:
      - 80:80

  user:
    image: aiagt/aiagt-user:latest
    networks:
      - aiagt-network
    ports:
      - 8931:80

  plugin:
    image: aiagt/aiagt-plugin:latest
    networks:
      - aiagt-network
    ports:
      - 8932:80

  app:
    image: aiagt/aiagt-app:latest
    networks:
      - aiagt-network
    ports:
      - 8933:80

  chat:
    image: aiagt/aiagt-chat:latest
    networks:
      - aiagt-network
    ports:
      - 8934:80

  model:
    image: aiagt/aiagt-model:latest
    networks:
      - aiagt-network
    ports:
      - 8935:80

networks:
  aiagt-network:
    external: true