// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package appsvc

import (
	"context"
	"fmt"
	"github.com/aiagt/aiagt/kitex_gen/base"
	"github.com/aiagt/aiagt/kitex_gen/openai"
	"github.com/aiagt/aiagt/kitex_gen/pluginsvc"
	"github.com/aiagt/aiagt/kitex_gen/usersvc"
)

type App struct {
	Id              int64                      `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Name            string                     `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Description     string                     `thrift:"description,3,required" frugal:"3,required,string" json:"description"`
	DescriptionMd   string                     `thrift:"description_md,4,required" frugal:"4,required,string" json:"description_md"`
	ModelId         int64                      `thrift:"model_id,5,required" frugal:"5,required,i64" json:"model_id"`
	EnableImage     bool                       `thrift:"enable_image,6,required" frugal:"6,required,bool" json:"enable_image"`
	EnableFile      bool                       `thrift:"enable_file,7,required" frugal:"7,required,bool" json:"enable_file"`
	Version         string                     `thrift:"version,8,required" frugal:"8,required,string" json:"version"`
	IsPrivate       bool                       `thrift:"is_private,9,required" frugal:"9,required,bool" json:"is_private"`
	HomePage        string                     `thrift:"home_page,10,required" frugal:"10,required,string" json:"home_page"`
	PresetQuestions []string                   `thrift:"preset_questions,11,required" frugal:"11,required,list<string>" json:"preset_questions"`
	ToolIds         []int64                    `thrift:"tool_ids,12,required" frugal:"12,required,list<i64>" json:"tool_ids"`
	Tools           []*pluginsvc.PluginTool    `thrift:"tools,13,optional" frugal:"13,optional,list<pluginsvc.PluginTool>" json:"tools,omitempty"`
	Logo            string                     `thrift:"logo,14,required" frugal:"14,required,string" json:"logo"`
	AuthorId        int64                      `thrift:"author_id,15,required" frugal:"15,required,i64" json:"author_id"`
	Author          *usersvc.User              `thrift:"author,16,optional" frugal:"16,optional,usersvc.User" json:"author,omitempty"`
	LabelIds        []int64                    `thrift:"label_ids,17,required" frugal:"17,required,list<i64>" json:"label_ids"`
	Labels          []*AppLabel                `thrift:"labels,18,optional" frugal:"18,optional,list<AppLabel>" json:"labels,omitempty"`
	ModelConfig     *ModelConfig               `thrift:"model_config,19,required" frugal:"19,required,ModelConfig" json:"model_config"`
	CreatedAt       *base.Time                 `thrift:"created_at,20,required" frugal:"20,required,base.Time" json:"created_at"`
	UpdatedAt       *base.Time                 `thrift:"updated_at,21,required" frugal:"21,required,base.Time" json:"updated_at"`
	PublishedAt     *base.Time                 `thrift:"published_at,22,optional" frugal:"22,optional,base.Time" json:"published_at,omitempty"`
	PluginSecrets   []*pluginsvc.PluginSecrets `thrift:"plugin_secrets,23,optional" frugal:"23,optional,list<pluginsvc.PluginSecrets>" json:"plugin_secrets,omitempty"`
}

func NewApp() *App {
	return &App{}
}

func (p *App) InitDefault() {
}

func (p *App) GetId() (v int64) {
	return p.Id
}

func (p *App) GetName() (v string) {
	return p.Name
}

func (p *App) GetDescription() (v string) {
	return p.Description
}

func (p *App) GetDescriptionMd() (v string) {
	return p.DescriptionMd
}

func (p *App) GetModelId() (v int64) {
	return p.ModelId
}

func (p *App) GetEnableImage() (v bool) {
	return p.EnableImage
}

func (p *App) GetEnableFile() (v bool) {
	return p.EnableFile
}

func (p *App) GetVersion() (v string) {
	return p.Version
}

func (p *App) GetIsPrivate() (v bool) {
	return p.IsPrivate
}

func (p *App) GetHomePage() (v string) {
	return p.HomePage
}

func (p *App) GetPresetQuestions() (v []string) {
	return p.PresetQuestions
}

func (p *App) GetToolIds() (v []int64) {
	return p.ToolIds
}

var App_Tools_DEFAULT []*pluginsvc.PluginTool

func (p *App) GetTools() (v []*pluginsvc.PluginTool) {
	if !p.IsSetTools() {
		return App_Tools_DEFAULT
	}
	return p.Tools
}

func (p *App) GetLogo() (v string) {
	return p.Logo
}

func (p *App) GetAuthorId() (v int64) {
	return p.AuthorId
}

var App_Author_DEFAULT *usersvc.User

func (p *App) GetAuthor() (v *usersvc.User) {
	if !p.IsSetAuthor() {
		return App_Author_DEFAULT
	}
	return p.Author
}

func (p *App) GetLabelIds() (v []int64) {
	return p.LabelIds
}

var App_Labels_DEFAULT []*AppLabel

func (p *App) GetLabels() (v []*AppLabel) {
	if !p.IsSetLabels() {
		return App_Labels_DEFAULT
	}
	return p.Labels
}

var App_ModelConfig_DEFAULT *ModelConfig

func (p *App) GetModelConfig() (v *ModelConfig) {
	if !p.IsSetModelConfig() {
		return App_ModelConfig_DEFAULT
	}
	return p.ModelConfig
}

var App_CreatedAt_DEFAULT *base.Time

func (p *App) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return App_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}

var App_UpdatedAt_DEFAULT *base.Time

func (p *App) GetUpdatedAt() (v *base.Time) {
	if !p.IsSetUpdatedAt() {
		return App_UpdatedAt_DEFAULT
	}
	return p.UpdatedAt
}

var App_PublishedAt_DEFAULT *base.Time

func (p *App) GetPublishedAt() (v *base.Time) {
	if !p.IsSetPublishedAt() {
		return App_PublishedAt_DEFAULT
	}
	return p.PublishedAt
}

var App_PluginSecrets_DEFAULT []*pluginsvc.PluginSecrets

func (p *App) GetPluginSecrets() (v []*pluginsvc.PluginSecrets) {
	if !p.IsSetPluginSecrets() {
		return App_PluginSecrets_DEFAULT
	}
	return p.PluginSecrets
}
func (p *App) SetId(val int64) {
	p.Id = val
}
func (p *App) SetName(val string) {
	p.Name = val
}
func (p *App) SetDescription(val string) {
	p.Description = val
}
func (p *App) SetDescriptionMd(val string) {
	p.DescriptionMd = val
}
func (p *App) SetModelId(val int64) {
	p.ModelId = val
}
func (p *App) SetEnableImage(val bool) {
	p.EnableImage = val
}
func (p *App) SetEnableFile(val bool) {
	p.EnableFile = val
}
func (p *App) SetVersion(val string) {
	p.Version = val
}
func (p *App) SetIsPrivate(val bool) {
	p.IsPrivate = val
}
func (p *App) SetHomePage(val string) {
	p.HomePage = val
}
func (p *App) SetPresetQuestions(val []string) {
	p.PresetQuestions = val
}
func (p *App) SetToolIds(val []int64) {
	p.ToolIds = val
}
func (p *App) SetTools(val []*pluginsvc.PluginTool) {
	p.Tools = val
}
func (p *App) SetLogo(val string) {
	p.Logo = val
}
func (p *App) SetAuthorId(val int64) {
	p.AuthorId = val
}
func (p *App) SetAuthor(val *usersvc.User) {
	p.Author = val
}
func (p *App) SetLabelIds(val []int64) {
	p.LabelIds = val
}
func (p *App) SetLabels(val []*AppLabel) {
	p.Labels = val
}
func (p *App) SetModelConfig(val *ModelConfig) {
	p.ModelConfig = val
}
func (p *App) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}
func (p *App) SetUpdatedAt(val *base.Time) {
	p.UpdatedAt = val
}
func (p *App) SetPublishedAt(val *base.Time) {
	p.PublishedAt = val
}
func (p *App) SetPluginSecrets(val []*pluginsvc.PluginSecrets) {
	p.PluginSecrets = val
}

func (p *App) IsSetTools() bool {
	return p.Tools != nil
}

func (p *App) IsSetAuthor() bool {
	return p.Author != nil
}

func (p *App) IsSetLabels() bool {
	return p.Labels != nil
}

func (p *App) IsSetModelConfig() bool {
	return p.ModelConfig != nil
}

func (p *App) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *App) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *App) IsSetPublishedAt() bool {
	return p.PublishedAt != nil
}

func (p *App) IsSetPluginSecrets() bool {
	return p.PluginSecrets != nil
}

func (p *App) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("App(%+v)", *p)
}

var fieldIDToName_App = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "description",
	4:  "description_md",
	5:  "model_id",
	6:  "enable_image",
	7:  "enable_file",
	8:  "version",
	9:  "is_private",
	10: "home_page",
	11: "preset_questions",
	12: "tool_ids",
	13: "tools",
	14: "logo",
	15: "author_id",
	16: "author",
	17: "label_ids",
	18: "labels",
	19: "model_config",
	20: "created_at",
	21: "updated_at",
	22: "published_at",
	23: "plugin_secrets",
}

type ModelConfig struct {
	MaxTokens        *int32                               `thrift:"max_tokens,1,optional" frugal:"1,optional,i32" json:"max_tokens,omitempty"`
	Temperature      *float64                             `thrift:"temperature,2,optional" frugal:"2,optional,double" json:"temperature,omitempty"`
	TopP             *float64                             `thrift:"top_p,3,optional" frugal:"3,optional,double" json:"top_p,omitempty"`
	N                int32                                `thrift:"n,4,optional" frugal:"4,optional,i32" json:"n,omitempty"`
	Stream           bool                                 `thrift:"stream,5,optional" frugal:"5,optional,bool" json:"stream,omitempty"`
	Stop             []string                             `thrift:"stop,6,optional" frugal:"6,optional,list<string>" json:"stop,omitempty"`
	PresencePenalty  *float64                             `thrift:"presence_penalty,7,optional" frugal:"7,optional,double" json:"presence_penalty,omitempty"`
	ResponseFormat   *openai.ChatCompletionResponseFormat `thrift:"response_format,8,optional" frugal:"8,optional,openai.ChatCompletionResponseFormat" json:"response_format,omitempty"`
	Seed             *int32                               `thrift:"seed,9,optional" frugal:"9,optional,i32" json:"seed,omitempty"`
	FrequencyPenalty *float64                             `thrift:"frequency_penalty,10,optional" frugal:"10,optional,double" json:"frequency_penalty,omitempty"`
	LogitBias        map[string]int32                     `thrift:"logit_bias,11,optional" frugal:"11,optional,map<string:i32>" json:"logit_bias,omitempty"`
	Logprobs         *bool                                `thrift:"logprobs,12,optional" frugal:"12,optional,bool" json:"logprobs,omitempty"`
	TopLogprobs      *int32                               `thrift:"top_logprobs,13,optional" frugal:"13,optional,i32" json:"top_logprobs,omitempty"`
	User             *string                              `thrift:"user,14,optional" frugal:"14,optional,string" json:"user,omitempty"`
	StreamOptions    *openai.StreamOptions                `thrift:"stream_options,15,optional" frugal:"15,optional,openai.StreamOptions" json:"stream_options,omitempty"`
}

func NewModelConfig() *ModelConfig {
	return &ModelConfig{

		N:      1,
		Stream: true,
	}
}

func (p *ModelConfig) InitDefault() {
	p.N = 1
	p.Stream = true
}

var ModelConfig_MaxTokens_DEFAULT int32

func (p *ModelConfig) GetMaxTokens() (v int32) {
	if !p.IsSetMaxTokens() {
		return ModelConfig_MaxTokens_DEFAULT
	}
	return *p.MaxTokens
}

var ModelConfig_Temperature_DEFAULT float64

func (p *ModelConfig) GetTemperature() (v float64) {
	if !p.IsSetTemperature() {
		return ModelConfig_Temperature_DEFAULT
	}
	return *p.Temperature
}

var ModelConfig_TopP_DEFAULT float64

func (p *ModelConfig) GetTopP() (v float64) {
	if !p.IsSetTopP() {
		return ModelConfig_TopP_DEFAULT
	}
	return *p.TopP
}

var ModelConfig_N_DEFAULT int32 = 1

func (p *ModelConfig) GetN() (v int32) {
	if !p.IsSetN() {
		return ModelConfig_N_DEFAULT
	}
	return p.N
}

var ModelConfig_Stream_DEFAULT bool = true

func (p *ModelConfig) GetStream() (v bool) {
	if !p.IsSetStream() {
		return ModelConfig_Stream_DEFAULT
	}
	return p.Stream
}

var ModelConfig_Stop_DEFAULT []string

func (p *ModelConfig) GetStop() (v []string) {
	if !p.IsSetStop() {
		return ModelConfig_Stop_DEFAULT
	}
	return p.Stop
}

var ModelConfig_PresencePenalty_DEFAULT float64

func (p *ModelConfig) GetPresencePenalty() (v float64) {
	if !p.IsSetPresencePenalty() {
		return ModelConfig_PresencePenalty_DEFAULT
	}
	return *p.PresencePenalty
}

var ModelConfig_ResponseFormat_DEFAULT *openai.ChatCompletionResponseFormat

func (p *ModelConfig) GetResponseFormat() (v *openai.ChatCompletionResponseFormat) {
	if !p.IsSetResponseFormat() {
		return ModelConfig_ResponseFormat_DEFAULT
	}
	return p.ResponseFormat
}

var ModelConfig_Seed_DEFAULT int32

func (p *ModelConfig) GetSeed() (v int32) {
	if !p.IsSetSeed() {
		return ModelConfig_Seed_DEFAULT
	}
	return *p.Seed
}

var ModelConfig_FrequencyPenalty_DEFAULT float64

func (p *ModelConfig) GetFrequencyPenalty() (v float64) {
	if !p.IsSetFrequencyPenalty() {
		return ModelConfig_FrequencyPenalty_DEFAULT
	}
	return *p.FrequencyPenalty
}

var ModelConfig_LogitBias_DEFAULT map[string]int32

func (p *ModelConfig) GetLogitBias() (v map[string]int32) {
	if !p.IsSetLogitBias() {
		return ModelConfig_LogitBias_DEFAULT
	}
	return p.LogitBias
}

var ModelConfig_Logprobs_DEFAULT bool

func (p *ModelConfig) GetLogprobs() (v bool) {
	if !p.IsSetLogprobs() {
		return ModelConfig_Logprobs_DEFAULT
	}
	return *p.Logprobs
}

var ModelConfig_TopLogprobs_DEFAULT int32

func (p *ModelConfig) GetTopLogprobs() (v int32) {
	if !p.IsSetTopLogprobs() {
		return ModelConfig_TopLogprobs_DEFAULT
	}
	return *p.TopLogprobs
}

var ModelConfig_User_DEFAULT string

func (p *ModelConfig) GetUser() (v string) {
	if !p.IsSetUser() {
		return ModelConfig_User_DEFAULT
	}
	return *p.User
}

var ModelConfig_StreamOptions_DEFAULT *openai.StreamOptions

func (p *ModelConfig) GetStreamOptions() (v *openai.StreamOptions) {
	if !p.IsSetStreamOptions() {
		return ModelConfig_StreamOptions_DEFAULT
	}
	return p.StreamOptions
}
func (p *ModelConfig) SetMaxTokens(val *int32) {
	p.MaxTokens = val
}
func (p *ModelConfig) SetTemperature(val *float64) {
	p.Temperature = val
}
func (p *ModelConfig) SetTopP(val *float64) {
	p.TopP = val
}
func (p *ModelConfig) SetN(val int32) {
	p.N = val
}
func (p *ModelConfig) SetStream(val bool) {
	p.Stream = val
}
func (p *ModelConfig) SetStop(val []string) {
	p.Stop = val
}
func (p *ModelConfig) SetPresencePenalty(val *float64) {
	p.PresencePenalty = val
}
func (p *ModelConfig) SetResponseFormat(val *openai.ChatCompletionResponseFormat) {
	p.ResponseFormat = val
}
func (p *ModelConfig) SetSeed(val *int32) {
	p.Seed = val
}
func (p *ModelConfig) SetFrequencyPenalty(val *float64) {
	p.FrequencyPenalty = val
}
func (p *ModelConfig) SetLogitBias(val map[string]int32) {
	p.LogitBias = val
}
func (p *ModelConfig) SetLogprobs(val *bool) {
	p.Logprobs = val
}
func (p *ModelConfig) SetTopLogprobs(val *int32) {
	p.TopLogprobs = val
}
func (p *ModelConfig) SetUser(val *string) {
	p.User = val
}
func (p *ModelConfig) SetStreamOptions(val *openai.StreamOptions) {
	p.StreamOptions = val
}

func (p *ModelConfig) IsSetMaxTokens() bool {
	return p.MaxTokens != nil
}

func (p *ModelConfig) IsSetTemperature() bool {
	return p.Temperature != nil
}

func (p *ModelConfig) IsSetTopP() bool {
	return p.TopP != nil
}

func (p *ModelConfig) IsSetN() bool {
	return p.N != ModelConfig_N_DEFAULT
}

func (p *ModelConfig) IsSetStream() bool {
	return p.Stream != ModelConfig_Stream_DEFAULT
}

func (p *ModelConfig) IsSetStop() bool {
	return p.Stop != nil
}

func (p *ModelConfig) IsSetPresencePenalty() bool {
	return p.PresencePenalty != nil
}

func (p *ModelConfig) IsSetResponseFormat() bool {
	return p.ResponseFormat != nil
}

func (p *ModelConfig) IsSetSeed() bool {
	return p.Seed != nil
}

func (p *ModelConfig) IsSetFrequencyPenalty() bool {
	return p.FrequencyPenalty != nil
}

func (p *ModelConfig) IsSetLogitBias() bool {
	return p.LogitBias != nil
}

func (p *ModelConfig) IsSetLogprobs() bool {
	return p.Logprobs != nil
}

func (p *ModelConfig) IsSetTopLogprobs() bool {
	return p.TopLogprobs != nil
}

func (p *ModelConfig) IsSetUser() bool {
	return p.User != nil
}

func (p *ModelConfig) IsSetStreamOptions() bool {
	return p.StreamOptions != nil
}

func (p *ModelConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelConfig(%+v)", *p)
}

var fieldIDToName_ModelConfig = map[int16]string{
	1:  "max_tokens",
	2:  "temperature",
	3:  "top_p",
	4:  "n",
	5:  "stream",
	6:  "stop",
	7:  "presence_penalty",
	8:  "response_format",
	9:  "seed",
	10: "frequency_penalty",
	11: "logit_bias",
	12: "logprobs",
	13: "top_logprobs",
	14: "user",
	15: "stream_options",
}

type CreateAppReq struct {
	Name            string       `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Description     string       `thrift:"description,2,required" frugal:"2,required,string" json:"description"`
	DescriptionMd   string       `thrift:"description_md,3,required" frugal:"3,required,string" json:"description_md"`
	ModelId         int64        `thrift:"model_id,4,required" frugal:"4,required,i64" json:"model_id"`
	EnableImage     bool         `thrift:"enable_image,5,required" frugal:"5,required,bool" json:"enable_image"`
	EnableFile      bool         `thrift:"enable_file,6,required" frugal:"6,required,bool" json:"enable_file"`
	Version         string       `thrift:"version,7,required" frugal:"7,required,string" json:"version"`
	IsPrivate       bool         `thrift:"is_private,8,required" frugal:"8,required,bool" json:"is_private"`
	HomePage        string       `thrift:"home_page,9,required" frugal:"9,required,string" json:"home_page"`
	PresetQuestions []string     `thrift:"preset_questions,10,required" frugal:"10,required,list<string>" json:"preset_questions"`
	ToolIds         []int64      `thrift:"tool_ids,11,required" frugal:"11,required,list<i64>" json:"tool_ids"`
	Logo            string       `thrift:"logo,12,required" frugal:"12,required,string" json:"logo"`
	LabelIds        []int64      `thrift:"label_ids,13,required" frugal:"13,required,list<i64>" json:"label_ids"`
	LabelTexts      []string     `thrift:"label_texts,14,required" frugal:"14,required,list<string>" json:"label_texts"`
	ModelConfig     *ModelConfig `thrift:"model_config,15,required" frugal:"15,required,ModelConfig" json:"model_config"`
}

func NewCreateAppReq() *CreateAppReq {
	return &CreateAppReq{}
}

func (p *CreateAppReq) InitDefault() {
}

func (p *CreateAppReq) GetName() (v string) {
	return p.Name
}

func (p *CreateAppReq) GetDescription() (v string) {
	return p.Description
}

func (p *CreateAppReq) GetDescriptionMd() (v string) {
	return p.DescriptionMd
}

func (p *CreateAppReq) GetModelId() (v int64) {
	return p.ModelId
}

func (p *CreateAppReq) GetEnableImage() (v bool) {
	return p.EnableImage
}

func (p *CreateAppReq) GetEnableFile() (v bool) {
	return p.EnableFile
}

func (p *CreateAppReq) GetVersion() (v string) {
	return p.Version
}

func (p *CreateAppReq) GetIsPrivate() (v bool) {
	return p.IsPrivate
}

func (p *CreateAppReq) GetHomePage() (v string) {
	return p.HomePage
}

func (p *CreateAppReq) GetPresetQuestions() (v []string) {
	return p.PresetQuestions
}

func (p *CreateAppReq) GetToolIds() (v []int64) {
	return p.ToolIds
}

func (p *CreateAppReq) GetLogo() (v string) {
	return p.Logo
}

func (p *CreateAppReq) GetLabelIds() (v []int64) {
	return p.LabelIds
}

func (p *CreateAppReq) GetLabelTexts() (v []string) {
	return p.LabelTexts
}

var CreateAppReq_ModelConfig_DEFAULT *ModelConfig

func (p *CreateAppReq) GetModelConfig() (v *ModelConfig) {
	if !p.IsSetModelConfig() {
		return CreateAppReq_ModelConfig_DEFAULT
	}
	return p.ModelConfig
}
func (p *CreateAppReq) SetName(val string) {
	p.Name = val
}
func (p *CreateAppReq) SetDescription(val string) {
	p.Description = val
}
func (p *CreateAppReq) SetDescriptionMd(val string) {
	p.DescriptionMd = val
}
func (p *CreateAppReq) SetModelId(val int64) {
	p.ModelId = val
}
func (p *CreateAppReq) SetEnableImage(val bool) {
	p.EnableImage = val
}
func (p *CreateAppReq) SetEnableFile(val bool) {
	p.EnableFile = val
}
func (p *CreateAppReq) SetVersion(val string) {
	p.Version = val
}
func (p *CreateAppReq) SetIsPrivate(val bool) {
	p.IsPrivate = val
}
func (p *CreateAppReq) SetHomePage(val string) {
	p.HomePage = val
}
func (p *CreateAppReq) SetPresetQuestions(val []string) {
	p.PresetQuestions = val
}
func (p *CreateAppReq) SetToolIds(val []int64) {
	p.ToolIds = val
}
func (p *CreateAppReq) SetLogo(val string) {
	p.Logo = val
}
func (p *CreateAppReq) SetLabelIds(val []int64) {
	p.LabelIds = val
}
func (p *CreateAppReq) SetLabelTexts(val []string) {
	p.LabelTexts = val
}
func (p *CreateAppReq) SetModelConfig(val *ModelConfig) {
	p.ModelConfig = val
}

func (p *CreateAppReq) IsSetModelConfig() bool {
	return p.ModelConfig != nil
}

func (p *CreateAppReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateAppReq(%+v)", *p)
}

var fieldIDToName_CreateAppReq = map[int16]string{
	1:  "name",
	2:  "description",
	3:  "description_md",
	4:  "model_id",
	5:  "enable_image",
	6:  "enable_file",
	7:  "version",
	8:  "is_private",
	9:  "home_page",
	10: "preset_questions",
	11: "tool_ids",
	12: "logo",
	13: "label_ids",
	14: "label_texts",
	15: "model_config",
}

type UpdateAppReq struct {
	Id              int64        `thrift:"id,1,required" frugal:"1,required,i64" path:"id"`
	Name            *string      `thrift:"name,2,optional" frugal:"2,optional,string" json:"name,omitempty"`
	Description     *string      `thrift:"description,3,optional" frugal:"3,optional,string" json:"description,omitempty"`
	DescriptionMd   *string      `thrift:"description_md,4,optional" frugal:"4,optional,string" json:"description_md,omitempty"`
	ModelId         *int64       `thrift:"model_id,5,optional" frugal:"5,optional,i64" json:"model_id,omitempty"`
	EnableImage     *bool        `thrift:"enable_image,6,optional" frugal:"6,optional,bool" json:"enable_image,omitempty"`
	EnableFile      *bool        `thrift:"enable_file,7,optional" frugal:"7,optional,bool" json:"enable_file,omitempty"`
	Version         *string      `thrift:"version,8,optional" frugal:"8,optional,string" json:"version,omitempty"`
	IsPrivate       *bool        `thrift:"is_private,9,optional" frugal:"9,optional,bool" json:"is_private,omitempty"`
	HomePage        *string      `thrift:"home_page,10,optional" frugal:"10,optional,string" json:"home_page,omitempty"`
	PresetQuestions []string     `thrift:"preset_questions,11,optional" frugal:"11,optional,list<string>" json:"preset_questions,omitempty"`
	ToolIds         []int64      `thrift:"tool_ids,12,optional" frugal:"12,optional,list<i64>" json:"tool_ids,omitempty"`
	Logo            *string      `thrift:"logo,13,optional" frugal:"13,optional,string" json:"logo,omitempty"`
	LabelIds        []int64      `thrift:"label_ids,14,optional" frugal:"14,optional,list<i64>" json:"label_ids,omitempty"`
	LabelTexts      []string     `thrift:"label_texts,15,optional" frugal:"15,optional,list<string>" json:"label_texts,omitempty"`
	ModelConfig     *ModelConfig `thrift:"model_config,16,optional" frugal:"16,optional,ModelConfig" json:"model_config,omitempty"`
}

func NewUpdateAppReq() *UpdateAppReq {
	return &UpdateAppReq{}
}

func (p *UpdateAppReq) InitDefault() {
}

func (p *UpdateAppReq) GetId() (v int64) {
	return p.Id
}

var UpdateAppReq_Name_DEFAULT string

func (p *UpdateAppReq) GetName() (v string) {
	if !p.IsSetName() {
		return UpdateAppReq_Name_DEFAULT
	}
	return *p.Name
}

var UpdateAppReq_Description_DEFAULT string

func (p *UpdateAppReq) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return UpdateAppReq_Description_DEFAULT
	}
	return *p.Description
}

var UpdateAppReq_DescriptionMd_DEFAULT string

func (p *UpdateAppReq) GetDescriptionMd() (v string) {
	if !p.IsSetDescriptionMd() {
		return UpdateAppReq_DescriptionMd_DEFAULT
	}
	return *p.DescriptionMd
}

var UpdateAppReq_ModelId_DEFAULT int64

func (p *UpdateAppReq) GetModelId() (v int64) {
	if !p.IsSetModelId() {
		return UpdateAppReq_ModelId_DEFAULT
	}
	return *p.ModelId
}

var UpdateAppReq_EnableImage_DEFAULT bool

func (p *UpdateAppReq) GetEnableImage() (v bool) {
	if !p.IsSetEnableImage() {
		return UpdateAppReq_EnableImage_DEFAULT
	}
	return *p.EnableImage
}

var UpdateAppReq_EnableFile_DEFAULT bool

func (p *UpdateAppReq) GetEnableFile() (v bool) {
	if !p.IsSetEnableFile() {
		return UpdateAppReq_EnableFile_DEFAULT
	}
	return *p.EnableFile
}

var UpdateAppReq_Version_DEFAULT string

func (p *UpdateAppReq) GetVersion() (v string) {
	if !p.IsSetVersion() {
		return UpdateAppReq_Version_DEFAULT
	}
	return *p.Version
}

var UpdateAppReq_IsPrivate_DEFAULT bool

func (p *UpdateAppReq) GetIsPrivate() (v bool) {
	if !p.IsSetIsPrivate() {
		return UpdateAppReq_IsPrivate_DEFAULT
	}
	return *p.IsPrivate
}

var UpdateAppReq_HomePage_DEFAULT string

func (p *UpdateAppReq) GetHomePage() (v string) {
	if !p.IsSetHomePage() {
		return UpdateAppReq_HomePage_DEFAULT
	}
	return *p.HomePage
}

var UpdateAppReq_PresetQuestions_DEFAULT []string

func (p *UpdateAppReq) GetPresetQuestions() (v []string) {
	if !p.IsSetPresetQuestions() {
		return UpdateAppReq_PresetQuestions_DEFAULT
	}
	return p.PresetQuestions
}

var UpdateAppReq_ToolIds_DEFAULT []int64

func (p *UpdateAppReq) GetToolIds() (v []int64) {
	if !p.IsSetToolIds() {
		return UpdateAppReq_ToolIds_DEFAULT
	}
	return p.ToolIds
}

var UpdateAppReq_Logo_DEFAULT string

func (p *UpdateAppReq) GetLogo() (v string) {
	if !p.IsSetLogo() {
		return UpdateAppReq_Logo_DEFAULT
	}
	return *p.Logo
}

var UpdateAppReq_LabelIds_DEFAULT []int64

func (p *UpdateAppReq) GetLabelIds() (v []int64) {
	if !p.IsSetLabelIds() {
		return UpdateAppReq_LabelIds_DEFAULT
	}
	return p.LabelIds
}

var UpdateAppReq_LabelTexts_DEFAULT []string

func (p *UpdateAppReq) GetLabelTexts() (v []string) {
	if !p.IsSetLabelTexts() {
		return UpdateAppReq_LabelTexts_DEFAULT
	}
	return p.LabelTexts
}

var UpdateAppReq_ModelConfig_DEFAULT *ModelConfig

func (p *UpdateAppReq) GetModelConfig() (v *ModelConfig) {
	if !p.IsSetModelConfig() {
		return UpdateAppReq_ModelConfig_DEFAULT
	}
	return p.ModelConfig
}
func (p *UpdateAppReq) SetId(val int64) {
	p.Id = val
}
func (p *UpdateAppReq) SetName(val *string) {
	p.Name = val
}
func (p *UpdateAppReq) SetDescription(val *string) {
	p.Description = val
}
func (p *UpdateAppReq) SetDescriptionMd(val *string) {
	p.DescriptionMd = val
}
func (p *UpdateAppReq) SetModelId(val *int64) {
	p.ModelId = val
}
func (p *UpdateAppReq) SetEnableImage(val *bool) {
	p.EnableImage = val
}
func (p *UpdateAppReq) SetEnableFile(val *bool) {
	p.EnableFile = val
}
func (p *UpdateAppReq) SetVersion(val *string) {
	p.Version = val
}
func (p *UpdateAppReq) SetIsPrivate(val *bool) {
	p.IsPrivate = val
}
func (p *UpdateAppReq) SetHomePage(val *string) {
	p.HomePage = val
}
func (p *UpdateAppReq) SetPresetQuestions(val []string) {
	p.PresetQuestions = val
}
func (p *UpdateAppReq) SetToolIds(val []int64) {
	p.ToolIds = val
}
func (p *UpdateAppReq) SetLogo(val *string) {
	p.Logo = val
}
func (p *UpdateAppReq) SetLabelIds(val []int64) {
	p.LabelIds = val
}
func (p *UpdateAppReq) SetLabelTexts(val []string) {
	p.LabelTexts = val
}
func (p *UpdateAppReq) SetModelConfig(val *ModelConfig) {
	p.ModelConfig = val
}

func (p *UpdateAppReq) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdateAppReq) IsSetDescription() bool {
	return p.Description != nil
}

func (p *UpdateAppReq) IsSetDescriptionMd() bool {
	return p.DescriptionMd != nil
}

func (p *UpdateAppReq) IsSetModelId() bool {
	return p.ModelId != nil
}

func (p *UpdateAppReq) IsSetEnableImage() bool {
	return p.EnableImage != nil
}

func (p *UpdateAppReq) IsSetEnableFile() bool {
	return p.EnableFile != nil
}

func (p *UpdateAppReq) IsSetVersion() bool {
	return p.Version != nil
}

func (p *UpdateAppReq) IsSetIsPrivate() bool {
	return p.IsPrivate != nil
}

func (p *UpdateAppReq) IsSetHomePage() bool {
	return p.HomePage != nil
}

func (p *UpdateAppReq) IsSetPresetQuestions() bool {
	return p.PresetQuestions != nil
}

func (p *UpdateAppReq) IsSetToolIds() bool {
	return p.ToolIds != nil
}

func (p *UpdateAppReq) IsSetLogo() bool {
	return p.Logo != nil
}

func (p *UpdateAppReq) IsSetLabelIds() bool {
	return p.LabelIds != nil
}

func (p *UpdateAppReq) IsSetLabelTexts() bool {
	return p.LabelTexts != nil
}

func (p *UpdateAppReq) IsSetModelConfig() bool {
	return p.ModelConfig != nil
}

func (p *UpdateAppReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAppReq(%+v)", *p)
}

var fieldIDToName_UpdateAppReq = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "description",
	4:  "description_md",
	5:  "model_id",
	6:  "enable_image",
	7:  "enable_file",
	8:  "version",
	9:  "is_private",
	10: "home_page",
	11: "preset_questions",
	12: "tool_ids",
	13: "logo",
	14: "label_ids",
	15: "label_texts",
	16: "model_config",
}

type ListAppReq struct {
	Pagination  *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	AuthorId    *int64              `thrift:"author_id,2,optional" frugal:"2,optional,i64" json:"author_id,omitempty"`
	Name        *string             `thrift:"name,3,optional" frugal:"3,optional,string" json:"name,omitempty"`
	Description *string             `thrift:"description,4,optional" frugal:"4,optional,string" json:"description,omitempty"`
	LabelIds    []int64             `thrift:"label_ids,5,optional" frugal:"5,optional,list<i64>" json:"label_ids,omitempty"`
	WithAuthor  *bool               `thrift:"with_author,6,optional" frugal:"6,optional,bool" json:"with_author,omitempty"`
}

func NewListAppReq() *ListAppReq {
	return &ListAppReq{}
}

func (p *ListAppReq) InitDefault() {
}

var ListAppReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListAppReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListAppReq_Pagination_DEFAULT
	}
	return p.Pagination
}

var ListAppReq_AuthorId_DEFAULT int64

func (p *ListAppReq) GetAuthorId() (v int64) {
	if !p.IsSetAuthorId() {
		return ListAppReq_AuthorId_DEFAULT
	}
	return *p.AuthorId
}

var ListAppReq_Name_DEFAULT string

func (p *ListAppReq) GetName() (v string) {
	if !p.IsSetName() {
		return ListAppReq_Name_DEFAULT
	}
	return *p.Name
}

var ListAppReq_Description_DEFAULT string

func (p *ListAppReq) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return ListAppReq_Description_DEFAULT
	}
	return *p.Description
}

var ListAppReq_LabelIds_DEFAULT []int64

func (p *ListAppReq) GetLabelIds() (v []int64) {
	if !p.IsSetLabelIds() {
		return ListAppReq_LabelIds_DEFAULT
	}
	return p.LabelIds
}

var ListAppReq_WithAuthor_DEFAULT bool

func (p *ListAppReq) GetWithAuthor() (v bool) {
	if !p.IsSetWithAuthor() {
		return ListAppReq_WithAuthor_DEFAULT
	}
	return *p.WithAuthor
}
func (p *ListAppReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListAppReq) SetAuthorId(val *int64) {
	p.AuthorId = val
}
func (p *ListAppReq) SetName(val *string) {
	p.Name = val
}
func (p *ListAppReq) SetDescription(val *string) {
	p.Description = val
}
func (p *ListAppReq) SetLabelIds(val []int64) {
	p.LabelIds = val
}
func (p *ListAppReq) SetWithAuthor(val *bool) {
	p.WithAuthor = val
}

func (p *ListAppReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListAppReq) IsSetAuthorId() bool {
	return p.AuthorId != nil
}

func (p *ListAppReq) IsSetName() bool {
	return p.Name != nil
}

func (p *ListAppReq) IsSetDescription() bool {
	return p.Description != nil
}

func (p *ListAppReq) IsSetLabelIds() bool {
	return p.LabelIds != nil
}

func (p *ListAppReq) IsSetWithAuthor() bool {
	return p.WithAuthor != nil
}

func (p *ListAppReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAppReq(%+v)", *p)
}

var fieldIDToName_ListAppReq = map[int16]string{
	1: "pagination",
	2: "author_id",
	3: "name",
	4: "description",
	5: "label_ids",
	6: "with_author",
}

type ListAppResp struct {
	Pagination *base.PaginationResp `thrift:"pagination,1,required" frugal:"1,required,base.PaginationResp" json:"pagination"`
	Apps       []*App               `thrift:"apps,2,required" frugal:"2,required,list<App>" json:"apps"`
}

func NewListAppResp() *ListAppResp {
	return &ListAppResp{}
}

func (p *ListAppResp) InitDefault() {
}

var ListAppResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListAppResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListAppResp_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListAppResp) GetApps() (v []*App) {
	return p.Apps
}
func (p *ListAppResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}
func (p *ListAppResp) SetApps(val []*App) {
	p.Apps = val
}

func (p *ListAppResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListAppResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAppResp(%+v)", *p)
}

var fieldIDToName_ListAppResp = map[int16]string{
	1: "pagination",
	2: "apps",
}

type PublishAppReq struct {
	Id      int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Version string `thrift:"version,2,required" frugal:"2,required,string" json:"version"`
}

func NewPublishAppReq() *PublishAppReq {
	return &PublishAppReq{}
}

func (p *PublishAppReq) InitDefault() {
}

func (p *PublishAppReq) GetId() (v int64) {
	return p.Id
}

func (p *PublishAppReq) GetVersion() (v string) {
	return p.Version
}
func (p *PublishAppReq) SetId(val int64) {
	p.Id = val
}
func (p *PublishAppReq) SetVersion(val string) {
	p.Version = val
}

func (p *PublishAppReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishAppReq(%+v)", *p)
}

var fieldIDToName_PublishAppReq = map[int16]string{
	1: "id",
	2: "version",
}

type AppLabel struct {
	Id        int64      `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Text      string     `thrift:"text,2,required" frugal:"2,required,string" json:"text"`
	CreatedAt *base.Time `thrift:"created_at,3,required" frugal:"3,required,base.Time" json:"created_at"`
	Pinned    *int32     `thrift:"pinned,4,optional" frugal:"4,optional,i32" json:"pinned,omitempty"`
}

func NewAppLabel() *AppLabel {
	return &AppLabel{}
}

func (p *AppLabel) InitDefault() {
}

func (p *AppLabel) GetId() (v int64) {
	return p.Id
}

func (p *AppLabel) GetText() (v string) {
	return p.Text
}

var AppLabel_CreatedAt_DEFAULT *base.Time

func (p *AppLabel) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return AppLabel_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}

var AppLabel_Pinned_DEFAULT int32

func (p *AppLabel) GetPinned() (v int32) {
	if !p.IsSetPinned() {
		return AppLabel_Pinned_DEFAULT
	}
	return *p.Pinned
}
func (p *AppLabel) SetId(val int64) {
	p.Id = val
}
func (p *AppLabel) SetText(val string) {
	p.Text = val
}
func (p *AppLabel) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}
func (p *AppLabel) SetPinned(val *int32) {
	p.Pinned = val
}

func (p *AppLabel) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *AppLabel) IsSetPinned() bool {
	return p.Pinned != nil
}

func (p *AppLabel) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppLabel(%+v)", *p)
}

var fieldIDToName_AppLabel = map[int16]string{
	1: "id",
	2: "text",
	3: "created_at",
	4: "pinned",
}

type ListAppLabelReq struct {
	Pagination *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	Text       *string             `thrift:"text,2,optional" frugal:"2,optional,string" query:"text"`
	Pinned     *bool               `thrift:"pinned,3,optional" frugal:"3,optional,bool" query:"pinned"`
}

func NewListAppLabelReq() *ListAppLabelReq {
	return &ListAppLabelReq{}
}

func (p *ListAppLabelReq) InitDefault() {
}

var ListAppLabelReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListAppLabelReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListAppLabelReq_Pagination_DEFAULT
	}
	return p.Pagination
}

var ListAppLabelReq_Text_DEFAULT string

func (p *ListAppLabelReq) GetText() (v string) {
	if !p.IsSetText() {
		return ListAppLabelReq_Text_DEFAULT
	}
	return *p.Text
}

var ListAppLabelReq_Pinned_DEFAULT bool

func (p *ListAppLabelReq) GetPinned() (v bool) {
	if !p.IsSetPinned() {
		return ListAppLabelReq_Pinned_DEFAULT
	}
	return *p.Pinned
}
func (p *ListAppLabelReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListAppLabelReq) SetText(val *string) {
	p.Text = val
}
func (p *ListAppLabelReq) SetPinned(val *bool) {
	p.Pinned = val
}

func (p *ListAppLabelReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListAppLabelReq) IsSetText() bool {
	return p.Text != nil
}

func (p *ListAppLabelReq) IsSetPinned() bool {
	return p.Pinned != nil
}

func (p *ListAppLabelReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAppLabelReq(%+v)", *p)
}

var fieldIDToName_ListAppLabelReq = map[int16]string{
	1: "pagination",
	2: "text",
	3: "pinned",
}

type ListAppLabelResp struct {
	Pagination *base.PaginationResp `thrift:"pagination,1,required" frugal:"1,required,base.PaginationResp" json:"pagination"`
	Labels     []*AppLabel          `thrift:"labels,2,required" frugal:"2,required,list<AppLabel>" json:"labels"`
}

func NewListAppLabelResp() *ListAppLabelResp {
	return &ListAppLabelResp{}
}

func (p *ListAppLabelResp) InitDefault() {
}

var ListAppLabelResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListAppLabelResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListAppLabelResp_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListAppLabelResp) GetLabels() (v []*AppLabel) {
	return p.Labels
}
func (p *ListAppLabelResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}
func (p *ListAppLabelResp) SetLabels(val []*AppLabel) {
	p.Labels = val
}

func (p *ListAppLabelResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListAppLabelResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAppLabelResp(%+v)", *p)
}

var fieldIDToName_ListAppLabelResp = map[int16]string{
	1: "pagination",
	2: "labels",
}

type GetAppByIDReq struct {
	Id     int64 `thrift:"id,1,required" frugal:"1,required,i64" path:"id"`
	Unfold *bool `thrift:"unfold,2,optional" frugal:"2,optional,bool" json:"unfold,omitempty"`
}

func NewGetAppByIDReq() *GetAppByIDReq {
	return &GetAppByIDReq{}
}

func (p *GetAppByIDReq) InitDefault() {
}

func (p *GetAppByIDReq) GetId() (v int64) {
	return p.Id
}

var GetAppByIDReq_Unfold_DEFAULT bool

func (p *GetAppByIDReq) GetUnfold() (v bool) {
	if !p.IsSetUnfold() {
		return GetAppByIDReq_Unfold_DEFAULT
	}
	return *p.Unfold
}
func (p *GetAppByIDReq) SetId(val int64) {
	p.Id = val
}
func (p *GetAppByIDReq) SetUnfold(val *bool) {
	p.Unfold = val
}

func (p *GetAppByIDReq) IsSetUnfold() bool {
	return p.Unfold != nil
}

func (p *GetAppByIDReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAppByIDReq(%+v)", *p)
}

var fieldIDToName_GetAppByIDReq = map[int16]string{
	1: "id",
	2: "unfold",
}

type GetAppByIDResp struct {
	App *App                  `thrift:"app,1,required" frugal:"1,required,App" json:"app"`
	Ext *GetAppByIDRespExtend `thrift:"ext,2,optional" frugal:"2,optional,GetAppByIDRespExtend" json:"ext,omitempty"`
}

func NewGetAppByIDResp() *GetAppByIDResp {
	return &GetAppByIDResp{}
}

func (p *GetAppByIDResp) InitDefault() {
}

var GetAppByIDResp_App_DEFAULT *App

func (p *GetAppByIDResp) GetApp() (v *App) {
	if !p.IsSetApp() {
		return GetAppByIDResp_App_DEFAULT
	}
	return p.App
}

var GetAppByIDResp_Ext_DEFAULT *GetAppByIDRespExtend

func (p *GetAppByIDResp) GetExt() (v *GetAppByIDRespExtend) {
	if !p.IsSetExt() {
		return GetAppByIDResp_Ext_DEFAULT
	}
	return p.Ext
}
func (p *GetAppByIDResp) SetApp(val *App) {
	p.App = val
}
func (p *GetAppByIDResp) SetExt(val *GetAppByIDRespExtend) {
	p.Ext = val
}

func (p *GetAppByIDResp) IsSetApp() bool {
	return p.App != nil
}

func (p *GetAppByIDResp) IsSetExt() bool {
	return p.Ext != nil
}

func (p *GetAppByIDResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAppByIDResp(%+v)", *p)
}

var fieldIDToName_GetAppByIDResp = map[int16]string{
	1: "app",
	2: "ext",
}

type GetAppByIDRespExtend struct {
	PrivateToolsCount int32 `thrift:"private_tools_count,1,required" frugal:"1,required,i32" json:"private_tools_count"`
}

func NewGetAppByIDRespExtend() *GetAppByIDRespExtend {
	return &GetAppByIDRespExtend{}
}

func (p *GetAppByIDRespExtend) InitDefault() {
}

func (p *GetAppByIDRespExtend) GetPrivateToolsCount() (v int32) {
	return p.PrivateToolsCount
}
func (p *GetAppByIDRespExtend) SetPrivateToolsCount(val int32) {
	p.PrivateToolsCount = val
}

func (p *GetAppByIDRespExtend) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAppByIDRespExtend(%+v)", *p)
}

var fieldIDToName_GetAppByIDRespExtend = map[int16]string{
	1: "private_tools_count",
}

type AppService interface {
	CreateApp(ctx context.Context, req *CreateAppReq) (r *base.Empty, err error)

	UpdateApp(ctx context.Context, req *UpdateAppReq) (r *base.Empty, err error)

	DeleteApp(ctx context.Context, req *base.IDReq) (r *base.Empty, err error)

	GetAppByID(ctx context.Context, req *GetAppByIDReq) (r *GetAppByIDResp, err error)

	ListApp(ctx context.Context, req *ListAppReq) (r *ListAppResp, err error)

	PublishApp(ctx context.Context, req *PublishAppReq) (r *base.Empty, err error)

	ListAppLabel(ctx context.Context, req *ListAppLabelReq) (r *ListAppLabelResp, err error)
}

type AppServiceCreateAppArgs struct {
	Req *CreateAppReq `thrift:"req,1" frugal:"1,default,CreateAppReq" json:"req"`
}

func NewAppServiceCreateAppArgs() *AppServiceCreateAppArgs {
	return &AppServiceCreateAppArgs{}
}

func (p *AppServiceCreateAppArgs) InitDefault() {
}

var AppServiceCreateAppArgs_Req_DEFAULT *CreateAppReq

func (p *AppServiceCreateAppArgs) GetReq() (v *CreateAppReq) {
	if !p.IsSetReq() {
		return AppServiceCreateAppArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AppServiceCreateAppArgs) SetReq(val *CreateAppReq) {
	p.Req = val
}

func (p *AppServiceCreateAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AppServiceCreateAppArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceCreateAppArgs(%+v)", *p)
}

var fieldIDToName_AppServiceCreateAppArgs = map[int16]string{
	1: "req",
}

type AppServiceCreateAppResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewAppServiceCreateAppResult() *AppServiceCreateAppResult {
	return &AppServiceCreateAppResult{}
}

func (p *AppServiceCreateAppResult) InitDefault() {
}

var AppServiceCreateAppResult_Success_DEFAULT *base.Empty

func (p *AppServiceCreateAppResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return AppServiceCreateAppResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AppServiceCreateAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *AppServiceCreateAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AppServiceCreateAppResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceCreateAppResult(%+v)", *p)
}

var fieldIDToName_AppServiceCreateAppResult = map[int16]string{
	0: "success",
}

type AppServiceUpdateAppArgs struct {
	Req *UpdateAppReq `thrift:"req,1" frugal:"1,default,UpdateAppReq" json:"req"`
}

func NewAppServiceUpdateAppArgs() *AppServiceUpdateAppArgs {
	return &AppServiceUpdateAppArgs{}
}

func (p *AppServiceUpdateAppArgs) InitDefault() {
}

var AppServiceUpdateAppArgs_Req_DEFAULT *UpdateAppReq

func (p *AppServiceUpdateAppArgs) GetReq() (v *UpdateAppReq) {
	if !p.IsSetReq() {
		return AppServiceUpdateAppArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AppServiceUpdateAppArgs) SetReq(val *UpdateAppReq) {
	p.Req = val
}

func (p *AppServiceUpdateAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AppServiceUpdateAppArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceUpdateAppArgs(%+v)", *p)
}

var fieldIDToName_AppServiceUpdateAppArgs = map[int16]string{
	1: "req",
}

type AppServiceUpdateAppResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewAppServiceUpdateAppResult() *AppServiceUpdateAppResult {
	return &AppServiceUpdateAppResult{}
}

func (p *AppServiceUpdateAppResult) InitDefault() {
}

var AppServiceUpdateAppResult_Success_DEFAULT *base.Empty

func (p *AppServiceUpdateAppResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return AppServiceUpdateAppResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AppServiceUpdateAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *AppServiceUpdateAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AppServiceUpdateAppResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceUpdateAppResult(%+v)", *p)
}

var fieldIDToName_AppServiceUpdateAppResult = map[int16]string{
	0: "success",
}

type AppServiceDeleteAppArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewAppServiceDeleteAppArgs() *AppServiceDeleteAppArgs {
	return &AppServiceDeleteAppArgs{}
}

func (p *AppServiceDeleteAppArgs) InitDefault() {
}

var AppServiceDeleteAppArgs_Req_DEFAULT *base.IDReq

func (p *AppServiceDeleteAppArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return AppServiceDeleteAppArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AppServiceDeleteAppArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *AppServiceDeleteAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AppServiceDeleteAppArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceDeleteAppArgs(%+v)", *p)
}

var fieldIDToName_AppServiceDeleteAppArgs = map[int16]string{
	1: "req",
}

type AppServiceDeleteAppResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewAppServiceDeleteAppResult() *AppServiceDeleteAppResult {
	return &AppServiceDeleteAppResult{}
}

func (p *AppServiceDeleteAppResult) InitDefault() {
}

var AppServiceDeleteAppResult_Success_DEFAULT *base.Empty

func (p *AppServiceDeleteAppResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return AppServiceDeleteAppResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AppServiceDeleteAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *AppServiceDeleteAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AppServiceDeleteAppResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceDeleteAppResult(%+v)", *p)
}

var fieldIDToName_AppServiceDeleteAppResult = map[int16]string{
	0: "success",
}

type AppServiceGetAppByIDArgs struct {
	Req *GetAppByIDReq `thrift:"req,1" frugal:"1,default,GetAppByIDReq" json:"req"`
}

func NewAppServiceGetAppByIDArgs() *AppServiceGetAppByIDArgs {
	return &AppServiceGetAppByIDArgs{}
}

func (p *AppServiceGetAppByIDArgs) InitDefault() {
}

var AppServiceGetAppByIDArgs_Req_DEFAULT *GetAppByIDReq

func (p *AppServiceGetAppByIDArgs) GetReq() (v *GetAppByIDReq) {
	if !p.IsSetReq() {
		return AppServiceGetAppByIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AppServiceGetAppByIDArgs) SetReq(val *GetAppByIDReq) {
	p.Req = val
}

func (p *AppServiceGetAppByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AppServiceGetAppByIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceGetAppByIDArgs(%+v)", *p)
}

var fieldIDToName_AppServiceGetAppByIDArgs = map[int16]string{
	1: "req",
}

type AppServiceGetAppByIDResult struct {
	Success *GetAppByIDResp `thrift:"success,0,optional" frugal:"0,optional,GetAppByIDResp" json:"success,omitempty"`
}

func NewAppServiceGetAppByIDResult() *AppServiceGetAppByIDResult {
	return &AppServiceGetAppByIDResult{}
}

func (p *AppServiceGetAppByIDResult) InitDefault() {
}

var AppServiceGetAppByIDResult_Success_DEFAULT *GetAppByIDResp

func (p *AppServiceGetAppByIDResult) GetSuccess() (v *GetAppByIDResp) {
	if !p.IsSetSuccess() {
		return AppServiceGetAppByIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AppServiceGetAppByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAppByIDResp)
}

func (p *AppServiceGetAppByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AppServiceGetAppByIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceGetAppByIDResult(%+v)", *p)
}

var fieldIDToName_AppServiceGetAppByIDResult = map[int16]string{
	0: "success",
}

type AppServiceListAppArgs struct {
	Req *ListAppReq `thrift:"req,1" frugal:"1,default,ListAppReq" json:"req"`
}

func NewAppServiceListAppArgs() *AppServiceListAppArgs {
	return &AppServiceListAppArgs{}
}

func (p *AppServiceListAppArgs) InitDefault() {
}

var AppServiceListAppArgs_Req_DEFAULT *ListAppReq

func (p *AppServiceListAppArgs) GetReq() (v *ListAppReq) {
	if !p.IsSetReq() {
		return AppServiceListAppArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AppServiceListAppArgs) SetReq(val *ListAppReq) {
	p.Req = val
}

func (p *AppServiceListAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AppServiceListAppArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceListAppArgs(%+v)", *p)
}

var fieldIDToName_AppServiceListAppArgs = map[int16]string{
	1: "req",
}

type AppServiceListAppResult struct {
	Success *ListAppResp `thrift:"success,0,optional" frugal:"0,optional,ListAppResp" json:"success,omitempty"`
}

func NewAppServiceListAppResult() *AppServiceListAppResult {
	return &AppServiceListAppResult{}
}

func (p *AppServiceListAppResult) InitDefault() {
}

var AppServiceListAppResult_Success_DEFAULT *ListAppResp

func (p *AppServiceListAppResult) GetSuccess() (v *ListAppResp) {
	if !p.IsSetSuccess() {
		return AppServiceListAppResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AppServiceListAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListAppResp)
}

func (p *AppServiceListAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AppServiceListAppResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceListAppResult(%+v)", *p)
}

var fieldIDToName_AppServiceListAppResult = map[int16]string{
	0: "success",
}

type AppServicePublishAppArgs struct {
	Req *PublishAppReq `thrift:"req,1" frugal:"1,default,PublishAppReq" json:"req"`
}

func NewAppServicePublishAppArgs() *AppServicePublishAppArgs {
	return &AppServicePublishAppArgs{}
}

func (p *AppServicePublishAppArgs) InitDefault() {
}

var AppServicePublishAppArgs_Req_DEFAULT *PublishAppReq

func (p *AppServicePublishAppArgs) GetReq() (v *PublishAppReq) {
	if !p.IsSetReq() {
		return AppServicePublishAppArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AppServicePublishAppArgs) SetReq(val *PublishAppReq) {
	p.Req = val
}

func (p *AppServicePublishAppArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AppServicePublishAppArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServicePublishAppArgs(%+v)", *p)
}

var fieldIDToName_AppServicePublishAppArgs = map[int16]string{
	1: "req",
}

type AppServicePublishAppResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewAppServicePublishAppResult() *AppServicePublishAppResult {
	return &AppServicePublishAppResult{}
}

func (p *AppServicePublishAppResult) InitDefault() {
}

var AppServicePublishAppResult_Success_DEFAULT *base.Empty

func (p *AppServicePublishAppResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return AppServicePublishAppResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AppServicePublishAppResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *AppServicePublishAppResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AppServicePublishAppResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServicePublishAppResult(%+v)", *p)
}

var fieldIDToName_AppServicePublishAppResult = map[int16]string{
	0: "success",
}

type AppServiceListAppLabelArgs struct {
	Req *ListAppLabelReq `thrift:"req,1" frugal:"1,default,ListAppLabelReq" json:"req"`
}

func NewAppServiceListAppLabelArgs() *AppServiceListAppLabelArgs {
	return &AppServiceListAppLabelArgs{}
}

func (p *AppServiceListAppLabelArgs) InitDefault() {
}

var AppServiceListAppLabelArgs_Req_DEFAULT *ListAppLabelReq

func (p *AppServiceListAppLabelArgs) GetReq() (v *ListAppLabelReq) {
	if !p.IsSetReq() {
		return AppServiceListAppLabelArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AppServiceListAppLabelArgs) SetReq(val *ListAppLabelReq) {
	p.Req = val
}

func (p *AppServiceListAppLabelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AppServiceListAppLabelArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceListAppLabelArgs(%+v)", *p)
}

var fieldIDToName_AppServiceListAppLabelArgs = map[int16]string{
	1: "req",
}

type AppServiceListAppLabelResult struct {
	Success *ListAppLabelResp `thrift:"success,0,optional" frugal:"0,optional,ListAppLabelResp" json:"success,omitempty"`
}

func NewAppServiceListAppLabelResult() *AppServiceListAppLabelResult {
	return &AppServiceListAppLabelResult{}
}

func (p *AppServiceListAppLabelResult) InitDefault() {
}

var AppServiceListAppLabelResult_Success_DEFAULT *ListAppLabelResp

func (p *AppServiceListAppLabelResult) GetSuccess() (v *ListAppLabelResp) {
	if !p.IsSetSuccess() {
		return AppServiceListAppLabelResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AppServiceListAppLabelResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListAppLabelResp)
}

func (p *AppServiceListAppLabelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AppServiceListAppLabelResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppServiceListAppLabelResult(%+v)", *p)
}

var fieldIDToName_AppServiceListAppLabelResult = map[int16]string{
	0: "success",
}
