// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package pluginsvc

import (
	"context"
	"fmt"
	"github.com/aiagt/aiagt/kitex_gen/base"
	"github.com/aiagt/aiagt/kitex_gen/usersvc"
)

type Plugin struct {
	Id            int64           `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Key           int64           `thrift:"key,2,required" frugal:"2,required,i64" json:"key"`
	Name          string          `thrift:"name,3,required" frugal:"3,required,string" json:"name"`
	Description   string          `thrift:"description,4,required" frugal:"4,required,string" json:"description"`
	DescriptionMd string          `thrift:"description_md,5,required" frugal:"5,required,string" json:"description_md"`
	AuthorId      int64           `thrift:"author_id,6,required" frugal:"6,required,i64" json:"author_id"`
	Author        *usersvc.User   `thrift:"author,7,optional" frugal:"7,optional,usersvc.User" json:"author,omitempty"`
	IsPrivate     bool            `thrift:"is_private,8,required" frugal:"8,required,bool" json:"is_private"`
	HomePage      string          `thrift:"home_page,9,required" frugal:"9,required,string" json:"home_page"`
	EnableSecret  bool            `thrift:"enable_secret,10,required" frugal:"10,required,bool" json:"enable_secret"`
	Secrets       []*PluginSecret `thrift:"secrets,11,required" frugal:"11,required,list<PluginSecret>" json:"secrets"`
	LabelIds      []int64         `thrift:"label_ids,12,required" frugal:"12,required,list<i64>" json:"label_ids"`
	Labels        []*PluginLabel  `thrift:"labels,13,optional" frugal:"13,optional,list<PluginLabel>" json:"labels,omitempty"`
	ToolIds       []int64         `thrift:"tool_ids,14,required" frugal:"14,required,list<i64>" json:"tool_ids"`
	Tools         []*PluginTool   `thrift:"tools,15,optional" frugal:"15,optional,list<PluginTool>" json:"tools,omitempty"`
	Logo          string          `thrift:"logo,16,required" frugal:"16,required,string" json:"logo"`
	CreatedAt     *base.Time      `thrift:"created_at,17,required" frugal:"17,required,base.Time" json:"created_at"`
	UpdatedAt     *base.Time      `thrift:"updated_at,18,required" frugal:"18,required,base.Time" json:"updated_at"`
	PublishedAt   *base.Time      `thrift:"published_at,19,optional" frugal:"19,optional,base.Time" json:"published_at,omitempty"`
}

func NewPlugin() *Plugin {
	return &Plugin{}
}

func (p *Plugin) InitDefault() {
}

func (p *Plugin) GetId() (v int64) {
	return p.Id
}

func (p *Plugin) GetKey() (v int64) {
	return p.Key
}

func (p *Plugin) GetName() (v string) {
	return p.Name
}

func (p *Plugin) GetDescription() (v string) {
	return p.Description
}

func (p *Plugin) GetDescriptionMd() (v string) {
	return p.DescriptionMd
}

func (p *Plugin) GetAuthorId() (v int64) {
	return p.AuthorId
}

var Plugin_Author_DEFAULT *usersvc.User

func (p *Plugin) GetAuthor() (v *usersvc.User) {
	if !p.IsSetAuthor() {
		return Plugin_Author_DEFAULT
	}
	return p.Author
}

func (p *Plugin) GetIsPrivate() (v bool) {
	return p.IsPrivate
}

func (p *Plugin) GetHomePage() (v string) {
	return p.HomePage
}

func (p *Plugin) GetEnableSecret() (v bool) {
	return p.EnableSecret
}

func (p *Plugin) GetSecrets() (v []*PluginSecret) {
	return p.Secrets
}

func (p *Plugin) GetLabelIds() (v []int64) {
	return p.LabelIds
}

var Plugin_Labels_DEFAULT []*PluginLabel

func (p *Plugin) GetLabels() (v []*PluginLabel) {
	if !p.IsSetLabels() {
		return Plugin_Labels_DEFAULT
	}
	return p.Labels
}

func (p *Plugin) GetToolIds() (v []int64) {
	return p.ToolIds
}

var Plugin_Tools_DEFAULT []*PluginTool

func (p *Plugin) GetTools() (v []*PluginTool) {
	if !p.IsSetTools() {
		return Plugin_Tools_DEFAULT
	}
	return p.Tools
}

func (p *Plugin) GetLogo() (v string) {
	return p.Logo
}

var Plugin_CreatedAt_DEFAULT *base.Time

func (p *Plugin) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return Plugin_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}

var Plugin_UpdatedAt_DEFAULT *base.Time

func (p *Plugin) GetUpdatedAt() (v *base.Time) {
	if !p.IsSetUpdatedAt() {
		return Plugin_UpdatedAt_DEFAULT
	}
	return p.UpdatedAt
}

var Plugin_PublishedAt_DEFAULT *base.Time

func (p *Plugin) GetPublishedAt() (v *base.Time) {
	if !p.IsSetPublishedAt() {
		return Plugin_PublishedAt_DEFAULT
	}
	return p.PublishedAt
}
func (p *Plugin) SetId(val int64) {
	p.Id = val
}
func (p *Plugin) SetKey(val int64) {
	p.Key = val
}
func (p *Plugin) SetName(val string) {
	p.Name = val
}
func (p *Plugin) SetDescription(val string) {
	p.Description = val
}
func (p *Plugin) SetDescriptionMd(val string) {
	p.DescriptionMd = val
}
func (p *Plugin) SetAuthorId(val int64) {
	p.AuthorId = val
}
func (p *Plugin) SetAuthor(val *usersvc.User) {
	p.Author = val
}
func (p *Plugin) SetIsPrivate(val bool) {
	p.IsPrivate = val
}
func (p *Plugin) SetHomePage(val string) {
	p.HomePage = val
}
func (p *Plugin) SetEnableSecret(val bool) {
	p.EnableSecret = val
}
func (p *Plugin) SetSecrets(val []*PluginSecret) {
	p.Secrets = val
}
func (p *Plugin) SetLabelIds(val []int64) {
	p.LabelIds = val
}
func (p *Plugin) SetLabels(val []*PluginLabel) {
	p.Labels = val
}
func (p *Plugin) SetToolIds(val []int64) {
	p.ToolIds = val
}
func (p *Plugin) SetTools(val []*PluginTool) {
	p.Tools = val
}
func (p *Plugin) SetLogo(val string) {
	p.Logo = val
}
func (p *Plugin) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}
func (p *Plugin) SetUpdatedAt(val *base.Time) {
	p.UpdatedAt = val
}
func (p *Plugin) SetPublishedAt(val *base.Time) {
	p.PublishedAt = val
}

func (p *Plugin) IsSetAuthor() bool {
	return p.Author != nil
}

func (p *Plugin) IsSetLabels() bool {
	return p.Labels != nil
}

func (p *Plugin) IsSetTools() bool {
	return p.Tools != nil
}

func (p *Plugin) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *Plugin) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *Plugin) IsSetPublishedAt() bool {
	return p.PublishedAt != nil
}

func (p *Plugin) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Plugin(%+v)", *p)
}

var fieldIDToName_Plugin = map[int16]string{
	1:  "id",
	2:  "key",
	3:  "name",
	4:  "description",
	5:  "description_md",
	6:  "author_id",
	7:  "author",
	8:  "is_private",
	9:  "home_page",
	10: "enable_secret",
	11: "secrets",
	12: "label_ids",
	13: "labels",
	14: "tool_ids",
	15: "tools",
	16: "logo",
	17: "created_at",
	18: "updated_at",
	19: "published_at",
}

type PluginSecret struct {
	Name          string `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Description   string `thrift:"description,2,required" frugal:"2,required,string" json:"description"`
	AcquireMethod string `thrift:"acquire_method,3,required" frugal:"3,required,string" json:"acquire_method"`
	Link          string `thrift:"link,4,required" frugal:"4,required,string" json:"link"`
}

func NewPluginSecret() *PluginSecret {
	return &PluginSecret{}
}

func (p *PluginSecret) InitDefault() {
}

func (p *PluginSecret) GetName() (v string) {
	return p.Name
}

func (p *PluginSecret) GetDescription() (v string) {
	return p.Description
}

func (p *PluginSecret) GetAcquireMethod() (v string) {
	return p.AcquireMethod
}

func (p *PluginSecret) GetLink() (v string) {
	return p.Link
}
func (p *PluginSecret) SetName(val string) {
	p.Name = val
}
func (p *PluginSecret) SetDescription(val string) {
	p.Description = val
}
func (p *PluginSecret) SetAcquireMethod(val string) {
	p.AcquireMethod = val
}
func (p *PluginSecret) SetLink(val string) {
	p.Link = val
}

func (p *PluginSecret) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginSecret(%+v)", *p)
}

var fieldIDToName_PluginSecret = map[int16]string{
	1: "name",
	2: "description",
	3: "acquire_method",
	4: "link",
}

type PluginTool struct {
	Id            int64      `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Name          string     `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Description   string     `thrift:"description,3,required" frugal:"3,required,string" json:"description"`
	PluginId      int64      `thrift:"plugin_id,4,required" frugal:"4,required,i64" json:"plugin_id"`
	Plugin        *Plugin    `thrift:"plugin,5,optional" frugal:"5,optional,Plugin" json:"plugin,omitempty"`
	RequestType   []byte     `thrift:"request_type,6,required" frugal:"6,required,binary" json:"request_type"`
	ResponseType  []byte     `thrift:"response_type,7,required" frugal:"7,required,binary" json:"response_type"`
	ApiUrl        string     `thrift:"api_url,8,required" frugal:"8,required,string" json:"api_url"`
	ImportModelId *int64     `thrift:"import_model_id,9,optional" frugal:"9,optional,i64" json:"import_model_id,omitempty"`
	CreatedAt     *base.Time `thrift:"created_at,10,required" frugal:"10,required,base.Time" json:"created_at"`
	UpdatedAt     *base.Time `thrift:"updated_at,11,required" frugal:"11,required,base.Time" json:"updated_at"`
	TestedAt      *base.Time `thrift:"tested_at,12,optional" frugal:"12,optional,base.Time" json:"tested_at,omitempty"`
}

func NewPluginTool() *PluginTool {
	return &PluginTool{}
}

func (p *PluginTool) InitDefault() {
}

func (p *PluginTool) GetId() (v int64) {
	return p.Id
}

func (p *PluginTool) GetName() (v string) {
	return p.Name
}

func (p *PluginTool) GetDescription() (v string) {
	return p.Description
}

func (p *PluginTool) GetPluginId() (v int64) {
	return p.PluginId
}

var PluginTool_Plugin_DEFAULT *Plugin

func (p *PluginTool) GetPlugin() (v *Plugin) {
	if !p.IsSetPlugin() {
		return PluginTool_Plugin_DEFAULT
	}
	return p.Plugin
}

func (p *PluginTool) GetRequestType() (v []byte) {
	return p.RequestType
}

func (p *PluginTool) GetResponseType() (v []byte) {
	return p.ResponseType
}

func (p *PluginTool) GetApiUrl() (v string) {
	return p.ApiUrl
}

var PluginTool_ImportModelId_DEFAULT int64

func (p *PluginTool) GetImportModelId() (v int64) {
	if !p.IsSetImportModelId() {
		return PluginTool_ImportModelId_DEFAULT
	}
	return *p.ImportModelId
}

var PluginTool_CreatedAt_DEFAULT *base.Time

func (p *PluginTool) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return PluginTool_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}

var PluginTool_UpdatedAt_DEFAULT *base.Time

func (p *PluginTool) GetUpdatedAt() (v *base.Time) {
	if !p.IsSetUpdatedAt() {
		return PluginTool_UpdatedAt_DEFAULT
	}
	return p.UpdatedAt
}

var PluginTool_TestedAt_DEFAULT *base.Time

func (p *PluginTool) GetTestedAt() (v *base.Time) {
	if !p.IsSetTestedAt() {
		return PluginTool_TestedAt_DEFAULT
	}
	return p.TestedAt
}
func (p *PluginTool) SetId(val int64) {
	p.Id = val
}
func (p *PluginTool) SetName(val string) {
	p.Name = val
}
func (p *PluginTool) SetDescription(val string) {
	p.Description = val
}
func (p *PluginTool) SetPluginId(val int64) {
	p.PluginId = val
}
func (p *PluginTool) SetPlugin(val *Plugin) {
	p.Plugin = val
}
func (p *PluginTool) SetRequestType(val []byte) {
	p.RequestType = val
}
func (p *PluginTool) SetResponseType(val []byte) {
	p.ResponseType = val
}
func (p *PluginTool) SetApiUrl(val string) {
	p.ApiUrl = val
}
func (p *PluginTool) SetImportModelId(val *int64) {
	p.ImportModelId = val
}
func (p *PluginTool) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}
func (p *PluginTool) SetUpdatedAt(val *base.Time) {
	p.UpdatedAt = val
}
func (p *PluginTool) SetTestedAt(val *base.Time) {
	p.TestedAt = val
}

func (p *PluginTool) IsSetPlugin() bool {
	return p.Plugin != nil
}

func (p *PluginTool) IsSetImportModelId() bool {
	return p.ImportModelId != nil
}

func (p *PluginTool) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *PluginTool) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *PluginTool) IsSetTestedAt() bool {
	return p.TestedAt != nil
}

func (p *PluginTool) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginTool(%+v)", *p)
}

var fieldIDToName_PluginTool = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "description",
	4:  "plugin_id",
	5:  "plugin",
	6:  "request_type",
	7:  "response_type",
	8:  "api_url",
	9:  "import_model_id",
	10: "created_at",
	11: "updated_at",
	12: "tested_at",
}

type PluginLabel struct {
	Id        int64      `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Text      string     `thrift:"text,2,required" frugal:"2,required,string" json:"text"`
	CreatedAt *base.Time `thrift:"created_at,3,required" frugal:"3,required,base.Time" json:"created_at"`
}

func NewPluginLabel() *PluginLabel {
	return &PluginLabel{}
}

func (p *PluginLabel) InitDefault() {
}

func (p *PluginLabel) GetId() (v int64) {
	return p.Id
}

func (p *PluginLabel) GetText() (v string) {
	return p.Text
}

var PluginLabel_CreatedAt_DEFAULT *base.Time

func (p *PluginLabel) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return PluginLabel_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}
func (p *PluginLabel) SetId(val int64) {
	p.Id = val
}
func (p *PluginLabel) SetText(val string) {
	p.Text = val
}
func (p *PluginLabel) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}

func (p *PluginLabel) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *PluginLabel) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginLabel(%+v)", *p)
}

var fieldIDToName_PluginLabel = map[int16]string{
	1: "id",
	2: "text",
	3: "created_at",
}

type GetPluginByKeyReq struct {
	Key int64 `thrift:"key,1,required" frugal:"1,required,i64" query:"key"`
}

func NewGetPluginByKeyReq() *GetPluginByKeyReq {
	return &GetPluginByKeyReq{}
}

func (p *GetPluginByKeyReq) InitDefault() {
}

func (p *GetPluginByKeyReq) GetKey() (v int64) {
	return p.Key
}
func (p *GetPluginByKeyReq) SetKey(val int64) {
	p.Key = val
}

func (p *GetPluginByKeyReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPluginByKeyReq(%+v)", *p)
}

var fieldIDToName_GetPluginByKeyReq = map[int16]string{
	1: "key",
}

type ListPluginLabelReq struct {
	Pagination *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	Text       *string             `thrift:"text,2,optional" frugal:"2,optional,string" query:"text"`
}

func NewListPluginLabelReq() *ListPluginLabelReq {
	return &ListPluginLabelReq{}
}

func (p *ListPluginLabelReq) InitDefault() {
}

var ListPluginLabelReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListPluginLabelReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListPluginLabelReq_Pagination_DEFAULT
	}
	return p.Pagination
}

var ListPluginLabelReq_Text_DEFAULT string

func (p *ListPluginLabelReq) GetText() (v string) {
	if !p.IsSetText() {
		return ListPluginLabelReq_Text_DEFAULT
	}
	return *p.Text
}
func (p *ListPluginLabelReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListPluginLabelReq) SetText(val *string) {
	p.Text = val
}

func (p *ListPluginLabelReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListPluginLabelReq) IsSetText() bool {
	return p.Text != nil
}

func (p *ListPluginLabelReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPluginLabelReq(%+v)", *p)
}

var fieldIDToName_ListPluginLabelReq = map[int16]string{
	1: "pagination",
	2: "text",
}

type ListPluginLabelResp struct {
	Pagination *base.PaginationResp `thrift:"pagination,1,required" frugal:"1,required,base.PaginationResp" json:"pagination"`
	Labels     []*PluginLabel       `thrift:"labels,2,required" frugal:"2,required,list<PluginLabel>" json:"labels"`
}

func NewListPluginLabelResp() *ListPluginLabelResp {
	return &ListPluginLabelResp{}
}

func (p *ListPluginLabelResp) InitDefault() {
}

var ListPluginLabelResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListPluginLabelResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListPluginLabelResp_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListPluginLabelResp) GetLabels() (v []*PluginLabel) {
	return p.Labels
}
func (p *ListPluginLabelResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}
func (p *ListPluginLabelResp) SetLabels(val []*PluginLabel) {
	p.Labels = val
}

func (p *ListPluginLabelResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListPluginLabelResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPluginLabelResp(%+v)", *p)
}

var fieldIDToName_ListPluginLabelResp = map[int16]string{
	1: "pagination",
	2: "labels",
}

type CreatePluginReq struct {
	Key           int64           `thrift:"key,1,required" frugal:"1,required,i64" json:"key"`
	Name          string          `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Description   string          `thrift:"description,3,required" frugal:"3,required,string" json:"description"`
	DescriptionMd string          `thrift:"description_md,4,required" frugal:"4,required,string" json:"description_md"`
	IsPrivate     bool            `thrift:"is_private,5,required" frugal:"5,required,bool" json:"is_private"`
	HomePage      string          `thrift:"home_page,6,required" frugal:"6,required,string" json:"home_page"`
	EnableSecret  bool            `thrift:"enable_secret,7,required" frugal:"7,required,bool" json:"enable_secret"`
	Secrets       []*PluginSecret `thrift:"secrets,8,required" frugal:"8,required,list<PluginSecret>" json:"secrets"`
	LabelIds      []int64         `thrift:"label_ids,9,required" frugal:"9,required,list<i64>" json:"label_ids"`
	LabelTexts    []string        `thrift:"label_texts,10,required" frugal:"10,required,list<string>" json:"label_texts"`
	ToolIds       []int64         `thrift:"tool_ids,11,required" frugal:"11,required,list<i64>" json:"tool_ids"`
	Logo          string          `thrift:"logo,12,required" frugal:"12,required,string" json:"logo"`
}

func NewCreatePluginReq() *CreatePluginReq {
	return &CreatePluginReq{}
}

func (p *CreatePluginReq) InitDefault() {
}

func (p *CreatePluginReq) GetKey() (v int64) {
	return p.Key
}

func (p *CreatePluginReq) GetName() (v string) {
	return p.Name
}

func (p *CreatePluginReq) GetDescription() (v string) {
	return p.Description
}

func (p *CreatePluginReq) GetDescriptionMd() (v string) {
	return p.DescriptionMd
}

func (p *CreatePluginReq) GetIsPrivate() (v bool) {
	return p.IsPrivate
}

func (p *CreatePluginReq) GetHomePage() (v string) {
	return p.HomePage
}

func (p *CreatePluginReq) GetEnableSecret() (v bool) {
	return p.EnableSecret
}

func (p *CreatePluginReq) GetSecrets() (v []*PluginSecret) {
	return p.Secrets
}

func (p *CreatePluginReq) GetLabelIds() (v []int64) {
	return p.LabelIds
}

func (p *CreatePluginReq) GetLabelTexts() (v []string) {
	return p.LabelTexts
}

func (p *CreatePluginReq) GetToolIds() (v []int64) {
	return p.ToolIds
}

func (p *CreatePluginReq) GetLogo() (v string) {
	return p.Logo
}
func (p *CreatePluginReq) SetKey(val int64) {
	p.Key = val
}
func (p *CreatePluginReq) SetName(val string) {
	p.Name = val
}
func (p *CreatePluginReq) SetDescription(val string) {
	p.Description = val
}
func (p *CreatePluginReq) SetDescriptionMd(val string) {
	p.DescriptionMd = val
}
func (p *CreatePluginReq) SetIsPrivate(val bool) {
	p.IsPrivate = val
}
func (p *CreatePluginReq) SetHomePage(val string) {
	p.HomePage = val
}
func (p *CreatePluginReq) SetEnableSecret(val bool) {
	p.EnableSecret = val
}
func (p *CreatePluginReq) SetSecrets(val []*PluginSecret) {
	p.Secrets = val
}
func (p *CreatePluginReq) SetLabelIds(val []int64) {
	p.LabelIds = val
}
func (p *CreatePluginReq) SetLabelTexts(val []string) {
	p.LabelTexts = val
}
func (p *CreatePluginReq) SetToolIds(val []int64) {
	p.ToolIds = val
}
func (p *CreatePluginReq) SetLogo(val string) {
	p.Logo = val
}

func (p *CreatePluginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreatePluginReq(%+v)", *p)
}

var fieldIDToName_CreatePluginReq = map[int16]string{
	1:  "key",
	2:  "name",
	3:  "description",
	4:  "description_md",
	5:  "is_private",
	6:  "home_page",
	7:  "enable_secret",
	8:  "secrets",
	9:  "label_ids",
	10: "label_texts",
	11: "tool_ids",
	12: "logo",
}

type UpdatePluginReq struct {
	Id            int64           `thrift:"id,1,required" frugal:"1,required,i64" path:"id"`
	Key           *int64          `thrift:"key,2,optional" frugal:"2,optional,i64" json:"key,omitempty"`
	Name          *string         `thrift:"name,3,optional" frugal:"3,optional,string" json:"name,omitempty"`
	Description   *string         `thrift:"description,4,optional" frugal:"4,optional,string" json:"description,omitempty"`
	DescriptionMd *string         `thrift:"description_md,5,optional" frugal:"5,optional,string" json:"description_md,omitempty"`
	IsPrivate     *bool           `thrift:"is_private,6,optional" frugal:"6,optional,bool" json:"is_private,omitempty"`
	HomePage      *string         `thrift:"home_page,7,optional" frugal:"7,optional,string" json:"home_page,omitempty"`
	EnableSecret  *bool           `thrift:"enable_secret,8,optional" frugal:"8,optional,bool" json:"enable_secret,omitempty"`
	Secrets       []*PluginSecret `thrift:"secrets,9,optional" frugal:"9,optional,list<PluginSecret>" json:"secrets,omitempty"`
	LabelIds      []int64         `thrift:"label_ids,10,optional" frugal:"10,optional,list<i64>" json:"label_ids,omitempty"`
	LabelTexts    []string        `thrift:"label_texts,11,optional" frugal:"11,optional,list<string>" json:"label_texts,omitempty"`
	ToolIds       []int64         `thrift:"tool_ids,12,optional" frugal:"12,optional,list<i64>" json:"tool_ids,omitempty"`
	Logo          *string         `thrift:"logo,13,optional" frugal:"13,optional,string" json:"logo,omitempty"`
}

func NewUpdatePluginReq() *UpdatePluginReq {
	return &UpdatePluginReq{}
}

func (p *UpdatePluginReq) InitDefault() {
}

func (p *UpdatePluginReq) GetId() (v int64) {
	return p.Id
}

var UpdatePluginReq_Key_DEFAULT int64

func (p *UpdatePluginReq) GetKey() (v int64) {
	if !p.IsSetKey() {
		return UpdatePluginReq_Key_DEFAULT
	}
	return *p.Key
}

var UpdatePluginReq_Name_DEFAULT string

func (p *UpdatePluginReq) GetName() (v string) {
	if !p.IsSetName() {
		return UpdatePluginReq_Name_DEFAULT
	}
	return *p.Name
}

var UpdatePluginReq_Description_DEFAULT string

func (p *UpdatePluginReq) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return UpdatePluginReq_Description_DEFAULT
	}
	return *p.Description
}

var UpdatePluginReq_DescriptionMd_DEFAULT string

func (p *UpdatePluginReq) GetDescriptionMd() (v string) {
	if !p.IsSetDescriptionMd() {
		return UpdatePluginReq_DescriptionMd_DEFAULT
	}
	return *p.DescriptionMd
}

var UpdatePluginReq_IsPrivate_DEFAULT bool

func (p *UpdatePluginReq) GetIsPrivate() (v bool) {
	if !p.IsSetIsPrivate() {
		return UpdatePluginReq_IsPrivate_DEFAULT
	}
	return *p.IsPrivate
}

var UpdatePluginReq_HomePage_DEFAULT string

func (p *UpdatePluginReq) GetHomePage() (v string) {
	if !p.IsSetHomePage() {
		return UpdatePluginReq_HomePage_DEFAULT
	}
	return *p.HomePage
}

var UpdatePluginReq_EnableSecret_DEFAULT bool

func (p *UpdatePluginReq) GetEnableSecret() (v bool) {
	if !p.IsSetEnableSecret() {
		return UpdatePluginReq_EnableSecret_DEFAULT
	}
	return *p.EnableSecret
}

var UpdatePluginReq_Secrets_DEFAULT []*PluginSecret

func (p *UpdatePluginReq) GetSecrets() (v []*PluginSecret) {
	if !p.IsSetSecrets() {
		return UpdatePluginReq_Secrets_DEFAULT
	}
	return p.Secrets
}

var UpdatePluginReq_LabelIds_DEFAULT []int64

func (p *UpdatePluginReq) GetLabelIds() (v []int64) {
	if !p.IsSetLabelIds() {
		return UpdatePluginReq_LabelIds_DEFAULT
	}
	return p.LabelIds
}

var UpdatePluginReq_LabelTexts_DEFAULT []string

func (p *UpdatePluginReq) GetLabelTexts() (v []string) {
	if !p.IsSetLabelTexts() {
		return UpdatePluginReq_LabelTexts_DEFAULT
	}
	return p.LabelTexts
}

var UpdatePluginReq_ToolIds_DEFAULT []int64

func (p *UpdatePluginReq) GetToolIds() (v []int64) {
	if !p.IsSetToolIds() {
		return UpdatePluginReq_ToolIds_DEFAULT
	}
	return p.ToolIds
}

var UpdatePluginReq_Logo_DEFAULT string

func (p *UpdatePluginReq) GetLogo() (v string) {
	if !p.IsSetLogo() {
		return UpdatePluginReq_Logo_DEFAULT
	}
	return *p.Logo
}
func (p *UpdatePluginReq) SetId(val int64) {
	p.Id = val
}
func (p *UpdatePluginReq) SetKey(val *int64) {
	p.Key = val
}
func (p *UpdatePluginReq) SetName(val *string) {
	p.Name = val
}
func (p *UpdatePluginReq) SetDescription(val *string) {
	p.Description = val
}
func (p *UpdatePluginReq) SetDescriptionMd(val *string) {
	p.DescriptionMd = val
}
func (p *UpdatePluginReq) SetIsPrivate(val *bool) {
	p.IsPrivate = val
}
func (p *UpdatePluginReq) SetHomePage(val *string) {
	p.HomePage = val
}
func (p *UpdatePluginReq) SetEnableSecret(val *bool) {
	p.EnableSecret = val
}
func (p *UpdatePluginReq) SetSecrets(val []*PluginSecret) {
	p.Secrets = val
}
func (p *UpdatePluginReq) SetLabelIds(val []int64) {
	p.LabelIds = val
}
func (p *UpdatePluginReq) SetLabelTexts(val []string) {
	p.LabelTexts = val
}
func (p *UpdatePluginReq) SetToolIds(val []int64) {
	p.ToolIds = val
}
func (p *UpdatePluginReq) SetLogo(val *string) {
	p.Logo = val
}

func (p *UpdatePluginReq) IsSetKey() bool {
	return p.Key != nil
}

func (p *UpdatePluginReq) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdatePluginReq) IsSetDescription() bool {
	return p.Description != nil
}

func (p *UpdatePluginReq) IsSetDescriptionMd() bool {
	return p.DescriptionMd != nil
}

func (p *UpdatePluginReq) IsSetIsPrivate() bool {
	return p.IsPrivate != nil
}

func (p *UpdatePluginReq) IsSetHomePage() bool {
	return p.HomePage != nil
}

func (p *UpdatePluginReq) IsSetEnableSecret() bool {
	return p.EnableSecret != nil
}

func (p *UpdatePluginReq) IsSetSecrets() bool {
	return p.Secrets != nil
}

func (p *UpdatePluginReq) IsSetLabelIds() bool {
	return p.LabelIds != nil
}

func (p *UpdatePluginReq) IsSetLabelTexts() bool {
	return p.LabelTexts != nil
}

func (p *UpdatePluginReq) IsSetToolIds() bool {
	return p.ToolIds != nil
}

func (p *UpdatePluginReq) IsSetLogo() bool {
	return p.Logo != nil
}

func (p *UpdatePluginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdatePluginReq(%+v)", *p)
}

var fieldIDToName_UpdatePluginReq = map[int16]string{
	1:  "id",
	2:  "key",
	3:  "name",
	4:  "description",
	5:  "description_md",
	6:  "is_private",
	7:  "home_page",
	8:  "enable_secret",
	9:  "secrets",
	10: "label_ids",
	11: "label_texts",
	12: "tool_ids",
	13: "logo",
}

type ListPluginReq struct {
	Pagination  *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	AuthorId    *int64              `thrift:"author_id,2,optional" frugal:"2,optional,i64" json:"author_id,omitempty"`
	Name        *string             `thrift:"name,3,optional" frugal:"3,optional,string" json:"name,omitempty"`
	Description *string             `thrift:"description,4,optional" frugal:"4,optional,string" json:"description,omitempty"`
	Labels      []int64             `thrift:"labels,5,optional" frugal:"5,optional,list<i64>" json:"labels,omitempty"`
}

func NewListPluginReq() *ListPluginReq {
	return &ListPluginReq{}
}

func (p *ListPluginReq) InitDefault() {
}

var ListPluginReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListPluginReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListPluginReq_Pagination_DEFAULT
	}
	return p.Pagination
}

var ListPluginReq_AuthorId_DEFAULT int64

func (p *ListPluginReq) GetAuthorId() (v int64) {
	if !p.IsSetAuthorId() {
		return ListPluginReq_AuthorId_DEFAULT
	}
	return *p.AuthorId
}

var ListPluginReq_Name_DEFAULT string

func (p *ListPluginReq) GetName() (v string) {
	if !p.IsSetName() {
		return ListPluginReq_Name_DEFAULT
	}
	return *p.Name
}

var ListPluginReq_Description_DEFAULT string

func (p *ListPluginReq) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return ListPluginReq_Description_DEFAULT
	}
	return *p.Description
}

var ListPluginReq_Labels_DEFAULT []int64

func (p *ListPluginReq) GetLabels() (v []int64) {
	if !p.IsSetLabels() {
		return ListPluginReq_Labels_DEFAULT
	}
	return p.Labels
}
func (p *ListPluginReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListPluginReq) SetAuthorId(val *int64) {
	p.AuthorId = val
}
func (p *ListPluginReq) SetName(val *string) {
	p.Name = val
}
func (p *ListPluginReq) SetDescription(val *string) {
	p.Description = val
}
func (p *ListPluginReq) SetLabels(val []int64) {
	p.Labels = val
}

func (p *ListPluginReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListPluginReq) IsSetAuthorId() bool {
	return p.AuthorId != nil
}

func (p *ListPluginReq) IsSetName() bool {
	return p.Name != nil
}

func (p *ListPluginReq) IsSetDescription() bool {
	return p.Description != nil
}

func (p *ListPluginReq) IsSetLabels() bool {
	return p.Labels != nil
}

func (p *ListPluginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPluginReq(%+v)", *p)
}

var fieldIDToName_ListPluginReq = map[int16]string{
	1: "pagination",
	2: "author_id",
	3: "name",
	4: "description",
	5: "labels",
}

type ListPluginResp struct {
	Pagination *base.PaginationResp `thrift:"pagination,1,required" frugal:"1,required,base.PaginationResp" json:"pagination"`
	Plugins    []*Plugin            `thrift:"plugins,2,required" frugal:"2,required,list<Plugin>" json:"plugins"`
}

func NewListPluginResp() *ListPluginResp {
	return &ListPluginResp{}
}

func (p *ListPluginResp) InitDefault() {
}

var ListPluginResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListPluginResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListPluginResp_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListPluginResp) GetPlugins() (v []*Plugin) {
	return p.Plugins
}
func (p *ListPluginResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}
func (p *ListPluginResp) SetPlugins(val []*Plugin) {
	p.Plugins = val
}

func (p *ListPluginResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListPluginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPluginResp(%+v)", *p)
}

var fieldIDToName_ListPluginResp = map[int16]string{
	1: "pagination",
	2: "plugins",
}

type CreatePluginToolReq struct {
	Name          string `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Description   string `thrift:"description,2,required" frugal:"2,required,string" json:"description"`
	PluginId      int64  `thrift:"plugin_id,3,required" frugal:"3,required,i64" json:"plugin_id"`
	RequestType   []byte `thrift:"request_type,4,required" frugal:"4,required,binary" json:"request_type"`
	ResponseType  []byte `thrift:"response_type,5,required" frugal:"5,required,binary" json:"response_type"`
	ApiUrl        string `thrift:"api_url,6,required" frugal:"6,required,string" json:"api_url"`
	ImportModelId *int64 `thrift:"import_model_id,7,optional" frugal:"7,optional,i64" json:"import_model_id,omitempty"`
}

func NewCreatePluginToolReq() *CreatePluginToolReq {
	return &CreatePluginToolReq{}
}

func (p *CreatePluginToolReq) InitDefault() {
}

func (p *CreatePluginToolReq) GetName() (v string) {
	return p.Name
}

func (p *CreatePluginToolReq) GetDescription() (v string) {
	return p.Description
}

func (p *CreatePluginToolReq) GetPluginId() (v int64) {
	return p.PluginId
}

func (p *CreatePluginToolReq) GetRequestType() (v []byte) {
	return p.RequestType
}

func (p *CreatePluginToolReq) GetResponseType() (v []byte) {
	return p.ResponseType
}

func (p *CreatePluginToolReq) GetApiUrl() (v string) {
	return p.ApiUrl
}

var CreatePluginToolReq_ImportModelId_DEFAULT int64

func (p *CreatePluginToolReq) GetImportModelId() (v int64) {
	if !p.IsSetImportModelId() {
		return CreatePluginToolReq_ImportModelId_DEFAULT
	}
	return *p.ImportModelId
}
func (p *CreatePluginToolReq) SetName(val string) {
	p.Name = val
}
func (p *CreatePluginToolReq) SetDescription(val string) {
	p.Description = val
}
func (p *CreatePluginToolReq) SetPluginId(val int64) {
	p.PluginId = val
}
func (p *CreatePluginToolReq) SetRequestType(val []byte) {
	p.RequestType = val
}
func (p *CreatePluginToolReq) SetResponseType(val []byte) {
	p.ResponseType = val
}
func (p *CreatePluginToolReq) SetApiUrl(val string) {
	p.ApiUrl = val
}
func (p *CreatePluginToolReq) SetImportModelId(val *int64) {
	p.ImportModelId = val
}

func (p *CreatePluginToolReq) IsSetImportModelId() bool {
	return p.ImportModelId != nil
}

func (p *CreatePluginToolReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreatePluginToolReq(%+v)", *p)
}

var fieldIDToName_CreatePluginToolReq = map[int16]string{
	1: "name",
	2: "description",
	3: "plugin_id",
	4: "request_type",
	5: "response_type",
	6: "api_url",
	7: "import_model_id",
}

type UpdatePluginToolReq struct {
	Id            int64   `thrift:"id,1,required" frugal:"1,required,i64" path:"id"`
	Name          *string `thrift:"name,2,optional" frugal:"2,optional,string" json:"name,omitempty"`
	Description   *string `thrift:"description,3,optional" frugal:"3,optional,string" json:"description,omitempty"`
	PluginId      *int64  `thrift:"plugin_id,4,optional" frugal:"4,optional,i64" json:"plugin_id,omitempty"`
	RequestType   []byte  `thrift:"request_type,5,optional" frugal:"5,optional,binary" json:"request_type,omitempty"`
	ResponseType  []byte  `thrift:"response_type,6,optional" frugal:"6,optional,binary" json:"response_type,omitempty"`
	ApiUrl        *string `thrift:"api_url,7,optional" frugal:"7,optional,string" json:"api_url,omitempty"`
	ImportModelId *int64  `thrift:"import_model_id,8,optional" frugal:"8,optional,i64" json:"import_model_id,omitempty"`
}

func NewUpdatePluginToolReq() *UpdatePluginToolReq {
	return &UpdatePluginToolReq{}
}

func (p *UpdatePluginToolReq) InitDefault() {
}

func (p *UpdatePluginToolReq) GetId() (v int64) {
	return p.Id
}

var UpdatePluginToolReq_Name_DEFAULT string

func (p *UpdatePluginToolReq) GetName() (v string) {
	if !p.IsSetName() {
		return UpdatePluginToolReq_Name_DEFAULT
	}
	return *p.Name
}

var UpdatePluginToolReq_Description_DEFAULT string

func (p *UpdatePluginToolReq) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return UpdatePluginToolReq_Description_DEFAULT
	}
	return *p.Description
}

var UpdatePluginToolReq_PluginId_DEFAULT int64

func (p *UpdatePluginToolReq) GetPluginId() (v int64) {
	if !p.IsSetPluginId() {
		return UpdatePluginToolReq_PluginId_DEFAULT
	}
	return *p.PluginId
}

var UpdatePluginToolReq_RequestType_DEFAULT []byte

func (p *UpdatePluginToolReq) GetRequestType() (v []byte) {
	if !p.IsSetRequestType() {
		return UpdatePluginToolReq_RequestType_DEFAULT
	}
	return p.RequestType
}

var UpdatePluginToolReq_ResponseType_DEFAULT []byte

func (p *UpdatePluginToolReq) GetResponseType() (v []byte) {
	if !p.IsSetResponseType() {
		return UpdatePluginToolReq_ResponseType_DEFAULT
	}
	return p.ResponseType
}

var UpdatePluginToolReq_ApiUrl_DEFAULT string

func (p *UpdatePluginToolReq) GetApiUrl() (v string) {
	if !p.IsSetApiUrl() {
		return UpdatePluginToolReq_ApiUrl_DEFAULT
	}
	return *p.ApiUrl
}

var UpdatePluginToolReq_ImportModelId_DEFAULT int64

func (p *UpdatePluginToolReq) GetImportModelId() (v int64) {
	if !p.IsSetImportModelId() {
		return UpdatePluginToolReq_ImportModelId_DEFAULT
	}
	return *p.ImportModelId
}
func (p *UpdatePluginToolReq) SetId(val int64) {
	p.Id = val
}
func (p *UpdatePluginToolReq) SetName(val *string) {
	p.Name = val
}
func (p *UpdatePluginToolReq) SetDescription(val *string) {
	p.Description = val
}
func (p *UpdatePluginToolReq) SetPluginId(val *int64) {
	p.PluginId = val
}
func (p *UpdatePluginToolReq) SetRequestType(val []byte) {
	p.RequestType = val
}
func (p *UpdatePluginToolReq) SetResponseType(val []byte) {
	p.ResponseType = val
}
func (p *UpdatePluginToolReq) SetApiUrl(val *string) {
	p.ApiUrl = val
}
func (p *UpdatePluginToolReq) SetImportModelId(val *int64) {
	p.ImportModelId = val
}

func (p *UpdatePluginToolReq) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdatePluginToolReq) IsSetDescription() bool {
	return p.Description != nil
}

func (p *UpdatePluginToolReq) IsSetPluginId() bool {
	return p.PluginId != nil
}

func (p *UpdatePluginToolReq) IsSetRequestType() bool {
	return p.RequestType != nil
}

func (p *UpdatePluginToolReq) IsSetResponseType() bool {
	return p.ResponseType != nil
}

func (p *UpdatePluginToolReq) IsSetApiUrl() bool {
	return p.ApiUrl != nil
}

func (p *UpdatePluginToolReq) IsSetImportModelId() bool {
	return p.ImportModelId != nil
}

func (p *UpdatePluginToolReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdatePluginToolReq(%+v)", *p)
}

var fieldIDToName_UpdatePluginToolReq = map[int16]string{
	1: "id",
	2: "name",
	3: "description",
	4: "plugin_id",
	5: "request_type",
	6: "response_type",
	7: "api_url",
	8: "import_model_id",
}

type ListPluginToolReq struct {
	Pagination *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	PluginId   *int64              `thrift:"plugin_id,2,optional" frugal:"2,optional,i64" json:"plugin_id,omitempty"`
	ToolIds    []int64             `thrift:"tool_ids,3,optional" frugal:"3,optional,list<i64>" json:"tool_ids,omitempty"`
}

func NewListPluginToolReq() *ListPluginToolReq {
	return &ListPluginToolReq{}
}

func (p *ListPluginToolReq) InitDefault() {
}

var ListPluginToolReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListPluginToolReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListPluginToolReq_Pagination_DEFAULT
	}
	return p.Pagination
}

var ListPluginToolReq_PluginId_DEFAULT int64

func (p *ListPluginToolReq) GetPluginId() (v int64) {
	if !p.IsSetPluginId() {
		return ListPluginToolReq_PluginId_DEFAULT
	}
	return *p.PluginId
}

var ListPluginToolReq_ToolIds_DEFAULT []int64

func (p *ListPluginToolReq) GetToolIds() (v []int64) {
	if !p.IsSetToolIds() {
		return ListPluginToolReq_ToolIds_DEFAULT
	}
	return p.ToolIds
}
func (p *ListPluginToolReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListPluginToolReq) SetPluginId(val *int64) {
	p.PluginId = val
}
func (p *ListPluginToolReq) SetToolIds(val []int64) {
	p.ToolIds = val
}

func (p *ListPluginToolReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListPluginToolReq) IsSetPluginId() bool {
	return p.PluginId != nil
}

func (p *ListPluginToolReq) IsSetToolIds() bool {
	return p.ToolIds != nil
}

func (p *ListPluginToolReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPluginToolReq(%+v)", *p)
}

var fieldIDToName_ListPluginToolReq = map[int16]string{
	1: "pagination",
	2: "plugin_id",
	3: "tool_ids",
}

type ListPluginToolResp struct {
	Tools      []*PluginTool        `thrift:"tools,1,required" frugal:"1,required,list<PluginTool>" json:"tools"`
	Pagination *base.PaginationResp `thrift:"pagination,2,required" frugal:"2,required,base.PaginationResp" json:"pagination"`
}

func NewListPluginToolResp() *ListPluginToolResp {
	return &ListPluginToolResp{}
}

func (p *ListPluginToolResp) InitDefault() {
}

func (p *ListPluginToolResp) GetTools() (v []*PluginTool) {
	return p.Tools
}

var ListPluginToolResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListPluginToolResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListPluginToolResp_Pagination_DEFAULT
	}
	return p.Pagination
}
func (p *ListPluginToolResp) SetTools(val []*PluginTool) {
	p.Tools = val
}
func (p *ListPluginToolResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}

func (p *ListPluginToolResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListPluginToolResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPluginToolResp(%+v)", *p)
}

var fieldIDToName_ListPluginToolResp = map[int16]string{
	1: "tools",
	2: "pagination",
}

type AllPluginToolReq struct {
	ToolIds []int64 `thrift:"tool_ids,1,required" frugal:"1,required,list<i64>" json:"tool_ids"`
}

func NewAllPluginToolReq() *AllPluginToolReq {
	return &AllPluginToolReq{}
}

func (p *AllPluginToolReq) InitDefault() {
}

func (p *AllPluginToolReq) GetToolIds() (v []int64) {
	return p.ToolIds
}
func (p *AllPluginToolReq) SetToolIds(val []int64) {
	p.ToolIds = val
}

func (p *AllPluginToolReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AllPluginToolReq(%+v)", *p)
}

var fieldIDToName_AllPluginToolReq = map[int16]string{
	1: "tool_ids",
}

type CallPluginToolReq struct {
	PluginId int64             `thrift:"plugin_id,1,required" frugal:"1,required,i64" json:"plugin_id"`
	ToolId   int64             `thrift:"tool_id,2,required" frugal:"2,required,i64" json:"tool_id"`
	Secrets  map[string]string `thrift:"secrets,3,optional" frugal:"3,optional,map<string:string>" json:"secrets,omitempty"`
	Request  []byte            `thrift:"request,4,required" frugal:"4,required,binary" json:"request"`
}

func NewCallPluginToolReq() *CallPluginToolReq {
	return &CallPluginToolReq{}
}

func (p *CallPluginToolReq) InitDefault() {
}

func (p *CallPluginToolReq) GetPluginId() (v int64) {
	return p.PluginId
}

func (p *CallPluginToolReq) GetToolId() (v int64) {
	return p.ToolId
}

var CallPluginToolReq_Secrets_DEFAULT map[string]string

func (p *CallPluginToolReq) GetSecrets() (v map[string]string) {
	if !p.IsSetSecrets() {
		return CallPluginToolReq_Secrets_DEFAULT
	}
	return p.Secrets
}

func (p *CallPluginToolReq) GetRequest() (v []byte) {
	return p.Request
}
func (p *CallPluginToolReq) SetPluginId(val int64) {
	p.PluginId = val
}
func (p *CallPluginToolReq) SetToolId(val int64) {
	p.ToolId = val
}
func (p *CallPluginToolReq) SetSecrets(val map[string]string) {
	p.Secrets = val
}
func (p *CallPluginToolReq) SetRequest(val []byte) {
	p.Request = val
}

func (p *CallPluginToolReq) IsSetSecrets() bool {
	return p.Secrets != nil
}

func (p *CallPluginToolReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CallPluginToolReq(%+v)", *p)
}

var fieldIDToName_CallPluginToolReq = map[int16]string{
	1: "plugin_id",
	2: "tool_id",
	3: "secrets",
	4: "request",
}

type CallPluginToolResp struct {
	Code     int64  `thrift:"code,1,required" frugal:"1,required,i64" json:"code"`
	Msg      string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Response []byte `thrift:"response,3,required" frugal:"3,required,binary" json:"response"`
	HttpCode int64  `thrift:"http_code,4,required" frugal:"4,required,i64" json:"http_code"`
}

func NewCallPluginToolResp() *CallPluginToolResp {
	return &CallPluginToolResp{}
}

func (p *CallPluginToolResp) InitDefault() {
}

func (p *CallPluginToolResp) GetCode() (v int64) {
	return p.Code
}

func (p *CallPluginToolResp) GetMsg() (v string) {
	return p.Msg
}

func (p *CallPluginToolResp) GetResponse() (v []byte) {
	return p.Response
}

func (p *CallPluginToolResp) GetHttpCode() (v int64) {
	return p.HttpCode
}
func (p *CallPluginToolResp) SetCode(val int64) {
	p.Code = val
}
func (p *CallPluginToolResp) SetMsg(val string) {
	p.Msg = val
}
func (p *CallPluginToolResp) SetResponse(val []byte) {
	p.Response = val
}
func (p *CallPluginToolResp) SetHttpCode(val int64) {
	p.HttpCode = val
}

func (p *CallPluginToolResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CallPluginToolResp(%+v)", *p)
}

var fieldIDToName_CallPluginToolResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "response",
	4: "http_code",
}

type TestPluginToolResp struct {
	Code     int64  `thrift:"code,1,required" frugal:"1,required,i64" json:"code"`
	Msg      string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Response []byte `thrift:"response,3,required" frugal:"3,required,binary" json:"response"`
	HttpCode int64  `thrift:"http_code,4,required" frugal:"4,required,i64" json:"http_code"`
}

func NewTestPluginToolResp() *TestPluginToolResp {
	return &TestPluginToolResp{}
}

func (p *TestPluginToolResp) InitDefault() {
}

func (p *TestPluginToolResp) GetCode() (v int64) {
	return p.Code
}

func (p *TestPluginToolResp) GetMsg() (v string) {
	return p.Msg
}

func (p *TestPluginToolResp) GetResponse() (v []byte) {
	return p.Response
}

func (p *TestPluginToolResp) GetHttpCode() (v int64) {
	return p.HttpCode
}
func (p *TestPluginToolResp) SetCode(val int64) {
	p.Code = val
}
func (p *TestPluginToolResp) SetMsg(val string) {
	p.Msg = val
}
func (p *TestPluginToolResp) SetResponse(val []byte) {
	p.Response = val
}
func (p *TestPluginToolResp) SetHttpCode(val int64) {
	p.HttpCode = val
}

func (p *TestPluginToolResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestPluginToolResp(%+v)", *p)
}

var fieldIDToName_TestPluginToolResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "response",
	4: "http_code",
}

type ListPluginByToolsReq struct {
	ToolIds []int64 `thrift:"tool_ids,1,required" frugal:"1,required,list<i64>" json:"tool_ids"`
}

func NewListPluginByToolsReq() *ListPluginByToolsReq {
	return &ListPluginByToolsReq{}
}

func (p *ListPluginByToolsReq) InitDefault() {
}

func (p *ListPluginByToolsReq) GetToolIds() (v []int64) {
	return p.ToolIds
}
func (p *ListPluginByToolsReq) SetToolIds(val []int64) {
	p.ToolIds = val
}

func (p *ListPluginByToolsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPluginByToolsReq(%+v)", *p)
}

var fieldIDToName_ListPluginByToolsReq = map[int16]string{
	1: "tool_ids",
}

type ListPluginByToolsResp struct {
	Plugins []*Plugin `thrift:"plugins,1,required" frugal:"1,required,list<Plugin>" json:"plugins"`
}

func NewListPluginByToolsResp() *ListPluginByToolsResp {
	return &ListPluginByToolsResp{}
}

func (p *ListPluginByToolsResp) InitDefault() {
}

func (p *ListPluginByToolsResp) GetPlugins() (v []*Plugin) {
	return p.Plugins
}
func (p *ListPluginByToolsResp) SetPlugins(val []*Plugin) {
	p.Plugins = val
}

func (p *ListPluginByToolsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPluginByToolsResp(%+v)", *p)
}

var fieldIDToName_ListPluginByToolsResp = map[int16]string{
	1: "plugins",
}

type PluginSecrets struct {
	PluginId   int64           `thrift:"plugin_id,1,required" frugal:"1,required,i64" json:"plugin_id"`
	PluginName string          `thrift:"plugin_name,2,required" frugal:"2,required,string" json:"plugin_name"`
	Secrets    []*PluginSecret `thrift:"secrets,3,required" frugal:"3,required,list<PluginSecret>" json:"secrets"`
	IsPrivate  bool            `thrift:"is_private,4,required" frugal:"4,required,bool" json:"is_private"`
	AuthorId   int64           `thrift:"author_id,5,required" frugal:"5,required,i64" json:"author_id"`
	PluginLogo string          `thrift:"plugin_logo,6,required" frugal:"6,required,string" json:"plugin_logo"`
}

func NewPluginSecrets() *PluginSecrets {
	return &PluginSecrets{}
}

func (p *PluginSecrets) InitDefault() {
}

func (p *PluginSecrets) GetPluginId() (v int64) {
	return p.PluginId
}

func (p *PluginSecrets) GetPluginName() (v string) {
	return p.PluginName
}

func (p *PluginSecrets) GetSecrets() (v []*PluginSecret) {
	return p.Secrets
}

func (p *PluginSecrets) GetIsPrivate() (v bool) {
	return p.IsPrivate
}

func (p *PluginSecrets) GetAuthorId() (v int64) {
	return p.AuthorId
}

func (p *PluginSecrets) GetPluginLogo() (v string) {
	return p.PluginLogo
}
func (p *PluginSecrets) SetPluginId(val int64) {
	p.PluginId = val
}
func (p *PluginSecrets) SetPluginName(val string) {
	p.PluginName = val
}
func (p *PluginSecrets) SetSecrets(val []*PluginSecret) {
	p.Secrets = val
}
func (p *PluginSecrets) SetIsPrivate(val bool) {
	p.IsPrivate = val
}
func (p *PluginSecrets) SetAuthorId(val int64) {
	p.AuthorId = val
}
func (p *PluginSecrets) SetPluginLogo(val string) {
	p.PluginLogo = val
}

func (p *PluginSecrets) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginSecrets(%+v)", *p)
}

var fieldIDToName_PluginSecrets = map[int16]string{
	1: "plugin_id",
	2: "plugin_name",
	3: "secrets",
	4: "is_private",
	5: "author_id",
	6: "plugin_logo",
}

type PluginService interface {
	CreatePlugin(ctx context.Context, req *CreatePluginReq) (r *base.Empty, err error)

	UpdatePlugin(ctx context.Context, req *UpdatePluginReq) (r *base.Empty, err error)

	DeletePlugin(ctx context.Context, req *base.IDReq) (r *base.Empty, err error)

	GetPluginByID(ctx context.Context, req *base.IDReq) (r *Plugin, err error)

	GetPluginByIDs(ctx context.Context, req *base.IDsReq) (r []*Plugin, err error)

	GetPluginByKey(ctx context.Context, req *GetPluginByKeyReq) (r *Plugin, err error)

	ListPlugin(ctx context.Context, req *ListPluginReq) (r *ListPluginResp, err error)

	ListPluginByTools(ctx context.Context, req *ListPluginByToolsReq) (r *ListPluginByToolsResp, err error)

	GetPluginSecretsByTools(ctx context.Context, req *base.IDsReq) (r []*PluginSecrets, err error)

	PublishPlugin(ctx context.Context, req *base.IDReq) (r *base.Empty, err error)

	CreateTool(ctx context.Context, req *CreatePluginToolReq) (r *base.Empty, err error)

	UpdateTool(ctx context.Context, req *UpdatePluginToolReq) (r *base.Empty, err error)

	DeleteTool(ctx context.Context, req *base.IDReq) (r *base.Empty, err error)

	GetToolByID(ctx context.Context, req *base.IDReq) (r *PluginTool, err error)

	ListPluginTool(ctx context.Context, req *ListPluginToolReq) (r *ListPluginToolResp, err error)

	AllPluginTool(ctx context.Context, req *AllPluginToolReq) (r []*PluginTool, err error)

	ListPluginLabel(ctx context.Context, req *ListPluginLabelReq) (r *ListPluginLabelResp, err error)

	CallPluginTool(ctx context.Context, req *CallPluginToolReq) (r *CallPluginToolResp, err error)

	TestPluginTool(ctx context.Context, req *CallPluginToolReq) (r *TestPluginToolResp, err error)
}

type PluginServiceCreatePluginArgs struct {
	Req *CreatePluginReq `thrift:"req,1" frugal:"1,default,CreatePluginReq" json:"req"`
}

func NewPluginServiceCreatePluginArgs() *PluginServiceCreatePluginArgs {
	return &PluginServiceCreatePluginArgs{}
}

func (p *PluginServiceCreatePluginArgs) InitDefault() {
}

var PluginServiceCreatePluginArgs_Req_DEFAULT *CreatePluginReq

func (p *PluginServiceCreatePluginArgs) GetReq() (v *CreatePluginReq) {
	if !p.IsSetReq() {
		return PluginServiceCreatePluginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceCreatePluginArgs) SetReq(val *CreatePluginReq) {
	p.Req = val
}

func (p *PluginServiceCreatePluginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceCreatePluginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceCreatePluginArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceCreatePluginArgs = map[int16]string{
	1: "req",
}

type PluginServiceCreatePluginResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewPluginServiceCreatePluginResult() *PluginServiceCreatePluginResult {
	return &PluginServiceCreatePluginResult{}
}

func (p *PluginServiceCreatePluginResult) InitDefault() {
}

var PluginServiceCreatePluginResult_Success_DEFAULT *base.Empty

func (p *PluginServiceCreatePluginResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return PluginServiceCreatePluginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceCreatePluginResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *PluginServiceCreatePluginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceCreatePluginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceCreatePluginResult(%+v)", *p)
}

var fieldIDToName_PluginServiceCreatePluginResult = map[int16]string{
	0: "success",
}

type PluginServiceUpdatePluginArgs struct {
	Req *UpdatePluginReq `thrift:"req,1" frugal:"1,default,UpdatePluginReq" json:"req"`
}

func NewPluginServiceUpdatePluginArgs() *PluginServiceUpdatePluginArgs {
	return &PluginServiceUpdatePluginArgs{}
}

func (p *PluginServiceUpdatePluginArgs) InitDefault() {
}

var PluginServiceUpdatePluginArgs_Req_DEFAULT *UpdatePluginReq

func (p *PluginServiceUpdatePluginArgs) GetReq() (v *UpdatePluginReq) {
	if !p.IsSetReq() {
		return PluginServiceUpdatePluginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceUpdatePluginArgs) SetReq(val *UpdatePluginReq) {
	p.Req = val
}

func (p *PluginServiceUpdatePluginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceUpdatePluginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceUpdatePluginArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceUpdatePluginArgs = map[int16]string{
	1: "req",
}

type PluginServiceUpdatePluginResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewPluginServiceUpdatePluginResult() *PluginServiceUpdatePluginResult {
	return &PluginServiceUpdatePluginResult{}
}

func (p *PluginServiceUpdatePluginResult) InitDefault() {
}

var PluginServiceUpdatePluginResult_Success_DEFAULT *base.Empty

func (p *PluginServiceUpdatePluginResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return PluginServiceUpdatePluginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceUpdatePluginResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *PluginServiceUpdatePluginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceUpdatePluginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceUpdatePluginResult(%+v)", *p)
}

var fieldIDToName_PluginServiceUpdatePluginResult = map[int16]string{
	0: "success",
}

type PluginServiceDeletePluginArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewPluginServiceDeletePluginArgs() *PluginServiceDeletePluginArgs {
	return &PluginServiceDeletePluginArgs{}
}

func (p *PluginServiceDeletePluginArgs) InitDefault() {
}

var PluginServiceDeletePluginArgs_Req_DEFAULT *base.IDReq

func (p *PluginServiceDeletePluginArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return PluginServiceDeletePluginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceDeletePluginArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *PluginServiceDeletePluginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceDeletePluginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceDeletePluginArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceDeletePluginArgs = map[int16]string{
	1: "req",
}

type PluginServiceDeletePluginResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewPluginServiceDeletePluginResult() *PluginServiceDeletePluginResult {
	return &PluginServiceDeletePluginResult{}
}

func (p *PluginServiceDeletePluginResult) InitDefault() {
}

var PluginServiceDeletePluginResult_Success_DEFAULT *base.Empty

func (p *PluginServiceDeletePluginResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return PluginServiceDeletePluginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceDeletePluginResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *PluginServiceDeletePluginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceDeletePluginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceDeletePluginResult(%+v)", *p)
}

var fieldIDToName_PluginServiceDeletePluginResult = map[int16]string{
	0: "success",
}

type PluginServiceGetPluginByIDArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewPluginServiceGetPluginByIDArgs() *PluginServiceGetPluginByIDArgs {
	return &PluginServiceGetPluginByIDArgs{}
}

func (p *PluginServiceGetPluginByIDArgs) InitDefault() {
}

var PluginServiceGetPluginByIDArgs_Req_DEFAULT *base.IDReq

func (p *PluginServiceGetPluginByIDArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return PluginServiceGetPluginByIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceGetPluginByIDArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *PluginServiceGetPluginByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceGetPluginByIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetPluginByIDArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceGetPluginByIDArgs = map[int16]string{
	1: "req",
}

type PluginServiceGetPluginByIDResult struct {
	Success *Plugin `thrift:"success,0,optional" frugal:"0,optional,Plugin" json:"success,omitempty"`
}

func NewPluginServiceGetPluginByIDResult() *PluginServiceGetPluginByIDResult {
	return &PluginServiceGetPluginByIDResult{}
}

func (p *PluginServiceGetPluginByIDResult) InitDefault() {
}

var PluginServiceGetPluginByIDResult_Success_DEFAULT *Plugin

func (p *PluginServiceGetPluginByIDResult) GetSuccess() (v *Plugin) {
	if !p.IsSetSuccess() {
		return PluginServiceGetPluginByIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceGetPluginByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*Plugin)
}

func (p *PluginServiceGetPluginByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceGetPluginByIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetPluginByIDResult(%+v)", *p)
}

var fieldIDToName_PluginServiceGetPluginByIDResult = map[int16]string{
	0: "success",
}

type PluginServiceGetPluginByIDsArgs struct {
	Req *base.IDsReq `thrift:"req,1" frugal:"1,default,base.IDsReq" json:"req"`
}

func NewPluginServiceGetPluginByIDsArgs() *PluginServiceGetPluginByIDsArgs {
	return &PluginServiceGetPluginByIDsArgs{}
}

func (p *PluginServiceGetPluginByIDsArgs) InitDefault() {
}

var PluginServiceGetPluginByIDsArgs_Req_DEFAULT *base.IDsReq

func (p *PluginServiceGetPluginByIDsArgs) GetReq() (v *base.IDsReq) {
	if !p.IsSetReq() {
		return PluginServiceGetPluginByIDsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceGetPluginByIDsArgs) SetReq(val *base.IDsReq) {
	p.Req = val
}

func (p *PluginServiceGetPluginByIDsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceGetPluginByIDsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetPluginByIDsArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceGetPluginByIDsArgs = map[int16]string{
	1: "req",
}

type PluginServiceGetPluginByIDsResult struct {
	Success []*Plugin `thrift:"success,0,optional" frugal:"0,optional,list<Plugin>" json:"success,omitempty"`
}

func NewPluginServiceGetPluginByIDsResult() *PluginServiceGetPluginByIDsResult {
	return &PluginServiceGetPluginByIDsResult{}
}

func (p *PluginServiceGetPluginByIDsResult) InitDefault() {
}

var PluginServiceGetPluginByIDsResult_Success_DEFAULT []*Plugin

func (p *PluginServiceGetPluginByIDsResult) GetSuccess() (v []*Plugin) {
	if !p.IsSetSuccess() {
		return PluginServiceGetPluginByIDsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceGetPluginByIDsResult) SetSuccess(x interface{}) {
	p.Success = x.([]*Plugin)
}

func (p *PluginServiceGetPluginByIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceGetPluginByIDsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetPluginByIDsResult(%+v)", *p)
}

var fieldIDToName_PluginServiceGetPluginByIDsResult = map[int16]string{
	0: "success",
}

type PluginServiceGetPluginByKeyArgs struct {
	Req *GetPluginByKeyReq `thrift:"req,1" frugal:"1,default,GetPluginByKeyReq" json:"req"`
}

func NewPluginServiceGetPluginByKeyArgs() *PluginServiceGetPluginByKeyArgs {
	return &PluginServiceGetPluginByKeyArgs{}
}

func (p *PluginServiceGetPluginByKeyArgs) InitDefault() {
}

var PluginServiceGetPluginByKeyArgs_Req_DEFAULT *GetPluginByKeyReq

func (p *PluginServiceGetPluginByKeyArgs) GetReq() (v *GetPluginByKeyReq) {
	if !p.IsSetReq() {
		return PluginServiceGetPluginByKeyArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceGetPluginByKeyArgs) SetReq(val *GetPluginByKeyReq) {
	p.Req = val
}

func (p *PluginServiceGetPluginByKeyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceGetPluginByKeyArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetPluginByKeyArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceGetPluginByKeyArgs = map[int16]string{
	1: "req",
}

type PluginServiceGetPluginByKeyResult struct {
	Success *Plugin `thrift:"success,0,optional" frugal:"0,optional,Plugin" json:"success,omitempty"`
}

func NewPluginServiceGetPluginByKeyResult() *PluginServiceGetPluginByKeyResult {
	return &PluginServiceGetPluginByKeyResult{}
}

func (p *PluginServiceGetPluginByKeyResult) InitDefault() {
}

var PluginServiceGetPluginByKeyResult_Success_DEFAULT *Plugin

func (p *PluginServiceGetPluginByKeyResult) GetSuccess() (v *Plugin) {
	if !p.IsSetSuccess() {
		return PluginServiceGetPluginByKeyResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceGetPluginByKeyResult) SetSuccess(x interface{}) {
	p.Success = x.(*Plugin)
}

func (p *PluginServiceGetPluginByKeyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceGetPluginByKeyResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetPluginByKeyResult(%+v)", *p)
}

var fieldIDToName_PluginServiceGetPluginByKeyResult = map[int16]string{
	0: "success",
}

type PluginServiceListPluginArgs struct {
	Req *ListPluginReq `thrift:"req,1" frugal:"1,default,ListPluginReq" json:"req"`
}

func NewPluginServiceListPluginArgs() *PluginServiceListPluginArgs {
	return &PluginServiceListPluginArgs{}
}

func (p *PluginServiceListPluginArgs) InitDefault() {
}

var PluginServiceListPluginArgs_Req_DEFAULT *ListPluginReq

func (p *PluginServiceListPluginArgs) GetReq() (v *ListPluginReq) {
	if !p.IsSetReq() {
		return PluginServiceListPluginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceListPluginArgs) SetReq(val *ListPluginReq) {
	p.Req = val
}

func (p *PluginServiceListPluginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceListPluginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceListPluginArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceListPluginArgs = map[int16]string{
	1: "req",
}

type PluginServiceListPluginResult struct {
	Success *ListPluginResp `thrift:"success,0,optional" frugal:"0,optional,ListPluginResp" json:"success,omitempty"`
}

func NewPluginServiceListPluginResult() *PluginServiceListPluginResult {
	return &PluginServiceListPluginResult{}
}

func (p *PluginServiceListPluginResult) InitDefault() {
}

var PluginServiceListPluginResult_Success_DEFAULT *ListPluginResp

func (p *PluginServiceListPluginResult) GetSuccess() (v *ListPluginResp) {
	if !p.IsSetSuccess() {
		return PluginServiceListPluginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceListPluginResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListPluginResp)
}

func (p *PluginServiceListPluginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceListPluginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceListPluginResult(%+v)", *p)
}

var fieldIDToName_PluginServiceListPluginResult = map[int16]string{
	0: "success",
}

type PluginServiceListPluginByToolsArgs struct {
	Req *ListPluginByToolsReq `thrift:"req,1" frugal:"1,default,ListPluginByToolsReq" json:"req"`
}

func NewPluginServiceListPluginByToolsArgs() *PluginServiceListPluginByToolsArgs {
	return &PluginServiceListPluginByToolsArgs{}
}

func (p *PluginServiceListPluginByToolsArgs) InitDefault() {
}

var PluginServiceListPluginByToolsArgs_Req_DEFAULT *ListPluginByToolsReq

func (p *PluginServiceListPluginByToolsArgs) GetReq() (v *ListPluginByToolsReq) {
	if !p.IsSetReq() {
		return PluginServiceListPluginByToolsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceListPluginByToolsArgs) SetReq(val *ListPluginByToolsReq) {
	p.Req = val
}

func (p *PluginServiceListPluginByToolsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceListPluginByToolsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceListPluginByToolsArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceListPluginByToolsArgs = map[int16]string{
	1: "req",
}

type PluginServiceListPluginByToolsResult struct {
	Success *ListPluginByToolsResp `thrift:"success,0,optional" frugal:"0,optional,ListPluginByToolsResp" json:"success,omitempty"`
}

func NewPluginServiceListPluginByToolsResult() *PluginServiceListPluginByToolsResult {
	return &PluginServiceListPluginByToolsResult{}
}

func (p *PluginServiceListPluginByToolsResult) InitDefault() {
}

var PluginServiceListPluginByToolsResult_Success_DEFAULT *ListPluginByToolsResp

func (p *PluginServiceListPluginByToolsResult) GetSuccess() (v *ListPluginByToolsResp) {
	if !p.IsSetSuccess() {
		return PluginServiceListPluginByToolsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceListPluginByToolsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListPluginByToolsResp)
}

func (p *PluginServiceListPluginByToolsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceListPluginByToolsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceListPluginByToolsResult(%+v)", *p)
}

var fieldIDToName_PluginServiceListPluginByToolsResult = map[int16]string{
	0: "success",
}

type PluginServiceGetPluginSecretsByToolsArgs struct {
	Req *base.IDsReq `thrift:"req,1" frugal:"1,default,base.IDsReq" json:"req"`
}

func NewPluginServiceGetPluginSecretsByToolsArgs() *PluginServiceGetPluginSecretsByToolsArgs {
	return &PluginServiceGetPluginSecretsByToolsArgs{}
}

func (p *PluginServiceGetPluginSecretsByToolsArgs) InitDefault() {
}

var PluginServiceGetPluginSecretsByToolsArgs_Req_DEFAULT *base.IDsReq

func (p *PluginServiceGetPluginSecretsByToolsArgs) GetReq() (v *base.IDsReq) {
	if !p.IsSetReq() {
		return PluginServiceGetPluginSecretsByToolsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceGetPluginSecretsByToolsArgs) SetReq(val *base.IDsReq) {
	p.Req = val
}

func (p *PluginServiceGetPluginSecretsByToolsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceGetPluginSecretsByToolsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetPluginSecretsByToolsArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceGetPluginSecretsByToolsArgs = map[int16]string{
	1: "req",
}

type PluginServiceGetPluginSecretsByToolsResult struct {
	Success []*PluginSecrets `thrift:"success,0,optional" frugal:"0,optional,list<PluginSecrets>" json:"success,omitempty"`
}

func NewPluginServiceGetPluginSecretsByToolsResult() *PluginServiceGetPluginSecretsByToolsResult {
	return &PluginServiceGetPluginSecretsByToolsResult{}
}

func (p *PluginServiceGetPluginSecretsByToolsResult) InitDefault() {
}

var PluginServiceGetPluginSecretsByToolsResult_Success_DEFAULT []*PluginSecrets

func (p *PluginServiceGetPluginSecretsByToolsResult) GetSuccess() (v []*PluginSecrets) {
	if !p.IsSetSuccess() {
		return PluginServiceGetPluginSecretsByToolsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceGetPluginSecretsByToolsResult) SetSuccess(x interface{}) {
	p.Success = x.([]*PluginSecrets)
}

func (p *PluginServiceGetPluginSecretsByToolsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceGetPluginSecretsByToolsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetPluginSecretsByToolsResult(%+v)", *p)
}

var fieldIDToName_PluginServiceGetPluginSecretsByToolsResult = map[int16]string{
	0: "success",
}

type PluginServicePublishPluginArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewPluginServicePublishPluginArgs() *PluginServicePublishPluginArgs {
	return &PluginServicePublishPluginArgs{}
}

func (p *PluginServicePublishPluginArgs) InitDefault() {
}

var PluginServicePublishPluginArgs_Req_DEFAULT *base.IDReq

func (p *PluginServicePublishPluginArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return PluginServicePublishPluginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServicePublishPluginArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *PluginServicePublishPluginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServicePublishPluginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServicePublishPluginArgs(%+v)", *p)
}

var fieldIDToName_PluginServicePublishPluginArgs = map[int16]string{
	1: "req",
}

type PluginServicePublishPluginResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewPluginServicePublishPluginResult() *PluginServicePublishPluginResult {
	return &PluginServicePublishPluginResult{}
}

func (p *PluginServicePublishPluginResult) InitDefault() {
}

var PluginServicePublishPluginResult_Success_DEFAULT *base.Empty

func (p *PluginServicePublishPluginResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return PluginServicePublishPluginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServicePublishPluginResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *PluginServicePublishPluginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServicePublishPluginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServicePublishPluginResult(%+v)", *p)
}

var fieldIDToName_PluginServicePublishPluginResult = map[int16]string{
	0: "success",
}

type PluginServiceCreateToolArgs struct {
	Req *CreatePluginToolReq `thrift:"req,1" frugal:"1,default,CreatePluginToolReq" json:"req"`
}

func NewPluginServiceCreateToolArgs() *PluginServiceCreateToolArgs {
	return &PluginServiceCreateToolArgs{}
}

func (p *PluginServiceCreateToolArgs) InitDefault() {
}

var PluginServiceCreateToolArgs_Req_DEFAULT *CreatePluginToolReq

func (p *PluginServiceCreateToolArgs) GetReq() (v *CreatePluginToolReq) {
	if !p.IsSetReq() {
		return PluginServiceCreateToolArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceCreateToolArgs) SetReq(val *CreatePluginToolReq) {
	p.Req = val
}

func (p *PluginServiceCreateToolArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceCreateToolArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceCreateToolArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceCreateToolArgs = map[int16]string{
	1: "req",
}

type PluginServiceCreateToolResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewPluginServiceCreateToolResult() *PluginServiceCreateToolResult {
	return &PluginServiceCreateToolResult{}
}

func (p *PluginServiceCreateToolResult) InitDefault() {
}

var PluginServiceCreateToolResult_Success_DEFAULT *base.Empty

func (p *PluginServiceCreateToolResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return PluginServiceCreateToolResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceCreateToolResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *PluginServiceCreateToolResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceCreateToolResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceCreateToolResult(%+v)", *p)
}

var fieldIDToName_PluginServiceCreateToolResult = map[int16]string{
	0: "success",
}

type PluginServiceUpdateToolArgs struct {
	Req *UpdatePluginToolReq `thrift:"req,1" frugal:"1,default,UpdatePluginToolReq" json:"req"`
}

func NewPluginServiceUpdateToolArgs() *PluginServiceUpdateToolArgs {
	return &PluginServiceUpdateToolArgs{}
}

func (p *PluginServiceUpdateToolArgs) InitDefault() {
}

var PluginServiceUpdateToolArgs_Req_DEFAULT *UpdatePluginToolReq

func (p *PluginServiceUpdateToolArgs) GetReq() (v *UpdatePluginToolReq) {
	if !p.IsSetReq() {
		return PluginServiceUpdateToolArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceUpdateToolArgs) SetReq(val *UpdatePluginToolReq) {
	p.Req = val
}

func (p *PluginServiceUpdateToolArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceUpdateToolArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceUpdateToolArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceUpdateToolArgs = map[int16]string{
	1: "req",
}

type PluginServiceUpdateToolResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewPluginServiceUpdateToolResult() *PluginServiceUpdateToolResult {
	return &PluginServiceUpdateToolResult{}
}

func (p *PluginServiceUpdateToolResult) InitDefault() {
}

var PluginServiceUpdateToolResult_Success_DEFAULT *base.Empty

func (p *PluginServiceUpdateToolResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return PluginServiceUpdateToolResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceUpdateToolResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *PluginServiceUpdateToolResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceUpdateToolResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceUpdateToolResult(%+v)", *p)
}

var fieldIDToName_PluginServiceUpdateToolResult = map[int16]string{
	0: "success",
}

type PluginServiceDeleteToolArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewPluginServiceDeleteToolArgs() *PluginServiceDeleteToolArgs {
	return &PluginServiceDeleteToolArgs{}
}

func (p *PluginServiceDeleteToolArgs) InitDefault() {
}

var PluginServiceDeleteToolArgs_Req_DEFAULT *base.IDReq

func (p *PluginServiceDeleteToolArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return PluginServiceDeleteToolArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceDeleteToolArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *PluginServiceDeleteToolArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceDeleteToolArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceDeleteToolArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceDeleteToolArgs = map[int16]string{
	1: "req",
}

type PluginServiceDeleteToolResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewPluginServiceDeleteToolResult() *PluginServiceDeleteToolResult {
	return &PluginServiceDeleteToolResult{}
}

func (p *PluginServiceDeleteToolResult) InitDefault() {
}

var PluginServiceDeleteToolResult_Success_DEFAULT *base.Empty

func (p *PluginServiceDeleteToolResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return PluginServiceDeleteToolResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceDeleteToolResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *PluginServiceDeleteToolResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceDeleteToolResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceDeleteToolResult(%+v)", *p)
}

var fieldIDToName_PluginServiceDeleteToolResult = map[int16]string{
	0: "success",
}

type PluginServiceGetToolByIDArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewPluginServiceGetToolByIDArgs() *PluginServiceGetToolByIDArgs {
	return &PluginServiceGetToolByIDArgs{}
}

func (p *PluginServiceGetToolByIDArgs) InitDefault() {
}

var PluginServiceGetToolByIDArgs_Req_DEFAULT *base.IDReq

func (p *PluginServiceGetToolByIDArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return PluginServiceGetToolByIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceGetToolByIDArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *PluginServiceGetToolByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceGetToolByIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetToolByIDArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceGetToolByIDArgs = map[int16]string{
	1: "req",
}

type PluginServiceGetToolByIDResult struct {
	Success *PluginTool `thrift:"success,0,optional" frugal:"0,optional,PluginTool" json:"success,omitempty"`
}

func NewPluginServiceGetToolByIDResult() *PluginServiceGetToolByIDResult {
	return &PluginServiceGetToolByIDResult{}
}

func (p *PluginServiceGetToolByIDResult) InitDefault() {
}

var PluginServiceGetToolByIDResult_Success_DEFAULT *PluginTool

func (p *PluginServiceGetToolByIDResult) GetSuccess() (v *PluginTool) {
	if !p.IsSetSuccess() {
		return PluginServiceGetToolByIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceGetToolByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*PluginTool)
}

func (p *PluginServiceGetToolByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceGetToolByIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceGetToolByIDResult(%+v)", *p)
}

var fieldIDToName_PluginServiceGetToolByIDResult = map[int16]string{
	0: "success",
}

type PluginServiceListPluginToolArgs struct {
	Req *ListPluginToolReq `thrift:"req,1" frugal:"1,default,ListPluginToolReq" json:"req"`
}

func NewPluginServiceListPluginToolArgs() *PluginServiceListPluginToolArgs {
	return &PluginServiceListPluginToolArgs{}
}

func (p *PluginServiceListPluginToolArgs) InitDefault() {
}

var PluginServiceListPluginToolArgs_Req_DEFAULT *ListPluginToolReq

func (p *PluginServiceListPluginToolArgs) GetReq() (v *ListPluginToolReq) {
	if !p.IsSetReq() {
		return PluginServiceListPluginToolArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceListPluginToolArgs) SetReq(val *ListPluginToolReq) {
	p.Req = val
}

func (p *PluginServiceListPluginToolArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceListPluginToolArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceListPluginToolArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceListPluginToolArgs = map[int16]string{
	1: "req",
}

type PluginServiceListPluginToolResult struct {
	Success *ListPluginToolResp `thrift:"success,0,optional" frugal:"0,optional,ListPluginToolResp" json:"success,omitempty"`
}

func NewPluginServiceListPluginToolResult() *PluginServiceListPluginToolResult {
	return &PluginServiceListPluginToolResult{}
}

func (p *PluginServiceListPluginToolResult) InitDefault() {
}

var PluginServiceListPluginToolResult_Success_DEFAULT *ListPluginToolResp

func (p *PluginServiceListPluginToolResult) GetSuccess() (v *ListPluginToolResp) {
	if !p.IsSetSuccess() {
		return PluginServiceListPluginToolResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceListPluginToolResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListPluginToolResp)
}

func (p *PluginServiceListPluginToolResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceListPluginToolResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceListPluginToolResult(%+v)", *p)
}

var fieldIDToName_PluginServiceListPluginToolResult = map[int16]string{
	0: "success",
}

type PluginServiceAllPluginToolArgs struct {
	Req *AllPluginToolReq `thrift:"req,1" frugal:"1,default,AllPluginToolReq" json:"req"`
}

func NewPluginServiceAllPluginToolArgs() *PluginServiceAllPluginToolArgs {
	return &PluginServiceAllPluginToolArgs{}
}

func (p *PluginServiceAllPluginToolArgs) InitDefault() {
}

var PluginServiceAllPluginToolArgs_Req_DEFAULT *AllPluginToolReq

func (p *PluginServiceAllPluginToolArgs) GetReq() (v *AllPluginToolReq) {
	if !p.IsSetReq() {
		return PluginServiceAllPluginToolArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceAllPluginToolArgs) SetReq(val *AllPluginToolReq) {
	p.Req = val
}

func (p *PluginServiceAllPluginToolArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceAllPluginToolArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceAllPluginToolArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceAllPluginToolArgs = map[int16]string{
	1: "req",
}

type PluginServiceAllPluginToolResult struct {
	Success []*PluginTool `thrift:"success,0,optional" frugal:"0,optional,list<PluginTool>" json:"success,omitempty"`
}

func NewPluginServiceAllPluginToolResult() *PluginServiceAllPluginToolResult {
	return &PluginServiceAllPluginToolResult{}
}

func (p *PluginServiceAllPluginToolResult) InitDefault() {
}

var PluginServiceAllPluginToolResult_Success_DEFAULT []*PluginTool

func (p *PluginServiceAllPluginToolResult) GetSuccess() (v []*PluginTool) {
	if !p.IsSetSuccess() {
		return PluginServiceAllPluginToolResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceAllPluginToolResult) SetSuccess(x interface{}) {
	p.Success = x.([]*PluginTool)
}

func (p *PluginServiceAllPluginToolResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceAllPluginToolResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceAllPluginToolResult(%+v)", *p)
}

var fieldIDToName_PluginServiceAllPluginToolResult = map[int16]string{
	0: "success",
}

type PluginServiceListPluginLabelArgs struct {
	Req *ListPluginLabelReq `thrift:"req,1" frugal:"1,default,ListPluginLabelReq" json:"req"`
}

func NewPluginServiceListPluginLabelArgs() *PluginServiceListPluginLabelArgs {
	return &PluginServiceListPluginLabelArgs{}
}

func (p *PluginServiceListPluginLabelArgs) InitDefault() {
}

var PluginServiceListPluginLabelArgs_Req_DEFAULT *ListPluginLabelReq

func (p *PluginServiceListPluginLabelArgs) GetReq() (v *ListPluginLabelReq) {
	if !p.IsSetReq() {
		return PluginServiceListPluginLabelArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceListPluginLabelArgs) SetReq(val *ListPluginLabelReq) {
	p.Req = val
}

func (p *PluginServiceListPluginLabelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceListPluginLabelArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceListPluginLabelArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceListPluginLabelArgs = map[int16]string{
	1: "req",
}

type PluginServiceListPluginLabelResult struct {
	Success *ListPluginLabelResp `thrift:"success,0,optional" frugal:"0,optional,ListPluginLabelResp" json:"success,omitempty"`
}

func NewPluginServiceListPluginLabelResult() *PluginServiceListPluginLabelResult {
	return &PluginServiceListPluginLabelResult{}
}

func (p *PluginServiceListPluginLabelResult) InitDefault() {
}

var PluginServiceListPluginLabelResult_Success_DEFAULT *ListPluginLabelResp

func (p *PluginServiceListPluginLabelResult) GetSuccess() (v *ListPluginLabelResp) {
	if !p.IsSetSuccess() {
		return PluginServiceListPluginLabelResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceListPluginLabelResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListPluginLabelResp)
}

func (p *PluginServiceListPluginLabelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceListPluginLabelResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceListPluginLabelResult(%+v)", *p)
}

var fieldIDToName_PluginServiceListPluginLabelResult = map[int16]string{
	0: "success",
}

type PluginServiceCallPluginToolArgs struct {
	Req *CallPluginToolReq `thrift:"req,1" frugal:"1,default,CallPluginToolReq" json:"req"`
}

func NewPluginServiceCallPluginToolArgs() *PluginServiceCallPluginToolArgs {
	return &PluginServiceCallPluginToolArgs{}
}

func (p *PluginServiceCallPluginToolArgs) InitDefault() {
}

var PluginServiceCallPluginToolArgs_Req_DEFAULT *CallPluginToolReq

func (p *PluginServiceCallPluginToolArgs) GetReq() (v *CallPluginToolReq) {
	if !p.IsSetReq() {
		return PluginServiceCallPluginToolArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceCallPluginToolArgs) SetReq(val *CallPluginToolReq) {
	p.Req = val
}

func (p *PluginServiceCallPluginToolArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceCallPluginToolArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceCallPluginToolArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceCallPluginToolArgs = map[int16]string{
	1: "req",
}

type PluginServiceCallPluginToolResult struct {
	Success *CallPluginToolResp `thrift:"success,0,optional" frugal:"0,optional,CallPluginToolResp" json:"success,omitempty"`
}

func NewPluginServiceCallPluginToolResult() *PluginServiceCallPluginToolResult {
	return &PluginServiceCallPluginToolResult{}
}

func (p *PluginServiceCallPluginToolResult) InitDefault() {
}

var PluginServiceCallPluginToolResult_Success_DEFAULT *CallPluginToolResp

func (p *PluginServiceCallPluginToolResult) GetSuccess() (v *CallPluginToolResp) {
	if !p.IsSetSuccess() {
		return PluginServiceCallPluginToolResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceCallPluginToolResult) SetSuccess(x interface{}) {
	p.Success = x.(*CallPluginToolResp)
}

func (p *PluginServiceCallPluginToolResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceCallPluginToolResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceCallPluginToolResult(%+v)", *p)
}

var fieldIDToName_PluginServiceCallPluginToolResult = map[int16]string{
	0: "success",
}

type PluginServiceTestPluginToolArgs struct {
	Req *CallPluginToolReq `thrift:"req,1" frugal:"1,default,CallPluginToolReq" json:"req"`
}

func NewPluginServiceTestPluginToolArgs() *PluginServiceTestPluginToolArgs {
	return &PluginServiceTestPluginToolArgs{}
}

func (p *PluginServiceTestPluginToolArgs) InitDefault() {
}

var PluginServiceTestPluginToolArgs_Req_DEFAULT *CallPluginToolReq

func (p *PluginServiceTestPluginToolArgs) GetReq() (v *CallPluginToolReq) {
	if !p.IsSetReq() {
		return PluginServiceTestPluginToolArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PluginServiceTestPluginToolArgs) SetReq(val *CallPluginToolReq) {
	p.Req = val
}

func (p *PluginServiceTestPluginToolArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PluginServiceTestPluginToolArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceTestPluginToolArgs(%+v)", *p)
}

var fieldIDToName_PluginServiceTestPluginToolArgs = map[int16]string{
	1: "req",
}

type PluginServiceTestPluginToolResult struct {
	Success *TestPluginToolResp `thrift:"success,0,optional" frugal:"0,optional,TestPluginToolResp" json:"success,omitempty"`
}

func NewPluginServiceTestPluginToolResult() *PluginServiceTestPluginToolResult {
	return &PluginServiceTestPluginToolResult{}
}

func (p *PluginServiceTestPluginToolResult) InitDefault() {
}

var PluginServiceTestPluginToolResult_Success_DEFAULT *TestPluginToolResp

func (p *PluginServiceTestPluginToolResult) GetSuccess() (v *TestPluginToolResp) {
	if !p.IsSetSuccess() {
		return PluginServiceTestPluginToolResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PluginServiceTestPluginToolResult) SetSuccess(x interface{}) {
	p.Success = x.(*TestPluginToolResp)
}

func (p *PluginServiceTestPluginToolResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PluginServiceTestPluginToolResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PluginServiceTestPluginToolResult(%+v)", *p)
}

var fieldIDToName_PluginServiceTestPluginToolResult = map[int16]string{
	0: "success",
}
