// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package chatsvc

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/aiagt/aiagt/kitex_gen/base"
	"github.com/cloudwego/kitex/pkg/streaming"
)

type MessageType int64

const (
	MessageType_TEXT          MessageType = 0
	MessageType_IMAGE         MessageType = 1
	MessageType_FILE          MessageType = 2
	MessageType_FUNCTION      MessageType = 3
	MessageType_FUNCTION_CALL MessageType = 4
	MessageType_TOOL          MessageType = 5
	MessageType_TOOL_CALL     MessageType = 6
)

func (p MessageType) String() string {
	switch p {
	case MessageType_TEXT:
		return "TEXT"
	case MessageType_IMAGE:
		return "IMAGE"
	case MessageType_FILE:
		return "FILE"
	case MessageType_FUNCTION:
		return "FUNCTION"
	case MessageType_FUNCTION_CALL:
		return "FUNCTION_CALL"
	case MessageType_TOOL:
		return "TOOL"
	case MessageType_TOOL_CALL:
		return "TOOL_CALL"
	}
	return "<UNSET>"
}

func MessageTypeFromString(s string) (MessageType, error) {
	switch s {
	case "TEXT":
		return MessageType_TEXT, nil
	case "IMAGE":
		return MessageType_IMAGE, nil
	case "FILE":
		return MessageType_FILE, nil
	case "FUNCTION":
		return MessageType_FUNCTION, nil
	case "FUNCTION_CALL":
		return MessageType_FUNCTION_CALL, nil
	case "TOOL":
		return MessageType_TOOL, nil
	case "TOOL_CALL":
		return MessageType_TOOL_CALL, nil
	}
	return MessageType(0), fmt.Errorf("not a valid MessageType string")
}

func MessageTypePtr(v MessageType) *MessageType { return &v }
func (p *MessageType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = MessageType(result.Int64)
	return
}

func (p *MessageType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type MessageRole int64

const (
	MessageRole_USER      MessageRole = 0
	MessageRole_ASSISTANT MessageRole = 1
	MessageRole_SYSTEM    MessageRole = 2
	MessageRole_FUNCTION  MessageRole = 3
	MessageRole_TOOL      MessageRole = 4
)

func (p MessageRole) String() string {
	switch p {
	case MessageRole_USER:
		return "USER"
	case MessageRole_ASSISTANT:
		return "ASSISTANT"
	case MessageRole_SYSTEM:
		return "SYSTEM"
	case MessageRole_FUNCTION:
		return "FUNCTION"
	case MessageRole_TOOL:
		return "TOOL"
	}
	return "<UNSET>"
}

func MessageRoleFromString(s string) (MessageRole, error) {
	switch s {
	case "USER":
		return MessageRole_USER, nil
	case "ASSISTANT":
		return MessageRole_ASSISTANT, nil
	case "SYSTEM":
		return MessageRole_SYSTEM, nil
	case "FUNCTION":
		return MessageRole_FUNCTION, nil
	case "TOOL":
		return MessageRole_TOOL, nil
	}
	return MessageRole(0), fmt.Errorf("not a valid MessageRole string")
}

func MessageRolePtr(v MessageRole) *MessageRole { return &v }
func (p *MessageRole) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = MessageRole(result.Int64)
	return
}

func (p *MessageRole) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type MessageContentValueText struct {
	Text string `thrift:"text,1,required" frugal:"1,required,string" json:"text"`
}

func NewMessageContentValueText() *MessageContentValueText {
	return &MessageContentValueText{}
}

func (p *MessageContentValueText) InitDefault() {
}

func (p *MessageContentValueText) GetText() (v string) {
	return p.Text
}
func (p *MessageContentValueText) SetText(val string) {
	p.Text = val
}

func (p *MessageContentValueText) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContentValueText(%+v)", *p)
}

var fieldIDToName_MessageContentValueText = map[int16]string{
	1: "text",
}

type MessageContentValueImage struct {
	Url string `thrift:"url,1,required" frugal:"1,required,string" json:"url"`
}

func NewMessageContentValueImage() *MessageContentValueImage {
	return &MessageContentValueImage{}
}

func (p *MessageContentValueImage) InitDefault() {
}

func (p *MessageContentValueImage) GetUrl() (v string) {
	return p.Url
}
func (p *MessageContentValueImage) SetUrl(val string) {
	p.Url = val
}

func (p *MessageContentValueImage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContentValueImage(%+v)", *p)
}

var fieldIDToName_MessageContentValueImage = map[int16]string{
	1: "url",
}

type MessageContentValueFile struct {
	Url  string `thrift:"url,1,required" frugal:"1,required,string" json:"url"`
	Type string `thrift:"type,2,required" frugal:"2,required,string" json:"type"`
}

func NewMessageContentValueFile() *MessageContentValueFile {
	return &MessageContentValueFile{}
}

func (p *MessageContentValueFile) InitDefault() {
}

func (p *MessageContentValueFile) GetUrl() (v string) {
	return p.Url
}

func (p *MessageContentValueFile) GetType() (v string) {
	return p.Type
}
func (p *MessageContentValueFile) SetUrl(val string) {
	p.Url = val
}
func (p *MessageContentValueFile) SetType(val string) {
	p.Type = val
}

func (p *MessageContentValueFile) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContentValueFile(%+v)", *p)
}

var fieldIDToName_MessageContentValueFile = map[int16]string{
	1: "url",
	2: "type",
}

type MessageContentValueFunc struct {
	Name    string `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Content string `thrift:"content,2,required" frugal:"2,required,string" json:"content"`
}

func NewMessageContentValueFunc() *MessageContentValueFunc {
	return &MessageContentValueFunc{}
}

func (p *MessageContentValueFunc) InitDefault() {
}

func (p *MessageContentValueFunc) GetName() (v string) {
	return p.Name
}

func (p *MessageContentValueFunc) GetContent() (v string) {
	return p.Content
}
func (p *MessageContentValueFunc) SetName(val string) {
	p.Name = val
}
func (p *MessageContentValueFunc) SetContent(val string) {
	p.Content = val
}

func (p *MessageContentValueFunc) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContentValueFunc(%+v)", *p)
}

var fieldIDToName_MessageContentValueFunc = map[int16]string{
	1: "name",
	2: "content",
}

type MessageContentValueFuncCall struct {
	Name      string `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Arguments string `thrift:"arguments,2,required" frugal:"2,required,string" json:"arguments"`
}

func NewMessageContentValueFuncCall() *MessageContentValueFuncCall {
	return &MessageContentValueFuncCall{}
}

func (p *MessageContentValueFuncCall) InitDefault() {
}

func (p *MessageContentValueFuncCall) GetName() (v string) {
	return p.Name
}

func (p *MessageContentValueFuncCall) GetArguments() (v string) {
	return p.Arguments
}
func (p *MessageContentValueFuncCall) SetName(val string) {
	p.Name = val
}
func (p *MessageContentValueFuncCall) SetArguments(val string) {
	p.Arguments = val
}

func (p *MessageContentValueFuncCall) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContentValueFuncCall(%+v)", *p)
}

var fieldIDToName_MessageContentValueFuncCall = map[int16]string{
	1: "name",
	2: "arguments",
}

type MessageContentValueTool struct {
	Id      string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	Name    string `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Content string `thrift:"content,3,required" frugal:"3,required,string" json:"content"`
}

func NewMessageContentValueTool() *MessageContentValueTool {
	return &MessageContentValueTool{}
}

func (p *MessageContentValueTool) InitDefault() {
}

func (p *MessageContentValueTool) GetId() (v string) {
	return p.Id
}

func (p *MessageContentValueTool) GetName() (v string) {
	return p.Name
}

func (p *MessageContentValueTool) GetContent() (v string) {
	return p.Content
}
func (p *MessageContentValueTool) SetId(val string) {
	p.Id = val
}
func (p *MessageContentValueTool) SetName(val string) {
	p.Name = val
}
func (p *MessageContentValueTool) SetContent(val string) {
	p.Content = val
}

func (p *MessageContentValueTool) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContentValueTool(%+v)", *p)
}

var fieldIDToName_MessageContentValueTool = map[int16]string{
	1: "id",
	2: "name",
	3: "content",
}

type MessageContentValueToolCall struct {
	Id        string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	Name      string `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Arguments string `thrift:"arguments,3,required" frugal:"3,required,string" json:"arguments"`
}

func NewMessageContentValueToolCall() *MessageContentValueToolCall {
	return &MessageContentValueToolCall{}
}

func (p *MessageContentValueToolCall) InitDefault() {
}

func (p *MessageContentValueToolCall) GetId() (v string) {
	return p.Id
}

func (p *MessageContentValueToolCall) GetName() (v string) {
	return p.Name
}

func (p *MessageContentValueToolCall) GetArguments() (v string) {
	return p.Arguments
}
func (p *MessageContentValueToolCall) SetId(val string) {
	p.Id = val
}
func (p *MessageContentValueToolCall) SetName(val string) {
	p.Name = val
}
func (p *MessageContentValueToolCall) SetArguments(val string) {
	p.Arguments = val
}

func (p *MessageContentValueToolCall) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContentValueToolCall(%+v)", *p)
}

var fieldIDToName_MessageContentValueToolCall = map[int16]string{
	1: "id",
	2: "name",
	3: "arguments",
}

type MessageContent struct {
	Type    MessageType          `thrift:"type,1,required" frugal:"1,required,MessageType" json:"type"`
	Content *MessageContentValue `thrift:"content,2,required" frugal:"2,required,MessageContentValue" json:"content"`
}

func NewMessageContent() *MessageContent {
	return &MessageContent{}
}

func (p *MessageContent) InitDefault() {
}

func (p *MessageContent) GetType() (v MessageType) {
	return p.Type
}

var MessageContent_Content_DEFAULT *MessageContentValue

func (p *MessageContent) GetContent() (v *MessageContentValue) {
	if !p.IsSetContent() {
		return MessageContent_Content_DEFAULT
	}
	return p.Content
}
func (p *MessageContent) SetType(val MessageType) {
	p.Type = val
}
func (p *MessageContent) SetContent(val *MessageContentValue) {
	p.Content = val
}

func (p *MessageContent) IsSetContent() bool {
	return p.Content != nil
}

func (p *MessageContent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContent(%+v)", *p)
}

var fieldIDToName_MessageContent = map[int16]string{
	1: "type",
	2: "content",
}

type ChatReq struct {
	ConversationId *int64            `thrift:"conversation_id,1,optional" frugal:"1,optional,i64" json:"conversation_id,omitempty"`
	AppId          int64             `thrift:"app_id,2,required" frugal:"2,required,i64" json:"app_id"`
	Messages       []*MessageContent `thrift:"messages,3,required" frugal:"3,required,list<MessageContent>" json:"messages"`
}

func NewChatReq() *ChatReq {
	return &ChatReq{}
}

func (p *ChatReq) InitDefault() {
}

var ChatReq_ConversationId_DEFAULT int64

func (p *ChatReq) GetConversationId() (v int64) {
	if !p.IsSetConversationId() {
		return ChatReq_ConversationId_DEFAULT
	}
	return *p.ConversationId
}

func (p *ChatReq) GetAppId() (v int64) {
	return p.AppId
}

func (p *ChatReq) GetMessages() (v []*MessageContent) {
	return p.Messages
}
func (p *ChatReq) SetConversationId(val *int64) {
	p.ConversationId = val
}
func (p *ChatReq) SetAppId(val int64) {
	p.AppId = val
}
func (p *ChatReq) SetMessages(val []*MessageContent) {
	p.Messages = val
}

func (p *ChatReq) IsSetConversationId() bool {
	return p.ConversationId != nil
}

func (p *ChatReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatReq(%+v)", *p)
}

var fieldIDToName_ChatReq = map[int16]string{
	1: "conversation_id",
	2: "app_id",
	3: "messages",
}

type ChatResp struct {
	Messages          []*Message `thrift:"messages,1,required" frugal:"1,required,list<Message>" json:"messages"`
	ConversationId    int64      `thrift:"conversation_id,2,required" frugal:"2,required,i64" json:"conversation_id"`
	ConversationTitle *string    `thrift:"conversation_title,3,optional" frugal:"3,optional,string" json:"conversation_title,omitempty"`
}

func NewChatResp() *ChatResp {
	return &ChatResp{}
}

func (p *ChatResp) InitDefault() {
}

func (p *ChatResp) GetMessages() (v []*Message) {
	return p.Messages
}

func (p *ChatResp) GetConversationId() (v int64) {
	return p.ConversationId
}

var ChatResp_ConversationTitle_DEFAULT string

func (p *ChatResp) GetConversationTitle() (v string) {
	if !p.IsSetConversationTitle() {
		return ChatResp_ConversationTitle_DEFAULT
	}
	return *p.ConversationTitle
}
func (p *ChatResp) SetMessages(val []*Message) {
	p.Messages = val
}
func (p *ChatResp) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *ChatResp) SetConversationTitle(val *string) {
	p.ConversationTitle = val
}

func (p *ChatResp) IsSetConversationTitle() bool {
	return p.ConversationTitle != nil
}

func (p *ChatResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatResp(%+v)", *p)
}

var fieldIDToName_ChatResp = map[int16]string{
	1: "messages",
	2: "conversation_id",
	3: "conversation_title",
}

type ChatRespMessage struct {
	Role    MessageRole     `thrift:"role,1,required" frugal:"1,required,MessageRole" json:"role"`
	Content *MessageContent `thrift:"content,2,required" frugal:"2,required,MessageContent" json:"content"`
}

func NewChatRespMessage() *ChatRespMessage {
	return &ChatRespMessage{}
}

func (p *ChatRespMessage) InitDefault() {
}

func (p *ChatRespMessage) GetRole() (v MessageRole) {
	return p.Role
}

var ChatRespMessage_Content_DEFAULT *MessageContent

func (p *ChatRespMessage) GetContent() (v *MessageContent) {
	if !p.IsSetContent() {
		return ChatRespMessage_Content_DEFAULT
	}
	return p.Content
}
func (p *ChatRespMessage) SetRole(val MessageRole) {
	p.Role = val
}
func (p *ChatRespMessage) SetContent(val *MessageContent) {
	p.Content = val
}

func (p *ChatRespMessage) IsSetContent() bool {
	return p.Content != nil
}

func (p *ChatRespMessage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatRespMessage(%+v)", *p)
}

var fieldIDToName_ChatRespMessage = map[int16]string{
	1: "role",
	2: "content",
}

type Conversation struct {
	Id        int64      `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	UserId    int64      `thrift:"user_id,2,required" frugal:"2,required,i64" json:"user_id"`
	AppId     int64      `thrift:"app_id,3,required" frugal:"3,required,i64" json:"app_id"`
	Title     string     `thrift:"title,4,required" frugal:"4,required,string" json:"title"`
	CreatedAt *base.Time `thrift:"created_at,5,required" frugal:"5,required,base.Time" json:"created_at"`
	UpdatedAt *base.Time `thrift:"updated_at,6,required" frugal:"6,required,base.Time" json:"updated_at"`
}

func NewConversation() *Conversation {
	return &Conversation{}
}

func (p *Conversation) InitDefault() {
}

func (p *Conversation) GetId() (v int64) {
	return p.Id
}

func (p *Conversation) GetUserId() (v int64) {
	return p.UserId
}

func (p *Conversation) GetAppId() (v int64) {
	return p.AppId
}

func (p *Conversation) GetTitle() (v string) {
	return p.Title
}

var Conversation_CreatedAt_DEFAULT *base.Time

func (p *Conversation) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return Conversation_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}

var Conversation_UpdatedAt_DEFAULT *base.Time

func (p *Conversation) GetUpdatedAt() (v *base.Time) {
	if !p.IsSetUpdatedAt() {
		return Conversation_UpdatedAt_DEFAULT
	}
	return p.UpdatedAt
}
func (p *Conversation) SetId(val int64) {
	p.Id = val
}
func (p *Conversation) SetUserId(val int64) {
	p.UserId = val
}
func (p *Conversation) SetAppId(val int64) {
	p.AppId = val
}
func (p *Conversation) SetTitle(val string) {
	p.Title = val
}
func (p *Conversation) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}
func (p *Conversation) SetUpdatedAt(val *base.Time) {
	p.UpdatedAt = val
}

func (p *Conversation) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *Conversation) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *Conversation) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Conversation(%+v)", *p)
}

var fieldIDToName_Conversation = map[int16]string{
	1: "id",
	2: "user_id",
	3: "app_id",
	4: "title",
	5: "created_at",
	6: "updated_at",
}

type Message struct {
	Id             int64           `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	ConversationId int64           `thrift:"conversation_id,2,required" frugal:"2,required,i64" json:"conversation_id"`
	Role           MessageRole     `thrift:"role,3,required" frugal:"3,required,MessageRole" json:"role"`
	Content        *MessageContent `thrift:"content,4,required" frugal:"4,required,MessageContent" json:"content"`
	CreatedAt      *base.Time      `thrift:"created_at,5,required" frugal:"5,required,base.Time" json:"created_at"`
	UpdatedAt      *base.Time      `thrift:"updated_at,6,required" frugal:"6,required,base.Time" json:"updated_at"`
}

func NewMessage() *Message {
	return &Message{}
}

func (p *Message) InitDefault() {
}

func (p *Message) GetId() (v int64) {
	return p.Id
}

func (p *Message) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *Message) GetRole() (v MessageRole) {
	return p.Role
}

var Message_Content_DEFAULT *MessageContent

func (p *Message) GetContent() (v *MessageContent) {
	if !p.IsSetContent() {
		return Message_Content_DEFAULT
	}
	return p.Content
}

var Message_CreatedAt_DEFAULT *base.Time

func (p *Message) GetCreatedAt() (v *base.Time) {
	if !p.IsSetCreatedAt() {
		return Message_CreatedAt_DEFAULT
	}
	return p.CreatedAt
}

var Message_UpdatedAt_DEFAULT *base.Time

func (p *Message) GetUpdatedAt() (v *base.Time) {
	if !p.IsSetUpdatedAt() {
		return Message_UpdatedAt_DEFAULT
	}
	return p.UpdatedAt
}
func (p *Message) SetId(val int64) {
	p.Id = val
}
func (p *Message) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *Message) SetRole(val MessageRole) {
	p.Role = val
}
func (p *Message) SetContent(val *MessageContent) {
	p.Content = val
}
func (p *Message) SetCreatedAt(val *base.Time) {
	p.CreatedAt = val
}
func (p *Message) SetUpdatedAt(val *base.Time) {
	p.UpdatedAt = val
}

func (p *Message) IsSetContent() bool {
	return p.Content != nil
}

func (p *Message) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *Message) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *Message) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Message(%+v)", *p)
}

var fieldIDToName_Message = map[int16]string{
	1: "id",
	2: "conversation_id",
	3: "role",
	4: "content",
	5: "created_at",
	6: "updated_at",
}

type UpdateMessageReq struct {
	Id      int64           `thrift:"id,1,required" frugal:"1,required,i64" path:"id"`
	Message *MessageContent `thrift:"message,2,required" frugal:"2,required,MessageContent" json:"message"`
}

func NewUpdateMessageReq() *UpdateMessageReq {
	return &UpdateMessageReq{}
}

func (p *UpdateMessageReq) InitDefault() {
}

func (p *UpdateMessageReq) GetId() (v int64) {
	return p.Id
}

var UpdateMessageReq_Message_DEFAULT *MessageContent

func (p *UpdateMessageReq) GetMessage() (v *MessageContent) {
	if !p.IsSetMessage() {
		return UpdateMessageReq_Message_DEFAULT
	}
	return p.Message
}
func (p *UpdateMessageReq) SetId(val int64) {
	p.Id = val
}
func (p *UpdateMessageReq) SetMessage(val *MessageContent) {
	p.Message = val
}

func (p *UpdateMessageReq) IsSetMessage() bool {
	return p.Message != nil
}

func (p *UpdateMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateMessageReq(%+v)", *p)
}

var fieldIDToName_UpdateMessageReq = map[int16]string{
	1: "id",
	2: "message",
}

type DeleteMessageReq struct {
	Id   int64 `thrift:"id,1,required" frugal:"1,required,i64" path:"id"`
	More *int8 `thrift:"more,2,optional" frugal:"2,optional,i8" query:"more"`
}

func NewDeleteMessageReq() *DeleteMessageReq {
	return &DeleteMessageReq{}
}

func (p *DeleteMessageReq) InitDefault() {
}

func (p *DeleteMessageReq) GetId() (v int64) {
	return p.Id
}

var DeleteMessageReq_More_DEFAULT int8

func (p *DeleteMessageReq) GetMore() (v int8) {
	if !p.IsSetMore() {
		return DeleteMessageReq_More_DEFAULT
	}
	return *p.More
}
func (p *DeleteMessageReq) SetId(val int64) {
	p.Id = val
}
func (p *DeleteMessageReq) SetMore(val *int8) {
	p.More = val
}

func (p *DeleteMessageReq) IsSetMore() bool {
	return p.More != nil
}

func (p *DeleteMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteMessageReq(%+v)", *p)
}

var fieldIDToName_DeleteMessageReq = map[int16]string{
	1: "id",
	2: "more",
}

type ListMessageReq struct {
	Pagination     *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	ConversationId int64               `thrift:"conversation_id,2,required" frugal:"2,required,i64" query:"conversation_id"`
}

func NewListMessageReq() *ListMessageReq {
	return &ListMessageReq{}
}

func (p *ListMessageReq) InitDefault() {
}

var ListMessageReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListMessageReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListMessageReq_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListMessageReq) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *ListMessageReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListMessageReq) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *ListMessageReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListMessageReq(%+v)", *p)
}

var fieldIDToName_ListMessageReq = map[int16]string{
	1: "pagination",
	2: "conversation_id",
}

type ListMessageResp struct {
	Pagination *base.PaginationResp `thrift:"pagination,1,required" frugal:"1,required,base.PaginationResp" json:"pagination"`
	Messages   []*Message           `thrift:"messages,2,required" frugal:"2,required,list<Message>" json:"messages"`
}

func NewListMessageResp() *ListMessageResp {
	return &ListMessageResp{}
}

func (p *ListMessageResp) InitDefault() {
}

var ListMessageResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListMessageResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListMessageResp_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListMessageResp) GetMessages() (v []*Message) {
	return p.Messages
}
func (p *ListMessageResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}
func (p *ListMessageResp) SetMessages(val []*Message) {
	p.Messages = val
}

func (p *ListMessageResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListMessageResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListMessageResp(%+v)", *p)
}

var fieldIDToName_ListMessageResp = map[int16]string{
	1: "pagination",
	2: "messages",
}

type UpdateConversationReq struct {
	Id    int64  `thrift:"id,1,required" frugal:"1,required,i64" path:"id"`
	Title string `thrift:"title,2,required" frugal:"2,required,string" json:"title"`
}

func NewUpdateConversationReq() *UpdateConversationReq {
	return &UpdateConversationReq{}
}

func (p *UpdateConversationReq) InitDefault() {
}

func (p *UpdateConversationReq) GetId() (v int64) {
	return p.Id
}

func (p *UpdateConversationReq) GetTitle() (v string) {
	return p.Title
}
func (p *UpdateConversationReq) SetId(val int64) {
	p.Id = val
}
func (p *UpdateConversationReq) SetTitle(val string) {
	p.Title = val
}

func (p *UpdateConversationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateConversationReq(%+v)", *p)
}

var fieldIDToName_UpdateConversationReq = map[int16]string{
	1: "id",
	2: "title",
}

type ListConversationReq struct {
	Pagination *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	AppId      int64               `thrift:"app_id,2,required" frugal:"2,required,i64" query:"app_id"`
}

func NewListConversationReq() *ListConversationReq {
	return &ListConversationReq{}
}

func (p *ListConversationReq) InitDefault() {
}

var ListConversationReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListConversationReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListConversationReq_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListConversationReq) GetAppId() (v int64) {
	return p.AppId
}
func (p *ListConversationReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListConversationReq) SetAppId(val int64) {
	p.AppId = val
}

func (p *ListConversationReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListConversationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListConversationReq(%+v)", *p)
}

var fieldIDToName_ListConversationReq = map[int16]string{
	1: "pagination",
	2: "app_id",
}

type ListConversationResp struct {
	Pagination    *base.PaginationResp `thrift:"pagination,1,required" frugal:"1,required,base.PaginationResp" json:"pagination"`
	Conversations []*Conversation      `thrift:"conversations,2,required" frugal:"2,required,list<Conversation>" json:"conversations"`
}

func NewListConversationResp() *ListConversationResp {
	return &ListConversationResp{}
}

func (p *ListConversationResp) InitDefault() {
}

var ListConversationResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListConversationResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListConversationResp_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListConversationResp) GetConversations() (v []*Conversation) {
	return p.Conversations
}
func (p *ListConversationResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}
func (p *ListConversationResp) SetConversations(val []*Conversation) {
	p.Conversations = val
}

func (p *ListConversationResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListConversationResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListConversationResp(%+v)", *p)
}

var fieldIDToName_ListConversationResp = map[int16]string{
	1: "pagination",
	2: "conversations",
}

type InitDevelopReq struct {
	AppId int64 `thrift:"app_id,1,required" frugal:"1,required,i64" json:"app_id"`
}

func NewInitDevelopReq() *InitDevelopReq {
	return &InitDevelopReq{}
}

func (p *InitDevelopReq) InitDefault() {
}

func (p *InitDevelopReq) GetAppId() (v int64) {
	return p.AppId
}
func (p *InitDevelopReq) SetAppId(val int64) {
	p.AppId = val
}

func (p *InitDevelopReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitDevelopReq(%+v)", *p)
}

var fieldIDToName_InitDevelopReq = map[int16]string{
	1: "app_id",
}

type InitDevelopResp struct {
	Conversation *Conversation `thrift:"conversation,1,required" frugal:"1,required,Conversation" json:"conversation"`
	Messages     []*Message    `thrift:"messages,2,required" frugal:"2,required,list<Message>" json:"messages"`
}

func NewInitDevelopResp() *InitDevelopResp {
	return &InitDevelopResp{}
}

func (p *InitDevelopResp) InitDefault() {
}

var InitDevelopResp_Conversation_DEFAULT *Conversation

func (p *InitDevelopResp) GetConversation() (v *Conversation) {
	if !p.IsSetConversation() {
		return InitDevelopResp_Conversation_DEFAULT
	}
	return p.Conversation
}

func (p *InitDevelopResp) GetMessages() (v []*Message) {
	return p.Messages
}
func (p *InitDevelopResp) SetConversation(val *Conversation) {
	p.Conversation = val
}
func (p *InitDevelopResp) SetMessages(val []*Message) {
	p.Messages = val
}

func (p *InitDevelopResp) IsSetConversation() bool {
	return p.Conversation != nil
}

func (p *InitDevelopResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitDevelopResp(%+v)", *p)
}

var fieldIDToName_InitDevelopResp = map[int16]string{
	1: "conversation",
	2: "messages",
}

type MessageContentValue struct {
	Text     *MessageContentValueText     `thrift:"text,1,optional" frugal:"1,optional,MessageContentValueText" json:"text,omitempty"`
	Image    *MessageContentValueImage    `thrift:"image,2,optional" frugal:"2,optional,MessageContentValueImage" json:"image,omitempty"`
	File     *MessageContentValueFile     `thrift:"file,3,optional" frugal:"3,optional,MessageContentValueFile" json:"file,omitempty"`
	Func     *MessageContentValueFunc     `thrift:"func,4,optional" frugal:"4,optional,MessageContentValueFunc" json:"func,omitempty"`
	FuncCall *MessageContentValueFuncCall `thrift:"func_call,5,optional" frugal:"5,optional,MessageContentValueFuncCall" json:"func_call,omitempty"`
	Tool     *MessageContentValueTool     `thrift:"tool,6,optional" frugal:"6,optional,MessageContentValueTool" json:"tool,omitempty"`
	ToolCall *MessageContentValueToolCall `thrift:"tool_call,7,optional" frugal:"7,optional,MessageContentValueToolCall" json:"tool_call,omitempty"`
}

func NewMessageContentValue() *MessageContentValue {
	return &MessageContentValue{}
}

func (p *MessageContentValue) InitDefault() {
}

var MessageContentValue_Text_DEFAULT *MessageContentValueText

func (p *MessageContentValue) GetText() (v *MessageContentValueText) {
	if !p.IsSetText() {
		return MessageContentValue_Text_DEFAULT
	}
	return p.Text
}

var MessageContentValue_Image_DEFAULT *MessageContentValueImage

func (p *MessageContentValue) GetImage() (v *MessageContentValueImage) {
	if !p.IsSetImage() {
		return MessageContentValue_Image_DEFAULT
	}
	return p.Image
}

var MessageContentValue_File_DEFAULT *MessageContentValueFile

func (p *MessageContentValue) GetFile() (v *MessageContentValueFile) {
	if !p.IsSetFile() {
		return MessageContentValue_File_DEFAULT
	}
	return p.File
}

var MessageContentValue_Func_DEFAULT *MessageContentValueFunc

func (p *MessageContentValue) GetFunc() (v *MessageContentValueFunc) {
	if !p.IsSetFunc() {
		return MessageContentValue_Func_DEFAULT
	}
	return p.Func
}

var MessageContentValue_FuncCall_DEFAULT *MessageContentValueFuncCall

func (p *MessageContentValue) GetFuncCall() (v *MessageContentValueFuncCall) {
	if !p.IsSetFuncCall() {
		return MessageContentValue_FuncCall_DEFAULT
	}
	return p.FuncCall
}

var MessageContentValue_Tool_DEFAULT *MessageContentValueTool

func (p *MessageContentValue) GetTool() (v *MessageContentValueTool) {
	if !p.IsSetTool() {
		return MessageContentValue_Tool_DEFAULT
	}
	return p.Tool
}

var MessageContentValue_ToolCall_DEFAULT *MessageContentValueToolCall

func (p *MessageContentValue) GetToolCall() (v *MessageContentValueToolCall) {
	if !p.IsSetToolCall() {
		return MessageContentValue_ToolCall_DEFAULT
	}
	return p.ToolCall
}
func (p *MessageContentValue) SetText(val *MessageContentValueText) {
	p.Text = val
}
func (p *MessageContentValue) SetImage(val *MessageContentValueImage) {
	p.Image = val
}
func (p *MessageContentValue) SetFile(val *MessageContentValueFile) {
	p.File = val
}
func (p *MessageContentValue) SetFunc(val *MessageContentValueFunc) {
	p.Func = val
}
func (p *MessageContentValue) SetFuncCall(val *MessageContentValueFuncCall) {
	p.FuncCall = val
}
func (p *MessageContentValue) SetTool(val *MessageContentValueTool) {
	p.Tool = val
}
func (p *MessageContentValue) SetToolCall(val *MessageContentValueToolCall) {
	p.ToolCall = val
}

func (p *MessageContentValue) CountSetFieldsMessageContentValue() int {
	count := 0
	if p.IsSetText() {
		count++
	}
	if p.IsSetImage() {
		count++
	}
	if p.IsSetFile() {
		count++
	}
	if p.IsSetFunc() {
		count++
	}
	if p.IsSetFuncCall() {
		count++
	}
	if p.IsSetTool() {
		count++
	}
	if p.IsSetToolCall() {
		count++
	}
	return count
}

func (p *MessageContentValue) IsSetText() bool {
	return p.Text != nil
}

func (p *MessageContentValue) IsSetImage() bool {
	return p.Image != nil
}

func (p *MessageContentValue) IsSetFile() bool {
	return p.File != nil
}

func (p *MessageContentValue) IsSetFunc() bool {
	return p.Func != nil
}

func (p *MessageContentValue) IsSetFuncCall() bool {
	return p.FuncCall != nil
}

func (p *MessageContentValue) IsSetTool() bool {
	return p.Tool != nil
}

func (p *MessageContentValue) IsSetToolCall() bool {
	return p.ToolCall != nil
}

func (p *MessageContentValue) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContentValue(%+v)", *p)
}

var fieldIDToName_MessageContentValue = map[int16]string{
	1: "text",
	2: "image",
	3: "file",
	4: "func",
	5: "func_call",
	6: "tool",
	7: "tool_call",
}

type ChatService interface {
	Chat(req *ChatReq, stream ChatService_ChatServer) (err error)

	UpdateMessage(ctx context.Context, req *UpdateMessageReq) (r *base.Empty, err error)

	DeleteMessage(ctx context.Context, req *DeleteMessageReq) (r *base.Empty, err error)

	ListMessage(ctx context.Context, req *ListMessageReq) (r *ListMessageResp, err error)

	UpdateConversation(ctx context.Context, req *UpdateConversationReq) (r *base.Empty, err error)

	DeleteConversation(ctx context.Context, req *base.IDReq) (r *base.Empty, err error)

	GetConversationByID(ctx context.Context, req *base.IDReq) (r *Conversation, err error)

	ListConversation(ctx context.Context, req *ListConversationReq) (r *ListConversationResp, err error)

	InitDevelop(ctx context.Context, req *InitDevelopReq) (r *InitDevelopResp, err error)
}

type ChatServiceChatArgs struct {
	Req *ChatReq `thrift:"req,1" frugal:"1,default,ChatReq" json:"req"`
}

func NewChatServiceChatArgs() *ChatServiceChatArgs {
	return &ChatServiceChatArgs{}
}

func (p *ChatServiceChatArgs) InitDefault() {
}

var ChatServiceChatArgs_Req_DEFAULT *ChatReq

func (p *ChatServiceChatArgs) GetReq() (v *ChatReq) {
	if !p.IsSetReq() {
		return ChatServiceChatArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceChatArgs) SetReq(val *ChatReq) {
	p.Req = val
}

func (p *ChatServiceChatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceChatArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceChatArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceChatArgs = map[int16]string{
	1: "req",
}

type ChatServiceChatResult struct {
	Success *ChatResp `thrift:"success,0,optional" frugal:"0,optional,ChatResp" json:"success,omitempty"`
}

func NewChatServiceChatResult() *ChatServiceChatResult {
	return &ChatServiceChatResult{}
}

func (p *ChatServiceChatResult) InitDefault() {
}

var ChatServiceChatResult_Success_DEFAULT *ChatResp

func (p *ChatServiceChatResult) GetSuccess() (v *ChatResp) {
	if !p.IsSetSuccess() {
		return ChatServiceChatResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceChatResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChatResp)
}

func (p *ChatServiceChatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceChatResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceChatResult(%+v)", *p)
}

var fieldIDToName_ChatServiceChatResult = map[int16]string{
	0: "success",
}

type ChatService_ChatServer interface {
	streaming.Stream

	Send(*ChatResp) error
}

type ChatServiceUpdateMessageArgs struct {
	Req *UpdateMessageReq `thrift:"req,1" frugal:"1,default,UpdateMessageReq" json:"req"`
}

func NewChatServiceUpdateMessageArgs() *ChatServiceUpdateMessageArgs {
	return &ChatServiceUpdateMessageArgs{}
}

func (p *ChatServiceUpdateMessageArgs) InitDefault() {
}

var ChatServiceUpdateMessageArgs_Req_DEFAULT *UpdateMessageReq

func (p *ChatServiceUpdateMessageArgs) GetReq() (v *UpdateMessageReq) {
	if !p.IsSetReq() {
		return ChatServiceUpdateMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceUpdateMessageArgs) SetReq(val *UpdateMessageReq) {
	p.Req = val
}

func (p *ChatServiceUpdateMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceUpdateMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceUpdateMessageArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceUpdateMessageArgs = map[int16]string{
	1: "req",
}

type ChatServiceUpdateMessageResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewChatServiceUpdateMessageResult() *ChatServiceUpdateMessageResult {
	return &ChatServiceUpdateMessageResult{}
}

func (p *ChatServiceUpdateMessageResult) InitDefault() {
}

var ChatServiceUpdateMessageResult_Success_DEFAULT *base.Empty

func (p *ChatServiceUpdateMessageResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return ChatServiceUpdateMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceUpdateMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *ChatServiceUpdateMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceUpdateMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceUpdateMessageResult(%+v)", *p)
}

var fieldIDToName_ChatServiceUpdateMessageResult = map[int16]string{
	0: "success",
}

type ChatServiceDeleteMessageArgs struct {
	Req *DeleteMessageReq `thrift:"req,1" frugal:"1,default,DeleteMessageReq" json:"req"`
}

func NewChatServiceDeleteMessageArgs() *ChatServiceDeleteMessageArgs {
	return &ChatServiceDeleteMessageArgs{}
}

func (p *ChatServiceDeleteMessageArgs) InitDefault() {
}

var ChatServiceDeleteMessageArgs_Req_DEFAULT *DeleteMessageReq

func (p *ChatServiceDeleteMessageArgs) GetReq() (v *DeleteMessageReq) {
	if !p.IsSetReq() {
		return ChatServiceDeleteMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceDeleteMessageArgs) SetReq(val *DeleteMessageReq) {
	p.Req = val
}

func (p *ChatServiceDeleteMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceDeleteMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceDeleteMessageArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceDeleteMessageArgs = map[int16]string{
	1: "req",
}

type ChatServiceDeleteMessageResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewChatServiceDeleteMessageResult() *ChatServiceDeleteMessageResult {
	return &ChatServiceDeleteMessageResult{}
}

func (p *ChatServiceDeleteMessageResult) InitDefault() {
}

var ChatServiceDeleteMessageResult_Success_DEFAULT *base.Empty

func (p *ChatServiceDeleteMessageResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return ChatServiceDeleteMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceDeleteMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *ChatServiceDeleteMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceDeleteMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceDeleteMessageResult(%+v)", *p)
}

var fieldIDToName_ChatServiceDeleteMessageResult = map[int16]string{
	0: "success",
}

type ChatServiceListMessageArgs struct {
	Req *ListMessageReq `thrift:"req,1" frugal:"1,default,ListMessageReq" json:"req"`
}

func NewChatServiceListMessageArgs() *ChatServiceListMessageArgs {
	return &ChatServiceListMessageArgs{}
}

func (p *ChatServiceListMessageArgs) InitDefault() {
}

var ChatServiceListMessageArgs_Req_DEFAULT *ListMessageReq

func (p *ChatServiceListMessageArgs) GetReq() (v *ListMessageReq) {
	if !p.IsSetReq() {
		return ChatServiceListMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceListMessageArgs) SetReq(val *ListMessageReq) {
	p.Req = val
}

func (p *ChatServiceListMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceListMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceListMessageArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceListMessageArgs = map[int16]string{
	1: "req",
}

type ChatServiceListMessageResult struct {
	Success *ListMessageResp `thrift:"success,0,optional" frugal:"0,optional,ListMessageResp" json:"success,omitempty"`
}

func NewChatServiceListMessageResult() *ChatServiceListMessageResult {
	return &ChatServiceListMessageResult{}
}

func (p *ChatServiceListMessageResult) InitDefault() {
}

var ChatServiceListMessageResult_Success_DEFAULT *ListMessageResp

func (p *ChatServiceListMessageResult) GetSuccess() (v *ListMessageResp) {
	if !p.IsSetSuccess() {
		return ChatServiceListMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceListMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListMessageResp)
}

func (p *ChatServiceListMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceListMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceListMessageResult(%+v)", *p)
}

var fieldIDToName_ChatServiceListMessageResult = map[int16]string{
	0: "success",
}

type ChatServiceUpdateConversationArgs struct {
	Req *UpdateConversationReq `thrift:"req,1" frugal:"1,default,UpdateConversationReq" json:"req"`
}

func NewChatServiceUpdateConversationArgs() *ChatServiceUpdateConversationArgs {
	return &ChatServiceUpdateConversationArgs{}
}

func (p *ChatServiceUpdateConversationArgs) InitDefault() {
}

var ChatServiceUpdateConversationArgs_Req_DEFAULT *UpdateConversationReq

func (p *ChatServiceUpdateConversationArgs) GetReq() (v *UpdateConversationReq) {
	if !p.IsSetReq() {
		return ChatServiceUpdateConversationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceUpdateConversationArgs) SetReq(val *UpdateConversationReq) {
	p.Req = val
}

func (p *ChatServiceUpdateConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceUpdateConversationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceUpdateConversationArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceUpdateConversationArgs = map[int16]string{
	1: "req",
}

type ChatServiceUpdateConversationResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewChatServiceUpdateConversationResult() *ChatServiceUpdateConversationResult {
	return &ChatServiceUpdateConversationResult{}
}

func (p *ChatServiceUpdateConversationResult) InitDefault() {
}

var ChatServiceUpdateConversationResult_Success_DEFAULT *base.Empty

func (p *ChatServiceUpdateConversationResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return ChatServiceUpdateConversationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceUpdateConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *ChatServiceUpdateConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceUpdateConversationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceUpdateConversationResult(%+v)", *p)
}

var fieldIDToName_ChatServiceUpdateConversationResult = map[int16]string{
	0: "success",
}

type ChatServiceDeleteConversationArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewChatServiceDeleteConversationArgs() *ChatServiceDeleteConversationArgs {
	return &ChatServiceDeleteConversationArgs{}
}

func (p *ChatServiceDeleteConversationArgs) InitDefault() {
}

var ChatServiceDeleteConversationArgs_Req_DEFAULT *base.IDReq

func (p *ChatServiceDeleteConversationArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return ChatServiceDeleteConversationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceDeleteConversationArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *ChatServiceDeleteConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceDeleteConversationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceDeleteConversationArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceDeleteConversationArgs = map[int16]string{
	1: "req",
}

type ChatServiceDeleteConversationResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewChatServiceDeleteConversationResult() *ChatServiceDeleteConversationResult {
	return &ChatServiceDeleteConversationResult{}
}

func (p *ChatServiceDeleteConversationResult) InitDefault() {
}

var ChatServiceDeleteConversationResult_Success_DEFAULT *base.Empty

func (p *ChatServiceDeleteConversationResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return ChatServiceDeleteConversationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceDeleteConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *ChatServiceDeleteConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceDeleteConversationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceDeleteConversationResult(%+v)", *p)
}

var fieldIDToName_ChatServiceDeleteConversationResult = map[int16]string{
	0: "success",
}

type ChatServiceGetConversationByIDArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewChatServiceGetConversationByIDArgs() *ChatServiceGetConversationByIDArgs {
	return &ChatServiceGetConversationByIDArgs{}
}

func (p *ChatServiceGetConversationByIDArgs) InitDefault() {
}

var ChatServiceGetConversationByIDArgs_Req_DEFAULT *base.IDReq

func (p *ChatServiceGetConversationByIDArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return ChatServiceGetConversationByIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceGetConversationByIDArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *ChatServiceGetConversationByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceGetConversationByIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetConversationByIDArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceGetConversationByIDArgs = map[int16]string{
	1: "req",
}

type ChatServiceGetConversationByIDResult struct {
	Success *Conversation `thrift:"success,0,optional" frugal:"0,optional,Conversation" json:"success,omitempty"`
}

func NewChatServiceGetConversationByIDResult() *ChatServiceGetConversationByIDResult {
	return &ChatServiceGetConversationByIDResult{}
}

func (p *ChatServiceGetConversationByIDResult) InitDefault() {
}

var ChatServiceGetConversationByIDResult_Success_DEFAULT *Conversation

func (p *ChatServiceGetConversationByIDResult) GetSuccess() (v *Conversation) {
	if !p.IsSetSuccess() {
		return ChatServiceGetConversationByIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceGetConversationByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*Conversation)
}

func (p *ChatServiceGetConversationByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceGetConversationByIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetConversationByIDResult(%+v)", *p)
}

var fieldIDToName_ChatServiceGetConversationByIDResult = map[int16]string{
	0: "success",
}

type ChatServiceListConversationArgs struct {
	Req *ListConversationReq `thrift:"req,1" frugal:"1,default,ListConversationReq" json:"req"`
}

func NewChatServiceListConversationArgs() *ChatServiceListConversationArgs {
	return &ChatServiceListConversationArgs{}
}

func (p *ChatServiceListConversationArgs) InitDefault() {
}

var ChatServiceListConversationArgs_Req_DEFAULT *ListConversationReq

func (p *ChatServiceListConversationArgs) GetReq() (v *ListConversationReq) {
	if !p.IsSetReq() {
		return ChatServiceListConversationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceListConversationArgs) SetReq(val *ListConversationReq) {
	p.Req = val
}

func (p *ChatServiceListConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceListConversationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceListConversationArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceListConversationArgs = map[int16]string{
	1: "req",
}

type ChatServiceListConversationResult struct {
	Success *ListConversationResp `thrift:"success,0,optional" frugal:"0,optional,ListConversationResp" json:"success,omitempty"`
}

func NewChatServiceListConversationResult() *ChatServiceListConversationResult {
	return &ChatServiceListConversationResult{}
}

func (p *ChatServiceListConversationResult) InitDefault() {
}

var ChatServiceListConversationResult_Success_DEFAULT *ListConversationResp

func (p *ChatServiceListConversationResult) GetSuccess() (v *ListConversationResp) {
	if !p.IsSetSuccess() {
		return ChatServiceListConversationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceListConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListConversationResp)
}

func (p *ChatServiceListConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceListConversationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceListConversationResult(%+v)", *p)
}

var fieldIDToName_ChatServiceListConversationResult = map[int16]string{
	0: "success",
}

type ChatServiceInitDevelopArgs struct {
	Req *InitDevelopReq `thrift:"req,1" frugal:"1,default,InitDevelopReq" json:"req"`
}

func NewChatServiceInitDevelopArgs() *ChatServiceInitDevelopArgs {
	return &ChatServiceInitDevelopArgs{}
}

func (p *ChatServiceInitDevelopArgs) InitDefault() {
}

var ChatServiceInitDevelopArgs_Req_DEFAULT *InitDevelopReq

func (p *ChatServiceInitDevelopArgs) GetReq() (v *InitDevelopReq) {
	if !p.IsSetReq() {
		return ChatServiceInitDevelopArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceInitDevelopArgs) SetReq(val *InitDevelopReq) {
	p.Req = val
}

func (p *ChatServiceInitDevelopArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceInitDevelopArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceInitDevelopArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceInitDevelopArgs = map[int16]string{
	1: "req",
}

type ChatServiceInitDevelopResult struct {
	Success *InitDevelopResp `thrift:"success,0,optional" frugal:"0,optional,InitDevelopResp" json:"success,omitempty"`
}

func NewChatServiceInitDevelopResult() *ChatServiceInitDevelopResult {
	return &ChatServiceInitDevelopResult{}
}

func (p *ChatServiceInitDevelopResult) InitDefault() {
}

var ChatServiceInitDevelopResult_Success_DEFAULT *InitDevelopResp

func (p *ChatServiceInitDevelopResult) GetSuccess() (v *InitDevelopResp) {
	if !p.IsSetSuccess() {
		return ChatServiceInitDevelopResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceInitDevelopResult) SetSuccess(x interface{}) {
	p.Success = x.(*InitDevelopResp)
}

func (p *ChatServiceInitDevelopResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceInitDevelopResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceInitDevelopResult(%+v)", *p)
}

var fieldIDToName_ChatServiceInitDevelopResult = map[int16]string{
	0: "success",
}
