// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package openai

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ToolType int64

const (
	ToolType_FUNCTION ToolType = 1
)

func (p ToolType) String() string {
	switch p {
	case ToolType_FUNCTION:
		return "FUNCTION"
	}
	return "<UNSET>"
}

func ToolTypeFromString(s string) (ToolType, error) {
	switch s {
	case "FUNCTION":
		return ToolType_FUNCTION, nil
	}
	return ToolType(0), fmt.Errorf("not a valid ToolType string")
}

func ToolTypePtr(v ToolType) *ToolType { return &v }
func (p *ToolType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ToolType(result.Int64)
	return
}

func (p *ToolType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ChatMessagePartType int64

const (
	ChatMessagePartType_TEXT      ChatMessagePartType = 1
	ChatMessagePartType_IMAGE_URL ChatMessagePartType = 2
)

func (p ChatMessagePartType) String() string {
	switch p {
	case ChatMessagePartType_TEXT:
		return "TEXT"
	case ChatMessagePartType_IMAGE_URL:
		return "IMAGE_URL"
	}
	return "<UNSET>"
}

func ChatMessagePartTypeFromString(s string) (ChatMessagePartType, error) {
	switch s {
	case "TEXT":
		return ChatMessagePartType_TEXT, nil
	case "IMAGE_URL":
		return ChatMessagePartType_IMAGE_URL, nil
	}
	return ChatMessagePartType(0), fmt.Errorf("not a valid ChatMessagePartType string")
}

func ChatMessagePartTypePtr(v ChatMessagePartType) *ChatMessagePartType { return &v }
func (p *ChatMessagePartType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ChatMessagePartType(result.Int64)
	return
}

func (p *ChatMessagePartType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ImageURLDetail int64

const (
	ImageURLDetail_HIGH ImageURLDetail = 1
	ImageURLDetail_LOW  ImageURLDetail = 2
	ImageURLDetail_AUTO ImageURLDetail = 3
)

func (p ImageURLDetail) String() string {
	switch p {
	case ImageURLDetail_HIGH:
		return "HIGH"
	case ImageURLDetail_LOW:
		return "LOW"
	case ImageURLDetail_AUTO:
		return "AUTO"
	}
	return "<UNSET>"
}

func ImageURLDetailFromString(s string) (ImageURLDetail, error) {
	switch s {
	case "HIGH":
		return ImageURLDetail_HIGH, nil
	case "LOW":
		return ImageURLDetail_LOW, nil
	case "AUTO":
		return ImageURLDetail_AUTO, nil
	}
	return ImageURLDetail(0), fmt.Errorf("not a valid ImageURLDetail string")
}

func ImageURLDetailPtr(v ImageURLDetail) *ImageURLDetail { return &v }
func (p *ImageURLDetail) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ImageURLDetail(result.Int64)
	return
}

func (p *ImageURLDetail) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ChatCompletionResponseFormatType int64

const (
	ChatCompletionResponseFormatType_JSON_OBJECT ChatCompletionResponseFormatType = 1
	ChatCompletionResponseFormatType_JSON_SCHEMA ChatCompletionResponseFormatType = 2
	ChatCompletionResponseFormatType_TEXT        ChatCompletionResponseFormatType = 3
)

func (p ChatCompletionResponseFormatType) String() string {
	switch p {
	case ChatCompletionResponseFormatType_JSON_OBJECT:
		return "JSON_OBJECT"
	case ChatCompletionResponseFormatType_JSON_SCHEMA:
		return "JSON_SCHEMA"
	case ChatCompletionResponseFormatType_TEXT:
		return "TEXT"
	}
	return "<UNSET>"
}

func ChatCompletionResponseFormatTypeFromString(s string) (ChatCompletionResponseFormatType, error) {
	switch s {
	case "JSON_OBJECT":
		return ChatCompletionResponseFormatType_JSON_OBJECT, nil
	case "JSON_SCHEMA":
		return ChatCompletionResponseFormatType_JSON_SCHEMA, nil
	case "TEXT":
		return ChatCompletionResponseFormatType_TEXT, nil
	}
	return ChatCompletionResponseFormatType(0), fmt.Errorf("not a valid ChatCompletionResponseFormatType string")
}

func ChatCompletionResponseFormatTypePtr(v ChatCompletionResponseFormatType) *ChatCompletionResponseFormatType {
	return &v
}
func (p *ChatCompletionResponseFormatType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ChatCompletionResponseFormatType(result.Int64)
	return
}

func (p *ChatCompletionResponseFormatType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type FinishReason int64

const (
	FinishReason_STOP           FinishReason = 1
	FinishReason_LENGTH         FinishReason = 2
	FinishReason_FUNCTION_CALL  FinishReason = 3
	FinishReason_TOOL_CALLS     FinishReason = 4
	FinishReason_CONTENT_FILTER FinishReason = 5
	FinishReason_NULL_REASON    FinishReason = 6
)

func (p FinishReason) String() string {
	switch p {
	case FinishReason_STOP:
		return "STOP"
	case FinishReason_LENGTH:
		return "LENGTH"
	case FinishReason_FUNCTION_CALL:
		return "FUNCTION_CALL"
	case FinishReason_TOOL_CALLS:
		return "TOOL_CALLS"
	case FinishReason_CONTENT_FILTER:
		return "CONTENT_FILTER"
	case FinishReason_NULL_REASON:
		return "NULL_REASON"
	}
	return "<UNSET>"
}

func FinishReasonFromString(s string) (FinishReason, error) {
	switch s {
	case "STOP":
		return FinishReason_STOP, nil
	case "LENGTH":
		return FinishReason_LENGTH, nil
	case "FUNCTION_CALL":
		return FinishReason_FUNCTION_CALL, nil
	case "TOOL_CALLS":
		return FinishReason_TOOL_CALLS, nil
	case "CONTENT_FILTER":
		return FinishReason_CONTENT_FILTER, nil
	case "NULL_REASON":
		return FinishReason_NULL_REASON, nil
	}
	return FinishReason(0), fmt.Errorf("not a valid FinishReason string")
}

func FinishReasonPtr(v FinishReason) *FinishReason { return &v }
func (p *FinishReason) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = FinishReason(result.Int64)
	return
}

func (p *FinishReason) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Hate struct {
	Filtered bool   `thrift:"filtered,1,required" frugal:"1,required,bool" json:"filtered"`
	Severity string `thrift:"severity,2,required" frugal:"2,required,string" json:"severity"`
}

func NewHate() *Hate {
	return &Hate{}
}

func (p *Hate) InitDefault() {
}

func (p *Hate) GetFiltered() (v bool) {
	return p.Filtered
}

func (p *Hate) GetSeverity() (v string) {
	return p.Severity
}
func (p *Hate) SetFiltered(val bool) {
	p.Filtered = val
}
func (p *Hate) SetSeverity(val string) {
	p.Severity = val
}

func (p *Hate) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Hate(%+v)", *p)
}

var fieldIDToName_Hate = map[int16]string{
	1: "filtered",
	2: "severity",
}

type SelfHarm struct {
	Filtered bool   `thrift:"filtered,1,required" frugal:"1,required,bool" json:"filtered"`
	Severity string `thrift:"severity,2,required" frugal:"2,required,string" json:"severity"`
}

func NewSelfHarm() *SelfHarm {
	return &SelfHarm{}
}

func (p *SelfHarm) InitDefault() {
}

func (p *SelfHarm) GetFiltered() (v bool) {
	return p.Filtered
}

func (p *SelfHarm) GetSeverity() (v string) {
	return p.Severity
}
func (p *SelfHarm) SetFiltered(val bool) {
	p.Filtered = val
}
func (p *SelfHarm) SetSeverity(val string) {
	p.Severity = val
}

func (p *SelfHarm) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SelfHarm(%+v)", *p)
}

var fieldIDToName_SelfHarm = map[int16]string{
	1: "filtered",
	2: "severity",
}

type Sexual struct {
	Filtered bool   `thrift:"filtered,1,required" frugal:"1,required,bool" json:"filtered"`
	Severity string `thrift:"severity,2,required" frugal:"2,required,string" json:"severity"`
}

func NewSexual() *Sexual {
	return &Sexual{}
}

func (p *Sexual) InitDefault() {
}

func (p *Sexual) GetFiltered() (v bool) {
	return p.Filtered
}

func (p *Sexual) GetSeverity() (v string) {
	return p.Severity
}
func (p *Sexual) SetFiltered(val bool) {
	p.Filtered = val
}
func (p *Sexual) SetSeverity(val string) {
	p.Severity = val
}

func (p *Sexual) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Sexual(%+v)", *p)
}

var fieldIDToName_Sexual = map[int16]string{
	1: "filtered",
	2: "severity",
}

type Violence struct {
	Filtered bool   `thrift:"filtered,1,required" frugal:"1,required,bool" json:"filtered"`
	Severity string `thrift:"severity,2,required" frugal:"2,required,string" json:"severity"`
}

func NewViolence() *Violence {
	return &Violence{}
}

func (p *Violence) InitDefault() {
}

func (p *Violence) GetFiltered() (v bool) {
	return p.Filtered
}

func (p *Violence) GetSeverity() (v string) {
	return p.Severity
}
func (p *Violence) SetFiltered(val bool) {
	p.Filtered = val
}
func (p *Violence) SetSeverity(val string) {
	p.Severity = val
}

func (p *Violence) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Violence(%+v)", *p)
}

var fieldIDToName_Violence = map[int16]string{
	1: "filtered",
	2: "severity",
}

type ContentFilterResults struct {
	Hate     *Hate     `thrift:"hate,1,required" frugal:"1,required,Hate" json:"hate"`
	SelfHarm *SelfHarm `thrift:"self_harm,2,required" frugal:"2,required,SelfHarm" json:"self_harm"`
	Sexual   *Sexual   `thrift:"sexual,3,required" frugal:"3,required,Sexual" json:"sexual"`
	Violence *Violence `thrift:"violence,4,required" frugal:"4,required,Violence" json:"violence"`
}

func NewContentFilterResults() *ContentFilterResults {
	return &ContentFilterResults{}
}

func (p *ContentFilterResults) InitDefault() {
}

var ContentFilterResults_Hate_DEFAULT *Hate

func (p *ContentFilterResults) GetHate() (v *Hate) {
	if !p.IsSetHate() {
		return ContentFilterResults_Hate_DEFAULT
	}
	return p.Hate
}

var ContentFilterResults_SelfHarm_DEFAULT *SelfHarm

func (p *ContentFilterResults) GetSelfHarm() (v *SelfHarm) {
	if !p.IsSetSelfHarm() {
		return ContentFilterResults_SelfHarm_DEFAULT
	}
	return p.SelfHarm
}

var ContentFilterResults_Sexual_DEFAULT *Sexual

func (p *ContentFilterResults) GetSexual() (v *Sexual) {
	if !p.IsSetSexual() {
		return ContentFilterResults_Sexual_DEFAULT
	}
	return p.Sexual
}

var ContentFilterResults_Violence_DEFAULT *Violence

func (p *ContentFilterResults) GetViolence() (v *Violence) {
	if !p.IsSetViolence() {
		return ContentFilterResults_Violence_DEFAULT
	}
	return p.Violence
}
func (p *ContentFilterResults) SetHate(val *Hate) {
	p.Hate = val
}
func (p *ContentFilterResults) SetSelfHarm(val *SelfHarm) {
	p.SelfHarm = val
}
func (p *ContentFilterResults) SetSexual(val *Sexual) {
	p.Sexual = val
}
func (p *ContentFilterResults) SetViolence(val *Violence) {
	p.Violence = val
}

func (p *ContentFilterResults) IsSetHate() bool {
	return p.Hate != nil
}

func (p *ContentFilterResults) IsSetSelfHarm() bool {
	return p.SelfHarm != nil
}

func (p *ContentFilterResults) IsSetSexual() bool {
	return p.Sexual != nil
}

func (p *ContentFilterResults) IsSetViolence() bool {
	return p.Violence != nil
}

func (p *ContentFilterResults) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ContentFilterResults(%+v)", *p)
}

var fieldIDToName_ContentFilterResults = map[int16]string{
	1: "hate",
	2: "self_harm",
	3: "sexual",
	4: "violence",
}

type PromptAnnotation struct {
	PromptIndex          int32                 `thrift:"prompt_index,1,required" frugal:"1,required,i32" json:"prompt_index"`
	ContentFilterResults *ContentFilterResults `thrift:"content_filter_results,2,required" frugal:"2,required,ContentFilterResults" json:"content_filter_results"`
}

func NewPromptAnnotation() *PromptAnnotation {
	return &PromptAnnotation{}
}

func (p *PromptAnnotation) InitDefault() {
}

func (p *PromptAnnotation) GetPromptIndex() (v int32) {
	return p.PromptIndex
}

var PromptAnnotation_ContentFilterResults_DEFAULT *ContentFilterResults

func (p *PromptAnnotation) GetContentFilterResults() (v *ContentFilterResults) {
	if !p.IsSetContentFilterResults() {
		return PromptAnnotation_ContentFilterResults_DEFAULT
	}
	return p.ContentFilterResults
}
func (p *PromptAnnotation) SetPromptIndex(val int32) {
	p.PromptIndex = val
}
func (p *PromptAnnotation) SetContentFilterResults(val *ContentFilterResults) {
	p.ContentFilterResults = val
}

func (p *PromptAnnotation) IsSetContentFilterResults() bool {
	return p.ContentFilterResults != nil
}

func (p *PromptAnnotation) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PromptAnnotation(%+v)", *p)
}

var fieldIDToName_PromptAnnotation = map[int16]string{
	1: "prompt_index",
	2: "content_filter_results",
}

type ChatMessageImageURL struct {
	Url    string         `thrift:"url,1,required" frugal:"1,required,string" json:"url"`
	Detail ImageURLDetail `thrift:"detail,2,required" frugal:"2,required,ImageURLDetail" json:"detail"`
}

func NewChatMessageImageURL() *ChatMessageImageURL {
	return &ChatMessageImageURL{}
}

func (p *ChatMessageImageURL) InitDefault() {
}

func (p *ChatMessageImageURL) GetUrl() (v string) {
	return p.Url
}

func (p *ChatMessageImageURL) GetDetail() (v ImageURLDetail) {
	return p.Detail
}
func (p *ChatMessageImageURL) SetUrl(val string) {
	p.Url = val
}
func (p *ChatMessageImageURL) SetDetail(val ImageURLDetail) {
	p.Detail = val
}

func (p *ChatMessageImageURL) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatMessageImageURL(%+v)", *p)
}

var fieldIDToName_ChatMessageImageURL = map[int16]string{
	1: "url",
	2: "detail",
}

type ChatMessagePart struct {
	Type     ChatMessagePartType  `thrift:"type,1,required" frugal:"1,required,ChatMessagePartType" json:"type"`
	Text     *string              `thrift:"text,2,optional" frugal:"2,optional,string" json:"text,omitempty"`
	ImageUrl *ChatMessageImageURL `thrift:"image_url,3,optional" frugal:"3,optional,ChatMessageImageURL" json:"image_url,omitempty"`
}

func NewChatMessagePart() *ChatMessagePart {
	return &ChatMessagePart{}
}

func (p *ChatMessagePart) InitDefault() {
}

func (p *ChatMessagePart) GetType() (v ChatMessagePartType) {
	return p.Type
}

var ChatMessagePart_Text_DEFAULT string

func (p *ChatMessagePart) GetText() (v string) {
	if !p.IsSetText() {
		return ChatMessagePart_Text_DEFAULT
	}
	return *p.Text
}

var ChatMessagePart_ImageUrl_DEFAULT *ChatMessageImageURL

func (p *ChatMessagePart) GetImageUrl() (v *ChatMessageImageURL) {
	if !p.IsSetImageUrl() {
		return ChatMessagePart_ImageUrl_DEFAULT
	}
	return p.ImageUrl
}
func (p *ChatMessagePart) SetType(val ChatMessagePartType) {
	p.Type = val
}
func (p *ChatMessagePart) SetText(val *string) {
	p.Text = val
}
func (p *ChatMessagePart) SetImageUrl(val *ChatMessageImageURL) {
	p.ImageUrl = val
}

func (p *ChatMessagePart) IsSetText() bool {
	return p.Text != nil
}

func (p *ChatMessagePart) IsSetImageUrl() bool {
	return p.ImageUrl != nil
}

func (p *ChatMessagePart) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatMessagePart(%+v)", *p)
}

var fieldIDToName_ChatMessagePart = map[int16]string{
	1: "type",
	2: "text",
	3: "image_url",
}

type FunctionCall struct {
	Name      *string `thrift:"name,1,optional" frugal:"1,optional,string" json:"name,omitempty"`
	Arguments *string `thrift:"arguments,2,optional" frugal:"2,optional,string" json:"arguments,omitempty"`
}

func NewFunctionCall() *FunctionCall {
	return &FunctionCall{}
}

func (p *FunctionCall) InitDefault() {
}

var FunctionCall_Name_DEFAULT string

func (p *FunctionCall) GetName() (v string) {
	if !p.IsSetName() {
		return FunctionCall_Name_DEFAULT
	}
	return *p.Name
}

var FunctionCall_Arguments_DEFAULT string

func (p *FunctionCall) GetArguments() (v string) {
	if !p.IsSetArguments() {
		return FunctionCall_Arguments_DEFAULT
	}
	return *p.Arguments
}
func (p *FunctionCall) SetName(val *string) {
	p.Name = val
}
func (p *FunctionCall) SetArguments(val *string) {
	p.Arguments = val
}

func (p *FunctionCall) IsSetName() bool {
	return p.Name != nil
}

func (p *FunctionCall) IsSetArguments() bool {
	return p.Arguments != nil
}

func (p *FunctionCall) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FunctionCall(%+v)", *p)
}

var fieldIDToName_FunctionCall = map[int16]string{
	1: "name",
	2: "arguments",
}

type ToolCall struct {
	Index    *int32        `thrift:"index,1,optional" frugal:"1,optional,i32" json:"index,omitempty"`
	Id       string        `thrift:"id,2,required" frugal:"2,required,string" json:"id"`
	Type     ToolType      `thrift:"type,3,required" frugal:"3,required,ToolType" json:"type"`
	Function *FunctionCall `thrift:"function,4,required" frugal:"4,required,FunctionCall" json:"function"`
}

func NewToolCall() *ToolCall {
	return &ToolCall{}
}

func (p *ToolCall) InitDefault() {
}

var ToolCall_Index_DEFAULT int32

func (p *ToolCall) GetIndex() (v int32) {
	if !p.IsSetIndex() {
		return ToolCall_Index_DEFAULT
	}
	return *p.Index
}

func (p *ToolCall) GetId() (v string) {
	return p.Id
}

func (p *ToolCall) GetType() (v ToolType) {
	return p.Type
}

var ToolCall_Function_DEFAULT *FunctionCall

func (p *ToolCall) GetFunction() (v *FunctionCall) {
	if !p.IsSetFunction() {
		return ToolCall_Function_DEFAULT
	}
	return p.Function
}
func (p *ToolCall) SetIndex(val *int32) {
	p.Index = val
}
func (p *ToolCall) SetId(val string) {
	p.Id = val
}
func (p *ToolCall) SetType(val ToolType) {
	p.Type = val
}
func (p *ToolCall) SetFunction(val *FunctionCall) {
	p.Function = val
}

func (p *ToolCall) IsSetIndex() bool {
	return p.Index != nil
}

func (p *ToolCall) IsSetFunction() bool {
	return p.Function != nil
}

func (p *ToolCall) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ToolCall(%+v)", *p)
}

var fieldIDToName_ToolCall = map[int16]string{
	1: "index",
	2: "id",
	3: "type",
	4: "function",
}

type ChatCompletionMessage struct {
	Role         string             `thrift:"role,1,required" frugal:"1,required,string" json:"role"`
	Content      *string            `thrift:"content,2,optional" frugal:"2,optional,string" json:"content,omitempty"`
	MultiContent []*ChatMessagePart `thrift:"multi_content,3,optional" frugal:"3,optional,list<ChatMessagePart>" json:"multi_content,omitempty"`
	Name         *string            `thrift:"name,4,optional" frugal:"4,optional,string" json:"name,omitempty"`
	FunctionCall *FunctionCall      `thrift:"function_call,5,optional" frugal:"5,optional,FunctionCall" json:"function_call,omitempty"`
	ToolCalls    []*ToolCall        `thrift:"tool_calls,6,optional" frugal:"6,optional,list<ToolCall>" json:"tool_calls,omitempty"`
	ToolCallId   *string            `thrift:"tool_call_id,7,optional" frugal:"7,optional,string" json:"tool_call_id,omitempty"`
}

func NewChatCompletionMessage() *ChatCompletionMessage {
	return &ChatCompletionMessage{}
}

func (p *ChatCompletionMessage) InitDefault() {
}

func (p *ChatCompletionMessage) GetRole() (v string) {
	return p.Role
}

var ChatCompletionMessage_Content_DEFAULT string

func (p *ChatCompletionMessage) GetContent() (v string) {
	if !p.IsSetContent() {
		return ChatCompletionMessage_Content_DEFAULT
	}
	return *p.Content
}

var ChatCompletionMessage_MultiContent_DEFAULT []*ChatMessagePart

func (p *ChatCompletionMessage) GetMultiContent() (v []*ChatMessagePart) {
	if !p.IsSetMultiContent() {
		return ChatCompletionMessage_MultiContent_DEFAULT
	}
	return p.MultiContent
}

var ChatCompletionMessage_Name_DEFAULT string

func (p *ChatCompletionMessage) GetName() (v string) {
	if !p.IsSetName() {
		return ChatCompletionMessage_Name_DEFAULT
	}
	return *p.Name
}

var ChatCompletionMessage_FunctionCall_DEFAULT *FunctionCall

func (p *ChatCompletionMessage) GetFunctionCall() (v *FunctionCall) {
	if !p.IsSetFunctionCall() {
		return ChatCompletionMessage_FunctionCall_DEFAULT
	}
	return p.FunctionCall
}

var ChatCompletionMessage_ToolCalls_DEFAULT []*ToolCall

func (p *ChatCompletionMessage) GetToolCalls() (v []*ToolCall) {
	if !p.IsSetToolCalls() {
		return ChatCompletionMessage_ToolCalls_DEFAULT
	}
	return p.ToolCalls
}

var ChatCompletionMessage_ToolCallId_DEFAULT string

func (p *ChatCompletionMessage) GetToolCallId() (v string) {
	if !p.IsSetToolCallId() {
		return ChatCompletionMessage_ToolCallId_DEFAULT
	}
	return *p.ToolCallId
}
func (p *ChatCompletionMessage) SetRole(val string) {
	p.Role = val
}
func (p *ChatCompletionMessage) SetContent(val *string) {
	p.Content = val
}
func (p *ChatCompletionMessage) SetMultiContent(val []*ChatMessagePart) {
	p.MultiContent = val
}
func (p *ChatCompletionMessage) SetName(val *string) {
	p.Name = val
}
func (p *ChatCompletionMessage) SetFunctionCall(val *FunctionCall) {
	p.FunctionCall = val
}
func (p *ChatCompletionMessage) SetToolCalls(val []*ToolCall) {
	p.ToolCalls = val
}
func (p *ChatCompletionMessage) SetToolCallId(val *string) {
	p.ToolCallId = val
}

func (p *ChatCompletionMessage) IsSetContent() bool {
	return p.Content != nil
}

func (p *ChatCompletionMessage) IsSetMultiContent() bool {
	return p.MultiContent != nil
}

func (p *ChatCompletionMessage) IsSetName() bool {
	return p.Name != nil
}

func (p *ChatCompletionMessage) IsSetFunctionCall() bool {
	return p.FunctionCall != nil
}

func (p *ChatCompletionMessage) IsSetToolCalls() bool {
	return p.ToolCalls != nil
}

func (p *ChatCompletionMessage) IsSetToolCallId() bool {
	return p.ToolCallId != nil
}

func (p *ChatCompletionMessage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatCompletionMessage(%+v)", *p)
}

var fieldIDToName_ChatCompletionMessage = map[int16]string{
	1: "role",
	2: "content",
	3: "multi_content",
	4: "name",
	5: "function_call",
	6: "tool_calls",
	7: "tool_call_id",
}

type FunctionDefinition struct {
	Name        string  `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Description *string `thrift:"description,2,optional" frugal:"2,optional,string" json:"description,omitempty"`
	Strict      *bool   `thrift:"strict,3,optional" frugal:"3,optional,bool" json:"strict,omitempty"`
	Parameters  []byte  `thrift:"parameters,4,optional" frugal:"4,optional,binary" json:"parameters,omitempty"`
}

func NewFunctionDefinition() *FunctionDefinition {
	return &FunctionDefinition{}
}

func (p *FunctionDefinition) InitDefault() {
}

func (p *FunctionDefinition) GetName() (v string) {
	return p.Name
}

var FunctionDefinition_Description_DEFAULT string

func (p *FunctionDefinition) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return FunctionDefinition_Description_DEFAULT
	}
	return *p.Description
}

var FunctionDefinition_Strict_DEFAULT bool

func (p *FunctionDefinition) GetStrict() (v bool) {
	if !p.IsSetStrict() {
		return FunctionDefinition_Strict_DEFAULT
	}
	return *p.Strict
}

var FunctionDefinition_Parameters_DEFAULT []byte

func (p *FunctionDefinition) GetParameters() (v []byte) {
	if !p.IsSetParameters() {
		return FunctionDefinition_Parameters_DEFAULT
	}
	return p.Parameters
}
func (p *FunctionDefinition) SetName(val string) {
	p.Name = val
}
func (p *FunctionDefinition) SetDescription(val *string) {
	p.Description = val
}
func (p *FunctionDefinition) SetStrict(val *bool) {
	p.Strict = val
}
func (p *FunctionDefinition) SetParameters(val []byte) {
	p.Parameters = val
}

func (p *FunctionDefinition) IsSetDescription() bool {
	return p.Description != nil
}

func (p *FunctionDefinition) IsSetStrict() bool {
	return p.Strict != nil
}

func (p *FunctionDefinition) IsSetParameters() bool {
	return p.Parameters != nil
}

func (p *FunctionDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FunctionDefinition(%+v)", *p)
}

var fieldIDToName_FunctionDefinition = map[int16]string{
	1: "name",
	2: "description",
	3: "strict",
	4: "parameters",
}

type Tool struct {
	Type     ToolType            `thrift:"type,1,required" frugal:"1,required,ToolType" json:"type"`
	Function *FunctionDefinition `thrift:"function,2,optional" frugal:"2,optional,FunctionDefinition" json:"function,omitempty"`
}

func NewTool() *Tool {
	return &Tool{}
}

func (p *Tool) InitDefault() {
}

func (p *Tool) GetType() (v ToolType) {
	return p.Type
}

var Tool_Function_DEFAULT *FunctionDefinition

func (p *Tool) GetFunction() (v *FunctionDefinition) {
	if !p.IsSetFunction() {
		return Tool_Function_DEFAULT
	}
	return p.Function
}
func (p *Tool) SetType(val ToolType) {
	p.Type = val
}
func (p *Tool) SetFunction(val *FunctionDefinition) {
	p.Function = val
}

func (p *Tool) IsSetFunction() bool {
	return p.Function != nil
}

func (p *Tool) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Tool(%+v)", *p)
}

var fieldIDToName_Tool = map[int16]string{
	1: "type",
	2: "function",
}

type ToolChoice struct {
	Type         ToolType `thrift:"type,1,required" frugal:"1,required,ToolType" json:"type"`
	FunctionName *string  `thrift:"function_name,2,optional" frugal:"2,optional,string" json:"function_name,omitempty"`
}

func NewToolChoice() *ToolChoice {
	return &ToolChoice{}
}

func (p *ToolChoice) InitDefault() {
}

func (p *ToolChoice) GetType() (v ToolType) {
	return p.Type
}

var ToolChoice_FunctionName_DEFAULT string

func (p *ToolChoice) GetFunctionName() (v string) {
	if !p.IsSetFunctionName() {
		return ToolChoice_FunctionName_DEFAULT
	}
	return *p.FunctionName
}
func (p *ToolChoice) SetType(val ToolType) {
	p.Type = val
}
func (p *ToolChoice) SetFunctionName(val *string) {
	p.FunctionName = val
}

func (p *ToolChoice) IsSetFunctionName() bool {
	return p.FunctionName != nil
}

func (p *ToolChoice) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ToolChoice(%+v)", *p)
}

var fieldIDToName_ToolChoice = map[int16]string{
	1: "type",
	2: "function_name",
}

type StreamOptions struct {
	IncludeUsage *bool `thrift:"include_usage,1,optional" frugal:"1,optional,bool" json:"include_usage,omitempty"`
}

func NewStreamOptions() *StreamOptions {
	return &StreamOptions{}
}

func (p *StreamOptions) InitDefault() {
}

var StreamOptions_IncludeUsage_DEFAULT bool

func (p *StreamOptions) GetIncludeUsage() (v bool) {
	if !p.IsSetIncludeUsage() {
		return StreamOptions_IncludeUsage_DEFAULT
	}
	return *p.IncludeUsage
}
func (p *StreamOptions) SetIncludeUsage(val *bool) {
	p.IncludeUsage = val
}

func (p *StreamOptions) IsSetIncludeUsage() bool {
	return p.IncludeUsage != nil
}

func (p *StreamOptions) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StreamOptions(%+v)", *p)
}

var fieldIDToName_StreamOptions = map[int16]string{
	1: "include_usage",
}

type ChatCompletionResponseFormatJSONSchema struct {
	Name        string  `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Description *string `thrift:"description,2,optional" frugal:"2,optional,string" json:"description,omitempty"`
	Schema      string  `thrift:"schema,3,required" frugal:"3,required,string" json:"schema"`
	Strict      *bool   `thrift:"strict,4,optional" frugal:"4,optional,bool" json:"strict,omitempty"`
}

func NewChatCompletionResponseFormatJSONSchema() *ChatCompletionResponseFormatJSONSchema {
	return &ChatCompletionResponseFormatJSONSchema{}
}

func (p *ChatCompletionResponseFormatJSONSchema) InitDefault() {
}

func (p *ChatCompletionResponseFormatJSONSchema) GetName() (v string) {
	return p.Name
}

var ChatCompletionResponseFormatJSONSchema_Description_DEFAULT string

func (p *ChatCompletionResponseFormatJSONSchema) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return ChatCompletionResponseFormatJSONSchema_Description_DEFAULT
	}
	return *p.Description
}

func (p *ChatCompletionResponseFormatJSONSchema) GetSchema() (v string) {
	return p.Schema
}

var ChatCompletionResponseFormatJSONSchema_Strict_DEFAULT bool

func (p *ChatCompletionResponseFormatJSONSchema) GetStrict() (v bool) {
	if !p.IsSetStrict() {
		return ChatCompletionResponseFormatJSONSchema_Strict_DEFAULT
	}
	return *p.Strict
}
func (p *ChatCompletionResponseFormatJSONSchema) SetName(val string) {
	p.Name = val
}
func (p *ChatCompletionResponseFormatJSONSchema) SetDescription(val *string) {
	p.Description = val
}
func (p *ChatCompletionResponseFormatJSONSchema) SetSchema(val string) {
	p.Schema = val
}
func (p *ChatCompletionResponseFormatJSONSchema) SetStrict(val *bool) {
	p.Strict = val
}

func (p *ChatCompletionResponseFormatJSONSchema) IsSetDescription() bool {
	return p.Description != nil
}

func (p *ChatCompletionResponseFormatJSONSchema) IsSetStrict() bool {
	return p.Strict != nil
}

func (p *ChatCompletionResponseFormatJSONSchema) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatCompletionResponseFormatJSONSchema(%+v)", *p)
}

var fieldIDToName_ChatCompletionResponseFormatJSONSchema = map[int16]string{
	1: "name",
	2: "description",
	3: "schema",
	4: "strict",
}

type ChatCompletionResponseFormat struct {
	Type       ChatCompletionResponseFormatType        `thrift:"type,1,required" frugal:"1,required,ChatCompletionResponseFormatType" json:"type"`
	JsonSchema *ChatCompletionResponseFormatJSONSchema `thrift:"json_schema,2,optional" frugal:"2,optional,ChatCompletionResponseFormatJSONSchema" json:"json_schema,omitempty"`
}

func NewChatCompletionResponseFormat() *ChatCompletionResponseFormat {
	return &ChatCompletionResponseFormat{}
}

func (p *ChatCompletionResponseFormat) InitDefault() {
}

func (p *ChatCompletionResponseFormat) GetType() (v ChatCompletionResponseFormatType) {
	return p.Type
}

var ChatCompletionResponseFormat_JsonSchema_DEFAULT *ChatCompletionResponseFormatJSONSchema

func (p *ChatCompletionResponseFormat) GetJsonSchema() (v *ChatCompletionResponseFormatJSONSchema) {
	if !p.IsSetJsonSchema() {
		return ChatCompletionResponseFormat_JsonSchema_DEFAULT
	}
	return p.JsonSchema
}
func (p *ChatCompletionResponseFormat) SetType(val ChatCompletionResponseFormatType) {
	p.Type = val
}
func (p *ChatCompletionResponseFormat) SetJsonSchema(val *ChatCompletionResponseFormatJSONSchema) {
	p.JsonSchema = val
}

func (p *ChatCompletionResponseFormat) IsSetJsonSchema() bool {
	return p.JsonSchema != nil
}

func (p *ChatCompletionResponseFormat) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatCompletionResponseFormat(%+v)", *p)
}

var fieldIDToName_ChatCompletionResponseFormat = map[int16]string{
	1: "type",
	2: "json_schema",
}

type ChatCompletionRequest struct {
	Model             string                        `thrift:"model,1,required" frugal:"1,required,string" json:"model"`
	Messages          []*ChatCompletionMessage      `thrift:"messages,2,required" frugal:"2,required,list<ChatCompletionMessage>" json:"messages"`
	MaxTokens         *int32                        `thrift:"max_tokens,3,optional" frugal:"3,optional,i32" json:"max_tokens,omitempty"`
	Temperature       *float64                      `thrift:"temperature,4,optional" frugal:"4,optional,double" json:"temperature,omitempty"`
	TopP              *float64                      `thrift:"top_p,5,optional" frugal:"5,optional,double" json:"top_p,omitempty"`
	N                 *int32                        `thrift:"n,6,optional" frugal:"6,optional,i32" json:"n,omitempty"`
	Stream            *bool                         `thrift:"stream,7,optional" frugal:"7,optional,bool" json:"stream,omitempty"`
	Stop              []string                      `thrift:"stop,8,optional" frugal:"8,optional,list<string>" json:"stop,omitempty"`
	PresencePenalty   *float64                      `thrift:"presence_penalty,9,optional" frugal:"9,optional,double" json:"presence_penalty,omitempty"`
	ResponseFormat    *ChatCompletionResponseFormat `thrift:"response_format,10,optional" frugal:"10,optional,ChatCompletionResponseFormat" json:"response_format,omitempty"`
	Seed              *int32                        `thrift:"seed,11,optional" frugal:"11,optional,i32" json:"seed,omitempty"`
	FrequencyPenalty  *float64                      `thrift:"frequency_penalty,12,optional" frugal:"12,optional,double" json:"frequency_penalty,omitempty"`
	LogitBias         map[string]int32              `thrift:"logit_bias,13,optional" frugal:"13,optional,map<string:i32>" json:"logit_bias,omitempty"`
	Logprobs          *bool                         `thrift:"logprobs,14,optional" frugal:"14,optional,bool" json:"logprobs,omitempty"`
	TopLogprobs       *int32                        `thrift:"top_logprobs,15,optional" frugal:"15,optional,i32" json:"top_logprobs,omitempty"`
	User              *string                       `thrift:"user,16,optional" frugal:"16,optional,string" json:"user,omitempty"`
	Functions         []*FunctionDefinition         `thrift:"functions,17,optional" frugal:"17,optional,list<FunctionDefinition>" json:"functions,omitempty"`
	FunctionCall      *string                       `thrift:"function_call,18,optional" frugal:"18,optional,string" json:"function_call,omitempty"`
	Tools             []*Tool                       `thrift:"tools,19,optional" frugal:"19,optional,list<Tool>" json:"tools,omitempty"`
	ToolChoice        *ToolChoice                   `thrift:"tool_choice,20,optional" frugal:"20,optional,ToolChoice" json:"tool_choice,omitempty"`
	StreamOptions     *StreamOptions                `thrift:"stream_options,21,optional" frugal:"21,optional,StreamOptions" json:"stream_options,omitempty"`
	ParallelToolCalls *bool                         `thrift:"parallel_tool_calls,22,optional" frugal:"22,optional,bool" json:"parallel_tool_calls,omitempty"`
}

func NewChatCompletionRequest() *ChatCompletionRequest {
	return &ChatCompletionRequest{}
}

func (p *ChatCompletionRequest) InitDefault() {
}

func (p *ChatCompletionRequest) GetModel() (v string) {
	return p.Model
}

func (p *ChatCompletionRequest) GetMessages() (v []*ChatCompletionMessage) {
	return p.Messages
}

var ChatCompletionRequest_MaxTokens_DEFAULT int32

func (p *ChatCompletionRequest) GetMaxTokens() (v int32) {
	if !p.IsSetMaxTokens() {
		return ChatCompletionRequest_MaxTokens_DEFAULT
	}
	return *p.MaxTokens
}

var ChatCompletionRequest_Temperature_DEFAULT float64

func (p *ChatCompletionRequest) GetTemperature() (v float64) {
	if !p.IsSetTemperature() {
		return ChatCompletionRequest_Temperature_DEFAULT
	}
	return *p.Temperature
}

var ChatCompletionRequest_TopP_DEFAULT float64

func (p *ChatCompletionRequest) GetTopP() (v float64) {
	if !p.IsSetTopP() {
		return ChatCompletionRequest_TopP_DEFAULT
	}
	return *p.TopP
}

var ChatCompletionRequest_N_DEFAULT int32

func (p *ChatCompletionRequest) GetN() (v int32) {
	if !p.IsSetN() {
		return ChatCompletionRequest_N_DEFAULT
	}
	return *p.N
}

var ChatCompletionRequest_Stream_DEFAULT bool

func (p *ChatCompletionRequest) GetStream() (v bool) {
	if !p.IsSetStream() {
		return ChatCompletionRequest_Stream_DEFAULT
	}
	return *p.Stream
}

var ChatCompletionRequest_Stop_DEFAULT []string

func (p *ChatCompletionRequest) GetStop() (v []string) {
	if !p.IsSetStop() {
		return ChatCompletionRequest_Stop_DEFAULT
	}
	return p.Stop
}

var ChatCompletionRequest_PresencePenalty_DEFAULT float64

func (p *ChatCompletionRequest) GetPresencePenalty() (v float64) {
	if !p.IsSetPresencePenalty() {
		return ChatCompletionRequest_PresencePenalty_DEFAULT
	}
	return *p.PresencePenalty
}

var ChatCompletionRequest_ResponseFormat_DEFAULT *ChatCompletionResponseFormat

func (p *ChatCompletionRequest) GetResponseFormat() (v *ChatCompletionResponseFormat) {
	if !p.IsSetResponseFormat() {
		return ChatCompletionRequest_ResponseFormat_DEFAULT
	}
	return p.ResponseFormat
}

var ChatCompletionRequest_Seed_DEFAULT int32

func (p *ChatCompletionRequest) GetSeed() (v int32) {
	if !p.IsSetSeed() {
		return ChatCompletionRequest_Seed_DEFAULT
	}
	return *p.Seed
}

var ChatCompletionRequest_FrequencyPenalty_DEFAULT float64

func (p *ChatCompletionRequest) GetFrequencyPenalty() (v float64) {
	if !p.IsSetFrequencyPenalty() {
		return ChatCompletionRequest_FrequencyPenalty_DEFAULT
	}
	return *p.FrequencyPenalty
}

var ChatCompletionRequest_LogitBias_DEFAULT map[string]int32

func (p *ChatCompletionRequest) GetLogitBias() (v map[string]int32) {
	if !p.IsSetLogitBias() {
		return ChatCompletionRequest_LogitBias_DEFAULT
	}
	return p.LogitBias
}

var ChatCompletionRequest_Logprobs_DEFAULT bool

func (p *ChatCompletionRequest) GetLogprobs() (v bool) {
	if !p.IsSetLogprobs() {
		return ChatCompletionRequest_Logprobs_DEFAULT
	}
	return *p.Logprobs
}

var ChatCompletionRequest_TopLogprobs_DEFAULT int32

func (p *ChatCompletionRequest) GetTopLogprobs() (v int32) {
	if !p.IsSetTopLogprobs() {
		return ChatCompletionRequest_TopLogprobs_DEFAULT
	}
	return *p.TopLogprobs
}

var ChatCompletionRequest_User_DEFAULT string

func (p *ChatCompletionRequest) GetUser() (v string) {
	if !p.IsSetUser() {
		return ChatCompletionRequest_User_DEFAULT
	}
	return *p.User
}

var ChatCompletionRequest_Functions_DEFAULT []*FunctionDefinition

func (p *ChatCompletionRequest) GetFunctions() (v []*FunctionDefinition) {
	if !p.IsSetFunctions() {
		return ChatCompletionRequest_Functions_DEFAULT
	}
	return p.Functions
}

var ChatCompletionRequest_FunctionCall_DEFAULT string

func (p *ChatCompletionRequest) GetFunctionCall() (v string) {
	if !p.IsSetFunctionCall() {
		return ChatCompletionRequest_FunctionCall_DEFAULT
	}
	return *p.FunctionCall
}

var ChatCompletionRequest_Tools_DEFAULT []*Tool

func (p *ChatCompletionRequest) GetTools() (v []*Tool) {
	if !p.IsSetTools() {
		return ChatCompletionRequest_Tools_DEFAULT
	}
	return p.Tools
}

var ChatCompletionRequest_ToolChoice_DEFAULT *ToolChoice

func (p *ChatCompletionRequest) GetToolChoice() (v *ToolChoice) {
	if !p.IsSetToolChoice() {
		return ChatCompletionRequest_ToolChoice_DEFAULT
	}
	return p.ToolChoice
}

var ChatCompletionRequest_StreamOptions_DEFAULT *StreamOptions

func (p *ChatCompletionRequest) GetStreamOptions() (v *StreamOptions) {
	if !p.IsSetStreamOptions() {
		return ChatCompletionRequest_StreamOptions_DEFAULT
	}
	return p.StreamOptions
}

var ChatCompletionRequest_ParallelToolCalls_DEFAULT bool

func (p *ChatCompletionRequest) GetParallelToolCalls() (v bool) {
	if !p.IsSetParallelToolCalls() {
		return ChatCompletionRequest_ParallelToolCalls_DEFAULT
	}
	return *p.ParallelToolCalls
}
func (p *ChatCompletionRequest) SetModel(val string) {
	p.Model = val
}
func (p *ChatCompletionRequest) SetMessages(val []*ChatCompletionMessage) {
	p.Messages = val
}
func (p *ChatCompletionRequest) SetMaxTokens(val *int32) {
	p.MaxTokens = val
}
func (p *ChatCompletionRequest) SetTemperature(val *float64) {
	p.Temperature = val
}
func (p *ChatCompletionRequest) SetTopP(val *float64) {
	p.TopP = val
}
func (p *ChatCompletionRequest) SetN(val *int32) {
	p.N = val
}
func (p *ChatCompletionRequest) SetStream(val *bool) {
	p.Stream = val
}
func (p *ChatCompletionRequest) SetStop(val []string) {
	p.Stop = val
}
func (p *ChatCompletionRequest) SetPresencePenalty(val *float64) {
	p.PresencePenalty = val
}
func (p *ChatCompletionRequest) SetResponseFormat(val *ChatCompletionResponseFormat) {
	p.ResponseFormat = val
}
func (p *ChatCompletionRequest) SetSeed(val *int32) {
	p.Seed = val
}
func (p *ChatCompletionRequest) SetFrequencyPenalty(val *float64) {
	p.FrequencyPenalty = val
}
func (p *ChatCompletionRequest) SetLogitBias(val map[string]int32) {
	p.LogitBias = val
}
func (p *ChatCompletionRequest) SetLogprobs(val *bool) {
	p.Logprobs = val
}
func (p *ChatCompletionRequest) SetTopLogprobs(val *int32) {
	p.TopLogprobs = val
}
func (p *ChatCompletionRequest) SetUser(val *string) {
	p.User = val
}
func (p *ChatCompletionRequest) SetFunctions(val []*FunctionDefinition) {
	p.Functions = val
}
func (p *ChatCompletionRequest) SetFunctionCall(val *string) {
	p.FunctionCall = val
}
func (p *ChatCompletionRequest) SetTools(val []*Tool) {
	p.Tools = val
}
func (p *ChatCompletionRequest) SetToolChoice(val *ToolChoice) {
	p.ToolChoice = val
}
func (p *ChatCompletionRequest) SetStreamOptions(val *StreamOptions) {
	p.StreamOptions = val
}
func (p *ChatCompletionRequest) SetParallelToolCalls(val *bool) {
	p.ParallelToolCalls = val
}

func (p *ChatCompletionRequest) IsSetMaxTokens() bool {
	return p.MaxTokens != nil
}

func (p *ChatCompletionRequest) IsSetTemperature() bool {
	return p.Temperature != nil
}

func (p *ChatCompletionRequest) IsSetTopP() bool {
	return p.TopP != nil
}

func (p *ChatCompletionRequest) IsSetN() bool {
	return p.N != nil
}

func (p *ChatCompletionRequest) IsSetStream() bool {
	return p.Stream != nil
}

func (p *ChatCompletionRequest) IsSetStop() bool {
	return p.Stop != nil
}

func (p *ChatCompletionRequest) IsSetPresencePenalty() bool {
	return p.PresencePenalty != nil
}

func (p *ChatCompletionRequest) IsSetResponseFormat() bool {
	return p.ResponseFormat != nil
}

func (p *ChatCompletionRequest) IsSetSeed() bool {
	return p.Seed != nil
}

func (p *ChatCompletionRequest) IsSetFrequencyPenalty() bool {
	return p.FrequencyPenalty != nil
}

func (p *ChatCompletionRequest) IsSetLogitBias() bool {
	return p.LogitBias != nil
}

func (p *ChatCompletionRequest) IsSetLogprobs() bool {
	return p.Logprobs != nil
}

func (p *ChatCompletionRequest) IsSetTopLogprobs() bool {
	return p.TopLogprobs != nil
}

func (p *ChatCompletionRequest) IsSetUser() bool {
	return p.User != nil
}

func (p *ChatCompletionRequest) IsSetFunctions() bool {
	return p.Functions != nil
}

func (p *ChatCompletionRequest) IsSetFunctionCall() bool {
	return p.FunctionCall != nil
}

func (p *ChatCompletionRequest) IsSetTools() bool {
	return p.Tools != nil
}

func (p *ChatCompletionRequest) IsSetToolChoice() bool {
	return p.ToolChoice != nil
}

func (p *ChatCompletionRequest) IsSetStreamOptions() bool {
	return p.StreamOptions != nil
}

func (p *ChatCompletionRequest) IsSetParallelToolCalls() bool {
	return p.ParallelToolCalls != nil
}

func (p *ChatCompletionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatCompletionRequest(%+v)", *p)
}

var fieldIDToName_ChatCompletionRequest = map[int16]string{
	1:  "model",
	2:  "messages",
	3:  "max_tokens",
	4:  "temperature",
	5:  "top_p",
	6:  "n",
	7:  "stream",
	8:  "stop",
	9:  "presence_penalty",
	10: "response_format",
	11: "seed",
	12: "frequency_penalty",
	13: "logit_bias",
	14: "logprobs",
	15: "top_logprobs",
	16: "user",
	17: "functions",
	18: "function_call",
	19: "tools",
	20: "tool_choice",
	21: "stream_options",
	22: "parallel_tool_calls",
}

type Usage struct {
	PromptTokens     int32 `thrift:"prompt_tokens,1" frugal:"1,default,i32" json:"prompt_tokens"`
	CompletionTokens int32 `thrift:"completion_tokens,2" frugal:"2,default,i32" json:"completion_tokens"`
	TotalTokens      int32 `thrift:"total_tokens,3" frugal:"3,default,i32" json:"total_tokens"`
}

func NewUsage() *Usage {
	return &Usage{}
}

func (p *Usage) InitDefault() {
}

func (p *Usage) GetPromptTokens() (v int32) {
	return p.PromptTokens
}

func (p *Usage) GetCompletionTokens() (v int32) {
	return p.CompletionTokens
}

func (p *Usage) GetTotalTokens() (v int32) {
	return p.TotalTokens
}
func (p *Usage) SetPromptTokens(val int32) {
	p.PromptTokens = val
}
func (p *Usage) SetCompletionTokens(val int32) {
	p.CompletionTokens = val
}
func (p *Usage) SetTotalTokens(val int32) {
	p.TotalTokens = val
}

func (p *Usage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Usage(%+v)", *p)
}

var fieldIDToName_Usage = map[int16]string{
	1: "prompt_tokens",
	2: "completion_tokens",
	3: "total_tokens",
}

type ChatCompletionStreamChoiceDelta struct {
	Content      *string       `thrift:"content,1,optional" frugal:"1,optional,string" json:"content,omitempty"`
	Role         *string       `thrift:"role,2,optional" frugal:"2,optional,string" json:"role,omitempty"`
	FunctionCall *FunctionCall `thrift:"function_call,3,optional" frugal:"3,optional,FunctionCall" json:"function_call,omitempty"`
	ToolCalls    []*ToolCall   `thrift:"tool_calls,4,optional" frugal:"4,optional,list<ToolCall>" json:"tool_calls,omitempty"`
}

func NewChatCompletionStreamChoiceDelta() *ChatCompletionStreamChoiceDelta {
	return &ChatCompletionStreamChoiceDelta{}
}

func (p *ChatCompletionStreamChoiceDelta) InitDefault() {
}

var ChatCompletionStreamChoiceDelta_Content_DEFAULT string

func (p *ChatCompletionStreamChoiceDelta) GetContent() (v string) {
	if !p.IsSetContent() {
		return ChatCompletionStreamChoiceDelta_Content_DEFAULT
	}
	return *p.Content
}

var ChatCompletionStreamChoiceDelta_Role_DEFAULT string

func (p *ChatCompletionStreamChoiceDelta) GetRole() (v string) {
	if !p.IsSetRole() {
		return ChatCompletionStreamChoiceDelta_Role_DEFAULT
	}
	return *p.Role
}

var ChatCompletionStreamChoiceDelta_FunctionCall_DEFAULT *FunctionCall

func (p *ChatCompletionStreamChoiceDelta) GetFunctionCall() (v *FunctionCall) {
	if !p.IsSetFunctionCall() {
		return ChatCompletionStreamChoiceDelta_FunctionCall_DEFAULT
	}
	return p.FunctionCall
}

var ChatCompletionStreamChoiceDelta_ToolCalls_DEFAULT []*ToolCall

func (p *ChatCompletionStreamChoiceDelta) GetToolCalls() (v []*ToolCall) {
	if !p.IsSetToolCalls() {
		return ChatCompletionStreamChoiceDelta_ToolCalls_DEFAULT
	}
	return p.ToolCalls
}
func (p *ChatCompletionStreamChoiceDelta) SetContent(val *string) {
	p.Content = val
}
func (p *ChatCompletionStreamChoiceDelta) SetRole(val *string) {
	p.Role = val
}
func (p *ChatCompletionStreamChoiceDelta) SetFunctionCall(val *FunctionCall) {
	p.FunctionCall = val
}
func (p *ChatCompletionStreamChoiceDelta) SetToolCalls(val []*ToolCall) {
	p.ToolCalls = val
}

func (p *ChatCompletionStreamChoiceDelta) IsSetContent() bool {
	return p.Content != nil
}

func (p *ChatCompletionStreamChoiceDelta) IsSetRole() bool {
	return p.Role != nil
}

func (p *ChatCompletionStreamChoiceDelta) IsSetFunctionCall() bool {
	return p.FunctionCall != nil
}

func (p *ChatCompletionStreamChoiceDelta) IsSetToolCalls() bool {
	return p.ToolCalls != nil
}

func (p *ChatCompletionStreamChoiceDelta) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatCompletionStreamChoiceDelta(%+v)", *p)
}

var fieldIDToName_ChatCompletionStreamChoiceDelta = map[int16]string{
	1: "content",
	2: "role",
	3: "function_call",
	4: "tool_calls",
}

type ChatCompletionStreamChoice struct {
	Index                int32                            `thrift:"index,1" frugal:"1,default,i32" json:"index"`
	Delta                *ChatCompletionStreamChoiceDelta `thrift:"delta,2" frugal:"2,default,ChatCompletionStreamChoiceDelta" json:"delta"`
	FinishReason         string                           `thrift:"finish_reason,3" frugal:"3,default,string" json:"finish_reason"`
	ContentFilterResults *ContentFilterResults            `thrift:"content_filter_results,4,optional" frugal:"4,optional,ContentFilterResults" json:"content_filter_results,omitempty"`
}

func NewChatCompletionStreamChoice() *ChatCompletionStreamChoice {
	return &ChatCompletionStreamChoice{}
}

func (p *ChatCompletionStreamChoice) InitDefault() {
}

func (p *ChatCompletionStreamChoice) GetIndex() (v int32) {
	return p.Index
}

var ChatCompletionStreamChoice_Delta_DEFAULT *ChatCompletionStreamChoiceDelta

func (p *ChatCompletionStreamChoice) GetDelta() (v *ChatCompletionStreamChoiceDelta) {
	if !p.IsSetDelta() {
		return ChatCompletionStreamChoice_Delta_DEFAULT
	}
	return p.Delta
}

func (p *ChatCompletionStreamChoice) GetFinishReason() (v string) {
	return p.FinishReason
}

var ChatCompletionStreamChoice_ContentFilterResults_DEFAULT *ContentFilterResults

func (p *ChatCompletionStreamChoice) GetContentFilterResults() (v *ContentFilterResults) {
	if !p.IsSetContentFilterResults() {
		return ChatCompletionStreamChoice_ContentFilterResults_DEFAULT
	}
	return p.ContentFilterResults
}
func (p *ChatCompletionStreamChoice) SetIndex(val int32) {
	p.Index = val
}
func (p *ChatCompletionStreamChoice) SetDelta(val *ChatCompletionStreamChoiceDelta) {
	p.Delta = val
}
func (p *ChatCompletionStreamChoice) SetFinishReason(val string) {
	p.FinishReason = val
}
func (p *ChatCompletionStreamChoice) SetContentFilterResults(val *ContentFilterResults) {
	p.ContentFilterResults = val
}

func (p *ChatCompletionStreamChoice) IsSetDelta() bool {
	return p.Delta != nil
}

func (p *ChatCompletionStreamChoice) IsSetContentFilterResults() bool {
	return p.ContentFilterResults != nil
}

func (p *ChatCompletionStreamChoice) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatCompletionStreamChoice(%+v)", *p)
}

var fieldIDToName_ChatCompletionStreamChoice = map[int16]string{
	1: "index",
	2: "delta",
	3: "finish_reason",
	4: "content_filter_results",
}

type PromptFilterResult_ struct {
	Index                int32                 `thrift:"index,1" frugal:"1,default,i32" json:"index"`
	ContentFilterResults *ContentFilterResults `thrift:"content_filter_results,2,optional" frugal:"2,optional,ContentFilterResults" json:"content_filter_results,omitempty"`
}

func NewPromptFilterResult_() *PromptFilterResult_ {
	return &PromptFilterResult_{}
}

func (p *PromptFilterResult_) InitDefault() {
}

func (p *PromptFilterResult_) GetIndex() (v int32) {
	return p.Index
}

var PromptFilterResult__ContentFilterResults_DEFAULT *ContentFilterResults

func (p *PromptFilterResult_) GetContentFilterResults() (v *ContentFilterResults) {
	if !p.IsSetContentFilterResults() {
		return PromptFilterResult__ContentFilterResults_DEFAULT
	}
	return p.ContentFilterResults
}
func (p *PromptFilterResult_) SetIndex(val int32) {
	p.Index = val
}
func (p *PromptFilterResult_) SetContentFilterResults(val *ContentFilterResults) {
	p.ContentFilterResults = val
}

func (p *PromptFilterResult_) IsSetContentFilterResults() bool {
	return p.ContentFilterResults != nil
}

func (p *PromptFilterResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PromptFilterResult_(%+v)", *p)
}

var fieldIDToName_PromptFilterResult_ = map[int16]string{
	1: "index",
	2: "content_filter_results",
}

type ChatCompletionStreamResponse struct {
	Id                  string                        `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Object              string                        `thrift:"object,2" frugal:"2,default,string" json:"object"`
	Created             int64                         `thrift:"created,3" frugal:"3,default,i64" json:"created"`
	Model               string                        `thrift:"model,4" frugal:"4,default,string" json:"model"`
	Choices             []*ChatCompletionStreamChoice `thrift:"choices,5" frugal:"5,default,list<ChatCompletionStreamChoice>" json:"choices"`
	SystemFingerprint   string                        `thrift:"system_fingerprint,6" frugal:"6,default,string" json:"system_fingerprint"`
	PromptAnnotations   []*PromptAnnotation           `thrift:"prompt_annotations,7,optional" frugal:"7,optional,list<PromptAnnotation>" json:"prompt_annotations,omitempty"`
	PromptFilterResults []*PromptFilterResult_        `thrift:"prompt_filter_results,8,optional" frugal:"8,optional,list<PromptFilterResult_>" json:"prompt_filter_results,omitempty"`
	Usage               *Usage                        `thrift:"usage,9,optional" frugal:"9,optional,Usage" json:"usage,omitempty"`
}

func NewChatCompletionStreamResponse() *ChatCompletionStreamResponse {
	return &ChatCompletionStreamResponse{}
}

func (p *ChatCompletionStreamResponse) InitDefault() {
}

func (p *ChatCompletionStreamResponse) GetId() (v string) {
	return p.Id
}

func (p *ChatCompletionStreamResponse) GetObject() (v string) {
	return p.Object
}

func (p *ChatCompletionStreamResponse) GetCreated() (v int64) {
	return p.Created
}

func (p *ChatCompletionStreamResponse) GetModel() (v string) {
	return p.Model
}

func (p *ChatCompletionStreamResponse) GetChoices() (v []*ChatCompletionStreamChoice) {
	return p.Choices
}

func (p *ChatCompletionStreamResponse) GetSystemFingerprint() (v string) {
	return p.SystemFingerprint
}

var ChatCompletionStreamResponse_PromptAnnotations_DEFAULT []*PromptAnnotation

func (p *ChatCompletionStreamResponse) GetPromptAnnotations() (v []*PromptAnnotation) {
	if !p.IsSetPromptAnnotations() {
		return ChatCompletionStreamResponse_PromptAnnotations_DEFAULT
	}
	return p.PromptAnnotations
}

var ChatCompletionStreamResponse_PromptFilterResults_DEFAULT []*PromptFilterResult_

func (p *ChatCompletionStreamResponse) GetPromptFilterResults() (v []*PromptFilterResult_) {
	if !p.IsSetPromptFilterResults() {
		return ChatCompletionStreamResponse_PromptFilterResults_DEFAULT
	}
	return p.PromptFilterResults
}

var ChatCompletionStreamResponse_Usage_DEFAULT *Usage

func (p *ChatCompletionStreamResponse) GetUsage() (v *Usage) {
	if !p.IsSetUsage() {
		return ChatCompletionStreamResponse_Usage_DEFAULT
	}
	return p.Usage
}
func (p *ChatCompletionStreamResponse) SetId(val string) {
	p.Id = val
}
func (p *ChatCompletionStreamResponse) SetObject(val string) {
	p.Object = val
}
func (p *ChatCompletionStreamResponse) SetCreated(val int64) {
	p.Created = val
}
func (p *ChatCompletionStreamResponse) SetModel(val string) {
	p.Model = val
}
func (p *ChatCompletionStreamResponse) SetChoices(val []*ChatCompletionStreamChoice) {
	p.Choices = val
}
func (p *ChatCompletionStreamResponse) SetSystemFingerprint(val string) {
	p.SystemFingerprint = val
}
func (p *ChatCompletionStreamResponse) SetPromptAnnotations(val []*PromptAnnotation) {
	p.PromptAnnotations = val
}
func (p *ChatCompletionStreamResponse) SetPromptFilterResults(val []*PromptFilterResult_) {
	p.PromptFilterResults = val
}
func (p *ChatCompletionStreamResponse) SetUsage(val *Usage) {
	p.Usage = val
}

func (p *ChatCompletionStreamResponse) IsSetPromptAnnotations() bool {
	return p.PromptAnnotations != nil
}

func (p *ChatCompletionStreamResponse) IsSetPromptFilterResults() bool {
	return p.PromptFilterResults != nil
}

func (p *ChatCompletionStreamResponse) IsSetUsage() bool {
	return p.Usage != nil
}

func (p *ChatCompletionStreamResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatCompletionStreamResponse(%+v)", *p)
}

var fieldIDToName_ChatCompletionStreamResponse = map[int16]string{
	1: "id",
	2: "object",
	3: "created",
	4: "model",
	5: "choices",
	6: "system_fingerprint",
	7: "prompt_annotations",
	8: "prompt_filter_results",
	9: "usage",
}
