// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package modelsvc

import (
	"context"
	"fmt"
	"github.com/aiagt/aiagt/kitex_gen/base"
	"github.com/aiagt/aiagt/kitex_gen/openai"
	"github.com/cloudwego/kitex/pkg/streaming"
)

type ChatReq struct {
	Token     string                        `thrift:"token,1,required" frugal:"1,required,string" json:"token"`
	ModelId   int64                         `thrift:"model_id,2,required" frugal:"2,required,i64" json:"model_id"`
	OpenaiReq *openai.ChatCompletionRequest `thrift:"openai_req,3,required" frugal:"3,required,openai.ChatCompletionRequest" json:"openai_req"`
}

func NewChatReq() *ChatReq {
	return &ChatReq{}
}

func (p *ChatReq) InitDefault() {
}

func (p *ChatReq) GetToken() (v string) {
	return p.Token
}

func (p *ChatReq) GetModelId() (v int64) {
	return p.ModelId
}

var ChatReq_OpenaiReq_DEFAULT *openai.ChatCompletionRequest

func (p *ChatReq) GetOpenaiReq() (v *openai.ChatCompletionRequest) {
	if !p.IsSetOpenaiReq() {
		return ChatReq_OpenaiReq_DEFAULT
	}
	return p.OpenaiReq
}
func (p *ChatReq) SetToken(val string) {
	p.Token = val
}
func (p *ChatReq) SetModelId(val int64) {
	p.ModelId = val
}
func (p *ChatReq) SetOpenaiReq(val *openai.ChatCompletionRequest) {
	p.OpenaiReq = val
}

func (p *ChatReq) IsSetOpenaiReq() bool {
	return p.OpenaiReq != nil
}

func (p *ChatReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatReq(%+v)", *p)
}

var fieldIDToName_ChatReq = map[int16]string{
	1: "token",
	2: "model_id",
	3: "openai_req",
}

type ChatResp struct {
	OpenaiResp *openai.ChatCompletionStreamResponse `thrift:"openai_resp,1,required" frugal:"1,required,openai.ChatCompletionStreamResponse" json:"openai_resp"`
}

func NewChatResp() *ChatResp {
	return &ChatResp{}
}

func (p *ChatResp) InitDefault() {
}

var ChatResp_OpenaiResp_DEFAULT *openai.ChatCompletionStreamResponse

func (p *ChatResp) GetOpenaiResp() (v *openai.ChatCompletionStreamResponse) {
	if !p.IsSetOpenaiResp() {
		return ChatResp_OpenaiResp_DEFAULT
	}
	return p.OpenaiResp
}
func (p *ChatResp) SetOpenaiResp(val *openai.ChatCompletionStreamResponse) {
	p.OpenaiResp = val
}

func (p *ChatResp) IsSetOpenaiResp() bool {
	return p.OpenaiResp != nil
}

func (p *ChatResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatResp(%+v)", *p)
}

var fieldIDToName_ChatResp = map[int16]string{
	1: "openai_resp",
}

type GenTokenReq struct {
	AppId          int64  `thrift:"app_id,1,required" frugal:"1,required,i64" json:"app_id"`
	PluginId       *int64 `thrift:"plugin_id,2,optional" frugal:"2,optional,i64" json:"plugin_id,omitempty"`
	ConversationId int64  `thrift:"conversation_id,3,required" frugal:"3,required,i64" json:"conversation_id"`
	CallLimit      int32  `thrift:"call_limit,4,required" frugal:"4,required,i32" json:"call_limit"`
}

func NewGenTokenReq() *GenTokenReq {
	return &GenTokenReq{}
}

func (p *GenTokenReq) InitDefault() {
}

func (p *GenTokenReq) GetAppId() (v int64) {
	return p.AppId
}

var GenTokenReq_PluginId_DEFAULT int64

func (p *GenTokenReq) GetPluginId() (v int64) {
	if !p.IsSetPluginId() {
		return GenTokenReq_PluginId_DEFAULT
	}
	return *p.PluginId
}

func (p *GenTokenReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *GenTokenReq) GetCallLimit() (v int32) {
	return p.CallLimit
}
func (p *GenTokenReq) SetAppId(val int64) {
	p.AppId = val
}
func (p *GenTokenReq) SetPluginId(val *int64) {
	p.PluginId = val
}
func (p *GenTokenReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *GenTokenReq) SetCallLimit(val int32) {
	p.CallLimit = val
}

func (p *GenTokenReq) IsSetPluginId() bool {
	return p.PluginId != nil
}

func (p *GenTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GenTokenReq(%+v)", *p)
}

var fieldIDToName_GenTokenReq = map[int16]string{
	1: "app_id",
	2: "plugin_id",
	3: "conversation_id",
	4: "call_limit",
}

type GenTokenResp struct {
	Token     string     `thrift:"token,1,required" frugal:"1,required,string" json:"token"`
	ExpiredAt *base.Time `thrift:"expired_at,2,required" frugal:"2,required,base.Time" json:"expired_at"`
}

func NewGenTokenResp() *GenTokenResp {
	return &GenTokenResp{}
}

func (p *GenTokenResp) InitDefault() {
}

func (p *GenTokenResp) GetToken() (v string) {
	return p.Token
}

var GenTokenResp_ExpiredAt_DEFAULT *base.Time

func (p *GenTokenResp) GetExpiredAt() (v *base.Time) {
	if !p.IsSetExpiredAt() {
		return GenTokenResp_ExpiredAt_DEFAULT
	}
	return p.ExpiredAt
}
func (p *GenTokenResp) SetToken(val string) {
	p.Token = val
}
func (p *GenTokenResp) SetExpiredAt(val *base.Time) {
	p.ExpiredAt = val
}

func (p *GenTokenResp) IsSetExpiredAt() bool {
	return p.ExpiredAt != nil
}

func (p *GenTokenResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GenTokenResp(%+v)", *p)
}

var fieldIDToName_GenTokenResp = map[int16]string{
	1: "token",
	2: "expired_at",
}

type Model struct {
	Id          int64    `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Name        string   `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Description string   `thrift:"description,3,required" frugal:"3,required,string" json:"description"`
	Source      string   `thrift:"source,4,required" frugal:"4,required,string" json:"source"`
	ModelKey    string   `thrift:"model_key,5,required" frugal:"5,required,string" json:"model_key"`
	Logo        string   `thrift:"logo,6,required" frugal:"6,required,string" json:"logo"`
	InputPrice  string   `thrift:"input_price,7,required" frugal:"7,required,string" json:"input_price"`
	OutputPrice string   `thrift:"output_price,8,required" frugal:"8,required,string" json:"output_price"`
	MaxToken    int64    `thrift:"max_token,9,required" frugal:"9,required,i64" json:"max_token"`
	Tags        []string `thrift:"tags,10,required" frugal:"10,required,list<string>" json:"tags"`
}

func NewModel() *Model {
	return &Model{}
}

func (p *Model) InitDefault() {
}

func (p *Model) GetId() (v int64) {
	return p.Id
}

func (p *Model) GetName() (v string) {
	return p.Name
}

func (p *Model) GetDescription() (v string) {
	return p.Description
}

func (p *Model) GetSource() (v string) {
	return p.Source
}

func (p *Model) GetModelKey() (v string) {
	return p.ModelKey
}

func (p *Model) GetLogo() (v string) {
	return p.Logo
}

func (p *Model) GetInputPrice() (v string) {
	return p.InputPrice
}

func (p *Model) GetOutputPrice() (v string) {
	return p.OutputPrice
}

func (p *Model) GetMaxToken() (v int64) {
	return p.MaxToken
}

func (p *Model) GetTags() (v []string) {
	return p.Tags
}
func (p *Model) SetId(val int64) {
	p.Id = val
}
func (p *Model) SetName(val string) {
	p.Name = val
}
func (p *Model) SetDescription(val string) {
	p.Description = val
}
func (p *Model) SetSource(val string) {
	p.Source = val
}
func (p *Model) SetModelKey(val string) {
	p.ModelKey = val
}
func (p *Model) SetLogo(val string) {
	p.Logo = val
}
func (p *Model) SetInputPrice(val string) {
	p.InputPrice = val
}
func (p *Model) SetOutputPrice(val string) {
	p.OutputPrice = val
}
func (p *Model) SetMaxToken(val int64) {
	p.MaxToken = val
}
func (p *Model) SetTags(val []string) {
	p.Tags = val
}

func (p *Model) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Model(%+v)", *p)
}

var fieldIDToName_Model = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "description",
	4:  "source",
	5:  "model_key",
	6:  "logo",
	7:  "input_price",
	8:  "output_price",
	9:  "max_token",
	10: "tags",
}

type CreateModelReq struct {
	Name        string   `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Description string   `thrift:"description,2,required" frugal:"2,required,string" json:"description"`
	Source      string   `thrift:"source,3,required" frugal:"3,required,string" json:"source"`
	ModelKey    string   `thrift:"model_key,4,required" frugal:"4,required,string" json:"model_key"`
	Logo        string   `thrift:"logo,5,required" frugal:"5,required,string" json:"logo"`
	InputPrice  string   `thrift:"input_price,6,required" frugal:"6,required,string" json:"input_price"`
	OutputPrice string   `thrift:"output_price,7,required" frugal:"7,required,string" json:"output_price"`
	MaxToken    int64    `thrift:"max_token,8,required" frugal:"8,required,i64" json:"max_token"`
	Tags        []string `thrift:"tags,9,required" frugal:"9,required,list<string>" json:"tags"`
}

func NewCreateModelReq() *CreateModelReq {
	return &CreateModelReq{}
}

func (p *CreateModelReq) InitDefault() {
}

func (p *CreateModelReq) GetName() (v string) {
	return p.Name
}

func (p *CreateModelReq) GetDescription() (v string) {
	return p.Description
}

func (p *CreateModelReq) GetSource() (v string) {
	return p.Source
}

func (p *CreateModelReq) GetModelKey() (v string) {
	return p.ModelKey
}

func (p *CreateModelReq) GetLogo() (v string) {
	return p.Logo
}

func (p *CreateModelReq) GetInputPrice() (v string) {
	return p.InputPrice
}

func (p *CreateModelReq) GetOutputPrice() (v string) {
	return p.OutputPrice
}

func (p *CreateModelReq) GetMaxToken() (v int64) {
	return p.MaxToken
}

func (p *CreateModelReq) GetTags() (v []string) {
	return p.Tags
}
func (p *CreateModelReq) SetName(val string) {
	p.Name = val
}
func (p *CreateModelReq) SetDescription(val string) {
	p.Description = val
}
func (p *CreateModelReq) SetSource(val string) {
	p.Source = val
}
func (p *CreateModelReq) SetModelKey(val string) {
	p.ModelKey = val
}
func (p *CreateModelReq) SetLogo(val string) {
	p.Logo = val
}
func (p *CreateModelReq) SetInputPrice(val string) {
	p.InputPrice = val
}
func (p *CreateModelReq) SetOutputPrice(val string) {
	p.OutputPrice = val
}
func (p *CreateModelReq) SetMaxToken(val int64) {
	p.MaxToken = val
}
func (p *CreateModelReq) SetTags(val []string) {
	p.Tags = val
}

func (p *CreateModelReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateModelReq(%+v)", *p)
}

var fieldIDToName_CreateModelReq = map[int16]string{
	1: "name",
	2: "description",
	3: "source",
	4: "model_key",
	5: "logo",
	6: "input_price",
	7: "output_price",
	8: "max_token",
	9: "tags",
}

type UpdateModelReq struct {
	Id          int64    `thrift:"id,1,required" frugal:"1,required,i64" path:"id"`
	Name        *string  `thrift:"name,2,optional" frugal:"2,optional,string" json:"name,omitempty"`
	Description *string  `thrift:"description,3,optional" frugal:"3,optional,string" json:"description,omitempty"`
	Source      *string  `thrift:"source,4,optional" frugal:"4,optional,string" json:"source,omitempty"`
	ModelKey    *string  `thrift:"model_key,5,optional" frugal:"5,optional,string" json:"model_key,omitempty"`
	Logo        *string  `thrift:"logo,6,optional" frugal:"6,optional,string" json:"logo,omitempty"`
	InputPrice  *string  `thrift:"input_price,7,optional" frugal:"7,optional,string" json:"input_price,omitempty"`
	OutputPrice *string  `thrift:"output_price,8,optional" frugal:"8,optional,string" json:"output_price,omitempty"`
	MaxToken    *int64   `thrift:"max_token,9,optional" frugal:"9,optional,i64" json:"max_token,omitempty"`
	Tags        []string `thrift:"tags,10,optional" frugal:"10,optional,list<string>" json:"tags,omitempty"`
}

func NewUpdateModelReq() *UpdateModelReq {
	return &UpdateModelReq{}
}

func (p *UpdateModelReq) InitDefault() {
}

func (p *UpdateModelReq) GetId() (v int64) {
	return p.Id
}

var UpdateModelReq_Name_DEFAULT string

func (p *UpdateModelReq) GetName() (v string) {
	if !p.IsSetName() {
		return UpdateModelReq_Name_DEFAULT
	}
	return *p.Name
}

var UpdateModelReq_Description_DEFAULT string

func (p *UpdateModelReq) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return UpdateModelReq_Description_DEFAULT
	}
	return *p.Description
}

var UpdateModelReq_Source_DEFAULT string

func (p *UpdateModelReq) GetSource() (v string) {
	if !p.IsSetSource() {
		return UpdateModelReq_Source_DEFAULT
	}
	return *p.Source
}

var UpdateModelReq_ModelKey_DEFAULT string

func (p *UpdateModelReq) GetModelKey() (v string) {
	if !p.IsSetModelKey() {
		return UpdateModelReq_ModelKey_DEFAULT
	}
	return *p.ModelKey
}

var UpdateModelReq_Logo_DEFAULT string

func (p *UpdateModelReq) GetLogo() (v string) {
	if !p.IsSetLogo() {
		return UpdateModelReq_Logo_DEFAULT
	}
	return *p.Logo
}

var UpdateModelReq_InputPrice_DEFAULT string

func (p *UpdateModelReq) GetInputPrice() (v string) {
	if !p.IsSetInputPrice() {
		return UpdateModelReq_InputPrice_DEFAULT
	}
	return *p.InputPrice
}

var UpdateModelReq_OutputPrice_DEFAULT string

func (p *UpdateModelReq) GetOutputPrice() (v string) {
	if !p.IsSetOutputPrice() {
		return UpdateModelReq_OutputPrice_DEFAULT
	}
	return *p.OutputPrice
}

var UpdateModelReq_MaxToken_DEFAULT int64

func (p *UpdateModelReq) GetMaxToken() (v int64) {
	if !p.IsSetMaxToken() {
		return UpdateModelReq_MaxToken_DEFAULT
	}
	return *p.MaxToken
}

var UpdateModelReq_Tags_DEFAULT []string

func (p *UpdateModelReq) GetTags() (v []string) {
	if !p.IsSetTags() {
		return UpdateModelReq_Tags_DEFAULT
	}
	return p.Tags
}
func (p *UpdateModelReq) SetId(val int64) {
	p.Id = val
}
func (p *UpdateModelReq) SetName(val *string) {
	p.Name = val
}
func (p *UpdateModelReq) SetDescription(val *string) {
	p.Description = val
}
func (p *UpdateModelReq) SetSource(val *string) {
	p.Source = val
}
func (p *UpdateModelReq) SetModelKey(val *string) {
	p.ModelKey = val
}
func (p *UpdateModelReq) SetLogo(val *string) {
	p.Logo = val
}
func (p *UpdateModelReq) SetInputPrice(val *string) {
	p.InputPrice = val
}
func (p *UpdateModelReq) SetOutputPrice(val *string) {
	p.OutputPrice = val
}
func (p *UpdateModelReq) SetMaxToken(val *int64) {
	p.MaxToken = val
}
func (p *UpdateModelReq) SetTags(val []string) {
	p.Tags = val
}

func (p *UpdateModelReq) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdateModelReq) IsSetDescription() bool {
	return p.Description != nil
}

func (p *UpdateModelReq) IsSetSource() bool {
	return p.Source != nil
}

func (p *UpdateModelReq) IsSetModelKey() bool {
	return p.ModelKey != nil
}

func (p *UpdateModelReq) IsSetLogo() bool {
	return p.Logo != nil
}

func (p *UpdateModelReq) IsSetInputPrice() bool {
	return p.InputPrice != nil
}

func (p *UpdateModelReq) IsSetOutputPrice() bool {
	return p.OutputPrice != nil
}

func (p *UpdateModelReq) IsSetMaxToken() bool {
	return p.MaxToken != nil
}

func (p *UpdateModelReq) IsSetTags() bool {
	return p.Tags != nil
}

func (p *UpdateModelReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateModelReq(%+v)", *p)
}

var fieldIDToName_UpdateModelReq = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "description",
	4:  "source",
	5:  "model_key",
	6:  "logo",
	7:  "input_price",
	8:  "output_price",
	9:  "max_token",
	10: "tags",
}

type ListModelReq struct {
	Pagination *base.PaginationReq `thrift:"pagination,1,required" frugal:"1,required,base.PaginationReq" json:"pagination"`
	Name       *string             `thrift:"name,2,optional" frugal:"2,optional,string" query:"name"`
	Source     *string             `thrift:"source,3,optional" frugal:"3,optional,string" query:"source"`
}

func NewListModelReq() *ListModelReq {
	return &ListModelReq{}
}

func (p *ListModelReq) InitDefault() {
}

var ListModelReq_Pagination_DEFAULT *base.PaginationReq

func (p *ListModelReq) GetPagination() (v *base.PaginationReq) {
	if !p.IsSetPagination() {
		return ListModelReq_Pagination_DEFAULT
	}
	return p.Pagination
}

var ListModelReq_Name_DEFAULT string

func (p *ListModelReq) GetName() (v string) {
	if !p.IsSetName() {
		return ListModelReq_Name_DEFAULT
	}
	return *p.Name
}

var ListModelReq_Source_DEFAULT string

func (p *ListModelReq) GetSource() (v string) {
	if !p.IsSetSource() {
		return ListModelReq_Source_DEFAULT
	}
	return *p.Source
}
func (p *ListModelReq) SetPagination(val *base.PaginationReq) {
	p.Pagination = val
}
func (p *ListModelReq) SetName(val *string) {
	p.Name = val
}
func (p *ListModelReq) SetSource(val *string) {
	p.Source = val
}

func (p *ListModelReq) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListModelReq) IsSetName() bool {
	return p.Name != nil
}

func (p *ListModelReq) IsSetSource() bool {
	return p.Source != nil
}

func (p *ListModelReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListModelReq(%+v)", *p)
}

var fieldIDToName_ListModelReq = map[int16]string{
	1: "pagination",
	2: "name",
	3: "source",
}

type ListModelResp struct {
	Pagination *base.PaginationResp `thrift:"pagination,1,required" frugal:"1,required,base.PaginationResp" json:"pagination"`
	Models     []*Model             `thrift:"models,2,required" frugal:"2,required,list<Model>" json:"models"`
}

func NewListModelResp() *ListModelResp {
	return &ListModelResp{}
}

func (p *ListModelResp) InitDefault() {
}

var ListModelResp_Pagination_DEFAULT *base.PaginationResp

func (p *ListModelResp) GetPagination() (v *base.PaginationResp) {
	if !p.IsSetPagination() {
		return ListModelResp_Pagination_DEFAULT
	}
	return p.Pagination
}

func (p *ListModelResp) GetModels() (v []*Model) {
	return p.Models
}
func (p *ListModelResp) SetPagination(val *base.PaginationResp) {
	p.Pagination = val
}
func (p *ListModelResp) SetModels(val []*Model) {
	p.Models = val
}

func (p *ListModelResp) IsSetPagination() bool {
	return p.Pagination != nil
}

func (p *ListModelResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListModelResp(%+v)", *p)
}

var fieldIDToName_ListModelResp = map[int16]string{
	1: "pagination",
	2: "models",
}

type APIKey struct {
	Id      int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Source  string `thrift:"source,2,required" frugal:"2,required,string" json:"source"`
	BaseUrl string `thrift:"base_url,3,required" frugal:"3,required,string" json:"base_url"`
	ApiKey  string `thrift:"api_key,4,required" frugal:"4,required,string" json:"api_key"`
}

func NewAPIKey() *APIKey {
	return &APIKey{}
}

func (p *APIKey) InitDefault() {
}

func (p *APIKey) GetId() (v int64) {
	return p.Id
}

func (p *APIKey) GetSource() (v string) {
	return p.Source
}

func (p *APIKey) GetBaseUrl() (v string) {
	return p.BaseUrl
}

func (p *APIKey) GetApiKey() (v string) {
	return p.ApiKey
}
func (p *APIKey) SetId(val int64) {
	p.Id = val
}
func (p *APIKey) SetSource(val string) {
	p.Source = val
}
func (p *APIKey) SetBaseUrl(val string) {
	p.BaseUrl = val
}
func (p *APIKey) SetApiKey(val string) {
	p.ApiKey = val
}

func (p *APIKey) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("APIKey(%+v)", *p)
}

var fieldIDToName_APIKey = map[int16]string{
	1: "id",
	2: "source",
	3: "base_url",
	4: "api_key",
}

type GetAPIKeyBySourceReq struct {
	Source string `thrift:"source,1,required" frugal:"1,required,string" json:"source"`
}

func NewGetAPIKeyBySourceReq() *GetAPIKeyBySourceReq {
	return &GetAPIKeyBySourceReq{}
}

func (p *GetAPIKeyBySourceReq) InitDefault() {
}

func (p *GetAPIKeyBySourceReq) GetSource() (v string) {
	return p.Source
}
func (p *GetAPIKeyBySourceReq) SetSource(val string) {
	p.Source = val
}

func (p *GetAPIKeyBySourceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAPIKeyBySourceReq(%+v)", *p)
}

var fieldIDToName_GetAPIKeyBySourceReq = map[int16]string{
	1: "source",
}

type GetAPIKeyByModelReq struct {
	Model   *string `thrift:"model,1,optional" frugal:"1,optional,string" json:"model,omitempty"`
	ModelId *int64  `thrift:"model_id,2,optional" frugal:"2,optional,i64" json:"model_id,omitempty"`
}

func NewGetAPIKeyByModelReq() *GetAPIKeyByModelReq {
	return &GetAPIKeyByModelReq{}
}

func (p *GetAPIKeyByModelReq) InitDefault() {
}

var GetAPIKeyByModelReq_Model_DEFAULT string

func (p *GetAPIKeyByModelReq) GetModel() (v string) {
	if !p.IsSetModel() {
		return GetAPIKeyByModelReq_Model_DEFAULT
	}
	return *p.Model
}

var GetAPIKeyByModelReq_ModelId_DEFAULT int64

func (p *GetAPIKeyByModelReq) GetModelId() (v int64) {
	if !p.IsSetModelId() {
		return GetAPIKeyByModelReq_ModelId_DEFAULT
	}
	return *p.ModelId
}
func (p *GetAPIKeyByModelReq) SetModel(val *string) {
	p.Model = val
}
func (p *GetAPIKeyByModelReq) SetModelId(val *int64) {
	p.ModelId = val
}

func (p *GetAPIKeyByModelReq) IsSetModel() bool {
	return p.Model != nil
}

func (p *GetAPIKeyByModelReq) IsSetModelId() bool {
	return p.ModelId != nil
}

func (p *GetAPIKeyByModelReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAPIKeyByModelReq(%+v)", *p)
}

var fieldIDToName_GetAPIKeyByModelReq = map[int16]string{
	1: "model",
	2: "model_id",
}

type ModelService interface {
	GenToken(ctx context.Context, req *GenTokenReq) (r *GenTokenResp, err error)

	Chat(req *ChatReq, stream ModelService_ChatServer) (err error)

	CreateModel(ctx context.Context, req *CreateModelReq) (r *base.Empty, err error)

	UpdateModel(ctx context.Context, req *UpdateModelReq) (r *base.Empty, err error)

	DeleteModel(ctx context.Context, req *base.IDReq) (r *base.Empty, err error)

	GetModelByID(ctx context.Context, req *base.IDReq) (r *Model, err error)

	ListModel(ctx context.Context, req *ListModelReq) (r *ListModelResp, err error)

	GetAPIKeyBySource(ctx context.Context, req *GetAPIKeyBySourceReq) (r *APIKey, err error)

	GetAPIKeyByModel(ctx context.Context, req *GetAPIKeyByModelReq) (r *APIKey, err error)
}

type ModelServiceGenTokenArgs struct {
	Req *GenTokenReq `thrift:"req,1" frugal:"1,default,GenTokenReq" json:"req"`
}

func NewModelServiceGenTokenArgs() *ModelServiceGenTokenArgs {
	return &ModelServiceGenTokenArgs{}
}

func (p *ModelServiceGenTokenArgs) InitDefault() {
}

var ModelServiceGenTokenArgs_Req_DEFAULT *GenTokenReq

func (p *ModelServiceGenTokenArgs) GetReq() (v *GenTokenReq) {
	if !p.IsSetReq() {
		return ModelServiceGenTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ModelServiceGenTokenArgs) SetReq(val *GenTokenReq) {
	p.Req = val
}

func (p *ModelServiceGenTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ModelServiceGenTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceGenTokenArgs(%+v)", *p)
}

var fieldIDToName_ModelServiceGenTokenArgs = map[int16]string{
	1: "req",
}

type ModelServiceGenTokenResult struct {
	Success *GenTokenResp `thrift:"success,0,optional" frugal:"0,optional,GenTokenResp" json:"success,omitempty"`
}

func NewModelServiceGenTokenResult() *ModelServiceGenTokenResult {
	return &ModelServiceGenTokenResult{}
}

func (p *ModelServiceGenTokenResult) InitDefault() {
}

var ModelServiceGenTokenResult_Success_DEFAULT *GenTokenResp

func (p *ModelServiceGenTokenResult) GetSuccess() (v *GenTokenResp) {
	if !p.IsSetSuccess() {
		return ModelServiceGenTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ModelServiceGenTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*GenTokenResp)
}

func (p *ModelServiceGenTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ModelServiceGenTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceGenTokenResult(%+v)", *p)
}

var fieldIDToName_ModelServiceGenTokenResult = map[int16]string{
	0: "success",
}

type ModelServiceChatArgs struct {
	Req *ChatReq `thrift:"req,1" frugal:"1,default,ChatReq" json:"req"`
}

func NewModelServiceChatArgs() *ModelServiceChatArgs {
	return &ModelServiceChatArgs{}
}

func (p *ModelServiceChatArgs) InitDefault() {
}

var ModelServiceChatArgs_Req_DEFAULT *ChatReq

func (p *ModelServiceChatArgs) GetReq() (v *ChatReq) {
	if !p.IsSetReq() {
		return ModelServiceChatArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ModelServiceChatArgs) SetReq(val *ChatReq) {
	p.Req = val
}

func (p *ModelServiceChatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ModelServiceChatArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceChatArgs(%+v)", *p)
}

var fieldIDToName_ModelServiceChatArgs = map[int16]string{
	1: "req",
}

type ModelServiceChatResult struct {
	Success *ChatResp `thrift:"success,0,optional" frugal:"0,optional,ChatResp" json:"success,omitempty"`
}

func NewModelServiceChatResult() *ModelServiceChatResult {
	return &ModelServiceChatResult{}
}

func (p *ModelServiceChatResult) InitDefault() {
}

var ModelServiceChatResult_Success_DEFAULT *ChatResp

func (p *ModelServiceChatResult) GetSuccess() (v *ChatResp) {
	if !p.IsSetSuccess() {
		return ModelServiceChatResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ModelServiceChatResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChatResp)
}

func (p *ModelServiceChatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ModelServiceChatResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceChatResult(%+v)", *p)
}

var fieldIDToName_ModelServiceChatResult = map[int16]string{
	0: "success",
}

type ModelService_ChatServer interface {
	streaming.Stream

	Send(*ChatResp) error
}

type ModelServiceCreateModelArgs struct {
	Req *CreateModelReq `thrift:"req,1" frugal:"1,default,CreateModelReq" json:"req"`
}

func NewModelServiceCreateModelArgs() *ModelServiceCreateModelArgs {
	return &ModelServiceCreateModelArgs{}
}

func (p *ModelServiceCreateModelArgs) InitDefault() {
}

var ModelServiceCreateModelArgs_Req_DEFAULT *CreateModelReq

func (p *ModelServiceCreateModelArgs) GetReq() (v *CreateModelReq) {
	if !p.IsSetReq() {
		return ModelServiceCreateModelArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ModelServiceCreateModelArgs) SetReq(val *CreateModelReq) {
	p.Req = val
}

func (p *ModelServiceCreateModelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ModelServiceCreateModelArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceCreateModelArgs(%+v)", *p)
}

var fieldIDToName_ModelServiceCreateModelArgs = map[int16]string{
	1: "req",
}

type ModelServiceCreateModelResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewModelServiceCreateModelResult() *ModelServiceCreateModelResult {
	return &ModelServiceCreateModelResult{}
}

func (p *ModelServiceCreateModelResult) InitDefault() {
}

var ModelServiceCreateModelResult_Success_DEFAULT *base.Empty

func (p *ModelServiceCreateModelResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return ModelServiceCreateModelResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ModelServiceCreateModelResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *ModelServiceCreateModelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ModelServiceCreateModelResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceCreateModelResult(%+v)", *p)
}

var fieldIDToName_ModelServiceCreateModelResult = map[int16]string{
	0: "success",
}

type ModelServiceUpdateModelArgs struct {
	Req *UpdateModelReq `thrift:"req,1" frugal:"1,default,UpdateModelReq" json:"req"`
}

func NewModelServiceUpdateModelArgs() *ModelServiceUpdateModelArgs {
	return &ModelServiceUpdateModelArgs{}
}

func (p *ModelServiceUpdateModelArgs) InitDefault() {
}

var ModelServiceUpdateModelArgs_Req_DEFAULT *UpdateModelReq

func (p *ModelServiceUpdateModelArgs) GetReq() (v *UpdateModelReq) {
	if !p.IsSetReq() {
		return ModelServiceUpdateModelArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ModelServiceUpdateModelArgs) SetReq(val *UpdateModelReq) {
	p.Req = val
}

func (p *ModelServiceUpdateModelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ModelServiceUpdateModelArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceUpdateModelArgs(%+v)", *p)
}

var fieldIDToName_ModelServiceUpdateModelArgs = map[int16]string{
	1: "req",
}

type ModelServiceUpdateModelResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewModelServiceUpdateModelResult() *ModelServiceUpdateModelResult {
	return &ModelServiceUpdateModelResult{}
}

func (p *ModelServiceUpdateModelResult) InitDefault() {
}

var ModelServiceUpdateModelResult_Success_DEFAULT *base.Empty

func (p *ModelServiceUpdateModelResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return ModelServiceUpdateModelResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ModelServiceUpdateModelResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *ModelServiceUpdateModelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ModelServiceUpdateModelResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceUpdateModelResult(%+v)", *p)
}

var fieldIDToName_ModelServiceUpdateModelResult = map[int16]string{
	0: "success",
}

type ModelServiceDeleteModelArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewModelServiceDeleteModelArgs() *ModelServiceDeleteModelArgs {
	return &ModelServiceDeleteModelArgs{}
}

func (p *ModelServiceDeleteModelArgs) InitDefault() {
}

var ModelServiceDeleteModelArgs_Req_DEFAULT *base.IDReq

func (p *ModelServiceDeleteModelArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return ModelServiceDeleteModelArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ModelServiceDeleteModelArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *ModelServiceDeleteModelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ModelServiceDeleteModelArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceDeleteModelArgs(%+v)", *p)
}

var fieldIDToName_ModelServiceDeleteModelArgs = map[int16]string{
	1: "req",
}

type ModelServiceDeleteModelResult struct {
	Success *base.Empty `thrift:"success,0,optional" frugal:"0,optional,base.Empty" json:"success,omitempty"`
}

func NewModelServiceDeleteModelResult() *ModelServiceDeleteModelResult {
	return &ModelServiceDeleteModelResult{}
}

func (p *ModelServiceDeleteModelResult) InitDefault() {
}

var ModelServiceDeleteModelResult_Success_DEFAULT *base.Empty

func (p *ModelServiceDeleteModelResult) GetSuccess() (v *base.Empty) {
	if !p.IsSetSuccess() {
		return ModelServiceDeleteModelResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ModelServiceDeleteModelResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.Empty)
}

func (p *ModelServiceDeleteModelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ModelServiceDeleteModelResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceDeleteModelResult(%+v)", *p)
}

var fieldIDToName_ModelServiceDeleteModelResult = map[int16]string{
	0: "success",
}

type ModelServiceGetModelByIDArgs struct {
	Req *base.IDReq `thrift:"req,1" frugal:"1,default,base.IDReq" json:"req"`
}

func NewModelServiceGetModelByIDArgs() *ModelServiceGetModelByIDArgs {
	return &ModelServiceGetModelByIDArgs{}
}

func (p *ModelServiceGetModelByIDArgs) InitDefault() {
}

var ModelServiceGetModelByIDArgs_Req_DEFAULT *base.IDReq

func (p *ModelServiceGetModelByIDArgs) GetReq() (v *base.IDReq) {
	if !p.IsSetReq() {
		return ModelServiceGetModelByIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ModelServiceGetModelByIDArgs) SetReq(val *base.IDReq) {
	p.Req = val
}

func (p *ModelServiceGetModelByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ModelServiceGetModelByIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceGetModelByIDArgs(%+v)", *p)
}

var fieldIDToName_ModelServiceGetModelByIDArgs = map[int16]string{
	1: "req",
}

type ModelServiceGetModelByIDResult struct {
	Success *Model `thrift:"success,0,optional" frugal:"0,optional,Model" json:"success,omitempty"`
}

func NewModelServiceGetModelByIDResult() *ModelServiceGetModelByIDResult {
	return &ModelServiceGetModelByIDResult{}
}

func (p *ModelServiceGetModelByIDResult) InitDefault() {
}

var ModelServiceGetModelByIDResult_Success_DEFAULT *Model

func (p *ModelServiceGetModelByIDResult) GetSuccess() (v *Model) {
	if !p.IsSetSuccess() {
		return ModelServiceGetModelByIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ModelServiceGetModelByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*Model)
}

func (p *ModelServiceGetModelByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ModelServiceGetModelByIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceGetModelByIDResult(%+v)", *p)
}

var fieldIDToName_ModelServiceGetModelByIDResult = map[int16]string{
	0: "success",
}

type ModelServiceListModelArgs struct {
	Req *ListModelReq `thrift:"req,1" frugal:"1,default,ListModelReq" json:"req"`
}

func NewModelServiceListModelArgs() *ModelServiceListModelArgs {
	return &ModelServiceListModelArgs{}
}

func (p *ModelServiceListModelArgs) InitDefault() {
}

var ModelServiceListModelArgs_Req_DEFAULT *ListModelReq

func (p *ModelServiceListModelArgs) GetReq() (v *ListModelReq) {
	if !p.IsSetReq() {
		return ModelServiceListModelArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ModelServiceListModelArgs) SetReq(val *ListModelReq) {
	p.Req = val
}

func (p *ModelServiceListModelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ModelServiceListModelArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceListModelArgs(%+v)", *p)
}

var fieldIDToName_ModelServiceListModelArgs = map[int16]string{
	1: "req",
}

type ModelServiceListModelResult struct {
	Success *ListModelResp `thrift:"success,0,optional" frugal:"0,optional,ListModelResp" json:"success,omitempty"`
}

func NewModelServiceListModelResult() *ModelServiceListModelResult {
	return &ModelServiceListModelResult{}
}

func (p *ModelServiceListModelResult) InitDefault() {
}

var ModelServiceListModelResult_Success_DEFAULT *ListModelResp

func (p *ModelServiceListModelResult) GetSuccess() (v *ListModelResp) {
	if !p.IsSetSuccess() {
		return ModelServiceListModelResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ModelServiceListModelResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListModelResp)
}

func (p *ModelServiceListModelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ModelServiceListModelResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceListModelResult(%+v)", *p)
}

var fieldIDToName_ModelServiceListModelResult = map[int16]string{
	0: "success",
}

type ModelServiceGetAPIKeyBySourceArgs struct {
	Req *GetAPIKeyBySourceReq `thrift:"req,1" frugal:"1,default,GetAPIKeyBySourceReq" json:"req"`
}

func NewModelServiceGetAPIKeyBySourceArgs() *ModelServiceGetAPIKeyBySourceArgs {
	return &ModelServiceGetAPIKeyBySourceArgs{}
}

func (p *ModelServiceGetAPIKeyBySourceArgs) InitDefault() {
}

var ModelServiceGetAPIKeyBySourceArgs_Req_DEFAULT *GetAPIKeyBySourceReq

func (p *ModelServiceGetAPIKeyBySourceArgs) GetReq() (v *GetAPIKeyBySourceReq) {
	if !p.IsSetReq() {
		return ModelServiceGetAPIKeyBySourceArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ModelServiceGetAPIKeyBySourceArgs) SetReq(val *GetAPIKeyBySourceReq) {
	p.Req = val
}

func (p *ModelServiceGetAPIKeyBySourceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ModelServiceGetAPIKeyBySourceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceGetAPIKeyBySourceArgs(%+v)", *p)
}

var fieldIDToName_ModelServiceGetAPIKeyBySourceArgs = map[int16]string{
	1: "req",
}

type ModelServiceGetAPIKeyBySourceResult struct {
	Success *APIKey `thrift:"success,0,optional" frugal:"0,optional,APIKey" json:"success,omitempty"`
}

func NewModelServiceGetAPIKeyBySourceResult() *ModelServiceGetAPIKeyBySourceResult {
	return &ModelServiceGetAPIKeyBySourceResult{}
}

func (p *ModelServiceGetAPIKeyBySourceResult) InitDefault() {
}

var ModelServiceGetAPIKeyBySourceResult_Success_DEFAULT *APIKey

func (p *ModelServiceGetAPIKeyBySourceResult) GetSuccess() (v *APIKey) {
	if !p.IsSetSuccess() {
		return ModelServiceGetAPIKeyBySourceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ModelServiceGetAPIKeyBySourceResult) SetSuccess(x interface{}) {
	p.Success = x.(*APIKey)
}

func (p *ModelServiceGetAPIKeyBySourceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ModelServiceGetAPIKeyBySourceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceGetAPIKeyBySourceResult(%+v)", *p)
}

var fieldIDToName_ModelServiceGetAPIKeyBySourceResult = map[int16]string{
	0: "success",
}

type ModelServiceGetAPIKeyByModelArgs struct {
	Req *GetAPIKeyByModelReq `thrift:"req,1" frugal:"1,default,GetAPIKeyByModelReq" json:"req"`
}

func NewModelServiceGetAPIKeyByModelArgs() *ModelServiceGetAPIKeyByModelArgs {
	return &ModelServiceGetAPIKeyByModelArgs{}
}

func (p *ModelServiceGetAPIKeyByModelArgs) InitDefault() {
}

var ModelServiceGetAPIKeyByModelArgs_Req_DEFAULT *GetAPIKeyByModelReq

func (p *ModelServiceGetAPIKeyByModelArgs) GetReq() (v *GetAPIKeyByModelReq) {
	if !p.IsSetReq() {
		return ModelServiceGetAPIKeyByModelArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ModelServiceGetAPIKeyByModelArgs) SetReq(val *GetAPIKeyByModelReq) {
	p.Req = val
}

func (p *ModelServiceGetAPIKeyByModelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ModelServiceGetAPIKeyByModelArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceGetAPIKeyByModelArgs(%+v)", *p)
}

var fieldIDToName_ModelServiceGetAPIKeyByModelArgs = map[int16]string{
	1: "req",
}

type ModelServiceGetAPIKeyByModelResult struct {
	Success *APIKey `thrift:"success,0,optional" frugal:"0,optional,APIKey" json:"success,omitempty"`
}

func NewModelServiceGetAPIKeyByModelResult() *ModelServiceGetAPIKeyByModelResult {
	return &ModelServiceGetAPIKeyByModelResult{}
}

func (p *ModelServiceGetAPIKeyByModelResult) InitDefault() {
}

var ModelServiceGetAPIKeyByModelResult_Success_DEFAULT *APIKey

func (p *ModelServiceGetAPIKeyByModelResult) GetSuccess() (v *APIKey) {
	if !p.IsSetSuccess() {
		return ModelServiceGetAPIKeyByModelResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ModelServiceGetAPIKeyByModelResult) SetSuccess(x interface{}) {
	p.Success = x.(*APIKey)
}

func (p *ModelServiceGetAPIKeyByModelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ModelServiceGetAPIKeyByModelResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelServiceGetAPIKeyByModelResult(%+v)", *p)
}

var fieldIDToName_ModelServiceGetAPIKeyByModelResult = map[int16]string{
	0: "success",
}
