// Code generated by Kitex v0.13.1. DO NOT EDIT.

package knowledgeservice

import (
	"context"
	base "github.com/aiagt/aiagt/kitex_gen/base"
	knowledgesvc "github.com/aiagt/aiagt/kitex_gen/knowledgesvc"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Retrieval(ctx context.Context, req *knowledgesvc.RetrievalReq, callOptions ...callopt.Option) (r *knowledgesvc.RetrievalResp, err error)
	ListKnowledge(ctx context.Context, req *knowledgesvc.ListKnowledgeReq, callOptions ...callopt.Option) (r *knowledgesvc.ListKnowledgeResp, err error)
	GetKnowledgeByID(ctx context.Context, req *base.IDReq, callOptions ...callopt.Option) (r *knowledgesvc.Knowledge, err error)
	GetKnowledgeByIDs(ctx context.Context, req *base.IDsReq, callOptions ...callopt.Option) (r []*knowledgesvc.Knowledge, err error)
	SaveKnowledge(ctx context.Context, req *knowledgesvc.SaveKnowledgeReq, callOptions ...callopt.Option) (r *base.Empty, err error)
	DeleteKnowledge(ctx context.Context, req *base.IDReq, callOptions ...callopt.Option) (r *base.Empty, err error)
	GetDocumentByKnowledge(ctx context.Context, req *base.IDReq, callOptions ...callopt.Option) (r *knowledgesvc.GetDocumentByKnowledgeResp, err error)
	UploadDocument(ctx context.Context, req *knowledgesvc.UploadDocumentReq, callOptions ...callopt.Option) (r *base.Empty, err error)
	UpdateDocument(ctx context.Context, req *knowledgesvc.UpdateDocumentReq, callOptions ...callopt.Option) (r *base.Empty, err error)
	DeleteDocument(ctx context.Context, req *base.IDReq, callOptions ...callopt.Option) (r *base.Empty, err error)
	PreviewChunks(ctx context.Context, req *knowledgesvc.PreviewChunksReq, callOptions ...callopt.Option) (r *knowledgesvc.PreviewChunksResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kKnowledgeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kKnowledgeServiceClient struct {
	*kClient
}

func (p *kKnowledgeServiceClient) Retrieval(ctx context.Context, req *knowledgesvc.RetrievalReq, callOptions ...callopt.Option) (r *knowledgesvc.RetrievalResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Retrieval(ctx, req)
}

func (p *kKnowledgeServiceClient) ListKnowledge(ctx context.Context, req *knowledgesvc.ListKnowledgeReq, callOptions ...callopt.Option) (r *knowledgesvc.ListKnowledgeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListKnowledge(ctx, req)
}

func (p *kKnowledgeServiceClient) GetKnowledgeByID(ctx context.Context, req *base.IDReq, callOptions ...callopt.Option) (r *knowledgesvc.Knowledge, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetKnowledgeByID(ctx, req)
}

func (p *kKnowledgeServiceClient) GetKnowledgeByIDs(ctx context.Context, req *base.IDsReq, callOptions ...callopt.Option) (r []*knowledgesvc.Knowledge, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetKnowledgeByIDs(ctx, req)
}

func (p *kKnowledgeServiceClient) SaveKnowledge(ctx context.Context, req *knowledgesvc.SaveKnowledgeReq, callOptions ...callopt.Option) (r *base.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveKnowledge(ctx, req)
}

func (p *kKnowledgeServiceClient) DeleteKnowledge(ctx context.Context, req *base.IDReq, callOptions ...callopt.Option) (r *base.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteKnowledge(ctx, req)
}

func (p *kKnowledgeServiceClient) GetDocumentByKnowledge(ctx context.Context, req *base.IDReq, callOptions ...callopt.Option) (r *knowledgesvc.GetDocumentByKnowledgeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDocumentByKnowledge(ctx, req)
}

func (p *kKnowledgeServiceClient) UploadDocument(ctx context.Context, req *knowledgesvc.UploadDocumentReq, callOptions ...callopt.Option) (r *base.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadDocument(ctx, req)
}

func (p *kKnowledgeServiceClient) UpdateDocument(ctx context.Context, req *knowledgesvc.UpdateDocumentReq, callOptions ...callopt.Option) (r *base.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDocument(ctx, req)
}

func (p *kKnowledgeServiceClient) DeleteDocument(ctx context.Context, req *base.IDReq, callOptions ...callopt.Option) (r *base.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteDocument(ctx, req)
}

func (p *kKnowledgeServiceClient) PreviewChunks(ctx context.Context, req *knowledgesvc.PreviewChunksReq, callOptions ...callopt.Option) (r *knowledgesvc.PreviewChunksResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreviewChunks(ctx, req)
}
