// Code generated by Kitex v0.13.1. DO NOT EDIT.

package knowledgeservice

import (
	"context"
	"errors"
	base "github.com/aiagt/aiagt/kitex_gen/base"
	knowledgesvc "github.com/aiagt/aiagt/kitex_gen/knowledgesvc"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Retrieval": kitex.NewMethodInfo(
		retrievalHandler,
		newKnowledgeServiceRetrievalArgs,
		newKnowledgeServiceRetrievalResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListKnowledge": kitex.NewMethodInfo(
		listKnowledgeHandler,
		newKnowledgeServiceListKnowledgeArgs,
		newKnowledgeServiceListKnowledgeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetKnowledgeByID": kitex.NewMethodInfo(
		getKnowledgeByIDHandler,
		newKnowledgeServiceGetKnowledgeByIDArgs,
		newKnowledgeServiceGetKnowledgeByIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetKnowledgeByIDs": kitex.NewMethodInfo(
		getKnowledgeByIDsHandler,
		newKnowledgeServiceGetKnowledgeByIDsArgs,
		newKnowledgeServiceGetKnowledgeByIDsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SaveKnowledge": kitex.NewMethodInfo(
		saveKnowledgeHandler,
		newKnowledgeServiceSaveKnowledgeArgs,
		newKnowledgeServiceSaveKnowledgeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteKnowledge": kitex.NewMethodInfo(
		deleteKnowledgeHandler,
		newKnowledgeServiceDeleteKnowledgeArgs,
		newKnowledgeServiceDeleteKnowledgeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetDocumentByKnowledge": kitex.NewMethodInfo(
		getDocumentByKnowledgeHandler,
		newKnowledgeServiceGetDocumentByKnowledgeArgs,
		newKnowledgeServiceGetDocumentByKnowledgeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadDocument": kitex.NewMethodInfo(
		uploadDocumentHandler,
		newKnowledgeServiceUploadDocumentArgs,
		newKnowledgeServiceUploadDocumentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateDocument": kitex.NewMethodInfo(
		updateDocumentHandler,
		newKnowledgeServiceUpdateDocumentArgs,
		newKnowledgeServiceUpdateDocumentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteDocument": kitex.NewMethodInfo(
		deleteDocumentHandler,
		newKnowledgeServiceDeleteDocumentArgs,
		newKnowledgeServiceDeleteDocumentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PreviewChunks": kitex.NewMethodInfo(
		previewChunksHandler,
		newKnowledgeServicePreviewChunksArgs,
		newKnowledgeServicePreviewChunksResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	knowledgeServiceServiceInfo                = NewServiceInfo()
	knowledgeServiceServiceInfoForClient       = NewServiceInfoForClient()
	knowledgeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KnowledgeService"
	handlerType := (*knowledgesvc.KnowledgeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "knowledgesvc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func retrievalHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceRetrievalArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceRetrievalResult)
	success, err := handler.(knowledgesvc.KnowledgeService).Retrieval(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceRetrievalArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceRetrievalArgs()
}

func newKnowledgeServiceRetrievalResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceRetrievalResult()
}

func listKnowledgeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceListKnowledgeArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceListKnowledgeResult)
	success, err := handler.(knowledgesvc.KnowledgeService).ListKnowledge(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceListKnowledgeArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceListKnowledgeArgs()
}

func newKnowledgeServiceListKnowledgeResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceListKnowledgeResult()
}

func getKnowledgeByIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceGetKnowledgeByIDArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceGetKnowledgeByIDResult)
	success, err := handler.(knowledgesvc.KnowledgeService).GetKnowledgeByID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceGetKnowledgeByIDArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceGetKnowledgeByIDArgs()
}

func newKnowledgeServiceGetKnowledgeByIDResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceGetKnowledgeByIDResult()
}

func getKnowledgeByIDsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceGetKnowledgeByIDsArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceGetKnowledgeByIDsResult)
	success, err := handler.(knowledgesvc.KnowledgeService).GetKnowledgeByIDs(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceGetKnowledgeByIDsArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceGetKnowledgeByIDsArgs()
}

func newKnowledgeServiceGetKnowledgeByIDsResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceGetKnowledgeByIDsResult()
}

func saveKnowledgeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceSaveKnowledgeArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceSaveKnowledgeResult)
	success, err := handler.(knowledgesvc.KnowledgeService).SaveKnowledge(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceSaveKnowledgeArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceSaveKnowledgeArgs()
}

func newKnowledgeServiceSaveKnowledgeResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceSaveKnowledgeResult()
}

func deleteKnowledgeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceDeleteKnowledgeArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceDeleteKnowledgeResult)
	success, err := handler.(knowledgesvc.KnowledgeService).DeleteKnowledge(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceDeleteKnowledgeArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceDeleteKnowledgeArgs()
}

func newKnowledgeServiceDeleteKnowledgeResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceDeleteKnowledgeResult()
}

func getDocumentByKnowledgeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceGetDocumentByKnowledgeArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceGetDocumentByKnowledgeResult)
	success, err := handler.(knowledgesvc.KnowledgeService).GetDocumentByKnowledge(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceGetDocumentByKnowledgeArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceGetDocumentByKnowledgeArgs()
}

func newKnowledgeServiceGetDocumentByKnowledgeResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceGetDocumentByKnowledgeResult()
}

func uploadDocumentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceUploadDocumentArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceUploadDocumentResult)
	success, err := handler.(knowledgesvc.KnowledgeService).UploadDocument(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceUploadDocumentArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceUploadDocumentArgs()
}

func newKnowledgeServiceUploadDocumentResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceUploadDocumentResult()
}

func updateDocumentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceUpdateDocumentArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceUpdateDocumentResult)
	success, err := handler.(knowledgesvc.KnowledgeService).UpdateDocument(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceUpdateDocumentArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceUpdateDocumentArgs()
}

func newKnowledgeServiceUpdateDocumentResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceUpdateDocumentResult()
}

func deleteDocumentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServiceDeleteDocumentArgs)
	realResult := result.(*knowledgesvc.KnowledgeServiceDeleteDocumentResult)
	success, err := handler.(knowledgesvc.KnowledgeService).DeleteDocument(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceDeleteDocumentArgs() interface{} {
	return knowledgesvc.NewKnowledgeServiceDeleteDocumentArgs()
}

func newKnowledgeServiceDeleteDocumentResult() interface{} {
	return knowledgesvc.NewKnowledgeServiceDeleteDocumentResult()
}

func previewChunksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledgesvc.KnowledgeServicePreviewChunksArgs)
	realResult := result.(*knowledgesvc.KnowledgeServicePreviewChunksResult)
	success, err := handler.(knowledgesvc.KnowledgeService).PreviewChunks(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServicePreviewChunksArgs() interface{} {
	return knowledgesvc.NewKnowledgeServicePreviewChunksArgs()
}

func newKnowledgeServicePreviewChunksResult() interface{} {
	return knowledgesvc.NewKnowledgeServicePreviewChunksResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Retrieval(ctx context.Context, req *knowledgesvc.RetrievalReq) (r *knowledgesvc.RetrievalResp, err error) {
	var _args knowledgesvc.KnowledgeServiceRetrievalArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceRetrievalResult
	if err = p.c.Call(ctx, "Retrieval", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListKnowledge(ctx context.Context, req *knowledgesvc.ListKnowledgeReq) (r *knowledgesvc.ListKnowledgeResp, err error) {
	var _args knowledgesvc.KnowledgeServiceListKnowledgeArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceListKnowledgeResult
	if err = p.c.Call(ctx, "ListKnowledge", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetKnowledgeByID(ctx context.Context, req *base.IDReq) (r *knowledgesvc.Knowledge, err error) {
	var _args knowledgesvc.KnowledgeServiceGetKnowledgeByIDArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceGetKnowledgeByIDResult
	if err = p.c.Call(ctx, "GetKnowledgeByID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetKnowledgeByIDs(ctx context.Context, req *base.IDsReq) (r []*knowledgesvc.Knowledge, err error) {
	var _args knowledgesvc.KnowledgeServiceGetKnowledgeByIDsArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceGetKnowledgeByIDsResult
	if err = p.c.Call(ctx, "GetKnowledgeByIDs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SaveKnowledge(ctx context.Context, req *knowledgesvc.SaveKnowledgeReq) (r *base.Empty, err error) {
	var _args knowledgesvc.KnowledgeServiceSaveKnowledgeArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceSaveKnowledgeResult
	if err = p.c.Call(ctx, "SaveKnowledge", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteKnowledge(ctx context.Context, req *base.IDReq) (r *base.Empty, err error) {
	var _args knowledgesvc.KnowledgeServiceDeleteKnowledgeArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceDeleteKnowledgeResult
	if err = p.c.Call(ctx, "DeleteKnowledge", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDocumentByKnowledge(ctx context.Context, req *base.IDReq) (r *knowledgesvc.GetDocumentByKnowledgeResp, err error) {
	var _args knowledgesvc.KnowledgeServiceGetDocumentByKnowledgeArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceGetDocumentByKnowledgeResult
	if err = p.c.Call(ctx, "GetDocumentByKnowledge", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadDocument(ctx context.Context, req *knowledgesvc.UploadDocumentReq) (r *base.Empty, err error) {
	var _args knowledgesvc.KnowledgeServiceUploadDocumentArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceUploadDocumentResult
	if err = p.c.Call(ctx, "UploadDocument", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateDocument(ctx context.Context, req *knowledgesvc.UpdateDocumentReq) (r *base.Empty, err error) {
	var _args knowledgesvc.KnowledgeServiceUpdateDocumentArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceUpdateDocumentResult
	if err = p.c.Call(ctx, "UpdateDocument", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteDocument(ctx context.Context, req *base.IDReq) (r *base.Empty, err error) {
	var _args knowledgesvc.KnowledgeServiceDeleteDocumentArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServiceDeleteDocumentResult
	if err = p.c.Call(ctx, "DeleteDocument", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PreviewChunks(ctx context.Context, req *knowledgesvc.PreviewChunksReq) (r *knowledgesvc.PreviewChunksResp, err error) {
	var _args knowledgesvc.KnowledgeServicePreviewChunksArgs
	_args.Req = req
	var _result knowledgesvc.KnowledgeServicePreviewChunksResult
	if err = p.c.Call(ctx, "PreviewChunks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
